### ISSUE TITLE
ADAP Aligner (GC) and Saving Project

### ISSUE THREAD

**Issue by nic-Oban** [mzmine/mzmine3#1000]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.2.48

### What happened

* Please describe what happened and how it differs from what you expected to happen.
After ADAP Aligner (GC) module, I can't save my project anymore. I ran again the workflow from the beginning saving and opening the project at each step and I had no problem before the Aligner.

* Please upload screenshots of any errors **and** your log/mzmine.log file.
![image](https://user-images.githubusercontent.com/32569756/202213005-980cd037-d32c-4c23-a09f-4f36c58ce893.png)

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
A simple project with 2 analysis: https://mycore.core-cloud.net/index.php/s/6IX7fr9BcuSumBJ/download
Here is the batch xml with the module parameters: https://mycore.core-cloud.net/index.php/s/xctjhzOKTZ7Cpj7/download

If I can help for tests or further information, feel free to ask.
Have a good day!

**Comment by asmirn1** [comment]
I think we worked on this issue recently. @tnguy271 did we push these changes already?

**Comment by tnguy271** [comment]
hi @nic-Oban I think this issue has been addressed. Could you try our newest development release? https://github.com/mzmine/mzmine3/releases/tag/Development-release

**Comment by nic-Oban** [comment]
Hello @tnguy271, @asmirn1,
Thanks a lot for modifications, Saving works fine now!
Have a good day.
