### ISSUE TITLE
SWATH data in mzMine3

### ISSUE THREAD

**Issue by MaxFeuerstein** [mzmine/mzmine3#1001]
**Is your feature request related to a problem? Please describe.**
So far, I haven't found a SWATH option in MZmine3 and I hope I haven't overlooked it.
It would be great to add this to the MZmine toolbox!

**Describe the solution you'd like**
Similar to the MS-DIAL workflow, I would suggest that the user has to provide a table (.txt) with scan information. I am not sure if this information is maintained during file conversion, and the external .txt file seems to be an easy solution. 
LC-based deconvolution could then be performed on specified mass range from MS1 scans and the corresponding MS2 windows (similar as for the recently introduced DIA / "All ions" workflow).

**Additional context**
I really appreciate the modular environment of MZmine and it would be great to be able to align DDA and DIA/SWATH data from the same batch and to perform deconvolution (e.g., pearson correlation based as for the IM-MS data) on SWATH files while using the "standard" workflow to pair MS1 and MS2 info for DDA data.

I really appreciate your work and would provide example data files if required.
Thanks a lot and best regards, 
Max

**Comment by SteffenHeu** [comment]
Hi Max, 

unfortunately we did not have the time to work on this yet. Since we have the required functionality now due to the DIA support, the groundwork is there if you want to contribute yourself. 😄 diaPASEF support would also be great.

**Comment by MaxFeuerstein** [comment]
Hi Steffen, 

thanks for your answer and sorry for the late reply. 
I'll try my best, but so far, my knowledge of Java will probably not suffice ;)
If I make any progress, I'll let you know!

Best, 
Max

**Comment by SteffenHeu** [comment]
Hey Max,

no worries and great to hear that you're looking into it.

Starting to learn programming with a specific goal in mind is the best thing you can do. I'd be happy to guide you in the right direction. If you look into this, feel free to reach out!

Best

Steffen
