### ISSUE TITLE
CSV exports rounds to 2 digits

### ISSUE THREAD

**Issue by PhilippTernes** [mzmine/mzmine3#1007]
### Basic information

* My operating system and version: Windows 10 Enterprise
* My MZmine version: 3.2.8

### What happened

This is what I did:

* Finished data processing and came up with a nice aligned feature list.
* Exported the aligned feature list as CSV (either using to CSV item or the GNPS item from the 'Export Feature Liste' menue). When using the GNPS menu item, I selected either COMPREHENSIVE or ALL as export format.
  + All columns which are exported in exponential number format (e.g. 1.1E3) have an accuracy of exactly 2 digits.
  + This applies to the following columns: area, height, intensity_range:min, intensity_range:max
* Exported the aligned feature list as CSV (legacy MZmine 2) or GNPS (SIMPLE format, which also calls the legacy CSV export).
  + All columns are exported to full accuracy.

It would be great if all columns could be exported at full accuracy also using the new CSV export function.

The attached file shows the output of the new CSV export function (first 8 rows only):
[Test_GNPS_export_quant_full.csv](https://github.com/mzmine/mzmine3/files/10047249/Test_GNPS_export_quant_full.csv)

**Comment by robinschmid** [comment]
Yeah thats a real issue actually. 
You can change the number format in the preferences. That controls both the export and visuals in mzmine. 

I think w should add a default option there to extend all values by 2 digits. Or maybe have separate formats for export

**Comment by tomas-pluskal** [comment]
In the past we did not reformat the values for export, is that a new feature/bug?
Why not use the default `Double.toString()` method?

**Comment by robinschmid** [comment]
Some modules format the values others not. 
I think it's bad practice to export just the Double or Float value and it bloats the exported files massively. 
But it is an issue to just use the visualization formats.

**Comment by SteffenHeu** [comment]
@PhilippTernes fixed in the latest development build. https://github.com/mzmine/mzmine3/releases/tag/Development-release
the digits are not modifiable for now, we chose a resonable number for each type. 

thanks for the report.
