### ISSUE TITLE
Possibility to add a custom numeric column to feature tables

### ISSUE THREAD

**Issue by gdelap** [mzmine/mzmine3#1008]
Dear MZmine development team,

My current usage of MZmine is for raw data preprocessing to obtain a data matrix which is then subjected to various data analysis methods commonly used in metabolomics such as PCA or PLS-DA.

After the analysis, I always have a look back at the raw data in MZmine, I have always found that this step could be made easier, since that currently, I need to look at the table (for example in Excel), figure out which variables to look for (for example the ones with the highest loading on a specific component) and then have a look at these specific variables in MZmine.

Being able to add custom (numeric) columns in a feature lists (for example to import PCA loadings) could improve this step, and ease the whole variable annotation and multivariate statistics interpretation process. It would then be possible to sort the table according to these columns, and then directly look at the raw data all in the same place. 

As I know little about software development and the way MZmine code is built, I don't know if this feature would represent a lot of work. If not, it seems to me that it could be given a thought to improve the data analysis process at small cost.

Thanks a lot for the work done on MZmine!

**Comment by SteffenHeu** [comment]
Hi gdelap,

from what i understand it could be relatively easy with our now data model. However, i am not too familiar with the statistics part which comes after the feature detection with MZmine. 

1. Are these values computed for individual features or for the whole row? Our annotation model is based on rows, not on features, so this is probably the crux. 
2. What kind of values would you want to import? 
3. Are you doing multiple statistical methods? 
4. Do you want to be able to look at multiple methods at the same time or would you want to import them one after another and replace the previous one?

**Comment by robinschmid** [comment]
We could have a simple import of those columns and just add them as new columns like
PCA1 PCA2 PCA3 ... 
For multiple methods we would just add a PCA column and then 1-5 for the components
https://www.youtube.com/watch?v=T02H4rwyCvk&t=381s

**Comment by gdelap** [comment]
Hi, 

Thanks a lot for your answers.

Some answers for Steffen:

- For methods such as PCA, these values are computed for the whole row (maybe it should find its place near the row m/z and RT values at the beginning of the feature list).
- These value are double, that can take take any real value.
- Yes, we can do multiple methods, but in that case we could specify the method used in the header of the column (for example PCA_01, PCA_02, PLSDA_01, PLSDA_02 etc.), if I understood it well, it is what Robin is proposing.

Just to clarify things, do you think you will plan to add a feature in MZmine to easily create new columns in tables (such as à "New Column" button or something like this) or will we have to do it by modifying MZmine code? (or is it not settled yet?)

**Comment by SteffenHeu** [comment]
Thanks for the info. We won't add the ability to add user defined columns, as in setting the header names and loading individual values for them. However, we can add a single (or multiple, as needed) columns that can hold user defined values.
