### ISSUE TITLE
MetaboAnalyst Export and Metadata Parameters Bugs

### ISSUE THREAD

**Issue by jdsmith145** [mzmine/mzmine3#1018]
### Basic information

* My operating system and version: Windows 11 Pro
* My MZmine version: 3.2.8

### What happened
First, is the inability to select a grouping parameter when trying to export data for MetaboAnalyst -- I noticed here in the documentation you should go to project --> set parameters, but this is not an option in the current version
![image](https://user-images.githubusercontent.com/82593722/205141635-70c61884-ebe6-45aa-a49e-551c6bb1e43a.png)
![image](https://user-images.githubusercontent.com/82593722/205141767-42623691-1826-483c-83b3-065919f93002.png)

Second, is that I am unable to import parameters from a .csv file to define the metadata. I tried uploading it also in .txt and .tsv since those are the the options for the export file type. Furthermore, I copied the files name from a a feature quant table, so the names should match. When uploaded, I always get some error with no information, nor does it seem like its processing. 
![image](https://user-images.githubusercontent.com/82593722/205142725-15e1cf16-184e-4fce-9d26-0cb65bc70b6c.png)

I was using a lot of files so I will attach a link to the mzml files once they are done uploading. 

[20221130_Metadata_all_chili_samples.csv](https://github.com/mzmine/mzmine3/files/10135661/20221130_Metadata_all_chili_samples.csv)

**Comment by robinschmid** [comment]
I will work on this and fix this

**Comment by jdsmith145** [comment]
Thank you robin. If you need the files that I tried to use, I think it would be easier for you to access them from the pluskal drive. It will take over 8 hours for file transfer and I have a flight before they will finish.

**Comment by robinschmid** [comment]
yeah no worries I know wha tI have to do
