### ISSUE TITLE
Local compound DB search using MF

### ISSUE THREAD

**Issue by guikool** [mzmine/mzmine3#1038]
### Basic information

* Mac OS M1, ventura 13
* My MZmine version: 3.30

### What happened
Hi,

I've tried the local DB search (CSV) using mz, rt, formula and name
only name and formula are correct, other parameters set to 0
Tick "use adducts" to calculate possible m/z from molecular formula.

The peak identification process remains to "0%"

Same behavior with correct RT and m/z

In attach the csv file used for queries
Thanks for your help
G.
 
[mzrtMZmineMF3.csv](https://github.com/mzmine/mzmine3/files/10222702/mzrtMZmineMF3.csv)

**Comment by SteffenHeu** [comment]
Please upload the log file.

Which addcuts did you set?

**Comment by Jay1o** [comment]
> Please upload the log file.
> 
> Which addcuts did you set?

Hi Steffen, I also have issue with local DB search (CSV). It showed that the peak identification was finished, but I can not see the column "Compund DB" in the feature table. I use Windows 11 pro, 64 bit. MZmine 3.3.0.

**Comment by guikool** [comment]
It works really well, unselect RT and mz provide the same matches. Still, the "feature list rows filter" using "identified only" did not filter anything after Local compound DB annotation. Is that because it looks only in "identity column" and not in "compoundDB" matches?
