### ISSUE TITLE
Guidance for data smoothing / direct analysis PESI

### ISSUE THREAD

**Issue by barnesalan** [mzmine/mzmine3#1039]
### Basic information

* My operating system: Win11 Pro
* My MZmine version: 3.3.0

### What happened

I have acquired data using the direct analysis LCMS source DPiMS (PESI) which generates many spikes of ion signal (i.e. not a continuous TIC). We want to average across this for the entire data acquisition time period. Currently when using MZmine the peak area generated appears too low and we believe that only the first spike in ion signal lasting about 0.3 sec is integrated leaving the remaining 60 seconds of data not used. Is there a feature finding mode that will average ion signal from a user defined start and end time of data acquisition?

Data was loaded as mzML > Mass Detection (defaults)
Feature detection > LC-MS > ADAP chromatogram builder (defaults)

![MZmine-PESI-test](https://user-images.githubusercontent.com/120561289/207573394-ed5c0e37-f347-4cec-b7ab-6e76584cba3c.jpg)

**Comment by SteffenHeu** [comment]
The peak area is calculated with minutes and not seconds. If you want the area with seconds as RT axis you have to multiply by 60

**Comment by SteffenHeu** [comment]
Closing since the issue seems to be solved.

**Comment by barnesalan** [comment]
Hi Steffen, 
Thank you for replying last week I really appreciate your help. I'm not convinced that MZmine is retrieving the peak area from the entire acquisition time. As one example there is a feature m/z 496.3400 RT range min 1.03 max 2.00 is correct producing an area of 3.9E3 but if I process the same peak in LabSolutions (Shimadzu software) I get a peak area of 2.3E5.

**Comment by SteffenHeu** [comment]
See my previous comment. The area is calculated with minutes as X axis, not seconds. The shimadzu software probably uses seconds.

3.9E3 * 60 = 2.3E5

**Comment by barnesalan** [comment]
That's great, thank you it makes sense now.
