### ISSUE TITLE
Processing wizard for GC-MS

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine3#1046]
The amazing processing wizard doesn't currently support GC-MS data processing. I suppose it should not be difficult to add it.

**Comment by asmirn1** [comment]
@tomas-pluskal Do you mean something like this?
<img width="1791" alt="Screen Shot 2022-12-16 at 1 32 06 PM" src="https://user-images.githubusercontent.com/13631120/208166004-776cfa52-9115-4ccd-8611-a7be7774fe46.png">

**Comment by SteffenHeu** [comment]
I think we should have a second wizard that creates a GC worklfow. The modules are quite different andit would probably complicate the LCMS wizard. Better to have a different one for that

**Comment by robinschmid** [comment]
HOw about this:
1. change the wizard to a PropertySheet, similar to the preferences. This allows grouping and headlining parameters.
2. add other workflows maybe as tabs into the same processing wizard or
3. add menu with different wizards

![image](https://user-images.githubusercontent.com/10366914/208891306-99fd5014-4622-4fc5-ab75-3ca14acaf929.png)

**Comment by SteffenHeu** [comment]
Lets not overcomplicate it. That also makes it harder to maintain for us.

Whats the problem with just making a second wizard?

**Comment by robinschmid** [comment]
which part is overcomplicating?
From my side either one works... adding tabs or just a different wizard for each workflow

The PropertySheet would be easier to maintain I think. 
The wizard is kind of buggy each time we add or remove a parameter and the layout is only good on larger screens.

**Comment by SteffenHeu** [comment]
1. GC and LC require a lot more parameters
2. more parameters will make the layout worse on smaller screens
3. more parameters will throw users off that just want to make a **simple** workflow, which is what the wizard is for
4. how does adding the gc wizard to the LC-(IMS)-MS wizard fix the issue of the wizard being buggy when we add a new parameter? Does not change it or make it worse
5. You can only expand one accordion at a time
6. 
![grafik](https://user-images.githubusercontent.com/37407705/208894976-fdbc4227-b2e3-475b-b95d-a0d0e7ef9071.png) name will be "LC-MS / LC-IMS-MS / GC-MS workflow" then?

**Comment by asmirn1** [comment]
@robinschmid @SteffenHeu Our current plan is to copy the existing wizard and replace the HPLC section with a new GC section. We'll reuse the MS section if possible.

This way we'll also have two menu items "LC-MS / LC-IMS-MS workflow" and "GC-MS workflow".

I do like @robinschmid ideas though. We can try to come up with a better design for a wizard with tabs and/or accordions if you are okay with that.

**Comment by robinschmid** [comment]
There would still be multiple menu items... I also want to split the workflows... so same idea there. 

The only option I was asking for is if we split the tabs completely or if people should be able to switch between GC to the LC wizard. So maybe have a tab pane or a ComboBox on the top to select the wizard

**Comment by robinschmid** [comment]
i will try something now
