### ISSUE TITLE
Feature detection menu and GC-MS

### ISSUE THREAD

**Issue by tomas-pluskal** [mzmine/mzmine3#1047]
The "Feature detection" menu has a submenu LC-MS, but no GC-MS submenu.
The ADAP chromatogram builder is in the LC-MS menu, but it is used for GC-MS too.
Perhaps we should rename the menu to "LC-MS and GC-MS"?

**Comment by tomas-pluskal** [comment]
@asmirn1 ?

**Comment by asmirn1** [comment]
@tomas-pluskal 
I actually like the current separation of methods based on data type. I'm not sure if the GridMass and Targeted feature detection can be used with GC-MS data (I never used them)? If not, renaming LC-MS to "LC-MS and GC-MS" somewhat breaks this separation.

How about moving ADAP Chromatogram building one level up alongside with Smoothing and Chromatogram resolving?

**Comment by SteffenHeu** [comment]
We could also just make a new gcms entry and put the adap there again

**Comment by asmirn1** [comment]
But ADAP Chromatogram builder is used by both LC-MS and GC-MS.

**Comment by SteffenHeu** [comment]
Yeah I meant just having 2 menu entires for the adap. In LC and gc

**Comment by asmirn1** [comment]
I see. I guess that would work also.

**Comment by robinschmid** [comment]
I guess this should do...
targeted does not really work here because we need the MS1 deconvolution later to get pseudo spectra
![image](https://user-images.githubusercontent.com/10366914/208888964-92ce4d9a-2369-4f2c-b40d-218323ff4c8e.png)
