### ISSUE TITLE
Spectral library batch generation: .mgf with line break

### ISSUE THREAD

**Issue by guikool** [mzmine/mzmine3#1048]
### Basic information

* My operating system and version:Mac OS M1
* My MZmine version: 3.30

### What happened
MZmine 3.30 spectral batch library generation generate a .mgf with one line break per feature. This cause software crash during reuse of the .mgf library. 
In attach the input used to create the library and the result (OutputMZmine.txt).

Other things I've noticed:

- The line break is perhaps caused by PubChemCID field since there is no line break when not using this identifier during annotation
- The field "INCHIAUX" instead of "INCHIKEY"
- All features are duplicated, one with raw fragments and another with chimeric precursor selection: is there a way to export either raw or curated ones, not both in the same file?

Still, this is really an interesting adds to mzmine!!
Congrats for the job

[Outputmzmine.txt](https://github.com/mzmine/mzmine3/files/10252239/Outputmzmine.txt)
[MZmineinput.csv](https://github.com/mzmine/mzmine3/files/10252240/MZmineinput.csv)

**Comment by robinschmid** [comment]
We are currently still in the process to restructure some of the library generation aspects. Great to see that you are already using it. 
- I will have to look into the pubChemCID thing. So you added them during compound annotation and then the mgf gets a break?
- INCHIAUX came from GNPS but we are now naming it INCHIKEY in the future. 
- Why duplicated? So the idea is that we merge all spectra with the same energy (if there are multiple per precursor) then we merge all spectra of different energies. 

Exported are the single best/most intense spectra and the merged spectra.

**Comment by robinschmid** [comment]
Once this is finished you can download the latest library generation version at the bottom
https://github.com/mzmine/mzmine3/actions/runs/3748621655

**Comment by guikool** [comment]
Dear Robin,
thanks for your reply, Yes PubChemCID comes from MZmineinput file used in "local database search" module. 
Then the idea was to transform results in MS/MS library file. 
I ran some test and indeed the line break appears when INCHIAUX (so inchikey) are added in the metadata, not PubchemCID as I thought before. 
I'll follow the update
thanks again
G.
