### ISSUE TITLE
Dark style accordion

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#1050]
Accordion is not styled in dark mode in jabref

![image](https://user-images.githubusercontent.com/10366914/208870745-0b7b0a1b-d4a6-4fde-bbaa-7296d2caedab.png)

**Comment by SteffenHeu** [comment]
The accordion is transparent, it's the pane you are using behind the accordion that's not styled. What is it?

**Comment by robinschmid** [comment]
BorderPane > Accordion > TitledPane for each tab
![image](https://user-images.githubusercontent.com/10366914/208885576-81dec820-93eb-4178-835f-4e89f3346d8a.png)

**Comment by SteffenHeu** [comment]
The broder pane should have the correct color... Whats around that border pane?
