### ISSUE TITLE
Not a bug/issue, but need a quick answer to 'polarity' option

### ISSUE THREAD

**Issue by fatloot** [mzmine/mzmine3#1055]
So I'm fairly new to MZmine and mass detection, etc. and bit of a dumb clarity question from me but I'm wondering about the 'polarity' option under the 'Set filters' button when doing Mass Metection or LC-MS: ADAP chromatagram builder.

So I understand that when doing LC-MS work you must add or subtract a proton (+H) in order to detect metabolites and your raw data will come out like this: m/z+1 [H] and m/z-1[H] aka your results will come out as 'positive' and 'negative' polarity. In MZmine3 you can choose which polarity option you want (depending on your raw data files you decide to drop in) [Any, -, +]. 

My question is, does this 'polarity' option in MZmine3 mean it automatically change your Mass/Charge (m/z) when you export your data (i.e. .csv file) back to the original Mass/Charge? Or does it keep the m/z charge that you originally have in the raw data from the machine when putting it into MZmine3?

Below is a more visual interpretation:

Pre-LC-MS machine: Metabolite m/z and Metabolite m/z
Post-LC-MS machine: Metabolite m/z+1[H] and Metabolite m/z-1[H]
**Post MZmine3 exported data: Metabolite m/z and Metabolite m/z** 

OR 

Pre-LC-MS machine: Metabolite m/z and Metabolite m/z
Post-LC-MS machine: Metabolite m/z+1[H] and Metabolite m/z-1[H]
**Post MZmine3 exported data: Metabolite m/z+1[H] and Metabolite m/z-1[H]**

Much thanks!

**Comment by fatloot** [comment]
Just saw the 'Discussions' tab! Moving it there :)

**Comment by SteffenHeu** [comment]
Hi fatloot,

the short answer is that the raw data is not altered no matter what kind of polarity you select.

I dont know what you mean by Pre and post LC MS machine.

The polarity parameter can be used as a filter, some instruments support positive and negative mode in a single run.
