### ISSUE TITLE
2-dimensional gas chromatography data processing

### ISSUE THREAD

**Issue by QizhiSu** [mzmine/mzmine3#1062]
Dear MZmine developers,

Thanks a lot for developing such amazing software. I am wondering if it supports or plans to support Agilent's GC x GC-qTOF/MS data? Manual processing of 2-dimensional GC data one by one is quite tedious and time-consuming. At the moment, we still don't find any open-source software that is capable of peaking detection, alignment, and identification of GC x GC-qTOF/MS. Do you plan to implement this in the future?

Best regards,
Sukis

**Comment by SteffenHeu** [comment]
Hi QizhiSu,

we have currently not planned to implement specific functionality for GCxGC data. However, there might be a way to make it work in the current MZmine versions. It may not be straightforward, however. If you have a experienced MZmine user in your group you can discuss with him what im suggesting below.

I assume the setup works with a single detector, so you have column 1, then collect there for some time and then column 2 right? while stuff elutes from column 2, you collect a new batch and then reinject on column 2.

So what you can do is use the scan filter options in the ADAP chromatogram builder.
In there, you can set the time windows when the second dimension GC elutes a injection.
![grafik](https://user-images.githubusercontent.com/37407705/210578707-229c92fa-6d8e-46f5-b760-49aea66853b3.png)
You will get one feature list per injection. 

As i said, not super straigth forward but it could be possible to make it work if my assumptions of the setup are correct.

**Comment by QizhiSu** [comment]
Thanks a lot, SteffenHeu. We will give it a try.
