### ISSUE TITLE
Error save and import feature list

### ISSUE THREAD

**Issue by Jay1o** [mzmine/mzmine3#1065]
### Basic information

* My operating system and version: Windows 11 Home
* My MZmine version: Mzmine 3.3.0

### What happened
Dear mzmine team, 

I tried to save the project but an error like #994 showed up.

Then I tried to save the feature list. Firstly I have succeeded to save it in csv format but somehow can not import it again. Error like this:
![grafik](https://user-images.githubusercontent.com/120556307/210874269-814e2d50-a8e1-4323-88fb-200654176120.png)

 I also tried to save it in mzTab format, but after importing it is empty. 
![grafik](https://user-images.githubusercontent.com/120556307/210875255-7b99d29a-34a1-4079-9bf3-5762eae01f11.png)

Modules used : ![grafik](https://user-images.githubusercontent.com/120556307/210875641-d2ec75e0-3254-4a77-b623-a3a737be0418.png)

Logfile:
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/10355524/mzmine_0_0.log)

Thanks a lot!

**Comment by SteffenHeu** [comment]
thanks for the report. can you please upload a set of raw files and a batch mode script (right click on the feature list, show summary, open in batch mode, and save that to a file) so we can reproduce it?

**Comment by Jay1o** [comment]
> thanks for the report. can you please upload a set of raw files and a batch mode script (right click on the feature list, show summary, open in batch mode, and save that to a file) so we can reproduce it?

Thanks for the reply. Here is the link for the files: https://drive.google.com/drive/folders/1IKXcwl-aq1ZT83ytvgP8DcEFd-ZW2JQK?usp=sharing

**Comment by SteffenHeu** [comment]
Pleas try the from the pull request #1066 here: https://github.com/mzmine/mzmine3/actions/runs/3854577187

You should be able to save the project now.
