### ISSUE TITLE
Error in targeted feature detection when importing CSV file of database targets...

### ISSUE THREAD

**Issue by churot** [mzmine/mzmine3#1071]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.3.0

* My operating system and version: Ubuntu Linux
* My MZmine version: 3.3.0

### What happened

* When trying to launch a targeted feature detection, (Tab Feature detection / LC-MS / Target Feature Detection), we select the  CSV file, fill parameters and click on OK button. Then a message error is warning us that "Error of task Targeted feature detection Z01-G07.raw: Did not find specified column [mz] in file."... But the column is in the CSV file ? 
* We tried to rename headers, to change order of column, and a lot of troubleshooting with the CSV input file, but there is always the same error... 
* It seems that MzMine 3.3.0 can't process the scan and the import of the CSV file. If we return to the 3.2.8 version of MzMine, the same task is working without any error or trouble. So maybe there is a regression trouble with the last version of MzMine c?

* Please include all parameter values for the MZmine modules you used. 
* The saved project has been uploaded 

* Please upload screenshots of any errors **and** your log/mzmine.log file.
* Two screeshots : Screen before the error and the error message just after the operation

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* The RAW file is included in the project uploaded

* Thanks a lot for your help
* Charlotte

[2023-01-10.zip](https://github.com/mzmine/mzmine3/files/10380788/2023-01-10.zip)
![Error message](https://user-images.githubusercontent.com/104909096/211506459-7e77037a-3379-4a3a-8196-d3eef02b5701.png)
![Parameters definition](https://user-images.githubusercontent.com/104909096/211506590-2c44fd58-9a8e-4ef9-ae72-edceb462e3c2.png)
[test_pool2.csv](https://github.com/mzmine/mzmine3/files/10380797/test_pool2.csv)
[mzmine_1_0.log](https://github.com/mzmine/mzmine3/files/10380817/mzmine_1_0.log)

**Comment by churot** [comment]
Thank you, you were right about the csv file. We solved part of the problem by converting the file to UTF-8. However, we are now facing a new error. 

2023-01-10 11:12:44 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception io.github.mzmine.util.exceptions.MissingMassListException: Missing mass list in scan Z09-A05.rawScan #1 @0.00min MS1 p +.  while processing task Targeted feature detection Z09-A05.raw
 
We suspect it could be due to the absence of "Noise Level" definition in 3.3 version, in contrast to the previous versions. With the same files and parameters, everything works fine on 2.8 and 3.1 versions. 
![image](https://user-images.githubusercontent.com/104909096/211536700-052e52d7-2d33-4be4-a815-42467568017e.png)
[mzmine_1_0.log](https://github.com/mzmine/mzmine3/files/10381960/mzmine_1_0.log)

**Comment by SteffenHeu** [comment]
You have to run mass detection before the targeted feature detection.

Since the 3.3.0 the algorithm was updated to  use the mass lists instead of unprocessed scan data.

**Comment by churot** [comment]
Thank you very much ! It worked perfectly.
