### ISSUE TITLE
Cannot save the project

### ISSUE THREAD

**Issue by pawansandhu77** [mzmine/mzmine3#1073]
### Basic information

* My operating system and version: Windows 10 64-bit 8GB
* My MZmine version: Mzmine 3.3.0

Hi MZmine team,
I am unable to save my project. It gives me an error as shown below:
![Capture](https://user-images.githubusercontent.com/122412776/211687405-9de4a230-6e82-415e-8554-e7a26f552bff.PNG)
The steps I followed:

1. I imported the .mzdata.xml files.
2. Then to save the project, I went into Project>Save project.
3. Set up the project file name as "trial".
4. Project type: Standalone (I also tried referencing, gives the same error).
5. Hit OK and it display the error.

[mzmine_log.txt](https://github.com/mzmine/mzmine3/files/10387685/mzmine_log.txt)

**Comment by pawansandhu77** [comment]
I was able to resolve it.

**Comment by tomas-pluskal** [comment]
How did you resolve it?

**Comment by pawansandhu77** [comment]
> How did you resolve it?

I was trying to save it on cloud space and mzMine needs disk space to save projects.
