### ISSUE TITLE
Can't find startMZmine_Linux.sh file in MZmine_Linux_portable_3.3.0.zip

### ISSUE THREAD

**Issue by qian-gao** [mzmine/mzmine3#1075]
### Basic information

My operating system and version: Unix-based supercomputer
My MZmine version: 3.3.0

### What happened

I can't find a startMZmine_Linux.sh file in the MZmine_Linux_portable_3.3.0.zip file and not sure how to create it. Could you tell me where I can find it?

Thank you very much!

**Comment by robinschmid** [comment]
I never used this - did it work in previous versions?
Maybe you could help us how to set up the portable version.
Maybe unpacking the other distributions work.

**Comment by tomas-pluskal** [comment]
Hi @qian-gao,
The `startMZmine_Linux.sh` script was used in MZmine 2, we don't have it anymore in MZmine 3.
Instead, you should run the binary `MZmine_Linux_portable_3.3.0/bin/MZmine`.

Now that I checked, it seems the binary in the ZIP archive is missing the executable bit. 
You can easily fix that by running `chmod a+x MZmine_Linux_portable_3.3.0/bin/MZmine`.

@robinschmid Can we update the build scripts to make the MZmine program executable?
