### ISSUE TITLE
Which m/z range is used for peak integration in untargeted analysis?

### ISSUE THREAD

**Issue by JethroHemmann** [mzmine/mzmine3#1081]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.3.0

I have a question regarding the m/z range values shown in the feature list for each datafile.
I realized that some of these ranges seem very small. In the case highlighted below, the range span 282.2784-282.2785.

<img src="https://user-images.githubusercontent.com/6010271/213162789-97221dad-f134-4761-b93f-a4f099992ea1.png" width=500>

If I plot a chromatogram using this m/z range, I get a signal with many interruptions, since not all masses are included in that very narrow range:

<img src="https://user-images.githubusercontent.com/6010271/213165916-ddace381-bfc4-41fc-9b79-f87d4e1c2659.png" width=500>

If I just slightly increase that range to 282.2780-282.2790,  I get a much better chromatogram:

<img src="https://user-images.githubusercontent.com/6010271/213168278-10c4482f-d7a7-4149-9115-f6a7ed4816a5.PNG" width=500>

My questions are:

- Are the m/z ranges shown in the feature list for each datafile actually correct? It seems like the local minimum feature resolver changes that range. After the ADAP Chromatogram Builder, the range was much larger (282.2776-282.2791) and more reasonable.
- And if yes, is this range also used for the integration of the peak? 

If the peak area is plotted in addition, it looks like the area does not follow the interrupted trace and looks much more reasonable. So I assume that other m/z ranges are used internally for the integration?

<img src="https://user-images.githubusercontent.com/6010271/213166667-4f0eeb31-2230-488e-9313-abdac0b38c38.png" width=500>

I hope it is clear what I mean, and thanks a lot! :-)

**Comment by robinschmid** [comment]
Its definitely just a visualization thing.
So in the feature table we use all the data points of the feature and calculate the range from the min / max values. 
I guess that those values are more precise than 282.2784-282.2785 and we round the numbers for formatting concerns.

Could you try to just use 282.2783-282.2786, to see if that's already enough?

Best
Robin

**Comment by JethroHemmann** [comment]
Yes, I think that might explain it, thanks!
