### ISSUE TITLE
An issue in the mgf file export

### ISSUE THREAD

**Issue by hbbarbieri** [mzmine/mzmine3#1082]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.3.0

### What happened
When I export the files to GNPS, my mgf file has 0 kB. I redid all the steps and converted the data in different ways, still, the mgf file has 0 kB.
![image](https://user-images.githubusercontent.com/123014348/213268746-854b69a3-87d2-4f66-bf05-b804d5ee933d.png)
![image](https://user-images.githubusercontent.com/123014348/213268775-0fccda20-08a7-4501-bb1d-82a3ece79614.png)
![image](https://user-images.githubusercontent.com/123014348/213268797-a3e17439-84d8-4f39-bca9-85721b7904d1.png)
![image](https://user-images.githubusercontent.com/123014348/213268814-de107eba-13d6-4819-bad7-eb6fdf48deb9.png)
![image](https://user-images.githubusercontent.com/123014348/213268834-37b93a9a-360d-4c87-964e-6f7c0093a0f1.png)
![image](https://user-images.githubusercontent.com/123014348/213268851-1f16a80a-8967-4164-be1b-281b18e05ff9.png)
![image](https://user-images.githubusercontent.com/123014348/213268869-b95825d7-c129-4165-becc-5e733aec825c.png)
![image](https://user-images.githubusercontent.com/123014348/213269057-36ccf32a-e87b-4c0c-bdcf-4df34bc24df1.png)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by ivanarozlan** [comment]
Hi. I have the same issue as well. When I export the files to GNPS, my mgf file has 0 kB. I redid all the steps and converted the data in different ways, still, the mgf file has 0 kB.

**Comment by biryb** [comment]
I've been having this issue for a long time. Trying to convert a .json to .mgf via mzmine, but mzmine keeps creating 0 kB files.
