### ISSUE TITLE
build chromatogram error with dda centroid data in NEG mode only

### ISSUE THREAD

**Issue by AnaKovacic** [mzmine/mzmine3#1084]
### Basic information

* My operating system:

* My MZmine version: 3.3.0

### What happened

I imported Centroid DDA data in positive mode after applying mass correction and scan event from 1-6 in msconverted, all steps of my non-target workflow for lcms data using mzmine went ok, while when doing the same thing with data analyzed in negative mode, I keep receiving the error when trying to build chromatogram "there are no scans satisfying filtering values. consider updating filters with set filters in the scans parameters."
![Screenshot 2023-01-20 141515_error_dda_centroid_NEG mdoe](https://user-images.githubusercontent.com/72231221/213705520-29136c8c-2700-4325-b204-a28f4f3e3bf4.png)

Do you maybe know how can I solve this issue? 
Thank you.
Ana

**Comment by SteffenHeu** [comment]
Hello Ana, 

Please follow the general issue descriptions. We cannot provide any support for your specific problem without an example dataset and batch file or better an project.

**Comment by AnaKovacic** [comment]
Dear Steffen,
sure.
For now, I just tested it with one file.
Please find the .rar file, the converted one, and the project on the
following link:
https://drive.google.com/file/d/12yX0dZZm7hC0J7dBEtWKQtNzxe0EjAoe/view?usp=sharing,
https://drive.google.com/drive/folders/1399wDJVRNyziD-VOVq2y_6OxtqpIvujW?usp=sharing,
https://drive.google.com/file/d/14rZCvrHZd1gI1XK958k_HS0B61956IkB/view?usp=sharing

I hope this is sufficient.
Thank you.
Ana

**Comment by SteffenHeu** [comment]
Hi Ana, 

the mzml is not centroided, as you can see in the raw data overview and the spectrum.

![grafik](https://user-images.githubusercontent.com/37407705/213758711-1d425252-bb7c-498d-944f-fac75f9592a2.png)

You can either use a profile mass detector and adjust the scan filter or convert them with centroiding.

**Comment by AnaKovacic** [comment]
Hi Steffen,

I had a problem with dda, centroid in negative mode also when acquiring,
before optimizing parameters, I got no signal, after optimization the
spectra looked correct.
I will check again if I made a mistake while acquiring or if I have not
solved already the first problem.

Thank you very much for your help and I apologize for my superficiality.

Best
Ana
