### ISSUE TITLE
Save Project Errors

### ISSUE THREAD

**Issue by kelloggresearchgroup** [mzmine/mzmine3#1088]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.2.0

### What happened

The steps I followed before the error.

I imported .mzML files and followed through the processing.
To save the project, I went into Project>Save project.
Set up the project file name as "trial".
Project type: Standalone (I also tried referencing, gives the same error).
Hit OK and it display the error.

![mzmine2](https://user-images.githubusercontent.com/57141760/213802036-2583b443-d2fb-42c5-af8d-bca3842b6b62.png)
![mzmine1](https://user-images.githubusercontent.com/57141760/213802038-53a448e0-f344-4df8-a971-4229db32e08f.png)

**Comment by SteffenHeu** [comment]
Hi,

This is basically a safety feature that I never managed to trigger during the development. Can you please provide me the exact procedure on how to reproduce this error? This will probably include a sequence of processing steps in a specific order and their parameters.

Best

Steffen

**Comment by SteffenHeu** [comment]
Hello @kelloggresearchgroup , i'd like to fix this issue. Can you please upload a file + batch to reproduce this?

**Comment by kelloggresearchgroup** [comment]
Hey @SteffenHeu. As luck would have it, MZmine crashed on me shortly after posting this, and I haven't been able to reconstruct the error yet. Reconstructing the dataset and project from scratch seemed to fix whatever bug it was, and it has saved now with no errors.

**Comment by NNavrot** [comment]
Hello, I just had the same issue.

**Comment by NNavrot** [comment]
HI, I just got the same problem a couple of times now. 
Just importing raw .mzml files and press save project. No processing performed.
Basic information

    My operating system and version: Windows 10
    My MZmine version: 3.4.14



![image](https://user-images.githubusercontent.com/99479164/225306596-fcfe3b55-3933-475b-b975-85bf96291a51.png)

Cheers,
Nicolas

**Comment by NNavrot** [comment]
Hi,
I got the same issues, and after several tries, I think I found that using the "remove file extension" right-click function is the cause of this problem for me.
Nicolas

**Comment by SteffenHeu** [comment]
remove file extension was removed from mzmine.
