### ISSUE TITLE
Export for GNPS Feature Based Molecular Networking not working correctly

### ISSUE THREAD

**Issue by mcmk3** [mzmine/mzmine3#1089]
### Basic information

* My operating system and version: Windows 11, version 22H2
* My MZmine version: MZmine v3.3.0

### What happened

After processing my raw data files using a procedure modified from the MZmine 2 tutorials for prepping data for FBMN + IIN on GNPS, I obtain feature containing files, which I can export as standalone mgf and csv files without issue, but which will not correctly export using the GNPS FBMN export option (which I need for the edges annotation file).

Below screenshots of all my steps:

Step 1 - Data Import
![Step 1 - Data Import](https://user-images.githubusercontent.com/67341505/213832268-35237881-62f4-41ae-acc3-6cc8c515394c.png)

Step 2 a - MS1 Mass Detection Parameters
![Step 2 a - MS1 Mass Detection Parameters ](https://user-images.githubusercontent.com/67341505/213832279-9a7898d1-910e-47b4-bcb2-0ac0df9347fd.png)

Step 2 b - MS1 Mass Detection Parameters
![Step 2 b - MS1 Mass Detection Parameters ](https://user-images.githubusercontent.com/67341505/213832280-60a9462c-0901-4877-bbf1-87461766a3fb.png)

Step 2 b - MS1 Mass Detection Parameters
![Step 2 b - MS1 Mass Detection Parameters ](https://user-images.githubusercontent.com/67341505/213832292-a158906f-bc6c-4a84-931f-5cbb8c60edcf.png)

Step 3 - MS2 Mass Detection Parameters
![Step 3 - MS2 Mass Detection Parameters ](https://user-images.githubusercontent.com/67341505/213832300-39812110-3898-4803-a1d6-896213dc211c.png)

Step 4 - Build Chromatogram
![Step 4 - Build Chromatogram](https://user-images.githubusercontent.com/67341505/213832307-f2507ad2-6e65-4a97-8c62-84862c921854.png)

Step 5 - Deconvolve the Chromatogram
![Step 5 - Deconvolve the Chromatogram](https://user-images.githubusercontent.com/67341505/213832310-e4fdd85c-58d3-4594-aef3-f2c3e59fee16.png)

Step 6 - Group MS2 scans with features parameters
![Step 6 - Group MS2 scans with features parameters](https://user-images.githubusercontent.com/67341505/213832316-9703c9bd-5dee-403d-b805-0846b653f4c7.png)

Step 7 - Isotopic Peak Grouper Parameters
![Step 7 - Isotopic Peak Grouper Parameters](https://user-images.githubusercontent.com/67341505/213832322-ef116e7a-78ff-4654-acbb-654d3794c402.png)

Step 8 - Remove peaks with less than 2 data points or without a MS2 scan
![Step 8 - Remove peaks with less than 2 data points or without a MS2 scan ](https://user-images.githubusercontent.com/67341505/213832323-3418e31d-3644-464a-b3e2-a8c53ed16837.png)

Step 9 - Gap-filling parameters
![Step 9 - Gap-filling parameters](https://user-images.githubusercontent.com/67341505/213832324-5419d5e9-a0d7-418d-9b45-d81fe7c9c7d2.png)

Step 10 1 - Confirmation feature lists contain data
![Step 10 1 - Confirmation feature lists contain data](https://user-
images.githubusercontent.com/67341505/213832336-0041896f-1cde-4046-b3bc-2656c6921404.png)

Step 10 2 - Align features with join aligner parameters
![Step 10 2 - Align features with join aligner parameters](https://user-images.githubusercontent.com/67341505/213832343-eb38f8e2-f21e-43ae-957f-7432b0f3e76a.png)

Step 10 3 - Confirmation aligned feature lists contain data
![Step 10 3 - Confirmation aligned feature lists contain data](https://user-images.githubusercontent.com/67341505/213832344-ccb93e2d-38e6-4071-b887-4c548890f427.png)

Step 11 - Ensure features have MS2 scans assigned by repeating grouping of MS2 scans with features on 
aligned feature list
![Step 11 - Ensure features have MS2 scans assigned by repeating grouping of MS2 scans with features on 
aligned feature list](https://user-images.githubusercontent.com/67341505/213832352-3e7276e2-fc64-401e-8d09-98f2c716127b.png)

Step 12 - Subtraction of blanks from feature list
![Step 12 - Subtraction of blanks from feature list](https://user-images.githubusercontent.com/67341505/213832354-6bdfdb1e-00e7-43c5-a072-0f4b9e3db85b.png)

Step 12 1 - Confirmation aligned feature list with blank subtraction contains data
![Step 12 1 - Confirmation aligned feature list with blank subtraction contains data](https://user-images.githubusercontent.com/67341505/213832358-499bff9b-b827-4572-8bff-58ef34376a6d.png)

Step 13 - metaCorrelate feature grouping parameters
![Step 13 - metaCorrelate feature grouping parameters](https://user-images.githubusercontent.com/67341505/213832361-3cf739ce-b045-46d9-af3f-2306364ed94f.png)

Step 14 1 - Ion Identity Networking Parameters
![Step 14 1 - Ion Identity Networking Parameters](https://user-images.githubusercontent.com/67341505/213832367-8cee1b2b-b743-4721-8b88-18929a78796b.png)

Step 14 2 - Confirmation aligned feature list has data
![Step 14 2 - Confirmation aligned feature list has data](https://user-images.githubusercontent.com/67341505/213832365-7694bee1-8daf-4c3c-95e0-cb188227404b.png)

Step 15 - Export for GNPS
![Step 15 - Export for GNPS](https://user-images.githubusercontent.com/67341505/213832366-7f937544-503c-46c5-b386-2ea20624109e.png)

Export finished but unsuccessful
![Export finished but unsuccessful](https://user-images.githubusercontent.com/67341505/213832433-5c5b22c4-ac19-4118-89c2-823989370061.png)

These screenshots were for the full dataset, and I did not keep any previous feature lists due to memory limitations. Below I have provided the log file and standalone MZmine project file for a smaller subset of this data, for which I kept some of the inbetween feature lists, but otherwise used exactly the same process as for the full dataset.
The MZmine log file: 
[mzmine_log_file.txt](https://github.com/mzmine/mzmine3/files/10471322/mzmine_log_file.txt)

The standalone project file (for only a few of the raw data files) is here: 
https://www.dropbox.com/s/acft8ch13vnvgd8/microcosm.bottle.experiment.DOM.demo.mzmine?dl=0

Any insight or advise as to what might be wrong would be appreciated. Please let me know if there is any other information I can provide.
Apologies in advance if this is some stupid error on my part, I am still new to using MZmine.

**Comment by SteffenHeu** [comment]
Hi mcmk,

I can't look into the files currently, but all the steps seem adequate on first sight.

Some notes:
1. The gap filling runs on aligned feature lists, so you must execute it after alignment.
2. The fragment scans column in your feature table screenshots is always 0, so somethjg is probably wrong during Ms2 assignment. 
3. You can try running a workflow using the processing wizard (see top menu). It will produce fbmn files with default parameters, so there you could check if the files contain data then.

If that doesn't help you should check if the data actually contains Ms2 scans.

**Comment by SteffenHeu** [comment]
I looked into it, we had a bug in the Feature filter. The features with MS2s were removed instead of kept. You can remove that step for now, the GNPS export only exports features with MS2 anyway.

You don't have a lot of MS2s in your data, are you doing targeted analysis? Otherwise you should check your MS2 intensity threshold/target intensity.

**Comment by robinschmid** [comment]
The newest dev release has the fix. Or like Steffen suggested do not apply the filtering as its not needed

**Comment by mcmk3** [comment]
Thank you for all your help! 
I will apply the suggested fixes/improvements. I am not doing a targeted analysis, so it is good to know that my MS2 intensity threshold is probably too high.

**Comment by Federicopg-Github** [comment]
Hi,
I am having the same problem as mcmk3 with the latest version of MZmine 3.6 but the only feature filter options I am applying are: 13C isotope filter and Duplicate peak filter. Does anyone have a clue of what might be happening?
Thanks in advance,

**Comment by typewritermonkey** [comment]
> Hi, I am having the same problem as mcmk3 with the latest version of MZmine 3.6 but the only feature filter options I am applying are: 13C isotope filter and Duplicate peak filter. Does anyone have a clue of what might be happening? Thanks in advance,

I'm having the problem in MZMine 4.03. Its exporting the .mgf and feature table but not the supplementary pairs file I need for IIMN. Or rather, it only creates that file about half the time
