### ISSUE TITLE
New batch library export

### ISSUE THREAD

**Issue by christophuv** [mzmine/mzmine3#1091]
Hello

Thank you for MzMine3, it is a great software!
I want to use it for MSMS annotation for 1) database generation and 2) matching new experiments to these databases. 
In the new version a "Batch spectral library generation" feature is available, which causes some problems for me. 

### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.3.0

### What happened

After generation of feature lists from different files, I selected a couple of example spectra to export. Their names and adducts were set and then I wanted to export them (see attached screenshot). 
However, I am getting the error (not in the message box but in the red text at the bottom of the window) that the export cannot be generated as an object "AdductType" is None. 

Is this a bug or did I forget to set some parameter? Or is this AdductType information automatically derived from some previous processing module? 
I did not find any documentation of this (I guess based on the changelog) rather new module. 

Thanks for any help on how to correct this. 

Best regards, christoph
![2023_01_21_20_24_55_MZmine_3 3 0](https://user-images.githubusercontent.com/78472147/213894075-439b5614-f35e-4d00-8670-924b3cc29ff0.png)

**Comment by robinschmid** [comment]
Thanks for already trying out the new module. Documentation will follow. The idea is that you use the Local csv data base search to annotate your compounds and then create a spectral library fully automatically.
We still do not support manual annotations or even spectral library matches. Could be something for the future.

Are you generating reference spectra or just spectra of your compound of interest?

So a few things we are still working on:
- a file format that holds all information we have
- batch submission format for the GNPS libraries

Cheers
Robin

**Comment by christophuv** [comment]
Hello

Thank you for the quick reply. I wanted to generate a reference spectra library. So far I was using the local CSV database search. I will check the adduct annotations there - thanks for the hint!

Best regards, christoph

**Comment by christophuv** [comment]
Hello

Thank you for the hint. With that (adducts in the compound annotation rather than the manual annotation) it worked. 
Would it please be possible to export only a single spectra per compound with that new module? E.g., the most intense one or an average spectrum? 

Thank you!

Best regards, christoph

**Comment by robinschmid** [comment]
We are still changing a lot and making room for more options.
Also you should check out the feature that you actually only annotate the compounds that are actually in the sample. So in the metadata file during local database search you select the column with the data file name or an identifier inside the file name. 

For each precursor ion and energy we export a merged spectrum and the most abundant.
And one spectrum merged from all energies.

**Comment by christophuv** [comment]
Hello

Oh, that is convenient. Thank you, I will give it a try
