### ISSUE TITLE
SIRIUS export exports NEG mode with "CHARGE=-0" 

### ISSUE THREAD

**Issue by XsirdanielX** [mzmine/mzmine3#1092]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: MZmine3.3.0

### What happened

When exporting NEG mode LC-MS/MS data for SIRIUS  the scans in the mgf have "CHARGE=-0"

**Comment by robinschmid** [comment]
The development release has a new SIRIUS export. Maybe you could test this

**Comment by mfleisch** [comment]
We have adapted the SIRIUS `.mgf` importer in `v5.6.4` (still pre-release state) so that it can handle the `-0` values.

**Comment by robinschmid** [comment]
Very nice. 
The Sirius export is completely rewritten in the next release. And this should also be resolved. As well as other issues. 
Fingers crossed. 
Thanks @SteffenHeu

**Comment by SteffenHeu** [comment]
We default to charge state +-1 now.

Is it better for Sirius to keep zero if the charge state was not detected in the new version?

**Comment by mfleisch** [comment]
No, +-1 and +-0 is now handled identically in SIRIUS. Both will result in a  pos/neg single charged compound.
