### ISSUE TITLE
Error when saving project (RawDataFilesSelection.java:61)

### ISSUE THREAD

**Issue by ThuridurNott** [mzmine/mzmine3#1099]
### Basic information

* My operating system: Windows 10 64-bit
* My MZmine version: 3.3.0

### What happened
When I want to save a project I get this error:
![image](https://user-images.githubusercontent.com/116361496/214559221-917715c4-4958-4657-aed9-5ce4922ca37e.png)
It doesn't happen when I only have raw data but after I have run my batch and try to save, the error pops up. I also can't import the feature list after saving it as an mzTab. When I try I get this error:
![image](https://user-images.githubusercontent.com/116361496/214560107-ea093afd-5de6-425a-a97f-3ac1a4415d3a.png)
I thought the two might be related.
Here is a google drive with my batch, the log file, two of the mzXML sample files I use, and the mass calibrant file I use (idk if you need it but still). 
https://drive.google.com/drive/folders/17IfRk-ET44fX_QOlN3vcczfgapen-N_g?usp=sharing

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
Hi, thank you for the report. This will be fixed in the next release.

you can use the "Artifacts" from here: https://github.com/mzmine/mzmine3/actions/runs/4072451379 for now.
