### ISSUE TITLE
precursor m/z issue

### ISSUE THREAD

**Issue by jcanderan** [mzmine/mzmine3#1101]
### Basic information

* My operating system and version: Windows 11
* My MZmine version: 3.3.0

### What happened

There seems to be an discrepancy with how mzmine determines the precursor m/z versus how other programs may determine it.

I converted a Thermo RAW file to mzml using ThermoRawFileParser (latest version). We end up with the following in an example scan:

` <cvParam cvRef="MS" accession="MS:1000827" value="658.32958984375" name="isolation window target m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />`

`<cvParam cvRef="MS" accession="MS:1000744" value="657.9956" name="selected ion m/z" unitAccession="MS:1000040" unitName="m/z" unitCvRef="MS" />`

mzmine3 seems to use the isolation window target m/z as the precursor mz, but other programs, such as PeptideShaker, use the selected ion m/z, which makes targeted peak detection more challenging.

mzmine:
![image](https://user-images.githubusercontent.com/23535425/214709050-eaab1734-48b1-405f-84d6-45c12ae9d415.png)

peptideshaker (it rounds to 658.00 here but will be 657.9956 in an export):
![image](https://user-images.githubusercontent.com/23535425/214709746-80c9e4fa-37c4-47d6-beb2-1b635d59c2d3.png)

There is an example discussion about this issue here: https://github.com/OpenMS/OpenMS/issues/4168

Their solution seems to be to support either method by user choice but it may be that selected ion m/z is more appropriate.

Thank you.

**Comment by SteffenHeu** [comment]
@robinschmid this is your work :D

**Comment by robinschmid** [comment]
So in our code we have this comment and we currently prefer the isolation center over the isolation MZ. 

> use center of isolation window. At least for Orbitrap instruments and
     msconvert conversion we found that the isolated ion actually refers to the main peak in
     an isotope pattern whereas the isolation window is the correct isolation mz
     see issue https://github.com/mzmine/mzmine3/issues/717

**Comment by jcanderan** [comment]
Thanks for the reply. I'll close the issue and work around it some other way.
