### ISSUE TITLE
error when opening the porject

### ISSUE THREAD

**Issue by AnaKovacic** [mzmine/mzmine3#1117]
### Basic information

* My operating system and version:windows10
* My MZmine version: 3.3.0

### What happened
I am storing all data on my transferable disk, including .raw, mzML, and mzmine projects. 
When switching to another computer using a transferable disk, and when trying to open the project I received the following error. 
Could not open the batch, mzML import via MSDK. please see the print screen of the error attached. Could you maybe advise me on how (if still possible) to open the project also on another computer? 
Please find the mzML data and project on the following link: 
https://drive.google.com/drive/folders/1Au8p0VBuDN6o6eTG4d-2ZaIYrZwEnIzU?usp=share_link
<img width="956" alt="mzmine error opening the project" src="https://user-images.githubusercontent.com/72231221/216296223-679ede25-b7b2-4683-ab52-d471f863cd11.png">

Thank you.
Ana

**Comment by SteffenHeu** [comment]
Hi Ana, 

you can save the project as a standalone project, then it can be opened on other PCs without further limitations. When saving it as a referencing project, all paths must stay the same. This means that you have to ensure that the transferable disk is assigned to the same letter on both machines.

**Comment by AnaKovacic** [comment]
Hi Steffene,

thank you for the answer.
Best
Ana
