### ISSUE TITLE
How to convert Waters QTOF raw data for MZmine 3?

### ISSUE THREAD

**Issue by QiuguoFu** [mzmine/mzmine3#1124]
### Basic information

* My operating system: windows
* My MZmine version: MZmine 3

### What happened
Is there a solution to easily convert Waters QTOF raw data for MZmine 3 analysis? Thanks

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by elnurgar** [comment]
Hello. You can use msconvert module of Proteowizard.

Do you have ms2 spectra?

**Comment by QiuguoFu** [comment]
Thank you for your advice. Yes, we have ms2 spectra. Our data are acquired
by Wasters QTOF in MSe mode. MSe data seems not to work well for MZmine 2
because some people used  Proteowizard to  transform MSe raw data into mzML
or mzXML file, but they didn't work well. For convenience, our lab just
sticks with waters data processing software UNIFI or Masslinks. I am not
very sure if MZmine3 has fixed this issue for waters data?

**Comment by elnurgar** [comment]
There is a problem of m/z values drift of precursor values for Waters. Here is some explanation. https://github.com/elnurgar/mzxml-precursor-corrector

**Comment by Sanchezillana** [comment]
Also now the proteowizrd people are working on this issue. https://github.com/ProteoWizard/pwiz/issues/1922

**Comment by robinschmid** [comment]
Did someone try this converter for water?
https://github.com/AnP311/Waters2mzML
