### ISSUE TITLE
MZmine3.3 will not open on MAC 12.6 Monterey

### ISSUE THREAD

**Issue by rklep** [mzmine/mzmine3#1125]
kleps@uic.edu  224 422 6200

Downloaded mzmine 3.3 as .dmg, put into APPs, tried to open and Mac called it damaged and to trash it.

Downloaded mzmine 3.3 as .zip , unzipped, moved to APPS, tried to open and got error could not open!
 SEE 10 images below

I think for version mzmine 2 I was given some commands to put into Terminal before mzmine would run.

There was difference in bits between image 8 vs 9

![mzmine--kleps1](https://user-images.githubusercontent.com/80644780/216790233-95ff7668-b038-4853-9ff8-a8f4e06c36fd.jpeg)
![mzmine--kleps2](https://user-images.githubusercontent.com/80644780/216790234-eeebdb54-7490-497a-b63d-3d7e652daed5.jpeg)
![mzmine--kleps3](https://user-images.githubusercontent.com/80644780/216790235-51148ece-2c2b-4455-b660-ed921362bf6f.jpeg)
![mzmine--kleps4](https://user-images.githubusercontent.com/80644780/216790236-a6d5e1b8-f65b-40fb-b9df-fe2374875a3d.jpeg)
![mzmine--kleps5](https://user-images.githubusercontent.com/80644780/216790237-85dd881e-edfe-47d2-9dc7-db07ed5c433a.jpeg)
![mzmine--kleps6](https://user-images.githubusercontent.com/80644780/216790238-ef247fe1-a4bf-4c80-8aae-b28f9e8b3b0a.jpeg)
![mzmine--kleps7](https://user-images.githubusercontent.com/80644780/216790239-282c0c93-ba4f-4a30-94d5-1de00b99a7eb.jpeg)
![mzmine--kleps8](https://user-images.githubusercontent.com/80644780/216790240-8e0c9757-6fb8-4045-806b-4151c9c7e049.jpeg)
![mzmine--kleps9](https://user-images.githubusercontent.com/80644780/216790241-f492583f-03e1-4ab1-b466-d3a4ecce0763.jpeg)
![mzmine--kleps10](https://user-images.githubusercontent.com/80644780/216790243-c474eada-1fbe-42e8-9da3-30e7402da251.jpeg)

* My operating system:
* My MZmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
did you try the how to run on mac os guide?

**Comment by rklep** [comment]
Thank you, I will try your suggestion.

Rob Kleps
________________________________

**Comment by rklep** [comment]
I used your suggestion for terminal within the mzmine icon in APPs.

Root passwd didn't work for sudo and I could not use sudo because I'm not listed in sudoers file

BUT

the big issue is that mzmine did NOT appear in the utilities app as an unknown supplier thus I could not override the MAC protection to open it.

A side issue is why did downloading the .dmg and .zip produce different error messages? Shouldn't both downloads yield the same program?

Rob Kleps


________________________________

**Comment by tomas-pluskal** [comment]
`sudo` normally works as long as your account is listed as Admin in the macOS preferences. What is the exact problem you had?

we are now working on digitally signing the macOS packages, but it will still take some time.

**Comment by rklep** [comment]
Thanks for the fast reply.

When discussing software there are two words I always fear hearing "should" and "normally"
I have download both mzmine.dmg and .zip on different macs and got the same results.

ADMIN was listed in /etc/sudoers when I last checked, but now ADMIN and rob cannot look at the file to see who is listed.

Looks like there may be three issues:
#1  .dmg and .zip downloads produce different results in errors
#2  mzmine does not appear in utilities>security as an untrusted app
#3  I cannot show what is in /etc/sudoers. It is listed as readable, but I can't read it.

Do you have any suggestions for solving any of the three problems? Could zsh be an issue?

Rob Kleps


________________________________

**Comment by tomas-pluskal** [comment]
Please forget about /etc/sudoers. I was asking if your user account is listed as Admin in the macOS preferences.

<img width="706" alt="Screenshot 2023-02-06 at 18 37 37" src="https://user-images.githubusercontent.com/1796692/217044323-c0318012-b295-4fc1-a561-8a1244b72b36.png">

**Comment by rklep** [comment]
My account rob is not an admin.

The admin is named ADMIN

Thanks again for the quick reply. I've been away all day.

Rob
________________________________

**Comment by tomas-pluskal** [comment]
Well, why don't you change your account to admin and try again?

**Comment by rklep** [comment]
I switched to my macmini OS 12.6 same as macbookpro.

logged in as admin download mzmine3.3.dmg , installed in APPs, tried to open got error,"file is damages send to trash"  Deleted
downloaded mzmine3.3.zip, unzipped, click to install got error"Cannot open" went to utilities and could not find mzmine listed so could not override mac's protection.

Being admin didn;t help.  Why are .dmg and .zip yielding different results?

I saw that other MAC users got mzmine3.3 to download and open then they ran into usage errors.

Any idea what my problem is with getting mzmine3.3 to run?

Rob Kleps
________________________________

**Comment by rklep** [comment]
While on Mm I reloaded .dmg into Apps then used yuour suggestion of opening terminal in the mzmine folder

sudo zattr -cr  ../MZmine.app

AND IT WORKED

Need to leave witout testing mzmine

Back in one hour

Rob
________________________________

**Comment by tomas-pluskal** [comment]
Rob, please follow the instructions here: https://mzmine.github.io/mzmine_documentation/getting_started.html#on-macos

**Comment by rklep** [comment]
In my last email I said that logging in as admin then running your terminal script in the mzmine.app worked.

As admin I opened mzmine then changed permissions so rob could read/write mzmine.
logged out and back in as rob
As rob mzmine opened. I set preferences and tried to open a Thermo.raw file I'd used before, but got an error message.

I'm getting paranoid and more confused.

Rob Kleps
________________________________

**Comment by tomas-pluskal** [comment]
If you have a different problem, please file a new issue for that problem, thanks.
