### ISSUE TITLE
Scans not sorted in retention time dimension (Waters mzML MSE)

### ISSUE THREAD

**Issue by Melakail** [mzmine/mzmine3#1126]
### Basic information

* Windows 64 bit
* Mzmine3.2.8

### What [happened](https://drive.google.com/file/d/1uvn_6VNGKHWmzPXwv1F3CxAPIRPupcCP/view?usp=sharing)

* I cannot use the ADAP chromatogram builder step because I get the following error attached
* I converted the raw files generated on a Waters MS to mzML
* I did the mass detection step 
![mzmine3prob](https://user-images.githubusercontent.com/124526795/216841000-3f6c0f65-be84-42a9-8264-5d1ccd1d094f.png)
 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by robinschmid** [comment]
We need more details on the data and a test dataset. 
First try the lastest mzmine version to see if the issue persists. 
The data formats from waters are weird sometimes

**Comment by Melakail** [comment]
https://drive.google.com/file/d/1uvn_6VNGKHWmzPXwv1F3CxAPIRPupcCP/view?usp=sharing
The mzML file. It was a .raw folder initially which I converted with MSconvert

It is MSe data. 

I tried Mzmine3.30 and the issue still persists unfortunately

**Comment by robinschmid** [comment]
Not sure how to takle this. Waters data comes in many different structures and its very different to the data from other vendors. 

I have to see if we can do something internally.
Did you try to convert with this converter - this might be another solution:
https://github.com/AnP311/Waters2mzML
