### ISSUE TITLE
Online compound database search

### ISSUE THREAD

**Issue by AnaKovacic** [mzmine/mzmine3#1137]
### Basic information

* My operating system and version: windows10
* My MZmine version: 3.3.0
### What happened
I am trying to run the online compound database search, using ChemSpider, but I am receiving the error attached.  
I was also trying by reducing the aligned list, but still, the same window appears.  I have tried will all databases, and the only one that does work is HMDB. Could you maybe advise me on how can I run the online database search also by using ChemSpider or PubChem? 
Thank you.
Best
Ana
<img width="521" alt="parameters" src="https://user-images.githubusercontent.com/72231221/218054556-31f02aa5-0e35-49bc-9b62-694a715dac2c.PNG">
<img width="351" alt="pubchem error" src="https://user-images.githubusercontent.com/72231221/218054576-b5fd0bd0-05f5-40a4-94ab-259a4f3cde48.PNG">
<img width="345" alt="chemspider error" src="https://user-images.githubusercontent.com/72231221/218054687-fc1d2232-7d8c-4542-90a0-512bdb112114.PNG">

**Comment by robinschmid** [comment]
This module is not really well maintained and also discouraged to use. 
There are way better tools for compound annotation.
You can use spectral library matching with open databases,
a local CSV compound database search,
export the feature finding results to SIRIUS and then use their workflow for annotation.

**Comment by AnaKovacic** [comment]
Yes, also for me first time, until know I was always using sirius.
I have DIA data but i have run also dda and I will annotate based on that,
just wanted to try how to make it work.

Thank you for the feedback.

Best.Ana

**Comment by robinschmid** [comment]
DDA is usually easier to work with. 
FOr any other issues open a new issue or conversation :)
