### ISSUE TITLE
Export Raw Data in Mzmine 3

### ISSUE THREAD

**Issue by ThaoPDoan** [mzmine/mzmine3#1138]
Dear all, 

I am following the untargeted LC-MS workflow found on this link:  https://mzmine.github.io/mzmine_documentation/workflows/lcmsworkflow/lcms-workflow.html

I'm always got the error when trying to export raw data (after importing one data in) 
I use "Export raw data" > "Export MS(n) trees"
The error I have is : "Could not open file C:\Program Files\ Mzmine for writing"

The main point of getting MS(n) trees out is to have a better view of the MS/MS spectra to set up the parameters for m/z tolerance and retention time tolerance. 

All in all, our project is to find effective way to analyze LC-MS data (.mzXML) based on MS/MS, retention time, m/z and intensity across all data/samples. I wonder what is the ultimate way to do so.

Best,
Thao.

**Comment by robinschmid** [comment]
Hey Thao,
check out the MZmine documentation page there is a lot of information.
ALso we have some videos on youtube on how to start with MZmine.

In general try the MZmine processing wizard to setup batch processing. It contains the most important steps and also allows annotation by spectral library matching.

You can also import and double click on a file in mzmine to look at spectra and chromatograms.

cheers
Robin
