### ISSUE TITLE
Feature list very slow

### ISSUE THREAD

**Issue by mountfort** [mzmine/mzmine3#1149]
### Basic information

* My operating system and version: Windows 10 Enterprise 21H2
* My MZmine version: 3.3.0

### What happened

When processing a large number of untargted lipid files (14,14) in MZmine3 the feature list becomes very slow to sort due to the shape drawing column taking a very long time to populate. Is there any way to hide this column whilst you filter the data? The PC has plenty of memory so i don't think that is the issue and the processor is not being taxed overly whilst it is doing this...

The standalone project is a bit big to upload.

**Comment by robinschmid** [comment]
Usually, we implemented a safeguard that the visual columns with charts are deactivated by default for all big datasets.
Will need to see that this works in all cases

**Comment by tomas-pluskal** [comment]
What was discussed during the MZmine web cafe:
1. The Shapes column can be hidden using the + button in the top right corner. The same button can be used to configure all other columns in the table.
2. The "Feature list rows filter" can be used to filter away some peaks (e.g., low intensity signals) before opening the feature list.

**Comment by mountfort** [comment]
Thanks for this. On e thing I could not see in the filter was the number detected in a % of the samples which would be the best way to filter when you have plenty of samples?

**Comment by mountfort** [comment]
Should I open a separate  case about the IDs?

**Comment by tomas-pluskal** [comment]
Yes, please open a separate issue for each problem. 
Regarding the addition of the additional option to the filtering module, that is quite easy to implement. Would you like to volunteer? :)

**Comment by mountfort** [comment]
Sure I can try giving it a go...

**Comment by robinschmid** [comment]
This issue is fixed by #1159 
All shape columns will be hidden automatically for datasets with >N samples. default is 12. 
![image](https://user-images.githubusercontent.com/10366914/220083001-b87d1a7a-2377-47ef-8e71-476f8c36dfea.png)

**Comment by robinschmid** [comment]
As for the relative number of samples.
This was already addressed in the next release. You can now provide both.
![image](https://user-images.githubusercontent.com/10366914/220084930-d9bc45ee-193d-4252-987b-71ad86d04bee.png)
