### ISSUE TITLE
The Platform does not provide 3D-Support (linux)

### ISSUE THREAD

**Issue by fdiversion** [mzmine/mzmine3#1150]
### Basic information

* My operating system and version: Siduction (Debian sid, Gnome on Wayland)
* My MZmine version: 3.3.0 from deb package

### What happened

Show 3D-Plot -> Dialoglogbox stating: The Platform does not provide 3D-Support.
All other diagrams work.
Hardware: AMD Ryzen™ 7 5800X and AMD Radeon™ RX 460 Graphics

**Comment by tomas-pluskal** [comment]
It seems JavaFX cannot use the 3D capabilities of your hardware. Not sure what the reason is - might be missing drivers in the linux kernel, for example, hard to say.
