### ISSUE TITLE
New User: Mass Lists were not detected in all files

### ISSUE THREAD

**Issue by agnilili** [mzmine/mzmine3#1153]
### Basic information

* My operating system: macOS Monterey 12.0
* My MZmine version: MZmine 3, 64-bit, java -version

Hi, I am struggling in using MZmine 3. 
I input the file, one at the time. The steps that I did: raw data methods > raw data import > mzML > choose the file > open > status:FINISHED > show raw data overview

but the mass list were all in red “x“ sign as showed in the screenshoot attached below. Then I cannot do the chromatogram building and the peak deconvolution.

<img width="1352" alt="Screen Shot 0005-02-18 at 18 38 46" src="https://user-images.githubusercontent.com/124765919/219853716-55031cb3-45ef-40d3-8e19-192eb9346258.png">

I am looking forward to your guidance how to do better. Thank you

**Comment by tomas-pluskal** [comment]
The mass list can be added by the Mass detection module, see the basic workflow here: https://mzmine.github.io/mzmine_documentation/workflows/lcmsworkflow/lcms-workflow.html

Or video tutorial: https://www.youtube.com/watch?v=hk7WeXibReg&list=PL0JAF-4UFc8N8DxAIOoF2cMSKy-wC4WWG&index=7&t=650s

**Comment by agnilili** [comment]
Ok, I am following your steps until from youtube until the ADAP chromatogram builder but still the mass list is not available. Here I attach the screenshoots of what I just did:

<img width="1352" alt="Screen Shot 0005-02-18 at 19 43 09" src="https://user-images.githubusercontent.com/124765919/219856684-90421cdd-1744-4e14-989c-390321de630e.png">

<img width="1352" alt="Screen Shot 0005-02-18 at 19 44 36" src="https://user-images.githubusercontent.com/124765919/219856695-7e3d6499-0605-4e9b-a00f-863c51662845.png">

<img width="1352" alt="Screen Shot 0005-02-18 at 19 44 52" src="https://user-images.githubusercontent.com/124765919/219856711-8dfaa4c7-1f0d-4213-aefd-4704111dbe3a.png">

<img width="1352" alt="Screen Shot 0005-02-18 at 19 55 06" src="https://user-images.githubusercontent.com/124765919/219856727-2969fdd5-1e64-4bf5-a633-a430245ee31a.png">

Looking forward to your further guidance. Thank you

**Comment by tomas-pluskal** [comment]
Why did you set `Scan definition: 1` in the Mass detection parameters?

**Comment by robinschmid** [comment]
You should not apply scan filtering in mass detection. Make sure that its applied to all scans - so no RT filter etc.
Only if needed, you can do mass detection on MS level 1 and then a second step on MS level 2.

**Comment by agnilili** [comment]
Hi all,
Thank you for your responses. Silly me, I click the wrong close button below yesterday.
About the mass detection, I tried again and not applied the scan definition. But, still I got the same result. Here I attached the screenshots for what I had done.

<img width="1352" alt="Screen Shot 0005-02-20 at 9 03 00" src="https://user-images.githubusercontent.com/124765919/219984413-74bae38b-ef76-4a65-88b8-e852a0ee41a6.png">

<img width="1352" alt="Screen Shot 0005-02-20 at 9 03 22" src="https://user-images.githubusercontent.com/124765919/219984471-7c485cfd-b784-4dd1-acfe-b44ed356c270.png">

I still do not get the mass list when I saw the raw data overview:
<img width="1352" alt="Screen Shot 0005-02-20 at 9 03 37" src="https://user-images.githubusercontent.com/124765919/219984553-33f2c52e-a054-441b-b318-9dbbb6598ef5.png">

Then, I changed the MS level 1 into MS level 2, and here what I saw:
<img width="1352" alt="Screen Shot 0005-02-20 at 9 04 46" src="https://user-images.githubusercontent.com/124765919/219984636-51b1a226-eb25-449b-ae9a-db1da3c262b4.png">

so when I run the ADAP chromatogram builder, it was written the files do not have a mass list as I attached below:
<img width="1352" alt="Screen Shot 0005-02-20 at 9 09 50" src="https://user-images.githubusercontent.com/124765919/219984779-413e71a2-b0a2-4ab9-a7d3-1a1c6098ed7d.png">

What should I improve? Thank you in advance.

Best regards,
Agni

**Comment by robinschmid** [comment]
Just press on the clear button for the scan filter. Do not apply a retention time range filter. Those fields should be blank.

**Comment by agnilili** [comment]
OK. I got it now. Thanks heaps!!! 
Please check the attached picture below. Is it correct?

![Screenshot (1)](https://user-images.githubusercontent.com/124765919/220094364-52045286-73fc-4827-930d-a87cf20d5174.png)

**Comment by robinschmid** [comment]
Make sure to apply mass detection to all scans.
either clear all scan filters in mass detection to do it in one step or if the noise levels are different for MS1 and MS2 then apply the mass detection 2 times. once for each MS level.
You can see in here
<img width="285" alt="image" src="https://user-images.githubusercontent.com/10366914/222226339-054737d8-2d05-4b93-834b-1ed04cc70c0a.png">
