### ISSUE TITLE
Feature identification using online databases

### ISSUE THREAD

**Issue by msheltra** [mzmine/mzmine3#1165]
### Basic information

* My operating system and version: Windows 10, 64 bit
* My MZmine version: 2.53

### What happened
I've been trying to identify some features once my data had undergone mass detection, chromatogram building and deconvolution, filtering, alignment, row filtering and gap-filling. I tried to use the online database search function in the identification menu, using the following parameters: Database: MassBank.eu, Ionization type: [M]-, number of results: 20, m/z tolerance 0.05 or 10ppm. I've tried running this process using a few of the different databases listed in the dropdown menu, but everytime it fails, and I get a pop-up message saying something similar to the screenshot attached here. 
* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed
![mzmine_error](https://user-images.githubusercontent.com/57718562/220206867-0bcbcd4d-d75d-4f5c-9008-7c5564ae002e.PNG)

**Comment by agnilili** [comment]
Hi, I have just tried the NIST library with .msp format and it works. If I am not mistaken, I ran the [aligned feature list gap-filled] with only NIST library, which is a long way after I resolved/deconvoluted, deisotoped, aligned feature list of all the samples, and finally the aligned feature gap-filled then run it for online database for only the [aligned feature list gap-filled] file. But, you have to wait around 1-2 hours until the work is done. Then, you can check again the file. Maybe you can try the library one at the time and how it works

**Comment by robinschmid** [comment]
We will actually deactivate the online database search. Its unmaintained and uses old APIs and entry points for the different libraries. 
The best way is to either download spectral libraries and perform spectral library matching (see documentation).
Or create a compound library as CSV with RT and m/z values to identify compounds.

**Comment by agnilili** [comment]
Hi @robinschmid 
Regarding the spectral libraries, I used NIST and MoNA after I gap filled the join aligner. My question, can I use directly the result of annotation using those two libraries to confirm the unknown compound in my samples? Or is there any further suggestion for the unknown compound analysis?

**Comment by robinschmid** [comment]
This is usually the best way you can see results in the feature table and also export to file.

**Comment by robinschmid** [comment]
closing this issue as we removed the online DB search
