### ISSUE TITLE
Create export of all CompoundAnnotations to csv

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#1166]
- [ ] FeatureListRow.streamAllFeatureAnnotations  (includes spectral library, compound library, lipid, ...)
- [ ] long table format, one row in CSV per annotation
- [ ] based on CompoundAnnotation interface
- [ ] use DataType uniqueID to name columns

**Comment by shamlymhd** [comment]
@robinschmid Can you please let me know if I am allowed to start working on this issue?

**Comment by Kaushik2201** [comment]
I Want to work on this project

**Comment by shekar007** [comment]
Hi, I would like to work on this issue. 
Can you guide me how to proceed?

**Comment by shamlymhd** [comment]
@Kaushik2201  and @shekar007 Based on my understanding, there is a need to add a new feature to the **Export feature list** Menu in the io.github.mzmine module. Specifically, this feature involves creating a MenuItem that enables the user to export all CompoundAnnotations to CSV. It appears that there are already other export options available under the (io.github.mzmine -> modules -> io) directory, but it is unclear if anyone is currently working on this particular issue. If nobody is working on this issue, one of us can work on it while others can work on other issues that need to be resolved in the module. please give us a reply @robinschmid

**Comment by shamlymhd** [comment]
I'm starting to work on this issue because it seems like no one else is working on it, and Robin Schmid is unavailable these days

**Comment by robinschmid** [comment]
@shamlymhd you can try out this issue.
We have documentation on how to contribute:
https://mzmine.github.io/mzmine_documentation/coding/general_structure.html

You can for example look into these classes for reference:
- SiriusExportModule: defines the module name etc
- SiriusExportParameters: defines the user parameters they can set by a dialog. For example, FileNameParameter to save a new file to disk
- SiriusExportTask: defines the logic

You can also look at the classes in package `io.github.mzmine.modules.example`

**Comment by robinschmid** [comment]
- You will need a FeatureListParameter and FileNameParameter
- in the task, you loop through all feature lists that were selected and export all into the same file
- structure is for each: FeatureList[] --> FeatureList.getRows() --> FeatureListRow.getAllFeatureAnnotations()
- this will give you a List<Object> because we are still in the process of changing all Annotation classes to FeatureAnnotation

For now you can just filter and only export all field that you find in FeatureAnnotation:
```java
if(object instanceof FeatureAnnotation annotation) .... export
```

**Comment by Kaushik2201** [comment]
Thank you @robinschmid for letting us know what can be done . I will too start working on this issue.

**Comment by robinschmid** [comment]
It does not make sense if multiple people work on this

**Comment by shamlymhd** [comment]
I started to work but it's okay. @Kaushik2201 Could you please inform me of your decision regarding this? If you are willing to work on it, that would be great. I may need to prioritize another issue. 

@robinschmid I just tried to use MZmine 3 using the given dataset. but I couldn't import it because it says that "it cannot be opened with MZmine 3.3.48. where can I find the sample dataset for MZmine 3.3.48?

**Comment by Kaushik2201** [comment]
@shamlymhd You may continue with this issue I will try any other.

**Comment by shamlymhd** [comment]
Ok Sure @Kaushik2201. keep in touch. also, I was able to find the sample dataset here: https://youtu.be/hk7WeXibReg

**Comment by robinschmid** [comment]
That is a good dataset to use. 
But in general for this small task it is not necessary to test anything.
If someone is taking on this task you can start by 
1. creating a new branch, 
2. draft pull request to the MZmine 3 main branch 
3. Creating the Task, Module, and Parameters classes

**Comment by shamlymhd** [comment]
I have created the draft pull request: https://github.com/mzmine/mzmine3/pull/1213
