### ISSUE TITLE
Error message Failed opening project: java.util.zip.ZipException: zip END header not found (ZipFile.java:1483)

### ISSUE THREAD

**Issue by froz9** [mzmine/mzmine3#1173]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.3.0

###Hello,

I'm writing this asking for any help. I had problems when I tried to open my project (.mzmine extension file) and I got this error message: "Failed opening project: java.util.zip.ZipException: zip END header not found (ZipFile.java:1483)"  and I don't know what to do.

![Captura1](https://user-images.githubusercontent.com/73253478/220499546-42538986-c2eb-4b70-827a-085a635f0dbd.PNG)
![Captura2](https://user-images.githubusercontent.com/73253478/220499566-93dc9fc0-c770-4c3c-a31c-23ffa52795dd.PNG)

I'll provide you with some background on how I came to this situation: My SSD failed due to an electric problem, and the computer technician told me that I lost the contained data. I didn't feel worried at first because I thought that I have written down all the parameters that I used in my analysis, but then I noticed that they were wrong and I couldn't recreate the original results. During our conversation, the technician said he used software to rescue some of the available files, but they were corrupted and I receive the error message mentioned earlier. 

Fortunately, I have exported the FBMN and the SIRIUS MGF files that I needed, but the PI asks me for the parameters and here I am. 

If someone could assist me in extracting the parameters I used, I would be very grateful, I don't need to open it again.

I would appreciate it if someone could help me. Best regards.

PD. I uploaded the recovered files to my drive account, here's the link to them.

[https://drive.google.com/drive/folders/1_8nbGjC0V41a-2E8jql8TvntRTC1iujs?usp=sharing](url)

**Comment by agnilili** [comment]
Hi
May I join this conversation. I also encounter the same problem. I hope any developer can guide us @SteffenHeu or @robinschmid.

The steps that I have been through are listed below
1. Mass detection: MS level 1, centroided

2. Feature detection: LC-MS, ADAP chromatogram builder, MS level 1, centroided, min group size in # of scans 4, group intensity threshold 3E5, min highest intensity 5E5, scan to scan accuracy (m/z) 0.002 m/z or 10 ppm, suffix chromatogram
<img width="1352" alt="ADAP" src="https://user-images.githubusercontent.com/124765919/221093505-f1cca301-b062-4200-aec1-edbc56868738.png">
 
3. Chromatogram resolving, local minimum resolver 
<img width="1352" alt="local minimum feature" src="https://user-images.githubusercontent.com/124765919/221093639-e6a5cb52-ed86-4b2c-9283-3c40e66aed07.png">

4. Isotopes, 13C isotope filter
<img width="1352" alt="isotope" src="https://user-images.githubusercontent.com/124765919/221093653-6ebe606e-e444-4f0d-b060-1c2f6bf4f242.png">

5. Alignment, join aligner, get the aligned feature list
<img width="1352" alt="join aligner" src="https://user-images.githubusercontent.com/124765919/221093713-75cf58cd-75e2-4bd2-9220-2194b282150c.png">

6. Gap filling, peak finder
7. Annotation, search spectra, spectral library search on aligned feature list gap-filled file
8. Project, save project, standalone, ok
<img width="1352" alt="save project" src="https://user-images.githubusercontent.com/124765919/221093784-2632e917-7f57-4ba8-86ce-aaf8e893e09c.png">

9. I close the program and open again the program

10. Project, open project, choose project, open the saved project but then I got this notification
<img width="1352" alt="Screen Shot 0005-02-24 at 12 31 10" src="https://user-images.githubusercontent.com/124765919/221093894-ce2e8b08-05b0-4279-887a-50d6133d8356.png">

Looking forward to your guidance. Thanks

Best regards,
Agni
