### ISSUE TITLE
"Some scans were recognized as empty (no detected peaks)." 

### ISSUE THREAD

**Issue by LuisMoreira50** [mzmine/mzmine3#1184]
### Basic information

* My operating system and version: windows 10 64bit
* My MZmine version: 3

Hi. I have imported my data to MZmine but I cannot apply any method because of the problem described in this printscreen. What can i do? Thanks in advance
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/126248442/221168339-328a653f-ad32-4109-8b21-f6520b42a66a.png">

**Comment by robinschmid** [comment]
Thats only a warning.
First check that your data conversion was correct. Usually its enough to ensure that the data is in centroid mode. Although MZmine can also handle profile mode data.

You can also open a file in MZmine by double clicking on one in the left list next to the scary warning symbol. 
Does the raw data overview open - and work for your data?

Also just try to apply regular feature finding workflow - e.g., guided by the processing wizard.

**Comment by LuisMoreira50** [comment]
Instead of using the converted files, i used the raw files and it works. Thanks!
