### ISSUE TITLE
RT wildcard not working in Local compound database search

### ISSUE THREAD

**Issue by pavelsmak** [mzmine/mzmine3#1187]
### Basic information

* My operating system and version: MacOS Ventura 13.1
* My MZmine version: 3.3.0

### What happened

Local compound database search does not process retention time of 0 as wildcard (as it should according to the documentation). This results in database records with RT = 0 not being identified. Setting retention time tolerance to a high value (such as 30 minutes) fixes the issue, meaning that RT = 0 is actually interpreted as RT = 0 (instead of wildcard).

Used database file example:
[arginin.csv](https://github.com/mzmine/mzmine3/files/10838107/arginin.csv)

**Comment by robinschmid** [comment]
You are right. Thanks fro reporting. Should be fixed in the next release.
