### ISSUE TITLE
MZmine crashes after screen resolution change?

### ISSUE THREAD

**Issue by mountfort** [mzmine/mzmine3#1190]
### Basic information

* My operating system and version: Windows 10 enterprise
* My MZmine version: Development version 2.3.44

### What happened

I am having issues where MZmine crashes whilst using a virtual server. It appears the Java engine crashes in the background. Our local IT support has asked if it is possible to turn on more verbose logging so they can see if they can figure out the problem. Is this possible?

**Comment by robinschmid** [comment]
It's a known issue that only appears on windows. Only the GUI freezes. So the data processing runs fine in the background. You can open the log file in the user folder and see that it still prints out things. 
There is a new javafx version that fixes this issue but it breaks the feature table.

**Comment by mountfort** [comment]
Ah okay thanks for the update. Will this be fixed any time soon or should I swap to Linux?

**Comment by robinschmid** [comment]
if you have that option you could do that.
Not sure when this will be fixed. We could also build a version where the remote works but the table bugs out sometimes

**Comment by SteffenHeu** [comment]
Will most likely be fixed in the next release.
