### ISSUE TITLE
Export of feature list as mzTab -m not working

### ISSUE THREAD

**Issue by CorinaMeyer** [mzmine/mzmine3#1194]
### Basic information

* My operating system and version: Windows Server 2012
* My MZmine version: 3.3

### What happened

After processing, I tried to export a feature table in mzTab -m format. However, I get the following error:
![image](https://user-images.githubusercontent.com/126093869/222162852-1f496474-22b3-4bb9-a741-c9cc12810ba8.png)
So it seems that somehow the columns get shifted.

The log file is attached: 
[20230301_mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/10861838/20230301_mzmine_0_0.log)
In the log file it reads that "The number of Data line items is "13", whereas the number of header line items count is "64". They MUST be the same." 

I wonder how I can influence the mzTab columns. I also tried to export it as mzTab, not mzTab-m, where I get an output, but the identifier is set to "null" for all entries. I would have had expected it to be numbers like 1,2,3... Such an identifier would be nice for further data processing.

Best,
Corina

**Comment by robinschmid** [comment]
@omokshyna and @nilshoffmann are working on this. But this will still need some time. Sorry for the inconvenience.
