### ISSUE TITLE
Unusual Isotope Search on MZmine

### ISSUE THREAD

**Issue by RicardoMBorges** [mzmine/mzmine3#1203]
Hello, this might not be an issue or a feature request actually. I'm quite sure it's possible but I couldn't remember how.

I need to search for a very specific isotope profile. Instead of looking for ~1.0033 Da difference, I need to look for cases that match a difference of 6. This is for an isotope labeling study where we're mixing cultures A and B where A was produced under natural abundance C source and B was produced under enriched C source. I expect to filter only chromatographic peaks that have this pattern M and M+6. It's already doable, right? I just don't know how.
Thanks

**Comment by robinschmid** [comment]
That's a good question. 
I think you could use ion identity networking for this. Does this already affect the feature shapes? Like are they slightly different?

**Comment by RicardoMBorges** [comment]
Make sense. I think that was what I was trying to remember. I’ll try that. Thanks
