### ISSUE TITLE
Export multiple feature lists to .mgf, without overwriting the same file

### ISSUE THREAD

**Issue by vormsborg** [mzmine/mzmine3#1214]
**Is your feature request related to a problem? Please describe.**
I need to export .mgf files of all feature lists in a project, but when I try the export to mgf module, I only get one .mgf file out of it. I assume this is because the module cannot give each exported feature list .mgf file a unique name, and thus overwrites same file over and over. A way to export multiple feature lists to .mgf would be very valuable for me.

**Describe the solution you'd like**
I want to be able to export all feature lists present in a project to individual .mgf files with unique names.

**Describe alternatives you've considered**
Until now, I have been using the exported .mgf of the aligned feature list.

**Additional context**

**Comment by SteffenHeu** [comment]
Which export are you referring to?

GNPS or Sirius?

Both come with the functionality to use '{}' to be replaced by the feature list name. This is also described in the tooltip and should do exactly what you want.

![grafik](https://user-images.githubusercontent.com/37407705/223105567-33b164ab-2d68-44b4-9830-cfb56453d438.png)

In case that is not available yet (we updated the sirius export in the last weeks) please try the newest mzmine version here: https://github.com/mzmine/mzmine3/releases/tag/Development-release

**Comment by vormsborg** [comment]
Thanks! It was GNPS module. I was not aware of the '{}'- feature, it did exactly what I wanted
