### ISSUE TITLE
Chromatogram resolver in MZMine 3

### ISSUE THREAD

**Issue by calderod** [mzmine/mzmine3#1227]
### Basic information

* My operating system: **Windows 11**
* My MZmine version: **3.2.8**

### What happened

* Please describe what happened and how it differs from what you expected to happen. 
**I have been trying to remove use some type of chromatogram resolver in MZMine 3 to remove non-sense peaks and optimize feature detection. I tried local minimum resolver explained in this tutorial (https://youtu.be/7VGn8Svqb4Y?t=1895) but the parameters I program does the opposite of what i would like it to do: this resolver tool takes huge peaks and chops them up and calls them individual features. Is there another youtube tutorial that explains other resolver tools that someone would recommend? I know there are steps listed in the manual but seeing a video tutorial would be more informative (https://mzmine.github.io/mzmine_documentation/module_docs/featdet_resolver_adap/adap-resolver.html).**  
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* **here is a snapshot of the local minimum resolver parameters I used.**
![image](https://user-images.githubusercontent.com/91331571/223481237-274aeb99-dc99-4612-82cf-62d5c5b9104a.png)

* Please upload an MZmine project file that demonstrates the problem you are reporting.

**I am happy to provide more context or clarify if needed.**

**Comment by robinschmid** [comment]
I only see one major peak in the bottom. This screenshot does not show what you are describing

**Comment by calderod** [comment]
Thank you for your rapid reply, here is an example of the issue using the parameters.
This first photo counts as one feature and it was present before the local minimum resolver step. Based on its weird peak shape, I would say it is a non-sense peak and is probably a fragment. I was hoping that the local minimum resolver would throw this peak out.
![Unresolved_example](https://user-images.githubusercontent.com/91331571/223505218-9bd6f95e-82f2-4df6-ae4c-46027fe6a4c7.png)
This second photo demonstrates that the resolver chopped it up into multiple features.
![Resolved_example](https://user-images.githubusercontent.com/91331571/223505464-bc66d7b2-c35b-4522-9c76-a24b321e842c.png)
I am concerned that if I do not use this local minimum resolver properly, then I might interpret erroneously that this sample has more features than it really has. if you think another resolver type might be better, please let me know.

**Comment by robinschmid** [comment]
is this GC-EI data or LC MS?

This definitely looks like multiple peaks. But in general its very spikey. I would apply chromatogram smoothing. The local min is usually the easiest to use and has the best speed/performance ratio

Otherwise you can use the ADAP resolver but its harder to optimize and takes longer to process.

We are releasing MZmine 3.4.0 today with the new batch wizard you can try it to get started with a "standard batch" and then optimize the batch steps from there

**Comment by calderod** [comment]
This is LC-MS data. Thank you for the smoothing suggestion and I will try and troubleshoot ADAP resolver. Besides these written manuals on ADAP resolver (https://mzmine.github.io/mzmine_documentation/module_docs/featdet_resolver_adap/adap-resolver.html) and some videos I found after a brief YouTube search (https://www.youtube.com/results?search_query=adap+resolver+mzmine3), is there an Youtube video tutorial you know of that describes the specific parameters of ADAP resolver? If not, I will start with these current sources and reach back out if I have more questions about ADAP resolver.

**Comment by robinschmid** [comment]
If you find any more information feel free to contribute to the documentation.
