### ISSUE TITLE
Error when exporting MGF of MS2 spectra when using rt range in mass detection module

### ISSUE THREAD

**Issue by RemyMG** [mzmine/mzmine3#1228]
### Basic information

* My operating system and version: Windows 10 Pro 22H2
* My MZmine version: 3.3.0

### What happened

This issue isn't redhibitory since it can be bypassed. 

But I encounter an error message when I export the feature list with MGF for FBMN after data processing while setting a retention time range for the `Mass detection` module. Even if I apply this retention time range for all next modules (i.e., `Chromatogram builder`, `Chromatogram resolving`, `Feature list rows filter`) I get this error message when I try to export the feature list (after `Join aligner`):

![image](https://user-images.githubusercontent.com/88542764/223478071-aad4fa43-45fa-46a6-a36a-fe6b195a87fb.png)

It's surprising since I can run all modules from  `Mass detection` module on MS1 and MS2 data until `Join aligner` without any error message, and I can even display the MS2 spectra for each feature: 

![image](https://user-images.githubusercontent.com/88542764/223486386-b5444d0d-0f89-4cc1-90d6-db1f2e2e3d6e.png)

I don't have this issue when I remove this retention time range for the following modules: `Mass detection`, `Chromatogram builder` and `Chromatogram resolving`. Of course I can filter the feature lists on a specified retention range with the `Feature list rows filter` module but when I have a very large number of data files, it increases the processing time.

I tried this on different software versions (3.2.8, 3.3.0), different data format (.mzML, .raw) acquired with different machines (Orbitrap QExactive, Exploris), also by removing different modules, but the error seems to come from this rt range option in the `Mass detection` module.

How can we get rid of this issue? Maybe is there something I'm doing wrong? 

Thank you for your hard work to improve the quality of MZmine every time 👌

**Comment by robinschmid** [comment]
Setting a filter in the mass detection step is discouraged. 
You should apply mass detection to all scans it usually takes a few seconds only.

**Comment by robinschmid** [comment]
We are releasing MZmine 3.4 just now. So better update right away :)

**Comment by SteffenHeu** [comment]
i suggest running mass detection for the whole file and just limiting the adap chromatogram builder step. as robin said, mass detection will not really enlongate your processing time.
