### ISSUE TITLE
Join aligner window isn't displaying anymore

### ISSUE THREAD

**Issue by RemyMG** [mzmine/mzmine3#1235]
### Basic information

* My operating system and version: Windows 10 Pro 22H2
* My MZmine version: 3.4.0

### What happened

* Since the latest update (MZmine 3.4.0) it is not possible to display the parameter window for `join aligner` module. So we can not parameter the `join aligner` module anymore (despite this, the module works anyway and generates an aligned feature list).
* This issue also occurs in the batch queue module, i.e., it is not possible to add this module to the queue (and of course to set it up).

Thank you for your kind help !

**Comment by robinschmid** [comment]
I found the bug. Thanks for the report. It will work fine if you load it already setup. Its a GUI bug with the parameter component.
