### ISSUE TITLE
Error on Join aligner (Unhanded exception in task)

### ISSUE THREAD

**Issue by matheus-feralv** [mzmine/mzmine3#1242]
* My operating system and version: Windows 11 Pro
* My MZmine version: 3.4.0

### What happened -->When I tried to perform the alignment using "Join aligner" the following error occurred:

![alignmenterror(joinaligner)mzmine3 4](https://user-images.githubusercontent.com/124372019/224023673-6d81ec5b-eec9-4c3e-a304-62d93b4061d4.png)

*The mentioned feature in error message (aligned feature list.Neg) are a feature of another project that were not opened on Mzmine when the error occurs. And even when delete this feature, the error still happening on this function.

This error is happening even when no parameters are set and no project file is open, so don't include here parameters or any files.

It seems to be a programming language error or something wrong with my pc?

I hope this report is valuable for the improvement of the software and if anyone else is having the same type of problem please comment here.

All the best,

Matheus.

**Comment by robinschmid** [comment]
Thanks for the report. 
Can you exactly describe how to recreate the issue. 
Step by step. 

There was an issue with the setup dialog that will be fixed in the next release.

**Comment by matheus-feralv** [comment]
Thank you Robin, for asnwer quickly.

Actually, don't have many steps to recreate the issue. Aways when I try to set the join aligner in the new version, the error described above happens. Even with no processment runnig or data uploaded.

I reached the error yesterday when I tried to run my project builted in v3.3.0 in the new version, and them now, aways happens with Join aligner.

If this explanation still unclear, please tell me how to contribute more.

**Comment by matheus-feralv** [comment]
Also, an idea to improve usability and help the users...

As Join aligner seems not to work here, I tried to migrate to RANSAC. It will be helpful to provide more details for setting up the parameters of this algorithm, such as the Ransac iterations, minimum number of points and threshold value, including for example, current values to TOF or Orbitrap, similarly to what has been done in join aligner by processing wizard.

**Comment by robinschmid** [comment]
We will push a new release tomorrow. With the join aligner fixed

**Comment by robinschmid** [comment]
You can download a fixed release already when you scroll down here. 
The macOS version is not signed though so for that you would need to wait.
https://github.com/mzmine/mzmine3/actions/runs/4372688388

**Comment by matheus-feralv** [comment]
Thanks Robin!
