### ISSUE TITLE
Error when detecting chromatograms

### ISSUE THREAD

**Issue by Kotchanipa** [mzmine/mzmine3#1254]
### Basic information

* My MZmine version: 3.2.8

### What happened

I cannot create chromatograms. 

![image](https://user-images.githubusercontent.com/89931476/224629108-812acbbe-d4d7-4a40-9769-51e24b0a3dcf.png)

I attached the link collected *mzML files. 
https://drive.google.com/drive/folders/17-ykfCK7EPQD4SdWVP_ItFAjt48m3dta?usp=sharing

**Comment by SteffenHeu** [comment]
This is the same issue as described in these issues below. Please check if any of the solutions work for you.

https://github.com/mzmine/mzmine3/issues/1126
https://github.com/mzmine/mzmine3/issues/855
