### ISSUE TITLE
ERROR WHILE OPENING RAW DATA FILES

### ISSUE THREAD

**Issue by Elloumianis** [mzmine/mzmine3#1256]
Hello 
I saved a job as "standalone large flexible" even though the job only contained MzML files and now I can't open it. 
ERROR WHILE OPENING RAW DATA FILES
Is there a way to recover my work? 
Thank you.

**Comment by robinschmid** [comment]
Hard to say without more information. 
1. send the project or a similar project
2. what version was used to save the project
3. what version to load the project
4. send the full log file (see documentation)
