### ISSUE TITLE
Join aligner unavailable

### ISSUE THREAD

**Issue by ChloePZS** [mzmine/mzmine3#1257]
### Basic information

* My operating system and version: macOs Monterey version 12.3
* My MZmine version: Mzmine 3.4.0

### What happened

Hello, 
It seems that the "Join Aligner" module is unavailable. 
When I select for Alignment > Join Aligner no window opens, whereas it does for the other modules. In the bottom left it says  : 

![image](https://user-images.githubusercontent.com/47737491/224745428-c813ac43-6999-471a-8ae6-b49288363e03.jpeg)

Thanks a lot for your help,
Chloe

**Comment by SteffenHeu** [comment]
Please try the latest development build here: https://github.com/mzmine/mzmine3/releases

**Comment by ChloePZS** [comment]
Thanks for your quick reply ! 
Problem solved !
