### ISSUE TITLE
Include documentation in MZmine archives for offline users

### ISSUE THREAD

**Issue by gdelap** [mzmine/mzmine3#1258]
We are using MZmine on computers with no internet access. I noticed that since MZmine 3, documentation was only available as a link to MZmine website.

Would it be possible to include documentation as html or pdf in the archive for offline help? As some tools are still under development, such embeded documentation may be outdated quickly, but at least it would be a start to have access to an earlier version offline.

As an alternative, it would be ok to be able to download a pdf with all the documentation from the website.

I am using MZmine 3.4.0 (portable version) on Windows 10.

Thank you in advance for your answer,
Best regards
G. Delaporte

**Comment by SteffenHeu** [comment]
Hi,

you can always download the documentation from here: https://github.com/mzmine/mzmine_documentation/blob/gh-pages/documentation.pdf

We will add a link to the online docs.

**Comment by gdelap** [comment]
Hi,

Thank you for your feedback.

I did not manage to find the document, thank you very much! You can close the issue, I can work with that.
