### ISSUE TITLE
Incorrect sorting of predicted formulae

### ISSUE THREAD

**Issue by AlfredMayhew** [mzmine/mzmine3#1260]
### Basic information

* My operating system and version: Windows 10 
* My MZmine version: 3.4.0

### What happened
The selected formula from those assigned to a feature based on the m/z, using the "formula prediction" module, is often incorrect. Where multiple fomulae are assigned, the selected main formula is the assignment with the lowest Δm/z as opposed to the lowest **absolute** Δm/z. 

For example, the feature below displays a predicted formula of C23H22N2O2 with a Δm/z ppm of -2.2257:
![image](https://user-images.githubusercontent.com/51374720/225071666-02093445-1624-42e8-8698-96c38819f9fd.png)

The dropdown menu on the formula shows an alternative of C15H26N4O4S, which has a lower absolute m/z difference (-0.4064) and a higher "Combined score":
![image](https://user-images.githubusercontent.com/51374720/225071988-c017e5b4-3742-46d1-8926-af8bc2f4f476.png)

This second formula should be the default, and the same is true whenever there is a suggested formula with a very negative Δm/z or multiple negative Δm/z suggestions. The behaviour is as expected when no negative Δm/z values are present as then the smallest Δm/z is also the smallest absolute Δm/z. This issue then carries through to exported csv's unless the formulae are manually changed prior to export, which is not feasible for a large untargeted analysis.

I have included an example project [here ](https://drive.google.com/file/d/1XSiGkDWRpf1av_R3KHLwf4y0ZALUVug1/view?usp=sharing)which should demonstrate this problem, but I believe the same will apply to any use of the formula prediction module. 

Thanks for taking the time to look through this, let me know if there is any more information I can provide to help clarify, and apologies if I have overlooked anything.

**Comment by robinschmid** [comment]
Did you apply sorting in formula prediction?

Can you add your batch processing file or screenshots of all parameters?

![image](https://user-images.githubusercontent.com/10366914/225241126-d6bcb9a3-37ca-46e0-8579-54a1e4ea0fd8.png)

**Comment by AlfredMayhew** [comment]
Yes, sorting was selected in the formula prediction module. I've put a screenshot below, and a link to the batch file [here](https://drive.google.com/file/d/1I0Z61ml067sLF7Tokjq-b2WHRHRJan0_/view?usp=sharing).

![image](https://user-images.githubusercontent.com/51374720/225261152-1396bef5-5e61-4d4d-95f9-dbac8be4f197.png)

I also tried adjusting these parameters to be 10, 0, 0 for max ppm distance (weight), weight isotope pattern score, and weight MS/MS score respectively. This didn't seem to make any difference to the outcome (presumably because isotope score and weight MS/MS score are empty in this example).

**Comment by djb561** [comment]
Hi there, I am also having exactly the same problem. It seems that where multiple formulae are assigned, the selected main formula is the assignment with the lowest Δm/z i.e largest negative value, as opposed to the lowest absolute Δm/z as previously stated. When exporting the csv, unfortunately the Δm/z is not given for all potential (Top N) formulae, so can't be sorted out in post processing. Currently, we are having to use mzmine 2.53 due to this issue.

**Comment by SteffenHeu** [comment]
Hi,

i think we finally found the issue. Feel free to test the latest development built, which should be available in a few minutes.
https://github.com/mzmine/mzmine3/releases/tag/Development-release
