### ISSUE TITLE
Retention time crop filter 

### ISSUE THREAD

**Issue by NNavrot** [mzmine/mzmine3#1261]
Basic information

    My operating system and version: Windows 10 Pro
    My MZmine version: 3.4.14

Hi,
My first post here, so I first wish to thank you all for the great work with MZMine.
I noticed that it should be possible (from the docs), to crop the files using retention time. In this case, I would like to remove the first 0.3 min of the analysis, and the last minute, in order to remove useless features/analysis time.
Is this possible in the current version, or do you consider implementing it in a future version? 
Thanks,
Nicolas

**Comment by NNavrot** [comment]
Hi nathalie,
Thanks for you reply! I will just crop in the later steps then.
Best regards
Nicolas

**Comment by robinschmid** [comment]
thanks @NthlLcrmp for answering here.

Just a small addition. I would only apply the filter to the chromatogram builder. NOT the mass detection. You might get problems further down the line if you do not apply mass detection to all scans.

**Comment by NNavrot** [comment]
Thanks Robin for your feedback!
