### ISSUE TITLE
Syntax error ... after install

### ISSUE THREAD

**Issue by flexcod** [mzmine/mzmine3#1263]
### Basic information

* My operating system and version: Debian 10
* My MZmine version: 3.4.11, 3.2.8.1, ...

### What happened

When i launch Mzmine with this command :

`sh /opt/mzmine-linux-installer/bin/MZmine`

The result is :

`$ /opt/mzmine-linux-installer/bin/MZmine: 1: cannot open @�: No such file
/opt/mzmine-linux-installer/bin/MZmine: 11: Syntax error: "(" unexpected (expecting ")")`

Have you a solution.

**Comment by robinschmid** [comment]
What file did you download. We have different distributions for linux. 
Would be great to get feedback how we can make it easier for people. Maybe pushing it to package managers etc.
