### ISSUE TITLE
Does UPLC-Q-Exactive data need to split polarity at conversion

### ISSUE THREAD

**Issue by qingju32** [mzmine/mzmine3#1272]
### Basic information

* My operating system and version: Windows 11 22621.1413
* My MZmine version: 3.4.0

### What happened

When performing the step of resolving local minimum features in untargeted LC-MS analysis, I observed an unusual pattern in the preview EIC diagram. 

<img width="1280" alt="Snipaste_2023-03-22_23-48-20" src="https://user-images.githubusercontent.com/40858189/226969086-58c015f5-68e5-418f-9810-780ae556530c.png">

However, since the UPLC-Q-Exactive instrument allows polarity switching, I separated the negative ions during the conversion of the .raw file to .mzml format. As a result, the EIC pattern normalized and appeared more typical.

<img width="1280" alt="Snipaste_2023-03-22_23-45-55" src="https://user-images.githubusercontent.com/40858189/226968765-ac62fec5-cfeb-43c1-a629-b17176a21659.png">

As a beginner, I am feeling a bit confused about whether the UPLC-Q-Exactive data should be split by polarity during conversion or if separate chromatograms of positive and negative ions should be constructed. 

After conducting a search on polarity and Q-Exactive, I may still be unsure about the correct approach. Could someone please explain this? Thank you very much.

**Comment by BioGavin** [comment]
So MZmine can‘t process polarity switching DDA data in one batch now, right?
