### ISSUE TITLE
Sample limit for blank subtraction

### ISSUE THREAD

**Issue by Sydney-Thomas** [mzmine/mzmine3#1274]
### Basic information

* My operating system: Windows 11
* My MZmine version:  3.4.16

### What happened

I'm running a large experiment (2500 samples and 250 blanks) and would like to do blank subtraction using the feature list blank subtraction module. However, when MZmine gets to that step, it says that the maximum number of blanks allowed is 100. Is there a reason for this limit (processing time, etc), or could it be increased? Thanks!

**Comment by SteffenHeu** [comment]
Hi, 

When I programmed it some years ago for Mzmine 2 I didn't think we would be able to process such large datasets, so I just wrote 100 there. 😅 Yet, here we are with MZmine 3. I updated the limit, and @christophuv added some more improvements to the module.

You can download the latest test build here: https://github.com/mzmine/mzmine3/releases/tag/Development-release

May i ask what hardware you are using for your analysis?

**Comment by Sydney-Thomas** [comment]
Thanks! MzMine3 is definitely a vast improvement for these larger datasets. 

Hardware
Processor: Intel i7, 3600 Mhz, 12 cores
RAM: 80 GB
Hard Drive: 2 TB

I've previously been able to run 500 samples in 10 minutes on this system, we'll see how long 2500 takes.
