### ISSUE TITLE
Filtering features for feature list

### ISSUE THREAD

**Issue by keunbae318** [mzmine/mzmine3#1276]
**Is your feature request related to a problem? Please describe.**

After deconvolution (GC-MS; hierarchical clustering), I assume depending on the base peak intensity, the number of features is significantly different. To be specific, relatively low base peak has the lower number of features, while overall higher base peak intensity gives more number of features. 

These biased numbers potentially due to the peak intensity, can lead a biased alignment. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

I was wondering if I can pick certain amount of compounds can be filtered by filtering features in the feature list before alignment process. for instance, just peak important 200 peaks (highest intensity or area, or user selection) to each sample before running alignment functions.

Alternatively, instead of setting up by absolute values, I was wondering if relative value can be applied to operate functions. It might possibly generate an equal number of feature after clustering even though they has different intensity across samples.

**Additional context**

**Comment by keunbae318** [comment]
Dear 

I have been thinking about this issue, I assume it would be great to filter out dominant 100 features to each sample before alignment.

Current, I have 100 samples, the number of features after hierarchical clustering decomposition is pretty different depending on sample, if I can sort the features out by refraining top dominant 100 features to each samples, then I might be able to remove some minor features to the treatment effect. 

Manually discarding features after dominant 100 features to each sample, seems hustle so far. Any function is available alternatively?

all the best,
Keunbae

**Comment by keunbae318** [comment]
Dear 

I have been thinking about this issue, I assume it would be great to filter out dominant 100 features to each sample before alignment.

Current, I have 100 samples, the number of features after hierarchical clustering decomposition is pretty different depending on sample, if I can sort the features out by refraining top dominant 100 features to each samples, then I might be able to remove some minor features to the treatment effect. 

Manually discarding features after dominant 100 features to each sample, seems hustle so far. Any function is available alternatively?

all the best,
Keunbae

**Comment by robinschmid** [comment]
Hey thanks for reaching out.

I think it might be risky to set such a threshold. Are you having problems to align all samples - because it might be better to prioritize after statistical analysis - depending on the study design. 

In MZmine there is a module for Feature list row filter and Feature filter. Feature filter is per sample and row filter removes complete rows.

**Comment by keunbae318** [comment]
Thanks robin,

I will consider flipped the way, but does feature annotation step becomes tremendous work after all?


Keunbae
