### ISSUE TITLE
I can not import a database

### ISSUE THREAD

**Issue by LuisMoreira50** [mzmine/mzmine3#1280]
Hi. I'm using MZmine3 in Windows10.
I'm trying to import a database but a error message popped up automatically on the screen.

What is the problem and how can i solve it?

Thanks in advance.
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/126248442/228015959-00a0144a-51ec-4a5a-a06a-e4e5f0b60aa8.png">

**Comment by robinschmid** [comment]
I need more information to solve it. You are downloading a uniprot json file? 
Are those MS2 spectra? 
We currently support MZmine, GNPS, MoNA json file formats

**Comment by LuisMoreira50** [comment]
Yes, I'm downloading json files from uniprot. In this case (in the picture), I downloaded the complete pig (sus scrofa) database. I think that this database contains MS1 and MS2 spectra acquired using both high and low resolution equipment.
Is there any software to convert the .json or fasta files to MZmine format?

I also have another questions if you don't mind to help me.

1. I 'm trying to use different noise levels (in mass detection, raw data methods) in the MS1 and MS2 data. But, after setting the noise level to the MS2, the MS1 noise level also changes to the one of the MS2. How can I save different values of noise level to MS1 and MS2? I followed the instructions of your tutorial in YOUTUBE but it is not working...

2. I aligned the spectra of several files, trying to find the ions that are unique in each sample. How can I set the table just to show those ions that are unique? I'm doing shotgun proteomics and I have thousands of peaks. I need to find the unique ions to each sample and with the highest intensity. I tried to do this, but i got a table with thousands of rows.

Thanks in advance.

**Comment by robinschmid** [comment]
So you are looking at protein data?
Right now we do not have special module for proteomics but you can use the default workflow. 
Just setup your first method with the processing wizard. 

1. use the batch mode to define multiple mass detection steps for separate levels
2. you can align all MS1 features and then export for statistical analysis.

**Comment by LuisMoreira50** [comment]
Yes, I'm looking at protein data.
Ok, I will try the batch mode.
Thanks!
