### ISSUE TITLE
MS1 only annotation? (spectral library search fail)

### ISSUE THREAD

**Issue by qingju32** [mzmine/mzmine3#1282]
### Basic information

* My operating system and version: Windows 11 22621.1413
* My MZmine version: 3.4.16

### What happened

When annotating uplc-q-exactive full-scan data using a mass spectrometry database, the annotation fails and the variable is blank. 
The data did not contain secondary mass spectrometry, only negative ions were retained when the data were transformed, and MoNA-export-LC-MS was used for the mass spectrometry database.json (https://mona.fiehnlab.ucdavis.edu/downloads ). 
The previous steps have successfully derived the retention time, mass-to-charge ratio, and peak area of each sample. 
No error was reported. The batch file is in the attachment. 

Since the data only has first-order mass spectrometry information, GNPS doesn't seem to apply, so if MZmine can't annotate, what's the good advice? 
Thank you!

<img width="1153" alt="Snipaste_2023-03-28_20-07-51" src="https://user-images.githubusercontent.com/40858189/228255273-be3bb440-a20e-4483-95a5-104abaa9685e.png">

[test.zip](https://github.com/mzmine/mzmine3/files/11090098/test.zip)

**Comment by robinschmid** [comment]
Some questions:
- its LC-MS1 only data without MS2 data?
- what instrument?
- what is the goal?

MS1 only data is hard to annotate. You can rely on MS1 isotope pattern, exact mass and retention time. There are options like the local csv compound database annotation in MZmine. GNPS does not apply as you need MS2 data.

Why not acquire MS2 DDA data and get good annotations?

**Comment by RosaCatherina** [comment]
I have the same issue with MS1 data for GC-MS analyses. 
When I try to annotate the aligned feature list with the MoNA GCMS spectral library (.json format), it seems like nothing happens. There are no features annotated in the updated Aligned feature list. Processing of the task seems to be one second, so I am not sure if anything happens at all. It might give me the wrong idea, but when I converted the MoNA library to a feature list, it showed that the gross of the features were present around RT 0.. Should this have something to do with the way I import the library? 

Thanks! 

![Screenshot 2023-05-03 at 15 24 13](https://user-images.githubusercontent.com/121615514/235928949-0c1e8457-609e-466f-9645-2df0d63cb6b2.png)

![Screenshot 2023-05-03 at 15 28 15](https://user-images.githubusercontent.com/121615514/235929979-d06a9b6c-d963-4344-b1ef-c51cb852a61d.png)

**Comment by JAEYOONSUNG** [comment]
I am also having the exact same problem as RosaCatherina. I am using a Mac OS, and when I perform annotation in the same format as in the Windows operating system, it works fine. However, I am unable to set parameters such as minimum ion intensity in Spectral library search on my Mac. Could you check this problem?
Thank you 👍🏼 
<img width="637" alt="스크린샷 2023-05-09 16 22 45" src="https://user-images.githubusercontent.com/42233037/237023992-99d05f6e-48dc-4d89-a79f-7b36700205e0.png">

**Comment by SenatorPalmitine** [comment]
Hi. The problem seems to persist. I'm on version 3.9 and no matter what library I upload (json, jdx, msp, different sources), the spectral search of MS1 data (haven't tried anything else, I work with GCMS) takes under one second and yields no results. It looks like it's not even considering the library. Even exporting a mass spectrum into a custom library and trying to match the same compound did not work. I have also tried loosening the search parameters to allow pretty much any match. An empty "Spectral match" tab does appear in the feature table though.

Transferring the libraries to feature lists and opening them does work and I can see a list of compounds, unless it's json, in which case every "Spectral match" entry is "null".

An msp library:
<img width="972" alt="01" src="https://github.com/mzmine/mzmine3/assets/143339529/3dbfe661-f782-40e3-aad6-db141c0e7bed">

A json library:
<img width="920" alt="02" src="https://github.com/mzmine/mzmine3/assets/143339529/ef130eee-1476-4c0a-92e2-9bcd149e935f">

**Comment by dav7841** [comment]
Hi, Sorry revive an old thread. I just want to confirm if this issue is resolved with MS1 only annotation. I've been trying to identify GCMS spectra of an imported database but I'm getting the same output as described above.

**Comment by mariasanichemeng** [comment]
Hi, just following up on this thread... I assume it is still not resolved.. Trying to annotate through MoNa library some lipids from MS2 spectra and it can find 0 (also does the search is less than 1 sec)....anyone managed to perform this?

**Comment by ansgarkorf** [comment]
Please share your batch file and mzmine version

**Comment by mariasanichemeng** [comment]
Hi MZmine is 3.9.0.
Regarding the batch queue: (each step imports the data or feature lists produced from the previous one)

Mass Detection 
ADAP Chromatograph builder
Chromatograph resolving
MS2 Scan Pairing
Join aligner
Peak finder
Duplicate peak filter
Feature grouping ->metaCorrelate
Feature grouping ->Ion identity network
Spectral library search -> with MoNa json library (fails for both MS2 all scans and precursor as well)

**Comment by ansgarkorf** [comment]
Please update to the latest version, 4.1.

**Comment by mariasanichemeng** [comment]
Hi, thanks so much for your reply. I downloaded it, made a user account but  it does not let me sign in. Even when I do it online still it does not recognise any user...
<img width="573" alt="Capture" src="https://github.com/mzmine/mzmine/assets/175015828/8fdea4a2-b5b9-4a08-9b53-96b09a7b95ae">

**Comment by mariasanichemeng** [comment]
Hm I made it work.. However, the same thing is happening as with the older version....

**Comment by RaktimBhattacharya** [comment]
Hi sorry to revive this old thread, I am trying to annotate my MS1 spectra obtained through an UPLC-QTOF negative mode with the help of MoNA LC-MS spectral library (.json). But every time I run the MZWizard with carefully keeping all the parameters as per the documentation and tutorials, still annotations are not coming up. All the other features are fine, except the annotations and spectral match. Also the csv file which is being generated is blank. Can anyone suggest any idea to resolve the issue? 
Operating system: MacOS
MZMine 4.3.0

**Comment by robinschmid** [comment]
please create a new issue and provide all information like log file and batch config
