### ISSUE TITLE
An Error in EmbeddedParameterSet 

### ISSUE THREAD

**Issue by shawjintran** [mzmine/mzmine3#1293]
### Basic information

* My operating system and version: Window 10 
* My MZmine version: 3.4.21
* IDEA 2022.1
* Java 17
### What happened
 when I try to build and run the Mzmine, IDEA shows this error, `Parameter<?>` is a supertype of `EmbeddedParameterSet<T,V>` so it seems always true ( i guess ).
![image](https://user-images.githubusercontent.com/71209299/229273808-d853ef3e-e547-440e-b3b2-353cf74c31a5.png)

and I try to find some suggestiones to solve it by Bing, but no.

then I use `String name =  this.getName() ;` to replace this, and run successful ( Temporary, coz I'm learning to use )

so,I want to know if there is a better way to solve or maybe it's my IDEA problem and others.

**Comment by robinschmid** [comment]
There should not be an issue.
check this:

- [ ] you use JDK 19
- [ ] run update gradle project in intellij
- [ ] invalidate caches in intellij

**Comment by shawjintran** [comment]
Sorry, I just switched to JDK19 and it ran successfully even though intellij still showed this error. I think it might be  the version of my intellij.  
Because I can't select the language level of the project as 19 :). I had to choose 18 preview    
Thank you for your guidance
