### ISSUE TITLE
Slow load times in aligned feature lists when enabling "Shapes"

### ISSUE THREAD

**Issue by jarrodRoachChem** [mzmine/mzmine3#1296]
### Basic information

* My operating system and version: Windows 10 Pro for Workstations
* My MZmine version: 3.4.14
* CPU: Intel(R) Xeon(R) W-2265 CPU @ 3.50GHz, 3504 Mhz, 12 Core(s), 24 Logical Processor(s)
* RAM: 128 GB

### What happened

I recently used MZmine to clean up the data of 250 samples. Traditionally, we have always looked at the peak shapes of our final aligned peak list to make sure our data processing was successful, so I enabled the "Shapes" option in my aligned feature list so that I could see the peak shapes. Upon adding "Shapes", the program took several minutes to update (>5 minutes, software froze up a few times). Additionally, the software was not using all of the computer RAM or all of the CPU cores during this process (despite all CPU cores being allowed in the settings). I was actually able to perform other actions on my computer while this was occurring. Upon opening with the shapes, any action I tried to perform (such as scrolling or deleting a row) would freeze or crash the program. We did not have this issue with MZmine 2.53 with datasets of similar or greater sizes. Any insight would be appreciated! Let me know if you need any other information, and thank you all for your work!

**Comment by robinschmid** [comment]
The issue is that the charts are now dynamic and It's a lot to visualize... Also not sure how much you can see when looking at chromatograms of 250 samples. 

We are currently looking into making the feature list more dynamic by coupling to charts like the chromatograms view so you could see it when clicking on a row. 
Also we are trying out image caching for the charts in the table

**Comment by robinschmid** [comment]
For now I would just directly go and do statistical analysis and in case look at chromatograms of individual features
