### ISSUE TITLE
Problem with compound database file

### ISSUE THREAD

**Issue by ainamiir** [mzmine/mzmine3#1299]
### Basic information

* My operating system: Windows 11 Pro
* My MZmine version: Mzmine 3.4.16

### What happened

I would like to use the Mzmine 3.0 program for the integration of the areas of a list of compounds but I can't manage to do it. When I enter the document (.csv) that contains the list of target compounds, I get an error message. Below I attach the error message and the list of compounds. I have tried to change several things in the document (.csv) but nothing has worked. I would like to ask you to help me to know what I am doing wrong. I look forward to your reply and thank you very much in advance,
Best regards,
Aina
[Prova.csv](https://github.com/mzmine/mzmine3/files/11147864/Prova.csv)
[prova5.csv](https://github.com/mzmine/mzmine3/files/11147865/prova5.csv)
![unnamed](https://user-images.githubusercontent.com/129854596/229776584-c7daa039-a63d-455f-836c-5acb5db167e9.png)

**Comment by ainamiir** [comment]
Hi,
which separator should I use in the document called prova?
Thank you for your help,
Aiba

**Comment by SteffenHeu** [comment]
Check the parameter dialog of the search module. You can set a separator there. Just set it to the same as you use in your file.
