### ISSUE TITLE
Targeted feature detection not working

### ISSUE THREAD

**Issue by Propane003** [mzmine/mzmine3#1301]
### Basic information

* My operating system and version: Windows 10, 64 bit
* My MZmine version: 3.4.16

### What happened

After importing a raw file (tried with mzML and netCDF file), there is only an empty chromatogram and spectrum in raw data overview.
![image](https://user-images.githubusercontent.com/129943433/230031182-2c6702d8-c8d4-4e3c-980b-5c708ddb2bdd.png

Trying to run the targeted feature detection (feature detection\LC-MS) results in this error:
![Screenshot 2023-04-04 170139](https://user-images.githubusercontent.com/129943433/230031713-ffe0368a-6ed5-4ba0-b5b1-8fee2577b7ae.png)
![image](https://user-images.githubusercontent.com/129943433/230032006-60e952ef-899b-4924-b694-420a6162e0a5.png)

The whole workflow works with the necessary adaptions in mzMine 2.53.

Thanks for your support.

**Comment by robinschmid** [comment]
Did you apply mass detection?
Make sure to apply it to all scans. In the data overview it shows no mass lists.

**Comment by Propane003** [comment]
Hi Robin!
Thank you very much for your fast reply. It worked out.
I don't remember applying mass detection in mzMine 2.53, but it does not matter.
