### ISSUE TITLE
documentation for batch mode XML files

### ISSUE THREAD

**Issue by bernt-matthias** [mzmine/mzmine3#1308]
**Is your feature request related to a problem? Please describe.**

I'm planning to work on wrapping MZmine for the Galaxy platform. And wondering if there is documentation on the XML file used for the batch mode (e.g. a schema definition or any other documentation). 

Btw. as a first step I'm working on a [bioconda package](https://github.com/bioconda/bioconda-recipes/pull/40445)

**Describe the solution you'd like**

Any kind of docs might be of help.

**Comment by robinschmid** [comment]
That's great. 
I can invite you to our mzmine slack if you are interested. That might be easier to coordinate. 
I thought about this for a while now actually so great that you are proactive. 

It's not documented. 
All Parameters are saved depending on their datattypes and names in mzmine.

Easiest would be to lock to a version and then have a batch file for that version and just change some parameters based on user input. 

Maybe we can meet and discuss

**Comment by bernt-matthias** [comment]
> I can invite you to our mzmine slack if you are interested. 

Seems like a good idea.

> Easiest would be to lock to a version and then have a batch file for that version and just change some parameters based on user input.

Maybe we can identify in a first iteration the most important parameters to keep it simple and add more advanced ones in the next iteration.

**Comment by bernt-matthias** [comment]
> Easiest would be to lock to a version and then have a batch file for that version and just change some parameters based on user input.

Since I got 3.2.8 running in [bioconda](https://github.com/bioconda/bioconda-recipes/pull/40700) I would go for this version for now. Would be happy about some input test data that I could try.

**Comment by robinschmid** [comment]
related to #1310
