### ISSUE TITLE
Java installation issues

### ISSUE THREAD

**Issue by bernt-matthias** [mzmine/mzmine3#1310]
### Basic information

* My operating system and version:
* My MZmine version: 

Ubuntu latest LTS version

MZmine 3.4.16

### What happened

When executing `gradlew` I get

```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> error: invalid source release: 19
```

Wondering if I can tell the build system where java is and which java version is required, e.g. would OpenJDK 17 work?

**Comment by robinschmid** [comment]
Welcome. 
Are you planning to code and maybe contribute to mzmine?

Refer to the documentation for a developer guide. It describes all the steps within IntelliJ but any other ide would be similar.

Currently we use openjdk19, temurine builds

**Comment by bernt-matthias** [comment]
> Are you planning to code and maybe contribute to mzmine?

Since I'm not actually working on mass spec (and java was never really the language of my choice) contributions will likely be very limited. But I always try to fix small bugs if I encounter them (or at least report them).

I was playing around a bit and tried to set https://github.com/mzmine/mzmine3/blob/5bcf1930a40f00801c178fc3305ee87a9a8f99a4/build.gradle#L60 and the following line to `"17"`.

Then at least the originally reported error does not appear. But I get: 

```
/src/main/java/io/github/mzmine/parameters/parametertypes/EmbeddedParameterSet.java:63: error: expression type EmbeddedParameterSet<T,V> is a subtype of pattern type Parameter<?>
       String name = (this instanceof Parameter<?> p) ? p.getName() : "";
                           ^
   where T,V are type-variables:
     T extends ParameterSet declared in interface EmbeddedParameterSet
     V extends Object declared in interface EmbeddedParameterSet
```

Alternatively maybe its an option to allow for multiple JDK versions https://www.jvt.me/posts/2021/06/09/gradle-toolchain/ .. could also be integrated in the github actions testing matrix .. might simplify installation for users and simplify transitions from one JDK version to another .. but no idea how complicated it will be in practice (at least the setup _seems_ easy).

The main problem is that JDK 17 is at the moment the latest version available for conda. So I tried to build for the last mzmine version supporting 17, i.e.[MZmine 3.2.8](https://github.com/mzmine/mzmine3/releases/tag/v3.2.8), which seems to build, but some tests  fail (`197 tests completed, 69 failed, 5 skipped`). For instance:

```
11:54:28 BIOCONDA INFO (OUT) IonIdentityTest > ionIdentityTest() FAILED
11:54:28 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at IonIdentityTest.java:76
...
11:54:29 BIOCONDA INFO (OUT) IsotopesUtilsTest > testFilter13C() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at IsotopesUtilsTest.java:257
...
11:54:29 BIOCONDA INFO (OUT) IsotopesUtilsTest > testFilter13CMultiChargePattern() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at IsotopesUtilsTest.java:220
...
11:54:29 BIOCONDA INFO (OUT) MobilityScanTest > testJumps() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at MobilityScanTest.java:129
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) MobilityScanTest > testMobilityScanStorageAssumptions() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at MobilityScanTest.java:129
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) MobilityScanTest > testMobilityScanDataAccessMassList() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at MobilityScanTest.java:238
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) MobilityScanTest > testMobilityScanDataAccess() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at MobilityScanTest.java:129
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) MobilityScanTest > testStorage() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at MobilityScanTest.java:129
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) ProjectTest > projectTest() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at ProjectTest.java:59
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) ProjectTest > testEmptyProjectAfterTest() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at ProjectTest.java:79
11:54:29 BIOCONDA INFO (OUT) 
11:54:29 BIOCONDA INFO (OUT) ProjectTest > setNewProjectTest() FAILED
11:54:29 BIOCONDA INFO (OUT)     java.lang.NoClassDefFoundError at ProjectTest.java:89
...
```

and a few more. Maybe we can ignore them for now? Is there a way to tell `gradlew` to skip tests? Otherwise we could try to fix them with a patch (that we could include in bioconda).

Ultimately I could try to setup a container, but I would like to avoid it because we would get this for free from bioconda :)

**Comment by bernt-matthias** [comment]
I managed to build the last MZmine version (3.2.8) that supports OpenJDK 17 for bioconda: https://github.com/bioconda/bioconda-recipes/pull/40700 .. this should allow to install MZmine for Linux and OSx  via bioconda. Furthermore a docker container will be deposited at biocontainer. 

OpenJDK 19 is unfortunately not yet available for bioconda. If you have an idea how the latest MZmine version could be build with JDK 17 then I would be interested. Otherwise I'm fine with closing this issue.

**Comment by bernt-matthias** [comment]
Just learned that JDK 17 seems to be the current LTS Java version (https://access.redhat.com/articles/1299013). See also discussion in https://github.com/conda-forge/openjdk-feedstock/issues/92. So maybe there is a way to keep support for this?

**Comment by robinschmid** [comment]
We are definitely interested in supplying MZmine to a wider community and to make it even easier... 
e.g. by supplying a docker container and maybe singularity and others

**Comment by bernt-matthias** [comment]
> I was traveling a lot, thats why the late response.

No worries. 

> The JVM is already sort of a container. I know some people still wrap it into docker or other containers to have even more control... Why do you want to use MZmine in conda?

Ultimately I would like to have MZmine in Galaxy. There are already a lot of metabolomics tools available in Galaxy (e.g. https://github.com/RECETOX/galaxytools, https://github.com/workflow4metabolomics/tools-metabolomics) and I and some of my colleagues think it would be a great addition. 

> We try to keep up with the latest Java versions as there are new language features being added - we also already depend on preview features. LTS is only important if you subscribe to that, which we do not do.
Currently, there is no way of reverting to JDK17.

OK. Cool for me. Then I will see if I can add JDK19 to conda-forge .. or would it run also for JDK20?

Should I just close https://github.com/mzmine/mzmine3/pull/1328 or might it still be useful, e.g. to check for 19 and 20?

**Comment by bernt-matthias** [comment]
Forgot to mention that conda (via conda-forge and bioconda) and/or biocontainers (which use conda) are the basis of Galaxy tools.

**Comment by bernt-matthias** [comment]
> We are definitely interested in supplying MZmine to a wider community and to make it even easier... 

We could also use prebuilt containers in Galaxy, but the preferred way is over conda/biocontainers. The pro is that you get containers for free. 

> e.g. by supplying a docker container and maybe singularity and others

In my opinion docker is sufficient, since singularity can usually just execute docker containers.

**Comment by robinschmid** [comment]
It would be great to have MZmine in Galaxy. And this way we would also finally ship an MZmine container.

I looked at your recipe and one thing I wonder - can we just pull the MZmine release and wrap it into a conda environment?
MZmine ships the JVM with it using JPackage. So there are no further requirements and we do not need an additional JDK/JVM.

**Comment by robinschmid** [comment]
Later this year there will be JDK21 and we will definitely update to this.

**Comment by robinschmid** [comment]
Modern java creates a customized JVM for each tool. So that there are no additional dependencies. Other Java tools will not use the MZmine packaged JVM. Also, it can strip away unneeded packages and make the whole JVM slimmer. 

So it's kind of like conda, in the sense that your virtual environment is encapsulated - in return, I do not understand so much about conda. 

I think our best bet also for future releases would be to install the MZmine version into conda. It seems like you can just download and install the package like this?

`conda install /path/to/package/package-name.deb`

.deb or .rpm are here
https://github.com/mzmine/mzmine3/releases/download/v3.4.27/mzmine-linux-installer_3.4.27.deb
https://github.com/mzmine/mzmine3/releases/download/v3.4.27/mzmine_linux_installer_3.4.27.rpm

Otherwise, we can try just to unpack the portable zip. But I guess if the above works that should be best. 
https://github.com/mzmine/mzmine3/releases/download/v3.4.27/MZmine_Linux_portable_3.4.27.zip

**Comment by robinschmid** [comment]
We can also try JDK20 but this would involve testing etc and then to push a new release

**Comment by bernt-matthias** [comment]
> conda install /path/to/package/package-name.deb

Never have seen this. Would be really surprising.

> So that there are no additional dependencies. 

Initially I really liked the idea. The problem is that JVM will still need some system requirements (zlib, x11 libraries, fonts, etc). These would come automatically due the `host` and `run` requirements specified in the [`openjdk` recipe]( https://github.com/conda-forge/openjdk-feedstock/blob/4426513f09b901ccde64e09d074558c364172d98/recipe/meta.yaml#L72). So I doubt that this would work .. in particular in containers. 

I still will try ... but also try to find people that could help me with the openjdk 19 problem at conda-forge.

**Comment by bernt-matthias** [comment]
Seems that jdk 20 is easier https://github.com/conda-forge/openjdk-feedstock/pull/120.. Would this be an option?

**Comment by bernt-matthias** [comment]
MZmine 3.6.0 is [now](https://github.com/galaxyproject/tools-iuc/pull/5462) available for Galaxy. It should soon be available on usegalaxy.eu.
