### ISSUE TITLE
Export to GNPS-GC-MS (with ADAP) Error

### ISSUE THREAD

**Issue by KolDmitry** [mzmine/mzmine3#1315]
### Basic information
* My operating system and version: Windows 10 Pro 22H2
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz
* My MZmine version: 3.4.27 

### What happened
I try to Export Aligned Feature List to GNPS-GC module.
Feature list was created after filtered procedure and gap-filling. All steps was done according to the YouTube Tutorial.
![image](https://user-images.githubusercontent.com/75040384/233577255-96567d78-f436-499f-84e7-e537166c70c1.png)

The Mistake:
![image](https://user-images.githubusercontent.com/75040384/233577334-58303ad6-7102-4539-a411-5f7ab0aadcfa.png)

Console:
![image](https://user-images.githubusercontent.com/75040384/233577619-fdc78fbb-a1a8-4b99-ac7c-ad9377e81788.png)

I don't know how to solve this issue.
Can you help me?

Thanks a lot!

**Comment by KolDmitry** [comment]
Good day!
I still can't solve the problem. Can you help me? Are there any solutions?

I really need the data to continue my scientific work.

Thank you!

**Comment by KolDmitry** [comment]
Good day!

Unfortunately, there is no feedback from you. But I keep hoping and trying to do something with my data.

I also tried to use ProteoWizard SW to ‘PeakPicking’ vendor algorithm before exporting the data to MZMine 3 (and convert files to mzml format), but that didn't help me get over my previous mistake either.

Probably I can use another way to convert GC-MS Aligned feature list filtered - for GNPS?
I have tested another option in converter, for example ''MGF File (ADAP)'' - work properly, as like as, ''Molecular Networking Files'' - Work correct too. 

Can you tell me, I must use only GNPS-GC-MS algorithm in order to convert GC-MS files and then work in GNPS? Or I can use ither approaches too...?

Please give me any suggestions.

**Comment by robinschmid** [comment]
Sorry for the late reply. We traveled a lot but I think I found a bug in the export. 
Can you try to download the development version from this fix:
https://github.com/mzmine/mzmine3/pull/1334

After logging in you should find it when scrolling down on the actions page:
https://github.com/mzmine/mzmine3/actions/runs/4925874389?pr=1334

**Comment by KolDmitry** [comment]
Hi, Robin!
Yes, now it's work properly!

Thank you very much for your job and for your support! 
I should say, that it's a perfect tool to post-processing data! 

Please don't stop to improve it! Good luck!
