### ISSUE TITLE
Error mzML import in MZmine3

### ISSUE THREAD

**Issue by Lizzievsj** [mzmine/mzmine3#1318]
### Basic information
Hi ! 

* My operating system and version: Ventura 13.1 (MacOS) and I also use Windows 10 PRO (V18363.1556)
* My MZmine version: 3.3.0 (also try 3.2.8, 3.4.16, 3.4.27)

### What happened : I need to export my data in mzML, but this message error when I try to use mass detection. I was recommended to try to convert my data twice in mzML, but then I have this message error.

When I open my mzML files in text editor, there are no special characters.

This is a conversion file in positive and negative mode, maybe the problem is here ?

Using mzXML seems better, but I always ended with an empty files at the end... Any solutions ?

**Comment by Lizzievsj** [comment]
I am working on shimadzu vendor files .lcd

**Comment by robinschmid** [comment]
Can you add an example file?
Raw and converted
