### ISSUE TITLE
Isotope export (csv)

### ISSUE THREAD

**Issue by Carole-re** [mzmine/mzmine3#1319]
Hi,

I use MZmine to process LC/MS data (orbitrap). I have a list of compounds I need to research but don't know the retention times for them. I prefer to use a "non-targeted" method, first with ADAP chromatogram builder, then chromatogram resolving and 13C isotope filter. I make the annotation from a csv file after these steps. However, I have several compounds with close masses that I cannot identify with mass accuracy alone but could identify through isotopic profiling. The variety of molecules present in the mixtures does not allow me to use the isotopic peaks finder (I tried but it identifies ions that have no connection).

In order to score other than by mass precision (specially when several DB compounds are possible), is it possible to export the 13C isotopes with their intensities in a CSV file? Or, during annotation step, add a score based on the isotopic profile ?

Thank you

**Comment by SteffenHeu** [comment]
An isotope score was recently added to the custom db search by @Sonja-analytik. YOu can try it.
