### ISSUE TITLE
Can mzmine3.4.27 directly identify the adduct form of each feature after GAP-FILLED? and  .msp format will not display the adduct information 

### ISSUE THREAD

**Issue by Judyzyw** [mzmine/mzmine3#1320]
### Basic information

* My operating system and version:windows 64 bits
* My MZmine version: 3.4.27

### What happened

1. * I want to directly see the adduct form of each feature detected in our sample data, and I have not found that there is a separate module step that can help me identify adduct, and When adjusting the Column in the feature list table, there is no separate ADDUCT option for the feature. Subsequently, I adopted the two steps of "metacorrelate-ion identity networking", and checked the three addition forms in the ion identity library option in "ion identity networking", but there are only a few features in the final feature list table has adduct form information, and other features lacking an adduct form are not sufficient to assist subsequent  spectral library matching and substance identification steps. 
<img width="893" alt="1682398129424" src="https://user-images.githubusercontent.com/120540244/234177274-c30698f4-5105-4f9b-8144-9c3c30ffb8bc.png">
2. At the same time, I also found that the database in .msp format will not display the adduct information in the feature list table.
<img width="955" alt="92a52f62019f7f103a74674caa87b9a" src="https://user-images.githubusercontent.com/120540244/234178532-6e032bb0-9be7-4fe6-90f7-989884799c32.png">
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by robinschmid** [comment]
Ion adducts formed depend on many experimental factors. Often you will only get one adduct and then we cannot identity it. But metaCorrelate + ion identity networking is the way to go. 
Use the batch wizard to setup a batch to see the default workflow. 

We typically export all to mgf for SIRIUS and GNPS. The msp export is outdated and mostly used in the GC-MS workflows.

**Comment by Judyzyw** [comment]
Thanks for your answer, but there are still some problems here.
I used the batch wizard to setup a batch, in which I successfully found ADDUCT through the method of "metaCorrelate + ion identity networking", but only part of the feature's adduct can be found, most of the feature's adduct information is still missing, the problem How can I solve it?

**Comment by robinschmid** [comment]
You will never find adducts for all features. 
- Many features might be noise.
- Many compounds are only ionized as one adduct
