### ISSUE TITLE
Cannot open Thermo Raw

### ISSUE THREAD

**Issue by gistamayo** [mzmine/mzmine3#1325]
### Basic information

* Mojave Mac IOS 10.14.6
* My MZmine version: 3.4.27

### java.lan error

cannot open thermo raw files from Orbitrap Exploris 120. I have to convert them to mzML to open them. This has always been so with Exploris 120 raw files in mac.

**Comment by robinschmid** [comment]
Can you provide a test file?

**Comment by gistamayo** [comment]
Robin: you will get (hopefully) an invitation from Google Drive to two experiments, one positive and one negative. They were obtained in our Explores 120. For some reason, experiments obtained in the Orbitraps Explores 120 we have measured, have to be converted to mzML to be seen by MZmine 3. 

The message I obtained from MZmine 3, is that there are no scans detected….
Dra. Giselle Tamayo Castillo
Prof. Catedrática
CIPRONA
Directora
***@***.***
***@***.***

**Comment by robinschmid** [comment]
I could not find it. My email is rschmid1789@gmail.com

**Comment by gistamayo** [comment]
Robin:  did you look into this issue (Thermo Raw from Explores 120 nor Thermo TSQ GC-MS) can be opened from raw files?

I was trying to load mzML from some HRMS/MS experiments from the Explores, I used Proteowizard and convert them with 64bits. Is that a problem? I got the following message:



Version of MZmine: 3.6.0


Dra. Giselle Tamayo Castillo
Prof. Catedrática
CIPRONA
Directora
***@***.***
***@***.***

**Comment by SteffenHeu** [comment]
No issue messages posted to github.
