### ISSUE TITLE
Cannot open Bruker IMS-MS file

### ISSUE THREAD

**Issue by bili123987** [mzmine/mzmine3#1339]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.4.27

### What happened

* **Cannot import Bruker IMS-MS .d or .tdf data file**，and the pop-up window shown below.
* My IMS-MS datas are collerted from Bruker timstof with data formats .d or .tdf:
* 
<img width="468" alt="image" src="https://github.com/mzmine/mzmine3/assets/133571002/090cd22e-7c38-42de-a5ba-c2d7d13a0a5c">

<img width="406" alt="image" src="https://github.com/mzmine/mzmine3/assets/133571002/7233a3a7-ed1f-4467-b546-7640aa0e351c">

* 
<img width="960" alt="image" src="https://github.com/mzmine/mzmine3/assets/133571002/c0305330-3fd4-4ee8-bec9-62b4ef1cc55b">

Here is a IMS-MS .tdf data file:
[analysis.zip](https://github.com/mzmine/mzmine3/files/11472172/analysis.zip)

**Comment by SteffenHeu** [comment]
Any updata? Otherwise the issue will be closed next week.
