### ISSUE TITLE
Questions about RANSAC algorithm

### ISSUE THREAD

**Issue by grimace9527** [mzmine/mzmine3#1348]
**Is your feature request related to a problem? Please describe.**
Dear mzmine team,
Thanks for your novel and user-friendly software. And this is actually not a feature request.
Since I'm new to quantitation of proteomics, when I am trying to learn the RANSAC algorithm in the MZmine2 article (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-395), some questions are encountered. Could you please explain the algorithm briefly to me and thanks a lot for your reply!

![image](https://github.com/mzmine/mzmine3/assets/56531544/1142dae8-2c15-4359-8ac5-78701d18efec)

About the sentence "The purpose of peak list alignment is to match relevant peaks across multiple samples.", I am curious about how the "relevant peaks across multiple samples" are decided or calculated. Are these peaks actually the "features" extracted from MS1 spectra? If yes, how to select the features used to align? If no, then what kind of peaks are selected?
And if the data used for alignment are just 1-d arrays containing time points?

Thank you again for your kind reply. : )

Best Wishes,
Jim Thompson

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by grimace9527** [comment]
Hi Dr. Tomas,
Thanks for your response and I think I get the principle the algorithm now. But I have just one more question...If all the features which passes the filteration of the "RANSAC aligner" window are used for the alignment, is there a set of preferred parameters based on your experience? Thanks a lot!
![image](https://github.com/mzmine/mzmine3/assets/56531544/1b24aebc-36e8-46d4-9cbc-88a7680a9edf)

Best regards & thanks
Jim

**Comment by tomas-pluskal** [comment]
Hi Jim, I personally use the Join aligner. because it is conceptually more simple.
You should try to optimize the parameter values based on your dataset.

**Comment by grimace9527** [comment]
Thanks for all your response! : ) I'll try the optimization
