### ISSUE TITLE
MS/MS spectral networking

### ISSUE THREAD

**Issue by m-beliaeva** [mzmine/mzmine3#1355]
### Basic information

* My operating system: macOS Ventura 13.3.1
* My MZmine version: 3.3.0 and 3.4.27

### What happened

I am processing MS2 data, and I would like to know if MZmine can group aligned feature list based on cosine similarity. It seems to me that MS/MS spectral networking (Molecular networking) module should do the trick, but eventually, I do not understand how it works and what is the output. I also haven't found any documentation or tutorials for this module. 

Below are the parameters I use. The task is running, but I cannot spot any difference before and after.
<img width="628" alt="image" src="https://github.com/mzmine/mzmine3/assets/134639434/dfe602de-3b09-43d0-a87e-0d71c8fc5a3f">

Technically, I can export data to GNPS and proceed there, however, my goal is the only list of grouped peaks with cosine similarity score, and GNPS is a bit of an overkill, so it would be great to use that feature in MZmine.

Thanks for the help!!

**Comment by robinschmid** [comment]
We are still working on this feature. The visualizer is broken at the moment but there is a feature list exportmodule that exports all the network to graphml
