### ISSUE TITLE
Settings Correlation grouping(meta Correlate) and Ion Identity networking

### ISSUE THREAD

**Issue by Locaardas** [mzmine/mzmine3#1358]
Dear MZmine community,

I am using MZmine3.4.27 and have created a batch queue for orbitrap measurements in negative mode. My problem is related to the "Correlation grouping(meta Correlate)" and "Ion Identity networking". To better understand the modules, I read the publication "Ion identity molecular networking for mass spectrometry-based metabolomics in the GNPS environment", watched the "CMFI Mass Spec Seminar" on YT, and read the online documentation.

I am a bit confused about the setting of the "Correlation grouping(meta Correlate)" regarding the "Min sampler filter". According to my understanding, this filter only groups features if they were found in a minimum number of samples. The module looks like this in my MzMine version:

![metaCorrelate](https://github.com/mzmine/mzmine3/assets/82817975/75737034-aa2f-4315-aa50-be5d565fbc24)

1) What should "Max of" mean in this context? Is this a display error (on the GitHub page, it says "abs" instead of "max of", which might mean absolute and would make more sense)?

2) I used the modules Gapfilling (Peak finder) before the "Correlation grouping" and afterward the "Duplicate peak filter". Under which conditions are enabling or disabling "Exclude estimated features (gap-filled)" recommended?

Regarding Ion Identity networking -> "Ion identity library", the Modules suggest possible adducts to the user with the help of the "Rest negative" button. Among the adducts, also " [M+Na]+" is listed. Is that a mistake? In negative mode, you should not see any + charged ions. 

![Ion Identity networking](https://github.com/mzmine/mzmine3/assets/82817975/5e58b374-b579-4aca-b168-d4faa389099f)

Thanks in advance; I genuinely appreciate the work and time you have put into MZmine to help make the MS community richer.

Many greetings,
Locardas

**Comment by robinschmid** [comment]
The gap filled features should usually be excluded. 
Just use the MZmine batch wizard to setup a batch file and see what we recommend. 
gap filling then duplicate filter, then grouping and IIN

As for the minimum samples filter it should be pretty clear you can provide absolute and relative numbers and the maximum will be used

**Comment by robinschmid** [comment]
The Na adduct in negative is only there so that you can easily mix Na with negative ions like Na-2H
