### ISSUE TITLE
spectral match Incomplete information

### ISSUE THREAD

**Issue by Judyzyw** [mzmine/mzmine3#1360]
### Basic information

* My operating system and version: Windows10 64bit
* My MZmine version: 3.4.27

### What happened
I tried to use the MONA database (.msp) for spectral matching, but the software could not display the INCHIKEY information contained in the database.
<img width="831" alt="bad0aade0ae7c01708202fe3ea8b0a9" src="https://github.com/mzmine/mzmine3/assets/120540244/6ce7d44e-694e-4151-9660-283a153a476f">
This is the interface of the spectrum database, because the amount of data is too large to upload, so only screenshot，
<img width="501" alt="e8b48ecc3644f997607c70a0f7739a7" src="https://github.com/mzmine/mzmine3/assets/120540244/ecc7c4d9-0c74-4a6c-a353-50b05fd24fee">

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.

**Comment by Judyzyw** [comment]
>

**Comment by SteffenHeu** [comment]
The Inchi is specified in a string, not as a regular data field seperated by ':', that's why it's not leaded.

**Comment by robinschmid** [comment]
The MoNA msp format is not default. 
We support their json format better. Or mgf
