### ISSUE TITLE
Saving MZmine project 

### ISSUE THREAD

**Issue by adriherar** [mzmine/mzmine3#1366]
### Basic information

* My operating system and version: Windows 11
* My MZmine version: 3.4.27

### What happened

After I've done every step to get the .csv file I was unable to save the project. The following error is showing:

![image](https://github.com/mzmine/mzmine3/assets/116106346/05f7ce89-9eb3-47db-a11d-b7bd32dd5c10)

It appears that Raw data files cannot be saved and I'm unable to upload the file to the drive, so you can download it and check for any mistake. Please help me with this issue.

**Comment by calderod** [comment]
try running MZMine 3 in administrator mode and seeing if you can save Raw files now. I experienced a similar issue many months back: https://github.com/mzmine/mzmine3/issues/1271

**Comment by adriherar** [comment]
Thanks a lot @calderod it worked perfectly.
