### ISSUE TITLE
no Kovats index extraction in Tools

### ISSUE THREAD

**Issue by marleenlk** [mzmine/mzmine3#1370]
### Basic information

* My operating system and version: macOS Ventura 13.0.1 (M1)
* My MZmine version: MzMine 3.4.27

### What happened

I was watching this YT tutorial on Kovats extraction using MZmine: https://www.youtube.com/watch?v=XodHMJcuwnk&t=2s
When I tried it myself I found that the Tools>Kovats Index Extraction was not existing in my MzMine version. See screenshot. 
![image](https://github.com/mzmine/mzmine3/assets/135966418/e2f3b39d-3494-4919-8f19-391d55451e61)* 

I uploaded my file in CDF format. Can someone help me out with what I am doing wrong?

**Comment by AGHeyer** [comment]
Hi there,
is there any further development in this issue?If there is no Kovats indexing any more, how can substance libraries be used, given that retention times depend on GC-Columns and separation methods. Is there any kind of work-around?
