### ISSUE TITLE
DIA pseudo MS2 builder fails when selecting MS2 scan by "Definition"

### ISSUE THREAD

**Issue by meowcat** [mzmine/mzmine3#1375]
### Basic information

* My operating system and version: Win10 22H2
* My MZmine version: 3.5.0

### What happened

Running a workflow with "DIA pseudo MS2 builder" and a value in "MS2 scan selection -> Scan definition" leads to an array out of bounds exception in the DIA MS2 builder step. The same does not happen when I don't use "Scan definition". 

Batch and raw files at: https://drive.switch.ch/index.php/s/0peARISSfhfihXb

Note that the raw files have two MS1 scans per MS2 scan of that type, maybe that plays a role?

Expected outcome: I don't know why specifically there is an error, maybe an empty scan somewhere is enough, but regardless of the data the workflow should not fail. 

![image](https://github.com/mzmine/mzmine3/assets/1563881/97396aaa-9f11-4580-8510-4b95df79aa0e)

![image](https://github.com/mzmine/mzmine3/assets/1563881/83174392-5361-4d76-858a-3c2a1bfb8ae9) (for every raw file)

**Comment by SteffenHeu** [comment]
Hi, 

i tested it and you only need to change two things:
1. the mass detection for MS2: i would not filter for scan definition there, best just do a mass detection in all ms2 scans
2. the selection in the ms2 grouping: the filter needs a wildcard before and after the 705: e.g. '*705*' -> without ' but with *

**Comment by meowcat** [comment]
thanks!
