### ISSUE TITLE
Getting started with mzmine

### ISSUE THREAD

**Issue by sanmol472** [mzmine/mzmine3#1376]
I have recently started using mzmine 3

I had raw LC-MS data in .d format which I converted into .mzdata format using mass hunter

then I opened mzmine and uploaded that .mzdata file.

TIC is not appearing and showing no scans found
although I can see 752 mass scans but no chromatograms/intensity

**Comment by robinschmid** [comment]
What instrument are you using?
You should aim for mzML as its the latest open data format and the defacto standard currently

**Comment by sanmol472** [comment]
thankyou for response

I have converted into mzml format and now its working fine

i have reached out to the level where i have to search library
i uploaded mona library and gnps library whose link was given in mzmine
tutorial

but no compounds were found in that (my targeted compounds are mainly
diterpenoid alkaloids)


i saw these type of compounds on coconut database but its format is .bson
and mzmine is not able to support it

how can i proceed
or suggest if i am doing something wrong?






With Regards
Anmol (10CC19A33030)
Senior Research Fellow
Phytochemistry and C-H Activation Lab
Chemical Technology Division
CSIR-Institute of Himalayan Bioresource Technology, Palampur (H.P)
Academy of Scientific and Innovative Research (AcSIR)
India, 176061

**Comment by robinschmid** [comment]
Spectral libraries only apply if you have MS2 data. 
COCONUT is a compound database. 
You can use SIRIUS for annotation in this case. But again need MS2 data for this

**Comment by sanmol472** [comment]
Warm greetings

please see trailing mail

you suggested me to use serius database

but still, nothing fruitful is coming.

is there any other alternative?

Any other software/database

or any media by which I can predict the fragmentation pattern of
structures ( from the literature)
create my own database which can be uploaded to mzmine?

With Regards
Anmol (10CC19A33030)
Senior Research Fellow
Phytochemistry and C-H Activation Lab
Chemical Technology Division
CSIR-Institute of Himalayan Bioresource Technology, Palampur (H.P)
Academy of Scientific and Innovative Research (AcSIR)
India, 176061
