### ISSUE TITLE
Add `--help` and `--version` argument to CLI

### ISSUE THREAD

**Issue by bernt-matthias** [mzmine/mzmine3#1378]
**Is your feature request related to a problem? Please describe.**

Currently there seems to be no way to determine the version of the mzmine command line interface. Would be cool to have these pretty standard arguments. 

**Describe the solution you'd like**

Add parameters. `MZmine` should print the version / help and exit with exit code 0.

**Additional context**

I noticed this, because for the bioconda recipe we use a simple call to `MZmine` as test. Since this exits with a non-zero exit code extra measures are needed. That is we call `(MZmine --help || true) |& grep "Starting MZmine {{ version }}"` .. could be easier :)

**Comment by robinschmid** [comment]
See the PR this should work right?

**Comment by bernt-matthias** [comment]
Excellent
