### ISSUE TITLE
Can't process MS2 data from timsTOF .tdf file

### ISSUE THREAD

**Issue by prfsullivan** [mzmine/mzmine3#1380]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 3.4.27, MZmine 3.5

### What happened

I have Bruker timsTOF Flex LC-IMS-MS data (.d -> .tdf) that I am trying to process.  I run mass detection for both MS1 and MS2 and raw data overview suggests it worked.  I used 'Frame only' and 'Centroid'.  See first figure.

However, when performing ADAP Chromatogram Builder, MS2 data are not included.  See the second figure for ADAP CB parameters I used.  When I try to export the feature table (or any downstream feature table), there are no MS2 data.  GNPS files are empty, for example.

I was, however, able to successfully create a feature table that included MS2 data processed using ADAP CB from an mzML file.  This file was converted from a .d file (no ion mobility) using MSConvert. 

I'm happy to provide any more information that is relevant.

Thanks,
Peter   

![MS2_mass_detection](https://github.com/mzmine/mzmine3/assets/32913798/0a4d4a6d-5bee-441d-bf89-f0653da9a133)

![ADAP_chromatogram_builder_parameters](https://github.com/mzmine/mzmine3/assets/32913798/5de5c736-774d-4602-9de2-a54d67fd6d1f)

**Comment by SteffenHeu** [comment]
Hi, 

>  I run mass detection for both MS1 and MS2 and raw data overview suggests it worked. I used 'Frame only' and 'Centroid'. See first figure.

You need to run mass detection in mobility scan dimension, too. Do you not want to get the IMS data also in MS1 dimension? Best follow the processing wizard and see what modules it uses for processing and then optimize the parameters for your dataset.

> I was, however, able to successfully create a feature table that included MS2 data processed using ADAP CB from an mzML file. This file was converted from a .d file (no ion mobility) using MSConvert.

I don't exactly know what happens with the MS2 data during conversion when removing the ims dimension. I'd not recommend this, it might merge all ms2 spectra from a single tims ramp.

**Comment by prfsullivan** [comment]
Yes -- that was the issue.  Appreciate the help, Steffen.
