### ISSUE TITLE
problem with mass detection 

### ISSUE THREAD

**Issue by marleenlk** [mzmine/mzmine3#1381]
### Basic information

* My operating system and version: MacOS ventura 13.0.1.
* My MZmine version: 3.5 

### What happened
When I import my raw data (netCDF or mzML) I want to perform mass detection as a first step using the following parameters: 
MS1, level = 1, RT[3,650..60.000]
centroid 
noise level: 5.0E5

MZmine says that the mass detection is finished and I want to continue with the ADAP chromatogram builder. However, I do get the following error; 

Scan #1 from ... does not have a mass list. Please run "Raw data methods" -> "Mass detection". 

This issue started occurring this week and wasn't an issue before. 

What could be the cause for my problem?

**Comment by SteffenHeu** [comment]
Hi,

i think scan 1 is not within the RT boundaries you set in mass detection. Either use the same boundaries in ADAP or just use no RT boundary during mass detection (recommended).

We recommend to start with the wizard workflow and adapt and optimize parameters for your specific application from there.

**Comment by marleenlk** [comment]
Thank you!
