### ISSUE TITLE
error  raw data import MZmine3.5.0

### ISSUE THREAD

**Issue by xiaoyaozhuangzi** [mzmine/mzmine3#1382]
Some scans were recognized as empty, when raw data import MZmine 3.3.0 to 3.5.0 . However, the error does not generate, while the same data import MZmine 3.2.8. What is the reason?

<img width="397" alt="image" src="https://github.com/mzmine/mzmine3/assets/108784543/94bdc435-d57a-4357-ac25-f526e4fb695a">

**Comment by robinschmid** [comment]
This error was added around that time. Maybe it was added it 3.3.0
This is not really an issue more something to be aware of
