### ISSUE TITLE
Sorting in scheduler

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#1387]
i am pretty certain this cannot be correct.
sorting will change the order of the indices and sorting is often done in multiple iterations. 
So the indices will then point to the wrong intensities....
I think you will need to do something like
```java
record IndexedValue(int i, double value){}

IntStream.range(0, intensities.length).map().map(i -> new IndexedValue(i, intensities[i]).sorted(Comparator.comparingDouble(IndexedValue::value).reversed()))
```
I think this is the only good way of sorting two lists together. Similar in python where the lists are zipped together into a list of tuples

_Originally posted by @robinschmid in https://github.com/mzmine/mzmine3/pull/1144#discussion_r1232570529_

**Comment by vivekd01** [comment]
i want to work on this issues please assign me this issue
