### ISSUE TITLE
Aligned feature list, some info not displayed

### ISSUE THREAD

**Issue by greencodefairy** [mzmine/mzmine3#1393]
### Basic information

* My operating system and version: Windows 10 enterprise 22H2
* My MZmine version: mzMine 3.4.27

### What happened

* Please describe what happened and how it differs from what you expected to happen.
Loaded converted qTOF Waters data (raw to mzML). At the step where the feature list is aligned, colored circles should appear to indicate, if feature is present or not in each sample, as shown [here](https://www.youtube.com/watch?v=hk7WeXibReg&t=2216s), (training video YouTube at around 20:20 min, also see pic below), but only the blue ones appeared. Is this just a different setting or a bug?

Example from training video
![grafik](https://github.com/mzmine/mzmine3/assets/77613275/47f3e534-6318-4a87-b1e2-eb2cb68cc8e0)

Screenshot of own data in comparison
![grafik](https://github.com/mzmine/mzmine3/assets/77613275/9cc321e0-5caf-4737-91b4-5517d4aae81c)

**Comment by SteffenHeu** [comment]
The video was made with an older version of mzmine. The removal of the dots is a side effect of interal optimisation regarding the memory footprint.

**Comment by greencodefairy** [comment]
Thanks for the fast answer.
