### ISSUE TITLE
Trouble with Untargeted LC-IMS-MS Workflow via ion mobility trace builder

### ISSUE THREAD

**Issue by sydneysc** [mzmine/mzmine3#1395]
### Basic information

* My operating system and version: mac os version 12.6.2
* My MZmine version: mzmine 3

### What happened

I used the ion mobility trace builder workflow on centroided mzml files. I used the same parameters for each sample as I wanted to compare results amongst them. It was difficult to choose parameters that gave robust feature lists. I used the recommended parameters if they were provided, otherwise I tried different values until I got a decent feature list. I am curious if this workflow is just not as great at populating feature lists for samples (since the ADAP version is recommended) or if there are steps I can take to expand the results that I am getting.

Here are the parameters I used for each step:
mass detection:
raw data files = as selected in main window
scan filters = MS1, level 1
scan types(IMS) = Mobility scans only
mass detector = Centroid
setup (noise level = 1.0E3)
Ion mobility Trace Builder:
raw data files = as selected in main window
scan filters = MS1, level =1
m/z tolerance(scan-to-scan) = 0.0050 m/z or 17.0000 ppm
minimum consecutive scans(RT) = 6
minimum total signals = 200
Resolving Retention:
feature list = as selected in main window
suffix = resolved
original feature list = KEEP
MS/MS scan pairing = N/A
Dimension = Retention time
Chromatographic threshold = 50.0%
Minimum search range RT/Mobility (absolute) = 0.010 (recommended that a smaller value be used for IMS data)
minimum relative height = 0.0%. (recommended by documentation, parameter skipped when at 0 , minimum relative height)
minimum absolute height = 1.0E3
min ratio of peak top/edge = 1.70
peak duration range (min/mobility) = 0.50 - 10.00
Minimum scans (data points) = 6 (more scans for IMS data so higher number is better, no less than 4-5 recommended)
Resolving Mobility Dimension:
feature list = as selected in main window
suffix = resolved
original feature list = KEEP
MS/MS scan pairing = N/A
Dimension = Mobility
Chromatographic threshold = 50.0% (lower to avoid relevant data points in the mobilogram being discarded, [mobilograms]
Minimum search range RT/Mobility (absolute) = 0.010 (recommended that a smaller value be used for IMS data)
minimum relative height = 0.0%. (recommended by documentation, parameter skipped when at 0 , minimum relative height)
minimum absolute height = 1.0E3
min ratio of peak top/edge = 1.70 - 2.0 (using 1.7)
peak duration range (min/mobility) = 0.00 - 10.00
Minimum scans (data points) = 6 (more scans for IMS data so higher number is better, no less than 4-5 recommended)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

It will not allow me to upload a  saved project with extension .mzmine. Here are two files that show an example of how I am getting small feature lists.

[40_tabbed_PNACIC_IntStd_Hplas_MixR1_RPLC_02_Pos_20May21_Lola-WHSS310461.mzML.gz_ionmobilitytrace_resolved_resolved_sm.csv](https://github.com/mzmine/mzmine3/files/11817849/40_tabbed_PNACIC_IntStd_Hplas_MixR1_RPLC_02_Pos_20May21_Lola-WHSS310461.mzML.gz_ionmobilitytrace_resolved_resolved_sm.csv)
[40_tabbed_PNACIC_IntStd_Hplas_MixR2_RPLC_01_Pos_20May21_Lola-WHSS310461.mzML.gz_ionmobilitytrace_resolved_resolved_sm.csv](https://github.com/mzmine/mzmine3/files/11817851/40_tabbed_PNACIC_IntStd_Hplas_MixR2_RPLC_01_Pos_20May21_Lola-WHSS310461.mzML.gz_ionmobilitytrace_resolved_resolved_sm.csv)

**Comment by SteffenHeu** [comment]
The noise level for mass detection seems quite high for mobility scan data. best check your actual file. I recommend you use the wizard to build the workflow, keep the intermediate feature lists, and optimise the individual steps from there.

Another note: 
> Minimum search range RT/Mobility (absolute) = 0.010 (recommended that a smaller value be used for IMS data)
The note is for the IMS dimension explicitly. When resolving the RT dimension, it does not matter if you have IMS data or not, use a value that fits your data. You can find it by using the preview in the dialogs. And i think we wrote the recommendation at a time we only used tims data. For DTIMS and TWIMS you need different values. Again, best double check with your data. 

> Minimum scans (data points) = 6 (more scans for IMS data so higher number is better, no less than 4-5 recommended)
same applies here. 

In general: yes, the ion mobility trace builder is less sensitive than the ADAP workflow. That's why we recommend it and it's also used in the wizard. See here why that is the case: https://mzmine.github.io/mzmine_documentation/workflows/imsworkflow/ion-mobility-data-processing-workflow.html
