### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by elnurgar** [mzmine/mzmine3#1396]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.6.0

Hello,

We use the windows distance connection system to connect to pc where mzmine is installed. Each connection to PC provokes a new login to the session and each time the screen of Mzmine becomes black and nothing can be done. is it possible to find a solution?

Thanks,
With best regards,
Elnur

**Comment by SteffenHeu** [comment]
Hi Elnur,

we are aware of the issue. Unfortunately, it's not our issue to fix, but it relies on the framework we use for the user interface. Newer versions don't have the issue you described, but come with additional problems that are more problematic. The only advice we can give is to start mzmine after you logged in via the remote desktop. If you have a bioformatician, you can also recompile MZmine using javafx 19, then you can reconnect but you will have other problems.

**Comment by elnurgar** [comment]
Thank you, Steffen for your reply. The issue can be closed.
