### ISSUE TITLE
wrong version reported

### ISSUE THREAD

**Issue by bernt-matthias** [mzmine/mzmine3#1405]
### Basic information

v3.6.0 reports 3.6.1

probably just wrong in src/main/resources/mzmineversion.properties

**Comment by robinschmid** [comment]
The latest release is 3.6.0
This might be happening as you are building from source right?

**Comment by bernt-matthias** [comment]
> This might be happening as you are building from source right?

Indeed. Just tried to install from the deb package. There its correct.
