### ISSUE TITLE
Some scans were recognized as empty (no detected peaks).The possible reason might be the high noise levels influencing mzml conversion

### ISSUE THREAD

**Issue by tyche416** [mzmine/mzmine3#1410]
### Basic information

* My operating system and version: windows 11 64bit
* My MZmine version: 3.5.0

Hi. I have imported my data to MZmine but I found a warning described in the screenshot. I have reviewed your answers to the same question before asking, but the original format of the data is .wiff and cannot be directly imported into mzmine, so I want to know what can I do to continue my data analysis and the reason that the warning appearing, the process of format conversion is also shown in the screenshot, and I only changed the scan polarity during the process. I would greatly appreciate receiving your reply.
![msconvert-1](https://github.com/mzmine/mzmine3/assets/138010793/73f93715-2c94-4262-aac3-833aa6e50a44)

![mzmine2](https://github.com/mzmine/mzmine3/assets/138010793/9dd68688-dfba-4faa-ba9c-2a2a53852cca)

**Comment by DanielQuiroz97** [comment]
I am seeing the same warning message as @tyche416.

These data is DDA iterative files acquired with an Agilent 6546. Interestingly, only the first QC injection has this problem.

I am using msconvert with the following parameters (also in the image)

* peakPicking = vendor msLevel = 1-
* msLevel = 1-

![Screenshot 2023-08-02 at 11 21 26 AM](https://github.com/mzmine/mzmine3/assets/18486943/fd6d7bc4-698d-45db-a981-0d2cc769b64a)


Best,
Daniel
