### ISSUE TITLE
No response during execution of numerous samples on virtual machine.

### ISSUE THREAD

**Issue by ryang015** [mzmine/mzmine3#1413]
### Basic information

* My operating system and version: Win 10 pro 64bits
* My MZmine version: 3.5.0

### What happened

A VM computer running in the esxi host, we allocated the VM with 16c (2 CPU, 8c per socket), 64GB mem, and a dedicated SSD volume. No other VMs were active in the same Esxi host, so there was no way that other VMs on the same physical esxi host competing for computing resource when mzMine was operating.
The mzMine just got stuck without any response while loading 217 samples from the ssd volume, and we attempted to read the logs from the console but no clues were found (P.S. the console was freezed also). We are unable to provide error-related information and log files because the GUI and console of MZmine appear to be frozen without crashing (unless attempting to interact with it, which triggers a "Not Responding" message and a crash). Additionally, it seems that the occurrence of this issue is random, and it may occur during Data import or ADAP Chromatogram Builder.
We have successfully run this project on a personal computer (Win 10 pro 64bits, i7-12700 1 CPU 12c, 32GB mem, and SSD) using the same samples and parameters, so it does not appear to be a problem with the samples or parameters.
![1](https://github.com/mzmine/mzmine3/assets/138191273/da411722-1e5f-4a62-b205-2e2eb89d0e64)
![2](https://github.com/mzmine/mzmine3/assets/138191273/d38e4c15-ac40-4156-9e81-ad47e6274020)

**Comment by SteffenHeu** [comment]
Hi, 

maybe it has to with the dual cpus, but i'm not sure. Can you try limiting it to one CPU? Usually i'd say it shouldnt be a problem.

**Comment by ryang015** [comment]
> Hi,
> 
> maybe it has to with the dual cpus, but i'm not sure. Can you try limiting it to one CPU? Usually i'd say it shouldnt be a problem.

Thanks for your response. After restricting it to one CPU, MZmine is running more stably.
