### ISSUE TITLE
Ion identity networking

### ISSUE THREAD

**Issue by carobirer** [mzmine/mzmine3#1419]
### Basic information

* My operating system and version: Windows
* My MZmine version: 3.6.0

### What happened

Hi Mzmine3, 
In Ion identity library, I don't see any adduct possibilities, is this normal? Is there a CSV file somewhere which I can download to upload all adducts possibilities here?
Thanks for your help, 
Caroline

![image](https://github.com/mzmine/mzmine3/assets/38260122/4a7ca15e-9522-44ba-a332-246535bcb060)

![mzmine3_ionidentity](https://github.com/mzmine/mzmine3/assets/38260122/7f8af91d-332c-44bc-99c7-3afab11da1fe)

**Comment by SteffenHeu** [comment]
Hi,

you need to press the reset buttons.

**Comment by carobirer** [comment]
Thanks! It is working just fine.
