### ISSUE TITLE
Challenges in Importing and Visualizing Text Data: Seeking Assistance and Ideas

### ISSUE THREAD

**Issue by adukkath** [mzmine/mzmine3#1421]
Hello Mzmine,

I am currently facing an issue and I was wondering if you could assist me in resolving it. I have a raw file that can be exported as a text file. However, I would like to import the text file in the same format as i exported and visualize its contents. I have been struggling with this task and would greatly appreciate your help. My ultimate goal is to extract features from the text data and visualize them once again.

Additionally, if you have any ideas or suggestions on how to approach this, I would be grateful to hear them. Thank you for your time and assistance.

**Comment by SteffenHeu** [comment]
Not enough information.
