### ISSUE TITLE
Issue with SIRIUS export

### ISSUE THREAD

**Issue by zglong1** [mzmine/mzmine3#1426]
### Basic information

* My operating system and version: Microsoft Windows 10 Home, Version 10.0.19045
* My MZmine version: 3.6.0

### What happened

1. Waters Xevo centroided FastDDA data, converted to .mzML format using MSConvert (msLevels 1-2, scan events 1-4 to keep MS and three MS/MS channels while removing lockmass), loaded into MZMine.
2. Used crop filter to remove empty scans. Used "Mass Detection" module to pick MS1 (NL = 2.5E2) and MS2 (NL = 0E0). 
3. Used "ADAP chromatogram builder" on MS1 scans (min. 5 scans, min. cons. 2.5E2, min. height 2.5E3, tol. 0.0025 m/z or 0 ppm). 
4. Used "ADAP resolver" on the generated feature list (SN = 5, wavelet (PWM = 3, abs), min. height = 1E3, C/A Thr = 50, peak dur. 0.05 - 2.00 min, RT wavelet range = 0.00 - 0.05 min). 
5. Used "13C isotope filter" (m/z tol. = 0.0050 m/z or 0 ppm, RT tol. = 0.025 min, monotonic, max charge = 1, lowest m/z). 
6. Used "duplicate feature filter" (new avg., m/z tol. 0.0025 m/z or 0 ppm, RT tol. 0.050 min).
7. Used "feature list rows filter" only to reset feature number ID (required (?) for SIRIUS but this isn't a checkable option in the export dialogue itself, seemingly unlike in MZMine2?).
8. Used "Assign MS2 to features" (precursor tol. = 0.1000 m/z or 0 ppm, feature edge restriction, min. rel. height = 5%, min. signals = 1, merge spectra, min. rel. int. = 5%).

On attempted export using "SIRIUS / CSI-FingerID" (C:\Users\zanel\...\Attempted_Export.mgf, merge MS/MS (across samples, weighted avg. remove outliers, sum int., mass dev. 0.0050 m/z or 0 ppm, cosine and signal 0%, iso. offset 0.000 m/z, iso. window 3.000 m/z), m/z tol. 0.0050 m/z or 0 ppm), the task usually hangs at 0 % completion, although, when running this example project, it got stuck at 7% in the bottom right hand progress indicator and 8% in the tasks panel... I can still click around the UI, and the free memory value seems to cycle (~20 GB, then ~18 GB, ~16 GB, etc., then back to ~20 and repeats). But I've left it for an hour and nothing happened to the process, and the created .mgf file is 0 KB. The plain MGF export option works (instantly, even with the ongoing but static SIRIUS task, generating a 1 KB file).

Log file included in the linked Dropbox file, along with standalone project: https://www.dropbox.com/sh/ccqyxd7efwkas9t/AACmYS3GqpAN0ZwFO5ToDoPQa?dl=0

I'm relatively new to MZMine, and very new to SIRIUS (I've basically just uploaded the mzML files directly so far), so any tips (including my MZMine processing settings) are appreciated, alongside this issue report. :D

**Comment by ivanarozlan** [comment]
Hi. have you resolved this issue? I have the same problem as you. Mind to share the solutions if you have already found one?

**Comment by zglong1** [comment]
Honestly, I've been using the export module recently and haven't run into
the same issue. I'm not sure if something happened with an update, or if it
was a problem with the original data I was using, but I'm no longer having
the issue. Sorry for that unhelpful information!

**Comment by SteffenHeu** [comment]
Great to hear the issue was solved and sorry for not replying.
