### ISSUE TITLE
Randomly-generated MS2 ions in only one scan were assigned to fragments of features.

### ISSUE THREAD

**Issue by yuhan2621** [mzmine/mzmine3#1429]
Dear Developer,
      Thank you for providing such a convenient tool for MS data. We are having a problem in the process of using MZmine.
* My operating system and version: Windows 10 Pro 21H1
* My MZmine version: 3.4.16
    In LC-MS/MS analysis, there are some ions appearing by chance in MS1 or MS2 spectra. These ions  have no correlation with components in the sample and usually exist for one scan. These random ions will be detected by "Mass detection". In "ADAP resolver", the one-scan random ions of MS1 can be filtered by "peak duration" and "RT wavelet". However, in MS2 ions assigned by "MS/MS scan pairing", the one-scan MS2 ions will be assigned to features. We tried to dispose the MS2 ions with "ADAP resolver" and the one-scan MS2 ions can be filtered. While in the exported mgf file, the MS2 ions of features still included with the  one-scan ions.
    For example, for a feature at m/z 487.14, a random ion at m/z 79.4189 appeared in one MS2 scan. In the exported mgf file, this ion was in the list of MS2 fragments of the procursor at m/z 487.14.
![image](https://github.com/mzmine/mzmine3/assets/139550927/dbca6282-f979-4387-9447-c457c51bc86b)
![image](https://github.com/mzmine/mzmine3/assets/139550927/b336276b-9e0c-40bc-9c97-c4a3a13fe63f)
   The m/z tolerance was set as 0.05 Da. The noise levels of MS1 and MS2 were respectively set as 50 and 10. “RT tolerance” was set as 0.2 min in "MS/MS scan pairing". For MS1, “Min highest intensity” and “group intensity threshold” were respectively set as 500 and 100. “Min highest intensity”, “group intensity threshold” and “min group size in # of scans” were set as 500, 50 and 4. The file of MZmine cannot be uploaded on this webpage for "Something went really wrong, and we can't process that fire. Try again".
![image](https://github.com/mzmine/mzmine3/assets/139550927/3bc84efa-6d5e-4d7f-93b2-dd13d5017bfd)
![image](https://github.com/mzmine/mzmine3/assets/139550927/0ea4fa77-38bc-491c-80dc-e005730066ca)
![image](https://github.com/mzmine/mzmine3/assets/139550927/85964674-dc68-4975-8736-b71e3acd57a1)
    Thank you  for reading this letter. We would appreciate it if you could kindly help to sovle this problem.

**Comment by SteffenHeu** [comment]
Hi yuhan,

you are right these are just noise signlas. Most of them should be filtered by the Mass detection step, if you set the appropriate nosie level. As you described, you set the noise level to 10 for the MS2 scans, the signal intensity of that signal ist >10, so it is still in your data.

See this article: https://mzmine.github.io/mzmine_documentation/module_docs/featdet_mass_detection/mass-detection.html#how-do-i-determine-the-noise-level-in-my-data

I suggest to start with the wizard and then check the documentation for to optimize the workflow.
