### ISSUE TITLE
SiriusExportModule no END IONS for certain entries

### ISSUE THREAD

**Issue by ekopylova-2** [mzmine/mzmine3#1433]
### Basic information

* My operating system and version: Ubuntu 20.04
* My MZmine version: MZmine_Linux_portable_3.3.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.

Some entries have a "BEGIN IONS" but not an "END IONS" statement in the output MGF file, for example (first block correct, 2nd block has 2 BEGIN IONS statements and 1 END IONS:

BEGIN IONS
FEATURE_ID=151
PEPMASS=88.03868787703689
CHARGE=0
RTINSECONDS=18.01099956035614
MSLEVEL=2
FILENAME=X1.mzML
SCANS=303
88.0214 6.8E1
88.0357 7.3E1
END IONS

BEGIN IONS
FEATURE_ID=151
PEPMASS=88.03868787703689
CHARGE=0
RTINSECONDS=18.01099956035614
MSLEVEL=2
FILENAME=X2.mzML
SCANS=325
BEGIN IONS
FEATURE_ID=151
PEPMASS=88.03868787703689
CHARGE=0
RTINSECONDS=12.276000380516052
MSLEVEL=2
FILENAME=X4.mzML
SCANS=229
88.0397 6.8E1
END IONS

* Please include all parameter values for the MZmine modules you used. 

  <batchstep method="io.github.mzmine.modules.io.export_features_sirius.SiriusExportModule">
    <parameter name="Feature lists" type="BATCH_LAST_FEATURELISTS" />
    <parameter name="Filename">
      <current_file>/home/mzmine3_batch_template_Sirius.mgf</current_file>
      <last_file>/home/mzmine3_batch_template_Sirius.mgf</last_file>
    </parameter>
    <parameter name="Merge MS/MS" selected="false">
      <parameter name="Select spectra to merge">across samples</parameter>
      <parameter name="m/z merge mode">weighted average (remove outliers)</parameter>
      <parameter name="intensity merge mode">sum intensities</parameter>
      <parameter name="Expected mass deviation">
        <absolutetolerance>0.001</absolutetolerance>
        <ppmtolerance>5.0</ppmtolerance>
      </parameter>
      <parameter name="Cosine threshold (%)">0.7</parameter>
      <parameter name="Signal count threshold (%)">0.2</parameter>
      <parameter name="Isolation window offset (m/z)">0.0</parameter>
      <parameter name="Isolation window width (m/z)">3.0</parameter>
    </parameter>
    <parameter name="m/z tolerance">
      <absolutetolerance>0.0</absolutetolerance>
      <ppmtolerance>5.0</ppmtolerance>
    </parameter>
    <parameter name="Renumber IDs">false</parameter>
    <parameter name="Only rows with annotation">false</parameter>
    <parameter name="Exclude empty MS/MS spectra">true</parameter>
    <parameter name="Exclude multiple charge">true</parameter>
    <parameter name="Exclude multimers">true</parameter>
  </batchstep>

**Comment by robinschmid** [comment]
The SIRIUS export was reworked in a newer release. Please try out the latest release that we released today.
