### ISSUE TITLE
Is it possible to merge two aligned feature lists from different projects?

### ISSUE THREAD

**Issue by RemyMG** [mzmine/mzmine3#1441]
Hello,

I want to merge aligned feature lists from two MZmine projects into a common aligned feature list. First, is it possible?
The two feature lists originate from the processing of data of different polarity mode (positive and negative, same samples analysed in positive and negative mode). It is apparently possible through this module: https://mzmine.github.io/mzmine_documentation/module_docs/align_merge_lists/align_merge_lists.html

With this in mind, I exported my aligned feature list (mzTab and mzTab-m) from one project and then I tried to import it into the other project. But, first, the module was missing from the GUI (The "export feature list" menu is missing from "Feature list methods" section) (I'm running MZmine 3.7.2 version on W10). I could still access it through the batch mode, but you should maybe add it again to the GUI. And when I tried to open the aligned feature list it gives me this error message: 

![image](https://github.com/mzmine/mzmine3/assets/88542764/7bbe4835-394b-4d0d-8843-7ff3f37f8365)

I can easily import a "feature list" coming from a unique sample but not an "**aligned** feature list", I will have systematically the previous error message. 

Finally, is it possible to merge aligned feature lists? If yes, should I better process all my data (positive and negative mode) into a unique MZmine project to avoid the export/import steps? 

I really thank you for your answers and kind help.

Rémy

**Comment by SteffenHeu** [comment]
Unfortunately, the mztab import is not working and needs to be maintained. 
Also, it is not possible to align lists from different projects. everything needs to be in one project.
