### ISSUE TITLE
No scans found (ThermoRawImportTask.Java:192)

### ISSUE THREAD

**Issue by nguy1006** [mzmine/mzmine3#1449]
* My operating system and version: 64-bit operating system, x64-based processor. Windows 10, Version	22H2
* My MZmine version: Mzmine3.5.0
* I am a new user. Mzmine has been working smoothly for about a week. Then, I cannot import Thermo raw file into the soft ware. The problem identified as " No scans found (ThermoRawImportTask.Java:192). The raw file can be opened by Thermo X-Calibur.
* The software is currently not able load MZmine parameters.
* 
Raw file:
https://drive.google.com/file/d/1r7n6nyBqse3v-FVn-BXHiXSrUx5RFTfx/view?usp=sharing

![MZmine_Issue](https://github.com/mzmine/mzmine3/assets/141164725/5a8abe66-399c-4bab-b4dd-4895961dd5a7)

**Comment by tomas-pluskal** [comment]
Please try to install and run ThermoRawfileParser, and afterwards try to import .raw files into MZmine again.
https://github.com/compomics/ThermoRawFileParser/releases

**Comment by robinschmid** [comment]
Since when do you need to install the thermo raw file parser?

**Comment by robinschmid** [comment]
For now you can use the parser to convert the files to mzML

**Comment by tomas-pluskal** [comment]
> Since when do you need to install the thermo raw file parser?

It should not be needed. But I have seen before that in some cases the parser embedded within MZmine fails, and the issue gets fixed after installing the "official" parser. I guess it has something to do with registering the DLL dependencies properly, but I have no clue about the technical details.

**Comment by nguy1006** [comment]
Hello,
Thanks for your rapid support!
I downloaded ThermoRawfileParser, extracted it to the same folder of MZmine 3. I opened the MZmine again and it gave me the same error.
I then brought the computer to our local computer tech support. He did stuffs that I don't fully understand. He restarted the computer. MZmine is working for some .raw files but for others that don't. Attached is the file that cannot be opened.
https://drive.google.com/file/d/1UCrpdvtODMRW0AzgxRk-JUMOZbhjKFad/view?usp=sharing
Moreover, MZmine on my lab computer had the same issue when I used it. When our local computer tech support came, they only restarted the computer and Mzmine works again.
Please let me know what you find and what I should do next?
Sincerely,
Van

**Comment by robinschmid** [comment]
Not sure what is happening here. 
Best is to just convert the files to mzML and import those to MZmine if you are struggling with your files.

**Comment by nguy1006** [comment]
Hello Robin,
Thanks for your response!
The software is now working with al of the files. I don't know what is happening.
I will reach out to you if there is any things else happens.
Thanks again,
Van
