### ISSUE TITLE
Unhandled exception in task Exporting GNPS of peak list(s)

### ISSUE THREAD

**Issue by hellolizhi** [mzmine/mzmine3#1477]
### Basic information

* My operating system and version: win11
* My MZmine version: MZ mine 2.37.1 corr.17.7

### What happened
when I'm running the "export to GNPS" ,the mgf file can not. The  bug tell me "Unhandled exception in task Exporting GNPS of peak list(s) [sample data.raw chromatograms deconvoluted deisotoped filtered corr PERSON r>=0.85 dp>=51 to MGF file (s): java.lang.NullPointerException (MsMsSpectraMergeModule.java:282)".
<img width="1280" alt="73f7e99567d14d8e26a35f187447a51" src="https://github.com/mzmine/mzmine3/assets/103119992/607537ed-4ab6-4a30-a4be-46992bfa0279">

**Comment by SteffenHeu** [comment]
Hi hellolizhi,

unfortunately we don't develop and provide support MZmine 2 anymore. Please try the latest version of MZmine 3 and open a new issue if it still appears.
