### ISSUE TITLE
Feature table charts requirements

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#1480]
- [ ] clone chart / node to add it to multiple feature lists
- [ ] create charts only on demand but in one task
- [ ] use thread pool with half of available cores? - maybe even loom
- [ ] maybe use ConcurrentLinkedQueue to list demanded charts like in ParallelTextWriterTask

### How to store the final 
- [ ] ConcurrentHashMap of final nodes/charts against cell (FeatureListRow, RawDataFile, datatype)

**Comment by SteffenHeu** [comment]
addressed in #1511
