### ISSUE TITLE
About data processing

### ISSUE THREAD

**Issue by sanmol472** [mzmine/mzmine3#1485]
Warm greeting

I am new user i am doing data processing 
LC-MC/MS data

I have done preprocessing.

I have searched many databases but targetted class of compounds ie diterpenoid alkaloids are not found in any freely available database

so i have to do it manually by searching fragments

so is there any option that i can get list of Molecular ion peak and corresponding fragment details in any file.

Just as in export feature list we get Excel sheet (gnps format) having RT M/Z AND AREA , so is there any option where fragments are also mentioned?

**Comment by SteffenHeu** [comment]
Hi, the fragments are in the .mgf file created during the gnps export.
