### ISSUE TITLE
Not showing MS2 function after loading Water's MSe data 

### ISSUE THREAD

**Issue by UjjalkumarDas-create** [mzmine/mzmine3#1487]
### Basic information

* My operating system and version: Win11 Home version 10.0.22631 Build 22631
* My MZmine version: 3.9.0

### What happened
I have MSe (DIA) data generated by waters Q-TOF (G2 XS) in centroid mode and converted to mzML file using MS convert. Uploaded into Mzmine3, it retained MS1 function and MS2 function shows only one precursor ion at m/z 650 for all MS2 functions. Since my scanning mass range was 100-1200 Da, it was an exact average of the mass window. I expected it to open with MS2 information but it could not open it. I have tried directly opening raw file as well but it resulted in the same. 

I have shared the link having MSe data (.raw file), converted file (.mzML file) and MZmine3 project file.
Could you please look at this and help in this regard?

Thanks

https://drive.google.com/drive/folders/1D0OYRgSvpUKJuiXDazSBAMLQX5vk9Uwx?usp=drive_link

**Comment by SteffenHeu** [comment]
Hi,

this is what is stored in the mzl file and what would be expected in

**Comment by UjjalkumarDas-create** [comment]
Hi Steffen,
I was getting MS (level 1) precursor ion information, but I was expecting to get MS/MS information from MSe data. All MS/MS information was showing precursor ion at m/z 650 as shown in the image. I didn't understand this. 
![image](https://github.com/mzmine/mzmine3/assets/61827386/b41c7128-159d-457f-8e66-43aefbbf1078)

**Comment by SteffenHeu** [comment]
Hi,

are you familiar with what MSe does? You get no direct precursor-to-product ion relationships. You have to process the data to get the MS2 information. I recommend to use the wizard and select the DIA workflow and start your optimisation from there.

**Comment by greencodefairy** [comment]
@UjjalkumarDas-create have you found a solution for this challenge? I am also using MSe data in MZMine3 and in some of my samples the parents were missing after conversion in the mzML file, that I have seen in the Waters raw data. Have you observed something like this?
