### ISSUE TITLE
MZMine 3.9.0 Mass detection centroid issue

### ISSUE THREAD

**Issue by kirankumarp20** [mzmine/mzmine3#1491]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.9.0

### What happened

![Capture9](https://github.com/mzmine/mzmine3/assets/75622361/fbac2bc4-4ba2-4c09-8ccc-0f2c047cd7e8)

* Having issues ulpoaded files type in .mzml which was centroided when did MSConvert. So, now I have to select the option of Centroid as sepctral denormalization. Why am i getting this issues to select the spectral denormalization: factor of lowest mass signal.

**Comment by corinnabrungs** [comment]
Which instrument did you use? The problem is that you must set the mass detector to **factor of lowest signal** if you want to use the denormalizer. This is also the message that you get, you selected centroid, where it is not supported.

**Comment by kirankumarp20** [comment]
I used Q-TOF. But during the conversion using MSConvert the data is centroided. So, we have to use centroid for mass detection. How the baseline works even with the correction using assymmetric baseline correction, it doesn't touch the 0.0E level. I used Rcaller, unable to use Rserve, I don't how to run baseline correction using Rserve. Kindly help with this issues. Thanks for the reply.
