### ISSUE TITLE
In commandline mode, include a command to set an output folder.

### ISSUE THREAD

**Issue by vormsborg** [mzmine/mzmine3#1497]
**Is your feature request related to a problem? Please describe.**
It would be very beneficial with a command to specify the output folder for all of the exports in the commandline, so the user would not have to open the GUI to edit the output pahts every time (it is very easy to forget). So a tool like the -input command for output.

**Describe the solution you'd like**
It would be very beneficial with a command to specify the output folder for all of the exports in the commandline, so the user would not have to open the GUI to edit the output pahts every time (it is very easy to forget). So a tool like the -input command for output.

**Describe alternatives you've considered**
I currently have a python script that updates the folders in the batch XML file, but having the option to edit all the output folders all at once in the commandline would be a simpler solution.

**Additional context**

**Comment by SteffenHeu** [comment]
Hi, 

thanks for suggesting that. We already had it on our list, but haven't found the time to implement it yet.

**Comment by SteffenHeu** [comment]
Closing this, because it's a duplicate.
