### ISSUE TITLE
Formula prediction issues

### ISSUE THREAD

**Issue by djb561** [mzmine/mzmine3#1513]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: Mzmine 3.9

### What happened
Using the "formula prediction" module, there is no difference in selecting "sorting" or not, as shown by the attached screenshot. My sorting settings when selected are 10, 0, 0 respectively. The top predicted formula is never the formula with the lowest delta ppm, m/z or highest score. As you can see the second to top formula has a smaller delta ppm and m/z and higher combined score. 

![Mzmine3_sorting](https://github.com/mzmine/mzmine3/assets/125557758/fd367195-04ac-45ee-9ba1-6d9ae0cb180c)
![Mzmine3_nosorting](https://github.com/mzmine/mzmine3/assets/125557758/d2843a06-c571-4571-8026-a0422d3c9fae)
![Top selected formula](https://github.com/mzmine/mzmine3/assets/125557758/59ecf138-88ef-4e92-8978-f1b833b1ce25)
![second selected formula](https://github.com/mzmine/mzmine3/assets/125557758/ce2f4644-6771-45ba-9af7-d751d68a46c7)

Link to google drive: https://drive.google.com/file/d/1pzWqzQIClNc3l2Jv1g4JLLva6Z3NGvw7/view?usp=sharing

**Comment by SteffenHeu** [comment]
Hi, 

thank you for investigating, this is a great catch. 
I fixed the issue with this PR: https://github.com/mzmine/mzmine3/pull/1521

A fixed build should be available in the next minutes as the Latest development build.
