### ISSUE TITLE
Bruker .d file import error

### ISSUE THREAD

**Issue by ttseit** [mzmine/mzmine3#1517]
### Basic information

* My operating system and version: Microsoft Windows 10 Enterprise LTSC
* My MZmine version: MZmine 3.9.0

### What happened
I am using an Bruker instrument and importing .d files is offered as an option in Import MS data, but it produces an error (see attached figures)

![image](https://github.com/mzmine/mzmine3/assets/148848942/97ca6f47-f375-40aa-a9ff-f55b3d97b29d)
![image](https://github.com/mzmine/mzmine3/assets/148848942/b36b5e66-a767-455d-8a75-d6807bc2ed67)

**Comment by SteffenHeu** [comment]
What instrument are the files from? is it a timsTOF or an earlier instrument?

**Comment by ttseit** [comment]
It is a Bruker UHPLC-QToF (MS/MS analyses were performed with an Impact II quadrupole time-of-flight (qTOF) tandem mass spectrometer (Bruker Corp.) using an electrospray ionization (ESI) source.)

**Comment by ttseit** [comment]
I do can convert the .d files with ProteoWizard's MSConvert but then I get this warning in MZmine (see attached figure). In addition, solving the conversion of .d files from Bruker does not seem to be a straight forward process when looking for the issue in google. Therefore, I would appreciate a lot if you can help me in this issue. Thank you!

![image](https://github.com/mzmine/mzmine3/assets/148848942/0d24f939-6579-47c2-ad65-6b8beaaac8b2)

**Comment by SteffenHeu** [comment]
Hi, the old Bruker format is not supported unfortunately. So the conversion is the correct way. 

The warning is just a warning. it's possible that some scans are empty. If you don't set one during conversion, then that's fine. I recommend to use peak picking during the conversion process in MSConvert.
