### ISSUE TITLE
MZMine could not identify data type needed for import of files

### ISSUE THREAD

**Issue by calderod** [mzmine/mzmine3#1520]
### Basic information

* My operating system and version: Windows 10
* My MZmine version: 3.5.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.
I have saved four Thermo .raw files in a standalone MZMine project and I get this error when I try and open it. For other MZMine projects, this issue has not emerged for other project files that have stored Thermo .raw files. What should I try and do to fix this issue?
* Please upload screenshots of any errors **and** your log/mzmine.log file.
![MZMine 3 issue 10 25 2023](https://github.com/mzmine/mzmine3/assets/91331571/db6afd89-63d8-41c0-822e-038942ceebc7)
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
Here is a link to download this standalone MZmine3 project file: https://app.box.com/s/jxbz07xygy3dt2x5sthhw7zjqwo3m3mv
Please let me know if you cannot download the file, I will request for a specific email address and I will send you a specific invite link at that email address.

**Comment by SteffenHeu** [comment]
I can't download the file. Please send me a copy to steffen.heuckeroth@uni-muenster.de

**Comment by calderod** [comment]
Thank you Steffen for looking into this further. I have sent you a copy. please let me know if you need something else from me!

**Comment by calderod** [comment]
@SteffenHeu You are 1000% correct, I can see that probably what happened is I interrupted the saving process of the .raw files and they were not stored in the standalone file. Thank you so much for finding the source of this problem. 

Have a delightful rest of your week!
