### ISSUE TITLE
MzMine uses more cores than allowed

### ISSUE THREAD

**Issue by bernt-matthias** [mzmine/mzmine3#1534]
### Basic information

I am running mzmine on the command line on HPC using `--threads 32`. In `top` I often see CPU loads that indicate that mzmine takes more than the 32 cores (e.g. in the `%CPU` column I see values > 3200). The values are significantly larger (often values close to 5500) and also for longer periods of time. 

Coincidentally the node I'm using has 56 CPUs .. so a good guess is that there are some steps where `--threads` does not apply yet.

On the one hand this is a good message (MzMine seems to scale well), but in an HPC context, I have to request a certain number of CPUs/cores and jobs are usually killed if they take more than the requested.

Requesting a whole node is also not ideal because HPC users will need to wait long until such a job is scheduled.

### What happened

The last messages in the output are 

```
...
INFO: Starting step # 12
Nov 08, 2023 1:06:54 PM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Starting processing of task Filtering duplicate feature list rows of Aligned feature list peak gaps
Nov 08, 2023 1:06:54 PM io.github.mzmine.modules.dataprocessing.filter_duplicatefilter.DuplicateFilterTask run
INFO: Filtering duplicate peaks list rows of Aligned feature list peak gaps
Nov 08, 2023 1:09:39 PM io.github.mzmine.modules.dataprocessing.filter_duplicatefilter.DuplicateFilterTask filterDuplicatePeakListRows
INFO: Removed 4481 duplicate rows
Nov 08, 2023 1:09:39 PM io.github.mzmine.modules.dataprocessing.filter_duplicatefilter.DuplicateFilterTask run
INFO: Finished filtering duplicate feature list rows on Aligned feature list peak gaps
Nov 08, 2023 1:09:39 PM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Processing of task Filtering duplicate feature list rows of Aligned feature list peak gaps done, status FINISHED
Nov 08, 2023 1:09:39 PM io.github.mzmine.modules.batchmode.BatchTask processQueueStep
INFO: Starting step # 13
Nov 08, 2023 1:09:39 PM io.github.mzmine.taskcontrol.impl.WorkerThread run
INFO: Starting processing of task Identification of groups in Aligned feature list peak gaps dup scan events (lists)
Nov 08, 2023 1:09:39 PM io.github.mzmine.modules.dataprocessing.group_metacorrelate.corrgrouping.CorrelateGroupingTask run
INFO: Starting metaCorrelation search in feature list Aligned feature list peak gaps dup
```

**Comment by bernt-matthias** [comment]
Using 3.6.0

**Comment by SteffenHeu** [comment]
Hi Matthias, 

 the set number of threads parameter restricts the number of threads run by mzmine at the same time. The threads are still created and are set to wait until another thread finishes. 

Maybe it's a jvm option that would restrict the actual number of cores that mzmine runs on.

**Comment by bernt-matthias** [comment]
This would mean that in my case only `32` threads run at the same time. Which should result in a load close to `3200%`. 

Not sure if `-XX:ActiveProcessorCount=...` makes sense .. will give it a try.

**Comment by SteffenHeu** [comment]
Hi Matthias, did the parameter work as intended?

**Comment by bernt-matthias** [comment]
Sorry for not feeding the info back. 

In my experiments it looked like it worked and we implemented it like this in the Galaxy wrapper: https://github.com/galaxyproject/tools-iuc/blob/d529dafd5a2d3a017de226cd59e42cf630348e06/tools/mzmine/mzmine_batch.xml#L43
