### ISSUE TITLE
There is not any assigned MS2 in the list of scans

### ISSUE THREAD

**Issue by GhsJahanmir** [mzmine/mzmine3#1540]
### Basic information

* My operating system: windows 10
* My MZmine version: 3.9.0

My raw data is from Agilent triple quad. I converted them to mzML first using MS convert. after importing to MZmine3, I got the triangle warning beside the name of sample after importing saying that scans were detected as centroids but contains zero intensity values. I ignored this one for now.

the issue I faced, according to the below scan list, there is not any MS2. all the MSn values are 1. 

![image](https://github.com/mzmine/mzmine3/assets/85613062/1555a893-fb7e-4ba2-9d0f-d84b7afd26b3)

has anyone faced this problem before?

Thanks in advance,
Ghs

**Comment by kyrasolaris01** [comment]
Hi Ghs,
can you share an example mzML file as well as the corresponding .d file? We need t check if something goes wrong during conversion or during data import.

**Comment by GhsJahanmir** [comment]
dear @kyrasolaris01 
Thanks for your comment.
Sure. Here is the link of the files in zipped format.
[mzML] (https://drive.google.com/file/d/1v_lG-GFuNuQoEZOWP2uzOFNopy16wWxE/view?usp=sharing)
.d [file ] (https://drive.google.com/file/d/1jdu0i6L6abevFzSc5nqiFFWjG92Yl_i3/view?usp=sharing)

Thanks in advance,
Ghs

**Comment by kyrasolaris01** [comment]
Hi Ghs,
I looked into your data, and my best guess is there was a problem during data conversion to mzML, as the warning suggests. Can you share a screenshot of your MSConvert settings?
![image](https://github.com/mzmine/mzmine3/assets/140096361/b6043fff-9e2f-4df3-8c5d-ff75e29c53ce)

**Comment by GhsJahanmir** [comment]
Dear @kyrasolaris01,
thank you.

Please have a look at them here.

![1](https://github.com/mzmine/mzmine3/assets/85613062/0c90eb2e-ab2e-4b74-9286-70b16a151dbe)
![2](https://github.com/mzmine/mzmine3/assets/85613062/16e952e4-511b-42f8-973b-65e2d0abd5c3)


another update is that: if we convert them using original agilent software to mzData, the triangle warning is gone but still no scan 2 can be observed.
[Uploading D23-0020-P.mzdata.xml.zip…]()

Best,
Ghs

**Comment by GhsJahanmir** [comment]
> Hi Ghs, I looked into your data, and my best guess is there was a problem during data conversion to mzML, as the warning suggests. Can you share a screenshot of your MSConvert settings? ![image](https://private-user-images.githubusercontent.com/140096361/285117523-b6043fff-9e2f-4df3-8c5d-ff75e29c53ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzc3NzksIm5iZiI6MTcwMTIzNzQ3OSwicGF0aCI6Ii8xNDAwOTYzNjEvMjg1MTE3NTIzLWI2MDQzZmZmLTllMmYtNGRmMy04YzVkLWZmNzVlMjljNTNjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwNTU3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzNhMzlmMWQ2OWNlY2VhMDQ3NGZkNWI3Nzg4MWY2ZmVlMzY1OTliNmFkM2U2OGQ5YTliNDExODdiYmJhMzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4NZfMfTpyD7pkrfqUCX00s3-y_5bD0mkI1sQKcTvKuU)

Dear @kyrasolaris01 

Have you got time to look at the screen shot I shared? 
could this be because of we did full scan mode when doing LC-MS/MS?

Best Regards,
Ghs

**Comment by kyrasolaris01** [comment]
Hi Ghs,
yes I did, sorry for not replying yet. Your MSConvert settings look fine, however there seems to be an issue with data conversion, because there are scans assigned as MS level 2 in the converted file. MZmine is reading it correctly. If you check the log file printed at the bottom of MSConvert you can read a statement that "vendor centroiding" was requested but did not work. Please check if you acquire your data as MSConvert expects it or contact Agilent support to get assistants on converting the file as expected.

**Comment by kyrasolaris01** [comment]
Sorry, i missed the word "no". There are NO scans assigned as MS level 2....

**Comment by GhsJahanmir** [comment]
> Sorry, i missed the word "no". There are NO scans assigned as MS level 2....

ok.
Because we used  full scan MS2 for our sample, means that we did MS2 for all the ions from MS1 step, still should we see both MS1 and MS2 label in mzMine raw data overview?

**Comment by kyrasolaris01** [comment]
Please have a look at your raw data file. MZmine can only show what is in the raw data. In the mzML file I cannot see any scan defined as ms level 2. Please check for yourself: 
<cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="1"/> for MS1 scans and <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="2"/> for MS2 scans.

**Comment by GhsJahanmir** [comment]
thank you for your time.

Ghs
