### ISSUE TITLE
Unhandled exception java error 2014

### ISSUE THREAD

**Issue by haniahollins** [mzmine/mzmine3#1541]
### Basic information

* My operating system and version:
* My MZmine version: 3.9.0
* MZmine 3

### What happened
Hello, I am still new to MZmine. 
My starting point is by importing mzML data files.
when processing a group of runs, the mass detection steps (for MS1 and M2) pass, then the chromatogram building fails by giving the following error message:
"Unhandled exception in task detecting chromatograms FILE NAME:java.lang.NullPointerException (referencePipeline.java:214". 
![mzMine error](https://github.com/mzmine/mzmine3/assets/138684015/72bfae99-8b52-4515-b112-3327bc1f2d0d)
 
I have tried processing one file - the ADAP chromatogram builder step still fails
i have re- generated new mzMLs, checked that there is a TIC (using data visualisation) the file seems ok to me. 

Can you please advise
regards,
Hania

![image](https://github.com/mzmine/mzmine3/assets/138684015/5a94ebc1-8a75-4de4-906f-a8b9d5082add)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by kyrasolaris01** [comment]
Hi Hania,
this can have many reasons. Most of the time it is due to a wrong parameter setup. If you are new to MZmine, I recommend to use the processing wizard: https://mzmine.github.io/mzmine_documentation/wizard.html
You can drag and drop your raw files, select you analysis setup and create a batch file.
Hope that helps.

**Comment by haniahollins** [comment]
Hi,
The processing PC i am using has the following specifications. Once i have an error Like the above. the SW crashes. 
![ProcessPC](https://github.com/mzmine/mzmine3/assets/138684015/026d8b1a-244d-4a12-9cd2-4b07214ee8f4)

**Comment by kyrasolaris01** [comment]
With parameters I dont mean PC configuration, I was referring to parameters you have to set for each module. The wizard will do that for you.

**Comment by haniahollins** [comment]
I know :-) i wasn't sure if the PC is very slow and makes it crash.
So far i run 3 files (average of 1GB per files). it is working. i will increase slowly the number of files. 
in your experience, how many files (GB) can be processed at once?

**Comment by kyrasolaris01** [comment]
Your system looks powerful. You should be able to process hundreds of samples without issues. Is the original problem solved by using the wizard?

**Comment by kyrasolaris01** [comment]
The number of files you can process at the very same time is limited by the number of CPU cores. You can create feature lists for as many files as you like and align them once they are all done. The wizard batch creator does exactly that. Glade your initial problem was solved.

**Comment by haniahollins** [comment]
Thanks for your quick help :-) i appreciate it
