### ISSUE TITLE
we did full scan MS2 but they can not be seen in the mzmine 3

### ISSUE THREAD

**Issue by GhsJahanmir** [mzmine/mzmine3#1555]
### Basic information

*My operating system: Windows 10
*My MZmine version: 3.9.0

Hello all,

We did full MS2 scan for all samples in Agilent LC-MS qqq. We can not see any MS2 scan when converted to mzML (by MSconvert) and imported to MZmine3. After discussing with the Agilent engineer, we are sure that the spectrum, we have is MS2 level. However, due to the software problem, (old and not-updated software), MS1 scans can not be recorded by the software. Therefore, when we import them into MZmine 3, they are detected as MS1.

Considering that we can not upgrade the software, can we proceed with the normal and routine data processing of the current spectrum and obtain the feature table?

Best Regards,
Ghs

**Comment by ansgarkorf** [comment]
Hi,
you can create a feature table with your data. Just make sure to setup the scan selection filter according to your data when doing mass detection and chromatogram building. 
Since mzML is an open, human readable format, you can manually change the MS level of your data.

**Comment by GhsJahanmir** [comment]
Hi @ansgarkorf 

Thanks for your reply.

Thanks for your prompt reply. If I manually change all MS1 scans to MS2 scans, would I still be able to perform chromatogram building? I read in the documentation that chromatogram building is typically done on the MS1 level.

By "by changing  manually" Do you mean either making the changes within MZmine or directly modifying the file's contents in a text format.
My objective is to compare and identify any significant differences between the sample categories. To achieve this, I require a clean feature table


Best Regards,
Ghs

**Comment by ansgarkorf** [comment]
Feature table can also be created on MS2 level, if it makes sense for the specific raw data type. You can select the MS level in the scan selection filter.
And yes, I was referring to modifying the raw file itself, not in MZmine, since you wrote the acquisition software is giving you the wrong MS level.

**Comment by GhsJahanmir** [comment]
> Feature table can also be created on MS2 level, if it makes sense for the specific raw data type. You can select the MS level in the scan selection filter. And yes, I was referring to modifying the raw file itself, not in MZmine, since you wrote the acquisition software is giving you the wrong MS level.



Thanks again,
Agilent mass hunter software is correct in exporting the MS2 level. the issue is that it gives only the final MS2 scan spectra (TIC and its MS2) data and there is not corresponding MS1 recorded. Total ions are fragmented.

so in this case, how can I change the level of data mannualy?

here is photo of setting in the agilent softare.
![20231205_155849](https://github.com/mzmine/mzmine3/assets/85613062/f5d51e71-4d3c-4806-86a2-c5e50c2565ba)
![20231205_113724](https://github.com/mzmine/mzmine3/assets/85613062/d7af63c9-847e-4e31-8bc0-cf2eca164635)
![20231207_161034](https://github.com/mzmine/mzmine3/assets/85613062/98180db1-acc4-445e-b04b-72ad4cbc7dbd)



Best Regards,
Ghs

**Comment by GhsJahanmir** [comment]
> > Feature table can also be created on MS2 level, if it makes sense for the specific raw data type. You can select the MS level in the scan selection filter. And yes, I was referring to modifying the raw file itself, not in MZmine, since you wrote the acquisition software is giving you the wrong MS level.
> 
> Thanks again, Agilent mass hunter software is correct in exporting the MS2 level. the issue is that it gives only the final MS2 scan spectra (TIC and its MS2) data and there is not corresponding MS1 recorded. Total ions are fragmented.
> 
> so in this case, how can I change the level of data mannualy?
> 
> Below are photos of setting and result in the agilent softare. ![20231205_155849](https://private-user-images.githubusercontent.com/85613062/289499334-f5d51e71-4d3c-4806-86a2-c5e50c2565ba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTY4NDgsIm5iZiI6MTcwMjUxNjU0OCwicGF0aCI6Ii84NTYxMzA2Mi8yODk0OTkzMzQtZjVkNTFlNzEtNGQzYy00ODA2LTg2YTItYzVlNTBjMjU2NWJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNmVkMTI0ZDU1NmM4NGU5NzJmODhiNTZjN2JhYTIyZDI0YmRmMzgxZjdlZmYzMGNmMjhhZGIyOWQxZTQwOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X4rrY9HjYQlWGck6vtrCrpmbY6TR8bix_wbLrW1KfoA) ![20231205_113724](https://private-user-images.githubusercontent.com/85613062/289499291-d7af63c9-847e-4e31-8bc0-cf2eca164635.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTY4NDgsIm5iZiI6MTcwMjUxNjU0OCwicGF0aCI6Ii84NTYxMzA2Mi8yODk0OTkyOTEtZDdhZjYzYzktODQ3ZS00ZTMxLThiYzAtY2YyZWNhMTY0NjM1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2E4MWVlYTZjZGRhODgxOGIyZDNlNThiYThlMTFkNjRkYzU5NzEwNzg5NDIzMGIyNmQxOTZiMzlhYTBkZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmwSZw6OBczXQA43k9ojxVn8x5lb0M8PF5CftHs-ftA) ![20231207_161034](https://private-user-images.githubusercontent.com/85613062/289499857-98180db1-acc4-445e-b04b-72ad4cbc7dbd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTY4NDgsIm5iZiI6MTcwMjUxNjU0OCwicGF0aCI6Ii84NTYxMzA2Mi8yODk0OTk4NTctOTgxODBkYjEtYWNjNC00NDVlLWIwNGItNzJhZDRjYmM3ZGJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNWY2ODA1MjU3NjBjZGQyM2E2Nzk5MTU1MDhmZmFjOWJlZDU5NmE3NmQ5Yzg2ZjhiODhmZWI3ZTQ3MDU4NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uR9za8miT74JrKbnNPcXw7wjRoKEE6cEiWD-PTSjH9Q)
> 
> Best Regards, Ghs

@ansgarkorf 
Do you have any idea on these?

Thanks in advance,
Ghs
