### ISSUE TITLE
How create batch to process data from two equipments: HPLC-Orbitrap-MS/MS data and  MALDI-FT-ICR-Imaging MS

### ISSUE THREAD

**Issue by anani-a-missinou** [mzmine/mzmine3#1561]
### Basic information

I want to analyze data from UPLC-Q-exactive-Orbitrap and by imaging MS data with mzmine3. 

Imaging MS data was collected from MALDI 7T FT-ICR mass spectrometer SolariX XR equipped with a Paracell (Bruker DaltoniK GmbH), the cross-sections of 20um, and a spatial resolution of 50um. 

I have for each sample, 3 replicates collected from both analytic methods in positive and negative mode.

* My operating system and version:
Processor : Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz 2.59 Ghz 
Ram: 64.0 GB (63.7 GB usable)
Windows 10 system

* My MZmine version: v3.9.0

Thank you for your help

**Comment by kyrasolaris01** [comment]
Hi,
the QExactive data should be no problem. You can use the wizard as a starting point. What is the data format of the SolariX XR files? Currently we only support Bruker native tdf and tsf but not old baf format. Best option would be imzML format.

**Comment by SteffenHeu** [comment]
In principle you can follow the wizard workflows for 
- imaging data: https://mzmine.github.io/mzmine_documentation/workflows/imagingworkflow/imaging-workflow.html
- LC data: https://mzmine.github.io/mzmine_documentation/workflows/lcmsworkflow/lcms-workflow.html
And then combine the results using the LC-Image Aligner: https://mzmine.github.io/mzmine_documentation/module_docs/align_lc-image/align_lc-image.html

The question is if the FTICR Imaging data can be converted to mzml. I suggest centroiding during the conversion

**Comment by anani-a-missinou** [comment]
dear @kyrasolaris01 , 

Thank you. I already convert Imaging data to *.ibd and *.imzXML.

**Comment by kyrasolaris01** [comment]
i am not aware of the the imzXML format to be honest. How did you convert your data?

**Comment by anani-a-missinou** [comment]
Data was converted flexImaging of Brucker

**Comment by kyrasolaris01** [comment]
Did you have any success using the above linked documentation? Bruker flexImaging should support the export of imzML since 2014:
![image](https://github.com/mzmine/mzmine3/assets/140096361/769ce4f4-a36c-4b75-940f-f95a6e67e44c)

If you have trouble with the converted data, please upload a file we can test ourselves.

**Comment by ansgarkorf** [comment]
Hi,
is this problem solved?

**Comment by anani-a-missinou** [comment]
Dear Developer,

I'm pleased to inform you that I've successfully analyzed both datasets using mzmine3.

The initial results have brought me much satisfaction, and I would like to express my gratitude for your dedicated development efforts. 

![image](https://github.com/mzmine/mzmine3/assets/45430190/77c016de-b064-4b7a-8b12-38cea4982dba)

However, as I delve deeper into the data, I've been trying to understand the reason behind a smaller count of spatially resolved LC-MS features, even with different counts of system-specific features (e.g. twice as many cationic features in LC-MS compared to MALDI-MS).

Our extraction solvent comprises methanol/formic acid, and we implement a gradient of H2O/ACN for the LC-MS system and 3AA and DHB serve as negative and positive mode matrices for the MALDI-MSI system. All of these chemicals represent background ions. I suspect that the current LC-Image-Aligner option may not consider the formation of adducts with sodium or potassium ions, along with matrix-induced cluster formations like [M-(9AA-H2O)-H]-, [M+(DHB-H2O) +H]+, [M +DHB+Na]+ in the MALDI-MSI system. This strongly would decrease the total count of unaligned mz-LC-MS-image and reduce false positives from alignment based only on accurate m/z.

If yes, is it easy to add an option before LC-Image-Aligner that computes co-localization of matrix–features adducts with their parent features, like your current IIMN for LC/GC-MS to detect co-localized subcommunities m/z -images (including these adducts).

Your insights into this matter would be highly appreciated.

Best regards

**Comment by ansgarkorf** [comment]
Very happy to hear you had success analyzing your data with MZmine. 
The LC-Imaging aligner is a very new tool and we are happy about feedback and ideas how to improve it. Modules like co-localization are already in the making for the next release. 
It would be very interesting to learn more about your needs to analyze LC and imaging data. Would you mind contacting me via e-Mail so we can setup a call?
ansgar.korf@mzmine.com

**Comment by SteffenHeu** [comment]
Additional note: it is only checked for exact mass matches, additional adducts are not grouped. Also, only image features that exist in the lc list are aligned. if they were not detected in lc, they wont show up in the aligned list. If you want that, you can first use the join aligner to align the lc feature lists and then use the join aligner on the aligned list and the imaging files with a super high rt tolerance and a low rt weight.
