### ISSUE TITLE
Not a bug just wondering, how many ".mzXML" files can I run on MZmine3 at the same time?

### ISSUE THREAD

**Issue by ZarluisMijangoR** [mzmine/mzmine3#1578]
### Basic information

* My operating system and version: macOS Sonoma 14.1.2
* My MZmine version: 3.9.0

### What happened

Hi there,

I am currently exploring some MS1 and MS2 chemical data and using the Processing wizard with 17 steps. I have successfully run samples before (n=30) but this time I am hoping to run it with 350 samples. I am planning to use .mzXML file types. So I was wondering if this is possible? 

In addition, is there a sample threshold to run MZmine3 without crashing; Is there a particular sample filet type (e.g., mzXML, RAW, etc) that is less heavier to run more samples? Is there a way to run this amount of samples without using a supercomputer? I am hoping to use my MacBook Pro.

Many thanks in advance,
All the best,
Zarluis

**Comment by ansgarkorf** [comment]
Hi,
Happy to hear you are having success with the wizard. Regarding your question, number of samples depends on a lot of factors:
MS instrument (scan speed), method length, sample complexity, profile vs centroid etc...
There is no simple answer to this question, however MZmine is designed to run on consumer laptops, even with hundreds of files. Regarding the file type, if we support the native file type of you instrument you should use it, e.g. Thermo raw.
Please also check the documentation to evaluate your performance options:
- https://mzmine.github.io/mzmine_documentation/performance.html

Once you have developed a batch, you can also opt to run MZmine as command-line tool:
https://mzmine.github.io/mzmine_documentation/commandline_tool.html

**Comment by ZarluisMijangoR** [comment]
Hello @ansgarkorf 

Thank you so much for your reply, and sharing the resources. I am not sure if this means much but my samples were ran using negative mode, centroided, using thermo fisher UHPLC, retention time is usually ranging from 0-20mins. The samples can be quit complex since I am studying leaves of tropical plants. File type-wise, I usually convert my files from ThermoRaw to mzXML files since Raw files can be heavier than mzXML but if using Raw files can help the performance of analysing more samples then I am happy to do the change. 

I am very eager to try to run my 350 samples using the batch mode on my laptop so if there is any suggestion that you could point out to make it possible I would be very grateful. 

Many thanks again,
Best,
Zarluis

**Comment by kyrasolaris01** [comment]
Hi,
if the raw data was recorded in centroid the .raw file should perform best. You could also try to convert to mzML using MSConvert and apply a threshold to filter out noise signals during conversion, reducing the file size further. 
As a starting point for 350 samples, try to use higher thresholds and go lower from there. Also, you can crop the retention time, removing e.g. dead volume peak and equilibration steps of your method.
