### ISSUE TITLE
Project Metadata Import

### ISSUE THREAD

**Issue by barnesalan1** [mzmine/mzmine3#1593]
### Basic information

Windows 11 Pro
MZmine 3.9.0

### What happened

I wanted to import data files (mzML) and also import project metadata (tsv/csv) into MZmine. Unfortunately I cannot get the project metadata to import. I have even entered Sample Metadata  in MZmine and exported, then used this to import and it still fails to import. I don't know what to try next.

**Comment by ansgarkorf** [comment]
Hi,
thanks for reporting the bug, we will look into this. Can you share the log file when so we can check what fails when you try to import the meta data?

**Comment by SteffenHeu** [comment]
HI, i know it's a late reply, but the issue will be fixed in the next release. Basically the export is doing wierd stuff.

**Comment by barnesalan1** [comment]
Thanks!
