### ISSUE TITLE
MS2 scans as detected to be MS1 in MZmine3

### ISSUE THREAD

**Issue by GhsJahanmir** [mzmine/mzmine3#1596]
### Basic information

My operating system: windows 10
My MZmine version: [3.9.0]

Dear developer,

We did full MS2 scan with agilent triplequad. After converting centroided .d file with MSconvert and importing them into MZmine 3, all scans are labeled as MS1 scan. we did MS2 scan for all the m/z between 100 to 1000.

Our aim is not annotation.. Can I still proceed with the normal processing in MZmine? 

screen shot of scan list:
![image](https://github.com/mzmine/mzmine3/assets/85613062/2edeb50a-8a0c-43f6-8995-8f5339efa156)

I insert the link for a batch file and one of our data for your reference.

[[Batch [file]]](https://drive.google.com/file/d/1UzwBz_eyCXqXHbPLkW1Jt8jbC2r_veAk/view?usp=sharing)
[data .d file](https://drive.google.com/file/d/1t-UiEpirRKBmo3NQWz67lE7mK7Ou4oaS/view?usp=sharing)

Best Regards and thanks in advance,
Ghs

**Comment by ansgarkorf** [comment]
Hi,
I can confirm that MZmine reads the MS level correctly from the mzML files. If you have a conversion problem please contact the Agilent support or the MSConvert team. 
However, you can process your data. I recommend to create a batch with the wizard. Make sure to select the "Low res." option.
kind regards,
Ansgar
 
![Screenshot 2024-01-10 at 10 21 08](https://github.com/mzmine/mzmine3/assets/27132602/fc949a43-1122-4523-ae10-7a17baf1ca54)
