### ISSUE TITLE
Error uploading untargeted data

### ISSUE THREAD

**Issue by sheim145** [mzmine/mzmine3#1597]
### Basic information

* Windows 11 Pro
* My MZmine version: mzmine 3
<img width="550" alt="mzmine_error2" src="https://github.com/mzmine/mzmine3/assets/92920993/22625313-426a-4e6e-a8d8-6b4cae4834cd">
<img width="557" alt="Error_mzmine1" src="https://github.com/mzmine/mzmine3/assets/92920993/ea6374de-81c7-4f87-bc4a-712aade8c09d">

### What happened
When uploading my batch of untargeted data, the attached errors occur on most of my samples at loading task 8.

I am processing mzML files acquired on an Agilent LC-ESI-QTOF. This is untargeted data in DIA mode except for my QC sample that are acquired by DDA to have MS/MS data by PC-driven exclusion of top n peaks detected.
The parameters I set in the processing wizard pannel were UHPLC, QTOF, DIA and mainly set the RT range (0.8-13 mins), MS1 threshold 10'000, MS2 threshold 3000, positive ionization mode, centroided data. The rest of the parameters were left as set by mzmine for the moment.
Here are the mzML files
https://drive.google.com/drive/folders/11i1WDxrA-k0QLrKhMNCYSgbI5FDWbRbP?usp=sharing

**Comment by ansgarkorf** [comment]
Hi,
looks like your raw data files dont have any MS2 scans. Please check your conversion settings, seems like you filtered away.

<img width="1111" alt="Screenshot 2024-01-10 at 11 49 44" src="https://github.com/mzmine/mzmine3/assets/27132602/2f8e5c65-9f5c-40d2-bf42-dfb96b193985">

**Comment by sheim145** [comment]
Thank you for you input! I will check and get back to you if I have any further issues.

Have a great day

Sara Heim
________________________________

**Comment by ansgarkorf** [comment]
Your welcome!

**Comment by sheim145** [comment]
Hello,

So just getting back to you because indeed the samples are all aquired in Full MS scan and only QC samples have MS/MS data in them. (I have now put them in the same google drive link https://drive.google.com/file/d/1WZLhqOIStYe0N6qgtXLVFLaloIo6_6Nj/view?usp=drive_link named QCcondclarkii1,2,3).
Here is also a shot of how I converted my .d files to mzML
<img width="650" alt="MSconvert_settings" src="https://github.com/mzmine/mzmine3/assets/92920993/da313265-c27e-4f69-82b4-79da9b88032e">
When I upload the QCs I also get this error:
<img width="583" alt="mzmine_error3" src="https://github.com/mzmine/mzmine3/assets/92920993/b070b1b5-1199-4ac8-97fc-2e3f698e9404">
I have all the data processed with MS-dial and I wanted to compare the processing with mzmine3. 
Thanks for your help

**Comment by sheim145** [comment]
Thanks for getting back to me.

My question now is: Is it possible for me to process my whole batch knowing that the QCconds need to have the DDA setting and have MS2 data, whereas the samples need to have the DIA and have only MS1 data? If I just want a feature list of MS1 hits at first?

Sorry for all these questions.. Really appreciate your help!

Have a great day

Sara Heim
________________________________

**Comment by ansgarkorf** [comment]
Yes, but it requires some tweaking of your batch file. I suggest the following:
- drag and drop all raw data files in the wizard and create a batch using UHPLC QTOF DDA
- Remove all steps that your batch only looks like this (Remove the second Mass Detection step, the first one is for MS1)
<img width="1488" alt="Screenshot 2024-01-10 at 16 25 33" src="https://github.com/mzmine/mzmine3/assets/27132602/4e90bf28-91ac-433f-b59f-55be6573597d">
- Then open click on the Local minimum feature resolver and deactivate the MS/MS scan pairing option
<img width="1488" alt="Screenshot 2024-01-10 at 16 27 19" src="https://github.com/mzmine/mzmine3/assets/27132602/b24b920e-b643-4845-9966-89a86b40f942">

This has giving me MS1 only results for the files you provided:
<img width="1488" alt="image" src="https://github.com/mzmine/mzmine3/assets/27132602/28a1d5c8-6377-4ceb-9f70-7c087a27b8a9">

Good luck!

**Comment by sheim145** [comment]
Thank you very much!

I'll try this out 🙂

Cheers

Sara
________________________________
