### ISSUE TITLE
exporting spectral match results to excel

### ISSUE THREAD

**Issue by luke-ferro28** [mzmine/mzmine3#1602]
mzmine 3.9.0
macOS Sonoma 14.1.2 (23B92)

When I view 'Spectral DB search results' I see the results I want. For publication, I need to replot the mirror plot, so I'm trying to export the mirror plot data. When I export data to excel, the excel table is completely empty. Any suggestions? 

<img width="844" alt="Screenshot 2024-01-11 at 2 18 13 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/59e0
<img width="859" alt="Screenshot 2024-01-11 
<img width="1032" alt="Screenshot 2024-01-11 at 2 14 34 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/7a561d2d-3a2b-4b38-ab89-cda931ca496a">
at 2 18 42 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/d4936d18-9d80-4a15-ad1a-0a6b3a1c956c">
c7ed-f0a5-485f-83bd-aca3911f1c32">

**Comment by luke-ferro28** [comment]
<img width="844" alt="Screenshot 2024-01-11 at 2 18 13 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/d4687d20-40eb-430b-9d31-4c813dc06100">

**Comment by luke-ferro28** [comment]
<img width="859" alt="Screenshot 2024-01-11 at 2 18 42 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/14e7acea-2b9a-4b88-8b31-2e66dcb395d3">

**Comment by robinschmid** [comment]
I would export the graphics to PDF and then open in illustrator. 
You can also export all matches as graphics in one go using an export module.

**Comment by luke-ferro28** [comment]
Thanks for your reply! Yes, that does work as a backup. I did try to replicate everything on a windows machine and get the same results. Just a blank excel file when I export as excel file.

I assume the export normally works? Should I perhaps try an earlier version of mzmine?

For some reason when I import the PDF in illustrator, information is lost so I have to use EPS which is much less easy to work with

It would be a great feature to be able to export the top spectral hit data for every metabolite.

<img width="1214" alt="Screenshot 2024-01-12 at 2 21 48 PM" src="https://github.com/mzmine/mzmine3/assets/133689959/2c1724be-9d61-4d2a-ad83-d60ea4443fb8">

**Comment by SteffenHeu** [comment]
> It would be a great feature to be able to export the top spectral hit data for every metabolite.

You can use the "Feature list methods -> Feature list export -> Graphics -> Annotations export" for that.

![grafik](https://github.com/mzmine/mzmine3/assets/37407705/81cfe8cd-ead5-4c3d-9da6-6cb8b58daa46)
