### ISSUE TITLE
Mzxml file upload error 

### ISSUE THREAD

**Issue by Kajalg9** [mzmine/mzmine3#1621]
### Basic information

* My operating system and version: macOS 14.0
* My MZmine version: mzmine 3

### What happened

* I uploaded mzxml files provided by the Mass spectrometry facility. However, I am getting an error " Scans were detected as centroid but contain zero intensity values." I have used mzmine3 for my other files and it works perfectly fine. These files in particular are giving me issues with uploading.  

 Attached is an image of the error.
![image](https://github.com/mzmine/mzmine3/assets/157322757/5494fdfc-1c5d-4f80-9f89-2cb1de1f383e)

Below is link for the mzmine standalone project
https://drive.google.com/file/d/1beqREz8P_Opvz55tAFpLroQ-uwEd15Wa/view?usp=sharing

Thanks

**Comment by SteffenHeu** [comment]
Hi, this as a frequently asked question. Something may be wrong with the conversion, but that's not an issue with mzmine. You can ask the MS facility to reconvert the files with the procedure provided in the tooltip.
