### ISSUE TITLE
Failed MS data import: "cannot run program, "wine":error=2"

### ISSUE THREAD

**Issue by gestevam** [mzmine/mzmine3#1629]
### Basic information

* My operating system and version: mac os ventura 13.5.2
* My MZmine version: 3.9.0

### What happened

When trying to import my data I keep getting a java error. I have tried to import the data multiple ways at this point, with the batch wizard, with the MS data import function, and by simply dragging and dropping each file. 

I'm working with Waters .raw files, and these files have been successfully opened on MZmine 3.6 on the windows computer the data was collected on. However, I want to be able to analyze the data on my mac. Trying to import with "Waters RAW" does not work either.

Here is a screen shot of the error: 
<img width="625" alt="Screenshot 2024-01-27 at 6 35 12 PM" src="https://github.com/mzmine/mzmine3/assets/52772182/29e5823f-beb4-4d03-8595-34a1378d69b1">

here's a project file with a sample .raw folder I'm working with: https://www.dropbox.com/scl/fo/j6r06pqihvlrr5x55obkn/h?rlkey=bf4gnn2k5b2qyhu3f3yul5wri&dl=0

**Comment by SteffenHeu** [comment]
Hi, the raw waters import only works on windows (sometimes). 
We and waters suggest to do the following: https://mzmine.github.io/mzmine_documentation/data_conversion.html#waters

**Comment by gestevam** [comment]
Got proteowizard to work and my files loaded!

**Comment by SteffenHeu** [comment]
Ok, that's great to hear. From what i know Waters does not guarantee that the MSConvert output is 100% what Waters wants the output to be.
