### ISSUE TITLE
MZmine not opening UTF-8 encoded mzXML files

### ISSUE THREAD

**Issue by crdzl** [mzmine/mzmine3#1632]
### Basic information

* Windows 10 v. 10.0.19045
* MZmine version 3.9.0 (but also happening in v 2.40.1 ) 

### What happened

Bruker updated the software in the ImpactII qTOF last week to Compass DataAnalysis 5.0, and since then, MZmine cannot open mzXML files that were converted using the automated script. It says "Corrupt mzXML file". 
I thought it was a problem of the file but they open perfectly fine in R (using mzR library) and in OpenChrom. I checked the files and the only difference between old and new mzXML files is that the old ones are encoded using ISO-8859-1 and the new ones are encoded in UTF-8. 
I send attached a blank run (zipped), and screenshots, log, etc. 

Also, running this in R plots the BPI chromatogram:

library(mzR)
rawFile<-openMSfile( "D:\\PATH\\TO\\FOLDER\\blnk_BA2_1_20718.mzXML");
auxTable<-header(rawFile,1:length(rawFile));
plot(auxTable$retentionTime[auxTable$msLevel==1],auxTable$basePeakIntensity[auxTable$msLevel==1],type="l")

[blnk_BA2_1_20718.zip](https://github.com/mzmine/mzmine3/files/14110015/blnk_BA2_1_20718.zip)

![ERROR_mzmine](https://github.com/mzmine/mzmine3/assets/22137456/68090859-8900-46a9-9b81-0ee9835600bf)
[mzmine_0_0_ERROR.log](https://github.com/mzmine/mzmine3/files/14109877/mzmine_0_0_ERROR.log)
![worksInR](https://github.com/mzmine/mzmine3/assets/22137456/4f2f613e-5ff5-4b54-bbe1-210ae9fea9fc)

**Comment by SteffenHeu** [comment]
Hi Carlos,

we checked the file and it does not seem to be an MZmine issue. yes it does not open, but we also cannot open it in MSconvert to make a mzml from it.

Failed - System.Exception: [SpectrumList_mzXML::HandlerPeaks] Invalid peak count.
   bei pwiz.CLI.msdata.MSDataFile.write(MSData msd, String filename, WriteConfig config, IterationListenerRegistry iterationListenerRegistry)
   bei MSConvertGUI.MainLogic.processFile(String filename, Config config, ReaderList readers, Map`2 usedOutputFilenames)
   bei MSConvertGUI.MainLogic.Go(Config config, Map`2 usedOutputFilenames)

Please try converting the raw data to mzml or contact Bruker.

**Comment by crdzl** [comment]
Hi Steffen,
I contacted Bruker and told me to open a bug report here, hehe. I will contact them again. In the mean time I will switch to mzML. 
Thanks!

Carlos

**Comment by SteffenHeu** [comment]
Hi Carlos, 

did you hear anything from Bruker?

**Comment by crdzl** [comment]
Hi Steffen!

They recommended converting to mzML instead, and those files could be open in MZmine. I'm no longer in that lab, but the pipeline was changed to automatically convert to mzML after each run and haven't heard of any issues. I will send them an e-mail to confirm, but I think the pipeline is working (no news is good news.) Thanks for following up!

All the best,

Carlos
