### ISSUE TITLE
PRM acquisition mode 

### ISSUE THREAD

**Issue by Pamou14160** [mzmine/mzmine3#1636]
Good afternoon everyone,
Not sure if I am at the good place to ask this question.
I have lc data that were acquired on orbitrape in prm mode. 
I canot find anything on this mode. 
Thanks!

**Comment by Pamou14160** [comment]
Please find some details about the PRM mode (for targeted analysis) on the Qexactive (Thermo). Here the link if you can't access the shared pdf : https://assets.thermofisher.com/TFS-Assets/CMD/Reference-Materials/wp-65147-ms-q-exactive-orbitrap-scan-modes-wp65147-en.pdf

I was looking to have access to the data of my targeted lists. When I import a .raw in full ms msd2 it opens on the usual page but when  do it with my .raw in PRM the page is blank. Like this mode is not taken in account. But if I am correct DIA is.

Thanks.



Envoyé à partir de Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Steffen Heuckeroth ***@***.***>
Envoyé : Wednesday, February 7, 2024 4:03:22 AM
À : mzmine/mzmine3 ***@***.***>
Cc : Nicolle, Pamela ***@***.***>; Author ***@***.***>
Objet : Re: [mzmine/mzmine3] PRM acquisition mode (Issue #1636)

Vous ne recevez pas souvent de courriers de la part de ***@***.*** Découvrez pourquoi cela est important<https://aka.ms/LearnAboutSenderIdentification>
Attention
L’émetteur de ce courriel est externe à l’Université du Québec en Outaouais.


Hi Pamou,
we'll need a bit more information than that.

what do you want to do with the data?
I don't know how the prm mode works on the orbitrap. What is actually acquired?

**Comment by SteffenHeu** [comment]
Hi,

if i read it correctly the prm mode does not inlcule MS1 scans? 
Then i think you can use one of the the MSn feature detection modules. regular processing is not possible then.
