### ISSUE TITLE
ThermoRawFileParser does not work WIN10

### ISSUE THREAD

**Issue by ErikN31** [mzmine/mzmine3#1638]
### Basic information

* My operating system and version: WIN10 22H2
* My MZmine version: 3.9.5

### What happened
Cannot import Thermo .raw files
Windows error message "ThermoRawFileParser does not work anymore", followed by Java error "java.lang.Exception: no scans found"
![JavaErrorThermoRawFile](https://github.com/mzmine/mzmine3/assets/159270360/e436a76e-9838-4fcc-b537-039be355eb15)
![ThermoRawFileParser](https://github.com/mzmine/mzmine3/assets/159270360/5dfdd8b2-2870-44c9-b92b-3724e8369968)

Thänks for this beautiful software, please help me :)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by SteffenHeu** [comment]
search for the "mzmine_thermo_raw_parser" folder in the mzmine temp folder and the system temp folder and delete it.
