### ISSUE TITLE
Test Failure  Compilation Issue on macOS with Apple M1 Chip

### ISSUE THREAD

**Issue by Aditya3425-Fst** [mzmine/mzmine3#1639]
Hi,

Here are the system details:

Chip: Apple M1
RAM: 8GB
macOS: 14.2.1 (23C71) sonomo
I'm attempting to compile this repository using the following command:

./gradlew

However, two test cases are failing as indicated below:

ThermoRawImportTest > Test data import of mzML and mzXML without advanced parameters FAILED
Error: org.opentest4j.AssertionFailedError at AssertionFailureBuilder.java:151

ThermoRawImportTest > Test data advanced import of mzML and mzXML with advanced parameters like mass detection FAILED
Error: org.opentest4j.AssertionFailedError at AssertionFailureBuilder.java:151

I've tried using JDK 21, but the issue persists. Interestingly, when I switch to a Ubuntu-based system with JDK 19, it works fine. I'm currently investigating why it's failing on macOS. If I find a solution, I'll update it here. Otherwise, if anyone else has encountered the same issue, please let me know.

**Comment by robinschmid** [comment]
It should work. Maybe update your branch to the latest version of mzmine. Our github actions also run on macOS. 
You should try latest branch + JDK 21.
