### ISSUE TITLE
CHROMATOGRAM RESOLVER DETECTION/PREVIEW NOT DISPLAYING

### ISSUE THREAD

**Issue by DarkWoof** [mzmine/mzmine3#1641]
### Basic information

* My operating system: Windows 11
* My MZmine version: 3.9

### What happened

Hello MzMine Team,

i have a strange issue where the local minimum chromatogram resolver is not correctly identifying features and displaying in the preview window.

i have MzMine on two computers, it displays correctly on one but not the other. I have kept the settings for mass detection and, chromatography builder, and resolver across both systems. 

I’m not sure if I am missing something, but it’s strange the my PC cannot display properly while my laptop can. 

![B106D519-7275-4CBE-B278-052CB55D9337](https://github.com/mzmine/mzmine3/assets/159969662/2ab429f3-66d8-4683-862f-bb06416b91bb)

![07F99168-3FD2-4B6B-AAD8-55B43B740B03](https://github.com/mzmine/mzmine3/assets/159969662/17290c1e-ff46-4889-9201-8980377f96ca)

 I’ve tried reinstalling on my PC, but I don’t get any change. I can work on my MS analysis on my laptop and transfer it over, but it would be nice to get it working on my PC also.

**Comment by ansgarkorf** [comment]
Hi,
looks like your settings are not the same. In the second screenshot the peak duration starts at 1 min while on the first it starts at 0 min. Set it to 0 in the second example and it should look fine.
kind regards,
Ansgar

**Comment by DarkWoof** [comment]
Hi Ansgar,

Yes, I had completely overlooked that setting, and changing it to 0 made it display. Thank you so much for your prompt response!
