### ISSUE TITLE
Raw file is not opening

### ISSUE THREAD

**Issue by hpblearn** [mzmine/mzmine3#1654]
### Basic information

* My operating system:
* My MZmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
Hi, please open a new issue and follow the template.

**Comment by hpblearn** [comment]
May I please know the process or link to do so.

The issue is also very basic.. I am not able to work on the imported data.

Thanks & Regards,
Hima

**Comment by hpblearn** [comment]
May I know how to resolve this
[Mzmine_issue1.docx](https://github.com/mzmine/mzmine3/files/14337621/Mzmine_issue1.docx)
