### ISSUE TITLE
Unable to import mzml files

### ISSUE THREAD

**Issue by Clerancecsy** [mzmine/mzmine3#1665]
### Basic information

* My operating system and version: Windows 11, 23H2
* My MZmine version: 3.9.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* MzML files were unable to upload due to illegal base 64 character 0x3c
* I am wondering if it's possible to encrypt the source file to prevent this kind of errors. In my case, the raw files were provided by the vendor ( please have a look at the attached screenshots and my mzml files' folder is provided here: https://drive.google.com/drive/folders/1OhPZ1cWdiIw335vTznf-5G-LAmkTZoR-?usp=drive_link). 
* Is there anyway to encrypt these errors on my end? Thank you so much in advance. 
![image](https://github.com/mzmine/mzmine3/assets/161328593/b2a3f41a-3095-424e-9167-6795b8d978c8)
<img width="906" alt="image" src="https://github.com/mzmine/mzmine3/assets/161328593/f4374389-b954-410a-aa27-a0e10c78af8e">

**Comment by SteffenHeu** [comment]
Please see the FAQ under the "mzml import" point. This will be fixed in the next release. I'm guessing the long hyphen is the issue (9912 **--** Pos)

**Comment by Clerancecsy** [comment]
Thank you! I have changed the file name before using MSConvert and it is working fine now.
