### ISSUE TITLE
Thermo Raw Import

### ISSUE THREAD

**Issue by EdwardRudt** [mzmine/mzmine3#1672]
### Basic information

* My operating system and version: Win 10
* My MZmine version: 3.9.0

### Problem with Themo Raw Data Import
![MZmine](https://github.com/mzmine/mzmine3/assets/123182909/e0357fd4-faa1-4010-81f3-18a85a8e861e)

**Comment by zh1yan** [comment]
Same issue on Mac
<img width="464" alt="Screen Shot 2024-02-29 at 17 20 22" src="https://github.com/mzmine/mzmine3/assets/54960859/19c8729a-2160-4742-9276-2bd092a6fe4d">

**Comment by SteffenHeu** [comment]
search for the "mzmine_thermo_raw_parser" folder in the mzmine temp folder and the system temp folder and delete it.
