### ISSUE TITLE
DataBase Search

### ISSUE THREAD

**Issue by Pamou14160** [mzmine/mzmine3#1682]
### Basic information

* My operating system and version: windows 11
* My MZmine version: 3.9.0

### What happened

* I have extracted the table from an article to create a custom database search. I am trying to use it and it failed!
* Please include all parameter values for the MZmine modules you used. 
![image](https://github.com/mzmine/mzmine3/assets/159185652/64d0fcfe-e3f5-4c8f-816d-dfb38c07f804)
* Please upload screenshots of any errors **and** your log/mzmine.log file.
![image](https://github.com/mzmine/mzmine3/assets/159185652/5beee196-6770-44c8-80f4-d4be2d708cb8)
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
[ForMZmine_Escobar2019.csv](https://github.com/mzmine/mzmine3/files/14453291/ForMZmine_Escobar2019.csv)

**Comment by SteffenHeu** [comment]
Hi pamou,

Your separator is ";" and not ",".

```
Name;Formula;rt;mz;Adduct
Monogalloyl-glucose(1);C13 H15 O10;3.6;331.0668;M-H
Gallicacid*;C7 H5 O5;4.3;169.0141;M-H
Monogalloyl-glucose(2);C13 H15 O10;5.38;331.0664;M-H
```
