### ISSUE TITLE
Question about the exported molecular formulas

### ISSUE THREAD

**Issue by kkcau9118** [mzmine/mzmine3#17]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 3

### What happened

Dear MZmine developers,

This is Kai, I'm now using MZmine 3 to analyze the raw data file from Orbitrap MS (Q-Exactive, Thermo Scientific), especially for the formula prediction. I would like to do one modification about the exported molecular formulas. As far as I know, in the default setting, the exported formulas are the formulas with the lowest mass tolerance between the detected m/z and the theoretic m/z. So, is it possible to export formulas with the highest isotope pattern score instead of the lowest mass tolerance and how to do it? Thanks a lot!

**Comment by tomas-pluskal** [comment]
Hi Kai,

I think you are mixing two different things - the prediction of chemical formulas, and the data export. Those are done by two different MZmine modules. Which module are you thinking to modify?

**Comment by kkcau9118** [comment]
> Hi Kai,
> 
> I think you are mixing two different things - the prediction of chemical formulas, and the data export. Those are done by two different MZmine modules. Which module are you thinking to modify?

Hi Tomas,

Thanks! For example (please see the screenshot below), There are three predicted formulas (C10H26N6O2S, C18H22N4 and C17H26O4) for the m/z 293.1768. And when I do the export, only the first one (C10H26N6O2S), which has the lowest mass tolerance but does not have the highest isotope pattern score, can be exported. However, I prefer to export the formula with the highest isotope pattern score. So, I think I need to modify the module of data export?
![image](https://user-images.githubusercontent.com/57988218/70447592-405a3f80-1a9f-11ea-8c18-ab8ff1805b23.png)

**Comment by tomas-pluskal** [comment]
The order of the formulas in this table can be changed manually and also the user can add or edit the identities using other MZmine modules or manually. So I think it makes sense to export the top selected identity and the export module should not change the order.

Instead, you should modify the formula prediction module to add the formulas in the proper order. Perhaps you should add a new parameter to the module where the user can select whether the formulas should be sorted by mass error or by isotope score.

**Comment by kkcau9118** [comment]
> The order of the formulas in this table can be changed manually and also the user can add or edit the identities using other MZmine modules or manually. So I think it makes sense to export the top selected identity and the export module should not change the order.
> 
> Instead, you should modify the formula prediction module to add the formulas in the proper order. Perhaps you should add a new parameter to the module where the user can select whether the formulas should be sorted by mass error or by isotope score.

Hi Tomas,
Yeah, the order of the formulas in the table can be changed manually. However, it will take a lot of time if I want to export hundreds of formulas.  So, I will try to add a new parameter to the 'FormulaPredictionPeakListTask.java' module to make it possible that the user can select whether the formulas should be sorted by mass error or isotope pattern score.  However, I only have a very few experience on the Java programming... Is there any example that I can follow to add the new parameter to the module? Thanks!

**Comment by tomas-pluskal** [comment]
The whole project is your example :) Take a look at how the module defines its parameters (the FormulaPredictionPeakListParameters class) and start from there.

**Comment by kkcau9118** [comment]
> The whole project is your example :) Take a look at how the module defines its parameters (the FormulaPredictionPeakListParameters class) and start from there.

OK, got it :)

**Comment by robinschmid** [comment]
Let me look for it. I have already implemented something like this in another branch. 
In this version you can set weighting factors for mass difference, isotope score, and MS/MS score.

**Comment by kkcau9118** [comment]
> Let me look for it. I have already implemented something like this in another branch.
> In this version you can set weighting factors for mass difference, isotope score, and MS/MS score.

Great, look forward to it:)

**Comment by robinschmid** [comment]
I have done a quick copy of some of my funtions into the latest branch.
see PR #22 
You can adjust the sorting score and anything else
