### ISSUE TITLE
Analysis of Direct Infusion Lipidomics Data

### ISSUE THREAD

**Issue by adam-grove** [mzmine/mzmine3#1731]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 3.9.0

### What happened

I am trying to analyse Direct infusion lipidomics data using MZmine 3. I have found instructions of how to do this in MZmine 2 but I'm not sure if this can be done in MZmine 3. Can you help me out please?

**Comment by ansgarkorf** [comment]
Hi Adam,
we are looking for feedback on our direct infusion workflow for lipid analysis. If you are interested we can jump on a quick call and process your data. You can send me an email to: ansgar.korf@mzio.io
kind regards,
Ansgar
