### ISSUE TITLE
Minimum performance requires for computer using mzmine3

### ISSUE THREAD

**Issue by gtouchais** [mzmine/mzmine3#1750]
Hello, 

I would like to know the computer performance required to use MZmine 3?
(Processor, RAM, GHz, )

Sincerely,
Gaël

**Comment by SteffenHeu** [comment]
Minimum requirements depend on the size of the study you want to analyse. We recommend a SSD for temporary storage and 4 or more cores. Ram depends on the number of samples. For small batches 16 gb should be fine for regular mzml files.

**Comment by SteffenHeu** [comment]
I recommend to start with the processing wizard. It could be that the drive where mzmine puts the temporary files on is full. you can change the temp folder in the preferences. 

Without looking at the files and your settings i cant say anything particular

**Comment by silvinaperin** [comment]
Dear Steffen, 

Thanks! it worked. I changed the temporary folder and now did not crush. 

Best, 

Silvina

**Comment by robinschmid** [comment]
Glad it was resolved
