### ISSUE TITLE
Uninstall from my computer?

### ISSUE THREAD

**Issue by marwa38** [mzmine/mzmine3#1792]
### Basic information

* My operating system and version: Windows 10 Enterprise
* My mzmine version: 4.0.3

### What happened

I think this is abug I didnt find any mzmine in my uninstall under control panel so I can't remove mzmine from my computer. Any help? To use another version and to use another computer instead.

**Comment by SteffenHeu** [comment]
Did you download the zip archive/portable version? Then you don't need to uninstall anything and you can just delete the folder you unzipped mzmine to.

**Comment by marwa38** [comment]
That is correct, thank you @SteffenHeu . For an older version 2.7.3 is that is the same thing? it is .zip for windows not the portable this time.

**Comment by marwa38** [comment]
Many thanks

**Comment by marwa38** [comment]
does that apply to .msi one too? just delete?

**Comment by robinschmid** [comment]
If you installed the .msi you can just go to the Apps system settings and remove mzmine
![image](https://github.com/mzmine/mzmine3/assets/10366914/734b6072-b092-4138-8bd9-1ee7a2d9157b)
