### ISSUE TITLE
Metadata Import Error

### ISSUE THREAD

**Issue by Shovann** [mzmine/mzmine3#1797]
### Basic information

* My operating system and version: Windows 10 Enterprise, version 10.0.19045 Build 19045
* My mzmine version: 4.0.3

### What happened

When importing metadata of my dataset, the import stops with the error message:
io.github.mzmine.taskcontrol.impl.WrappedTask run Error of task Importing metadata parameters from the selected file(s): Couldn't import metadata from D:\converts\desm_metadata.csv
The same happens if metadata read-in is part of the batch workflow. Processing works without any issues if no metadata is read in.

You asked me at the workshop to upload some data files and the metadata file I used. They are in a zip file here: https://drive.google.com/file/d/1HvYt0eXvdBHkVDdryh1GM4T-J43IhVMr/view?usp=sharing

**Comment by SteffenHeu** [comment]
Solved at the workshop, probably caused by manual generation of the metadata file.

**Comment by sohafarah** [comment]
Hello, please can you tell me how did you resolve this problem?
