### ISSUE TITLE
User login requested during some tasks (off-line use)

### ISSUE THREAD

**Issue by gdelap** [mzmine/mzmine3#1799]
### Basic information

* My operating system and version: Windows 10 22H2 (off-line computer)
* My mzmine version: 4.0.3

### What happened

When trying the new MZmine 4.0.3 version, the "User" window opens when performing some tasks (happened with the GC-MS (EI) spectral deconvolution and the spectral database match) and the task does not run. It seems a bit random as I succeded to run the GC-MS (EI) deconvolution yesterday.

It goes with the following error:
`Unhandled exception java.lang.NullPointerException: Cannot invoke "org.keycloak.common.util.KeycloakUriBuilder.clone()* because the return value of "org.Keycloak.adapter.KeycloakDeployment.getAuthUrl()* is null while processing task User login`

Thanks for your help,
Best regards
Grégoire

**Comment by gdelap** [comment]
Update:

It was a licence problem. I followed the procedure for off-line use and now it works.
Maybe there could be a document that summarize the main evolutions between MZmine 3 and 4? (or maybe it already exists and I did not find it :) )
I close the issue.
Best
Grégoire

**Comment by robinschmid** [comment]
We are still trying to figure out why this happens. Most likely this has something to do with your firewall blocking it.
