### ISSUE TITLE
Feature table crashes java fx application thread

### ISSUE THREAD

**Issue by SteffenHeu** [mzmine/mzmine3#192]
This exception:

https://pastebin.com/eNpitPeu

Happened at some point when scrolling through the feature table. 
I have investigated it a bit and i think i narrowed it down to the bufferedColChart in the ModularFeature and ModularFeatureListRow. 
I can only assume how it would cause the issue. However, i came up with these two solutions.

1. removing the bufferedColChart,xecute as usual https://github.com/SteffenHeu/mzmine3/tree/nobufferedcharts
2. removing the bufferedColChart, use Platform.runLater to execute the graphical node task. See branch https://github.com/SteffenHeu/mzmine3/tree/checkfx

Both worked fine for me while testing it, altough i cannot guarantee it was the issue ultimately. A third solution would be to directly create the chart pane without any runnable in the getCellNode method of the data type.

Option 1 loads charts the slowest but causes the least lag in the feature table. Option 2 loads the charts faster but caused a little lag in the table and option 3 loaded the charts the fastest, but caused a little more lag again.

What do you guys think? Any ideas why storing the node would cause these issues? My guess would be some kind of concurrent modification, but it's hard to guess how that would happen. Note: i added `assert Platform.isFxApplicationThread()` to all the charts at some point and did not get any errors, so yeah... One thing i noticed was, that if the chart was buffered, it would be returned as the node directly, but if it was created, it would be wrapped in an additional StackPane.

**Comment by robinschmid** [comment]
Hm. Good work. 
Thats weird. Lets define what we need to be on the same page:
1. The charts need to be created on a separate thread to not freeze JavaFX
2. We need to buffer (store created charts) as the getCellNode method is called at least every time we scroll over the cell
3. The list/map needs to be thread safe
4. do everything on the JavaFX thread if possible

**Comment by SteffenHeu** [comment]
The gui wasn't lagging badly in 2 and 3, at least for me. Compared to the earliest implementation which used the java fx charts, we don't have to load/calculate the chart data, since the underlying feature data is plotted as-is. However, we might run into problems with aligned feature list when there is more data in the charts.

(note i edited the initial post, i mixed up 1 and 2, it's correct now)

**Comment by robinschmid** [comment]
Inactivity. Seems fixed.
