### ISSUE TITLE
Add Utility.copyRow method to harmonize all modules

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#2]
Add a utility method to copy a row. 
All modules implement such a method - this should be harmonized.

**Comment by SteffenHeu** [comment]
I put something like that into the utility class during my latest commit. Should probably be renamed to copyFeatureRow to stay consistent, though.
https://github.com/mzmine/mzmine3/blob/b9af7009a98cde31db91faeffafb81c8f8fdf56f/src/main/java/net/sf/mzmine/util/PeakUtils.java#L298-L326

Same for the applied methods to a feature/peak list:
https://github.com/mzmine/mzmine3/blob/b9af7009a98cde31db91faeffafb81c8f8fdf56f/src/main/java/net/sf/mzmine/util/PeakListUtils.java#L12-L17

**Comment by SteffenHeu** [comment]
To add to my previes comment:
Maybe create a harmonized addFeatureListToProject method, that creates the applied method by itself.
