### ISSUE TITLE
One MemoryMapStorage per module call

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#206]
We still need to create a way to safely control the creation of MemoryMapStorage
The idea is to bundle all RawDataFiles, MassLists, and FeatureLists that were created by the same module call to limit the number of files.

In Windows 10 I had the issue that we could only create 8 temp files with 1GB each on ~8 GB free disk space.

### TODO
- Maybe keep track of all MemoryMapStorage instances in a List / Map to delete them if not needed anymore
- Have a way to create a single memory map for a module call

**Comment by SteffenHeu** [comment]
#209
