### ISSUE TITLE
a problem after merging a new module for sorting predicted formulas

### ISSUE THREAD

**Issue by kkcau9118** [mzmine/mzmine3#26]
### Basic information

* My operating system: Windows10
* My MZmine version: MZmine3

### What happened

Dear MZmine developer,

This is Kai, again... First, I would like to really thank the MZmine developers for helping me solve several problems. Now I have a new problem. Today I merged a new module for sorting predicted formulas (which was contributed by Robin) in my MZmine3 repository and then cloned this modified MZmine3 to my Eclipse for running. However, when I did the step of formula prediction (by clicking Feature list method/identification/formula prediction) ,it looked that nothing happened and there was no task progress bar running on the screen and finally no predicted formulas were observed. It means that the function of formula prediction did not work. Could you please tell me how to figure it out? I have attached the java codes in the text file.
[20191217_codes of formula prediction.txt](https://github.com/mzmine/mzmine3/files/3974367/20191217_codes.of.formula.prediction.txt)

**Comment by tomas-pluskal** [comment]
@robinschmid Seems like a NPE in the FormulaPredictionPeakListTask constructor.

@kkcau9118 Could you add screenshots of the exact parameter values you used to run the module? Including all the sub-module settings please (like the isotope pattern filter etc.).

**Comment by kkcau9118** [comment]
> @robinschmid Seems like a NPE in the FormulaPredictionPeakListTask constructor.
> 
> @kkcau9118 Could you add screenshots of the exact parameter values you used to run the module? Including all the sub-module settings please (like the isotope pattern filter etc.).

Hi,

I just run this module again and it still did not work. Here is the text file of java code and the screenshots (I set the mass tolerance m/z to 0 m/z or 3 ppm, since I prefer to only use the unit of ppm in this step).
[20191217_02_codes of formula prediction.txt](https://github.com/mzmine/mzmine3/files/3975024/20191217_02_codes.of.formula.prediction.txt)
![image](https://user-images.githubusercontent.com/57988218/71026825-43da7000-210a-11ea-9a0e-ee928043bf42.png)
![image](https://user-images.githubusercontent.com/57988218/71026838-4b017e00-210a-11ea-8233-f33de485c2fd.png)
![image](https://user-images.githubusercontent.com/57988218/71026857-53f24f80-210a-11ea-85a7-60e4d1f8ac91.png)

**Comment by tomas-pluskal** [comment]
Should be now fixed in master

**Comment by robinschmid** [comment]
Sorry for the late response. Thanks for fixing it. I have also added the fix to the isotope pattern parameters.

**Comment by kkcau9118** [comment]
> Should be now fixed in master

Hi,

Thanks! So, how can I merge the fixed module of formula prediction into my own MZmine3 master repository?

**Comment by tomas-pluskal** [comment]
You need to use git Fetch and Merge. First fetch from the main repository, then merge the master branch to your branch.

**Comment by kkcau9118** [comment]
> You need to use git Fetch and Merge. First fetch from the main repository, then merge the master branch to your branch.

Hi,
I think firstly I need to update this fixed module in my online MZmine3 repository (please see the screenshot), then git Fetch and Merge in Eclipse, right? So, how to update this fixed module in my online MZmine3 repository? Thanks!
![image](https://user-images.githubusercontent.com/57988218/71121781-6a1e0f80-21df-11ea-8811-026876f5b7e7.png)

**Comment by tomas-pluskal** [comment]
You don't need to update your online mzmine3 repository, actually. You just need to add a "remote" in Eclipse that points to the original repository, and then you can fetch from there:

<img width="1047" alt="Screen Shot 2019-12-18 at 16 54 31" src="https://user-images.githubusercontent.com/1796692/71126524-2ca58c00-21b7-11ea-8110-6a681462e1b9.png">

**Comment by kkcau9118** [comment]
> You don't need to update your online mzmine3 repository, actually. You just need to add a "remote" in Eclipse that points to the original repository, and then you can fetch from there:
> 
> <img alt="Screen Shot 2019-12-18 at 16 54 31" width="1047" src="https://user-images.githubusercontent.com/1796692/71126524-2ca58c00-21b7-11ea-8110-6a681462e1b9.png">

Hi,

Thanks for the help! Since several modules need to be updated and merged, I decided to clone the newest version of MZmine 3 (from https://github.com/mzmine/mzmine3) to my Eclipse. Then I run this newest MZmine 3 by right-click 'MZmineCore.java', click 'Run as'/'Run configuration',setting the VM arguments as '-Xmx6g -Djava.util.logging.config.file=conf/logging.properties' and working directory as '${workspace_loc:mzmine3_master_20191219/src/main}'. However, I got an error message in the console panel, showing 'Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: log\mzmine.log.lck
java.nio.file.NoSuchFileException: log\mzmine.log.lck' (also please see the screenshot'. And after I imported the raw data, there was No data file displaying in the panel of 'Raw data files' (please see the screenshot'.
![image](https://user-images.githubusercontent.com/57988218/71178356-52419c80-226e-11ea-8a32-467247b3c4cb.png)
![image](https://user-images.githubusercontent.com/57988218/71178542-b49a9d00-226e-11ea-9355-350fbf5d439e.png)

**Comment by tomas-pluskal** [comment]
Sorry for that, I just fixed the raw data files not showing up in https://github.com/mzmine/mzmine3/pull/31. You can ignore the warning about the log files when you run from Eclipse.

Please update your sources again from the main repo and the data import should work fine.

**Comment by kkcau9118** [comment]
> Sorry for that, I just fixed the raw data files not showing up in #31. You can ignore the warning about the log files when you run from Eclipse.
> 
> Please update your sources again from the main repo and the data import should work fine.

Hi, 

Thanks! it works after I update the fixed sources.
