### ISSUE TITLE
Add: Export - Feature Table - CSV

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine3#26]

**Comment by dyrlund** [comment]
Each `IonAnnotation` can have a lot of information associated to it in addition to a description, e.g.:
-	Chemical structure
-	Formula
-	Ion type
-	Expected m/z value

Any suggestion about how to handle the IonAnnotation column in the export? Should we make a separate parameter in the dialog window which will allow the user to select which information from the ion annotation to export? This is how it was done in MZmine 2.

**Comment by dyrlund** [comment]
The initial version of the CSV export was added in #92 & #95 and [MSDK #105](https://github.com/msdk/msdk/pull/105) & [MSDK #107](https://github.com/msdk/msdk/pull/107).

**Comment by tomas-pluskal** [comment]
I'd rather not add a separate parameter for this. If the IonAnnotation column is exported, it can create multiple columns in the CSV file, one for each field. How about that?

**Comment by dyrlund** [comment]
I also don't like the idea of adding a separate parameter. However, if we expand the IonAnnotation with more information, as proposed in [MSDK issue #108](https://github.com/msdk/msdk/issues/108), then we are adding a lot of additional columns to the CSV file.

We could try to just add them and see how it work and what the reaction is. I will then only add columns for which there is associated data in the feature table. Are you happy with this?

**Comment by tomas-pluskal** [comment]
The approach to add the columns only if we have data for them has one major disadvantage, that the number of columns generated by the CSV export might be non-deterministic. This can cause problem for any kind of batch processing downstream.

**Comment by dyrlund** [comment]
True - so I guess we add all columns for now and then we can always add a paramter to limit this in the future.

**Comment by tomas-pluskal** [comment]
OK!

**Comment by dyrlund** [comment]
I made the change in [MSDK #112](https://github.com/msdk/msdk/pull/112). Please let me know if you have a better way to make the implementation especially given that we will have to extend this to cover the other IonAnnotation data which we are [planning ](https://github.com/msdk/msdk/issues/108)to add to the MSDK data model.

**Comment by dyrlund** [comment]
With the updated IonAnnotation datamodel in [MSDK #121](https://github.com/msdk/msdk/pull/121), the CSV export is now done.

Please let me know if you find any bugs or if you have any suggestions to improving the method then please feel free to change the code directly.
