### ISSUE TITLE
Problem with mass detection

### ISSUE THREAD

**Issue by JustinRCrossMSKCC** [mzmine/mzmine3#275]
### Basic information

* My operating system: Win10
* My MZmine version: 3

### What happened

After loading files mass detection reaches status: FINISHED on the status bar, but this is instantaneous and no mass list is created. Have tested Agilent .d files converted with MSConvert to XML and mzXML files downloaded from MASSIve.

![image](https://user-images.githubusercontent.com/84399135/118677832-8f46f100-b7ca-11eb-8d88-726795a97c9a.png)

Data is centroid and the same files process successfully in mzMine 2.53
We have tried changing noise level, MS1 v. MS2 level with no success. There are no other filters active.

Best,
Justin

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
MZmine 3 is not yet stable, therefore we recommend using MZmine 2 currently. 

However, that is an issue worth looking into. Can you please share your xml/mzxml files?
Does the issue also occur for mzML files?

**Comment by SteffenHeu** [comment]
Also: As a change from MZmine 2 to 3, we have changed how mass lists work. There will only be one mass list per scan, therefore there will be no mass list selection. Also, currently there is no indicator in the raw data file list, that a mass list was created. 
Furthermore, the way the scan data is stored was changed, which might let it seem instantaneous because it is just faster than before. Have you tried running chromatogram building after?

**Comment by robinschmid** [comment]
Did you download the latest development release? As Steffen pointed out - its not yet stable. It is more for testing purposes.
In general, you should check out the mzML format - as this is the successor of mzXML.

If you still want to test it:
1. you need to create a new batch file if you want to run in batch mode
2. project saving loading is still in progress to be updated - and deactivated.

**Comment by JustinRCrossMSKCC** [comment]
Thanks for the quick response and yes, we understand MZmine 3 is still in development.

The version we are using was downloaded using "download as Zip" from the main GitHub MZmine 3 page. I then compiled on the local machine by running the gradlew.bat file.

I have the same issue with the version I downloaded 3 weeks ago and the version I downloaded today.

We have tested 3 files, 2 are Agilent .D containing MS1 and DDA MS2, converted with MSConvert settings shown below...

6550_BEHpos_Comp10_ITMSMS_01_no_sum.mzML
Just the vendor centroid peak picker

6550_BEHpos_Comp10_ITMSMS_01.mzML
Adding the scan summing of MS2 spectra since Agilent collects at 10, 20, 40 eV.

As you probably know, GNPS cannot handle multiple MS2 spectra so our plan was to compare 'pre-summing' MS2 spectra at the MSConvert stage v. spectral averaging on the MZMine -> GNPS workflow.

There is no mass list created after mass detection although status says it's completed. When I go onto the next step to build the chromatogram the table is empty.

The 3rd test file is mzXML downloaded from MASSive has the same issue, I think it's Bruker data processed with OpenMS and has the same issue.

These are out MSConvert settings we used for the Agilent files:
![image](https://user-images.githubusercontent.com/84399135/118683844-b3590100-b7cf-11eb-8af4-3a9fd0e319f6.png)

Happy to share the mzML files, what is the best way to transfer them?
I can also show you on a Zoom call if helpful.

**Comment by SteffenHeu** [comment]
Uploading to google drive, dropbox, mega or any other file hoster is fine, then we can check the files.

As far as i understand what you are trying to do should also be possible with MZmine 2, since you are summing the scans in MSConvert, or?

**Comment by JustinRCrossMSKCC** [comment]
You should have received an MSK Box.com link to the 2 converted Agilent files.

Agreed, we can probably use MZmine 2.53. We were interested to start exploring MZmine 3 and particularly the merge MS/MS option in the GNPS export, since that function is marked as experimental in MZmine 2.53.

Do you have any recommendation for how to leverage this merger MS/MS feature for typical Agilent metabolomics DDA  (which is: allow each precursor to be isolated twice, and fragment each time at 3 collision energies). Getting this right may become important for retaining good spectral matches in GNPS.

Settings we were planning to use (and compare to summing MS2 spectra in MSConvert):

**Select spectra to merge:** SAME SAMPLE - since there will be an MS1 scan between the first time a precursor ion is isolated at the 3 collision energies and the 2nd time it is isolated.

**m/z merge mode:** WEIGHTED AVERAGE? I think on a GNPS video square root of the MS2 peak intensities prior to summing was suggested, but this is not available as an option?

**Intensity merge mode:** SUM INTENSITIES

Any advice on this step would be much appreciated!

**Comment by SteffenHeu** [comment]
Unfortunately, I cannot reproduce what you reported. I used an MS 1 filter and no filter, both worked.

Example feature list:
![grafik](https://user-images.githubusercontent.com/37407705/118688841-b3c0be80-b806-11eb-964d-3772a281aac5.png)

I am not too famliar with the merging parameters in MSConvert, it's probably best to ask them directly.
For merging in the GNPS module, it's probably best to ask @robinschmid (implemented GNPS export in MZmine) and @kaibioinfo (I think he wrote the MS2 merger that is used in the GNPS export). Perhaps they can just comment here.

**Comment by robinschmid** [comment]
The merging is quite complex and it is still experimental. With the latest MZmine 2 version you can at least refer to this version for publication. Really only use MZmine 3 for testing purposes.

I think the best way to build MZmine is to use a development IDE (IntelliJ IDEA, eclipse, ...).
