### ISSUE TITLE
a problem of gap filling process in MZmine3

### ISSUE THREAD

**Issue by kkcau9118** [mzmine/mzmine3#29]
### Basic information

* My operating system: Windows10
* My MZmine version: MZmine3

### What happened

Hi,
I tried to do the process of gap filling  after the step of Join aligner. I chose the method of peak finder for the gap filling process. However, after the gap filling, all the m/z values became to 0. Do you know why? I have attached the java codes in the text file and the settings of the gap filling in the screenshots. Thanks a lot !
[201912128_gap filling problem.txt](https://github.com/mzmine/mzmine3/files/3979990/201912128_gap.filling.problem.txt)
![image](https://user-images.githubusercontent.com/57988218/71113313-9af54900-21cd-11ea-9923-b5ea391eae51.png)
![image](https://user-images.githubusercontent.com/57988218/71113327-a183c080-21cd-11ea-9bd7-10cc94b1d0f4.png)

**Comment by tomas-pluskal** [comment]
Does it still happen if you uncheck the RT correction_

**Comment by kkcau9118** [comment]
> Does it still happen if you uncheck the RT correction?

It looks ok now after I added two samples for gap filling process.  Previously, I only processed one sample. Maybe that's the reason.

**Comment by tomas-pluskal** [comment]
Gap filling can only work if you have multiple files aligned together. We should add a check for that.

**Comment by SurajViitk** [comment]
I want to work on the issue, but I cannot recreate the error. I'm using ubuntu 19.04, I have not in depth understanding of spectrometry, but according to my understanding, to recreate the error I performed following steps - 
1. Generated 3 mass detection feature list from 3 raw mzdata files.
2. Generated join alignment from the 3 files.
3. Generated gap filled data with settings given above.
Final "Aligned feature list gap-filled" data was fine, with green status and non 0 m/z values.
Can someone point out what I'm doing wrong?

**Comment by tomas-pluskal** [comment]
@SurajViitk I suppose you are interested in the Google Summer of Code program, is that correct? If that's the case, please send us an email first (mzmine@mzmine.org) to introduce yourself and let's discuss the next steps over email.
