### ISSUE TITLE
Data model for "spectral deconvolution" and ion identity networking

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#3]
### Group signals from the same molecule
Data structure to link all signals (ions) that originate from the same molecule:
- GC-EI-MS 
- adducts and other ions from CI or ESI-MS

- RowGroup extends FeatureListRow
  - representative row
  - List<Row>

### Correlation results
- not all rows in the same group are actually correlated - more like a correlation network
- **how to store the correlations?**
  - Row2RowRelationship map? 
    - key: "ID1+ID2"
    - value: any relationship

### Annotation results (ion identity networking: M+H, M+Na ...)
- another layer of RowGroup
- not all grouped rows are annotated
- one correlation group might have multiple annotation networks

### Renumbering of rows
- needs to number all rows in the RowGroup to have a unique identifier

### Other
- Parameter to choose "ALL" or "REPRESENTATIVE" features for export

**Comment by SteffenHeu** [comment]
#235

**Comment by robinschmid** [comment]
Most was addressed
