### ISSUE TITLE
Add: Filtering - Row Filter

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine3#30]

**Comment by dyrlund** [comment]
Added in pull request #45 and [MSDK # 58](https://github.com/msdk/msdk/pull/58)

**Comment by dyrlund** [comment]
@tomas-pluskal With regards to the "min features in a row" parameter, I have had a request to also support a % value. What do you think about parsing values below 1 as a relative value (%) and anything above as the absolute value? Or would you prefer that I add a new parameter similar to the RT tolerance?

**Comment by tomas-pluskal** [comment]
Sure, you can add the <1 percentage function, although I think you will be the only one to use it :)

**Comment by tomas-pluskal** [comment]
We could also add a list of textual expressions, so the user could design their own conditions. For example, 
NUM_FEATURES > 2
NUM_FEATURE / TOTAL_FEATURES > 0.5
RT > 5
AREA_2 / AREA_3 > 2.5

The module would simply replace the keywords with values and evaluate the expression. What do you think?

**Comment by dyrlund** [comment]
So you are suggesting to add an additional parameter which will interpret textual expressions or do you want to replace the current parameter dialog? This idea will make the module very flexible for the user but will be a bit complex to code.

For now I will add the <1 percentage function.
