### ISSUE TITLE
An error message of centroid mass detector

### ISSUE THREAD

**Issue by kkcau9118** [mzmine/mzmine3#30]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine3

### What happened

Hi,
I always got an error message (please see the screenshots) when I selected the 'centroid' as the mass detector in the step of mass detection. The error message shows that if I use the centroid mass detector, it will likely produce wrong results. However, after I clicked 'ok' and the results actually seems fine. So, is it ok that I just ignore this error message? do you also meet this error message? Thanks!
![image](https://user-images.githubusercontent.com/57988218/71123713-8cb22780-21e3-11ea-8dd5-a872c4cdd18c.png)
![image](https://user-images.githubusercontent.com/57988218/71123722-93409f00-21e3-11ea-997e-1812c8f68fbb.png)

**Comment by tomas-pluskal** [comment]
This is not an error message. It is just a warning.

Is your data actually centroid or profile?

**Comment by kkcau9118** [comment]
> This is not an error message. It is just a warning.
> 
> Is your data actually centroid or profile?

The imported data is generated from Orbitrap MS (Q-exactive, Thermo Scientific) with full-scan MS mode  and the suffix of the file is '.raw'.

**Comment by tomas-pluskal** [comment]
That actually doesn’t answer my question whether the data is profile or centroid. If you didn’t acquire the data yourself, try talking to the people who acquired it.

**Comment by robinschmid** [comment]
zoom into the signals very closely. If they are peak shapes - you should use the exact mass detector. If the signals are only centroid signals of m/z and intensity then use the centroid mass detection.

**Comment by kkcau9118** [comment]
> zoom into the signals very closely. If they are peak shapes - you should use the exact mass detector. If the signals are only centroid signals of m/z and intensity then use the centroid mass detection.

**Comment by kkcau9118** [comment]
> zoom into the signals very closely. If they are peak shapes - you should use the exact mass detector. If the signals are only centroid signals of m/z and intensity then use the centroid mass detection.

Hi,
I just zoom in one MS peak in the Xcalibur software (please see the screenshot). It looks that the data is profile, correct?
![image](https://user-images.githubusercontent.com/57988218/71182870-3393d380-2277-11ea-8663-4bb541b4c988.png)

**Comment by robinschmid** [comment]
yes it is profile. 
You directly import the raw files into MZmine right?
SOme people convert to mzML and perform peak picking in msconvert - then the spectrum type changes to centroid.

**Comment by kkcau9118** [comment]
Yes, I directly import the raw files into MZmine without the conversion.

**Comment by tomas-pluskal** [comment]
Could you upload one of your files? I can check why MZmine is giving you the warning.

**Comment by tomas-pluskal** [comment]
Oh wait, nevermind. MZmine was giving you the correct warning, because your scans are profile. You should use the "Exact mass" detector instead.
