### ISSUE TITLE
Add: Alignment - Join Aligner

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine3#31]

**Comment by dyrlund** [comment]
@tomas-pluskal What is the reason behind naming the join aligner module in MZmine 2 "Join Aligner"? I don't see the logic in what "Join" refers to other than it aligns two lists – but the RANSAC aligner does the same.

Why not re-name it to something like:
- m/z & RT aligner
- Match score aligner
- Closet match aligner
- Closet m/z & RT aligner

**Comment by tomas-pluskal** [comment]
As far as I understand the reason is purely historical - it had this name since early MZmine versions. I don't mind renaming it. I am more concerned about the fate of the RANSAC aligner - does anyone ever use it?

**Comment by dyrlund** [comment]
The RANSAC aligner has been used 116 times so far in December versus 594 for the join aligner. So yes, about 16% of alignments are performed using the RANSAC aligner.

**Comment by dyrlund** [comment]
For now I renamed it to "Match Aligner". See pull request #62 and [MSDK #71](https://github.com/msdk/msdk/pull/71)

**Comment by tomas-pluskal** [comment]
Hi Thomas, 
Just thinking - is Match Aligner really more explanatory than Join Aligner? 
I am gradually getting the feeling it might be better to stick to the established name. The reason is that the name Join Aligner is extensively mentioned in the previous publication (BMC Bioinformatics 2010) and the algorithm is explained there. Perhaps by changing the name now we would be just generating more confusion..

**Comment by dyrlund** [comment]
I agree that match aligner is also not good. But I still believe that the more useful names we use, the easier and more intuitive MZmine will be.

I’m happy to continue with established names (also Join Aligner) if there is an argument or support for the naming. Otherwise I think that MZmine 3 is a good time to update the vocabulary to use as precise and correct vocabulary from the mass spectrometry field. This is also why we changed the name of the peak lists to feature tables.

**Comment by tomas-pluskal** [comment]
In case of the join aligner, I think there is a good argument to keep the established name. By the way, MZmine's Join Aligner is also mentioned in the recent Tsugawa et al. MS-DIAL paper.
