### ISSUE TITLE
GUI Design ListView vs TreeView

### ISSUE THREAD

**Issue by Annexhc** [mzmine/mzmine3#33]
Hey Tomas,
I was wondering why we are using ListView instead of TreeView  for the RawDataTree in the main window. I talked to @robinschmid today about the possibility to use TableTreeView. That would make it more complicated but would also enable nice possibilities to observe a raw file.
What do you think?

**Comment by tomas-pluskal** [comment]
This is something we can still change, of course. But in the past, when giving tutorials or workshops with MZmine, I found that many users are initially confused by the "+" buttons in the project tree. For example when asked to open the feature list, they don't know if they should click on the + button or double click on the feature list name. In contrast, ListView is conceptually simpler and easy to understand for everyone. And we could add an option to explore the RawDataFile using a separate window (e.g., list all scans of the file and details about them in a table). The separate window could be implemented using TreeTableView, as you suggest. What do you think about that?

**Comment by tomas-pluskal** [comment]
@robinschmid @Annexhc By the way, I am about half-way done with JavaFXing the whole MZmine on my branch: https://github.com/tomas-pluskal/mzmine3/tree/javafx_parameters 
Feel free to take a look. It still has compilation errors, but you can run it in Eclipse, load files and projects, run TIC plots, etc.

<img width="1566" alt="Screen Shot 2019-12-30 at 11 42 19" src="https://user-images.githubusercontent.com/1796692/71591216-7cf6e500-2af9-11ea-8a5e-18d68e8fa04b.png">

**Comment by tomas-pluskal** [comment]
Once the JavaFXing is done, we can talk more about how to improve the main window further - e.g., using tabs or dockable components.

**Comment by Annexhc** [comment]
Nice progress Tomas! I totally get your point. The TreeView of ALL scans isnt really the best option anyway. I like the idea of a separated window to visualize the raw data. @robinschmid do you agree?

**Comment by robinschmid** [comment]
I know some people who did get confused with the feature lists. They would only open the feature list with the + of the tree and not by double clicking the item. I still like the tree or the idea for a TableTreeView. However, this could be a checkbox menu item ("advanced project trees").

@tomas-pluskal Great :)
I also saw that you have switched to EChartViewer. Nice.

**Comment by Annexhc** [comment]
I will close this one. See rawdataoverview package
