### ISSUE TITLE
Parallel processing using mzmine3 on HPC cluster

### ISSUE THREAD

**Issue by che25** [mzmine/mzmine3#369]
### The case for parallel processing

I am working in a Metabolomics core facility where we turn over a lot of samples. We're keen to use MZmine as we think it offers the best solutions that are on the market. 

Since we regularly run into problems when we process large datasets on a desktop computer (computational time is the key issue), we are thinking of setting up a processing pipeline on an HPC cluster, probably involving docker/singularity.

Will it be possible to run mzmine3 non-interactively, and will it be possible to distribute some of steps in parallel to multiple nodes? Can we expect large gains in computational time through parallelisation?

You are probably aware of the SLAW project (https://github.com/adelabriere/SLAW) where this has been achieved to some degree. Is this my best bet or is there going to be a version of MZmine 3 that is aimed in this direction? We'd much rather use the same version of MZmine on our local computer and on the cluster.

###  Our ideas of a workflow are the following

- interactively and visually inspect experiment with subset of data on desktop computer
- determine best parameter set, which could be based on previous experiments 
- do the heavy calculations on the cluster
- do some quality check manually

I'd be very interested to hear your thoughts, comments and suggestions.

**Comment by robinschmid** [comment]
Hey @che25 

Sorry for the late response we were still heavily focused on some changes to the core data structure improving the performance and memory use. 
We can soon share a version with you and coordinate some performance tests if you are interested.

Your plan sounds reasonable. All processing-intensive modules in MZmine are multithreaded. It should actually scale. 

Best regards
Robin

**Comment by robinschmid** [comment]
@che25 I will close this issue due to inactivity. 
We just released the beta version of MZmine and if you would like to work with big datasets, try it out and reach out if you want to tune Mzmine to your needs. We can reopen this issue if needed.

Best regards,
Robin
