### ISSUE TITLE
[new feature] XFlow suggestion

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#372]
Hi fellow mzminers!

Walking randomly through literature, I encountered https://doi.org/10.1371/journal.pone.0227659. 
As it is parameter-free and already written in Java I thought it might be a good idea to pin it here...

Best,

**Comment by titodamiani** [comment]
Hi, I'll close this for now. @gutierrezm00 feel free to re-open it and/or reach out to us if you're still planning to work on it:)
