### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by Annexhc** [mzmine/mzmine3#38]
Hi all,
I want to start a discussion on how to harmonize the colors used in MZmine, especially for charts. @robinschmid has added utility classes to manage colors in accordance to a selected vision. The vision can be set in the preferences. I tried to use this utility for the raw data overview visualizer, it works really well. Nevertheless, I think it is not the best solution to call the methods to get colors based on vision in every single module when ever a plot is generated. So my idea would be to integrate color themes (based on vision) directly in the preferences. The user can change the colors there and they will be globally applied on every chromatogram, spectrum, etc.
Any other/better ideas or opinions?

**Comment by tomas-pluskal** [comment]
I agree the color scheme selection should be in the Preferences. But the user should be able to change the color of each plot individually. I imagine each visualizer should have a similar bottom panel like the new 3D visualizer does, where the user can individually set the colors, opacity, and other parameters of each plotted dataset. The default colors can be provided by the color scheme selected in the Preferences based on the vision profile.

**Comment by SteffenHeu** [comment]
How would you want to organize the colours? I was thinking about something like this maybe?

![grafik](https://user-images.githubusercontent.com/37407705/73014774-ab26c680-3e12-11ea-90c9-d00221fcd6f0.png)

**Comment by robinschmid** [comment]
I thought we could have standard color palettes for different numbers of colors. in Colors or ColorsFX there is a link to a scientific article with more palettes for color blind. Those can be used as a standard and users should be able to supply their own.
Most modules should just follow the selected palette. With less variety between the modules - the overall look and feel of MZmine will be more straight forward.

Same for positive, negative, and neutral feedback colors.

Some modules could then still implement their own color palettes and the programmer should add this to the preferences or to the module parameters?

**Comment by SteffenHeu** [comment]
I would do the same, going for one colour palette as a default. But should the user, in general, be able to choose different palettes for tics/bpcs and integrated peaks? Or should we just use one palette.
And should the 3 colours i am currently listing as "global" colours be set seperately or should they for example use the first 3 colours from the colour palette?

**Comment by robinschmid** [comment]
I would make them use the colors from the palettes. 
We can still allow different modules to use specific colors (ColorParameter in the preferences or in their own parameters), however, it would be nice if most of the charts look similar

**Comment by tomas-pluskal** [comment]
I agree with Robin, I would make only one default color palette that the modules can pick colors from. Then the user can modify the colors manually in each plot when needed.

Would you like to work on adding the color palette parameter to the Preferences?

**Comment by SteffenHeu** [comment]
I can do that if i find the time, yes.

**Comment by SteffenHeu** [comment]
I'm working on it, you can see the progress here:
https://github.com/SteffenHeu/mzmine3/commit/8817ec3f6032793fa1040246471d095f7ef54fb4

**Comment by SteffenHeu** [comment]
Made some progress on the component
![grafik](https://user-images.githubusercontent.com/37407705/73500624-1ea07900-43bb-11ea-8e93-cdbe3464784b.png)

**Comment by tomas-pluskal** [comment]
Looks great!!

**Comment by Annexhc** [comment]
Looks amazing! Btw, good look today with brexit, come back safe!

**Comment by robinschmid** [comment]
Great.
Can you drag and drop the color panels to change the order? this might be useful.
And it would be nice if people could
- name the palettes
- save/load from files
- choose from a drop-down menu 
    - (helpful if some other modules use this parameter/component to define custom colors)
    - we could then also define multiple standard palettes for the users to choose

**Comment by SteffenHeu** [comment]
Drag and drop sounds like a good idea. 
Since the main component is a combobox, the drop down menu is implemented ;).
Saving and loading separately to the regular parameter functions probably at some point in the future. I think we should focus more on the implementation of this to the preferences and all the plots. 

Will mzmine 3 have styling (e.g. a dark thme)? Or to ask in another way: is it easy to implement that in java fx? Maybe via a stylesheet or so?

**Comment by robinschmid** [comment]
it is mainly css. However, the charts are controlled via ChartThemes

**Comment by kmAyush** [comment]
Hi, in my opinion, it will improve its user interface. It seems to be good way for me to start contributing. May I contribute on this?
Right now I am trying to understand code structure better and I think contributing will be a better way to do this. 
> Will mzmine 3 have styling (e.g. a dark thme)? Or to ask in another way: is it easy to implement that in java fx? Maybe via a stylesheet or so?

**Comment by tomas-pluskal** [comment]
@kmAyush Please contact me by email, and I will give you a task to implement. The CSS styling is not the best start I think, because there is no clear goal.

**Comment by tomas-pluskal** [comment]
Can we close this issue now that @SteffenHeu 's color palette settings have been merged? Or anything still missing?
