### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by SteffenHeu** [mzmine/mzmine3#5]
Hey @robinschmid & @tomas-pluskal,
I hope I'm allowed to chip in my two cents about the recent PR #1 aswell. Sorry that I am late:

I do understand that you want to make the structure of the modules less complicated by removing unnecessary differentiation between the module classes, but I do think that stuff like "featdet_deisotoper" is not quite fitting, too. Either it should be listed under filter or there should be at least one more category like featproc for feature processing.
Yes, it does make sense to keep it as simple as possible, but oversimplification can also lead to confusion and that is certainly not what we want.

Best regards
Steffen

**Comment by tomas-pluskal** [comment]
Thanks for the input, @SteffenHeu !

I agree we can move the deisotoper to filter_, it makes more sense for now.
