### ISSUE TITLE
Add: Identification - Custom Database Search

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine3#52]

**Comment by dyrlund** [comment]
I suggest that we add adduct as a standard input when performing local database identifications. The order of the input will therefore be:
- Id
- m/z
- Retention time
- Compound name
- Formula
- Adduct

The formula and adduct values can be empty.

Furthermore, with the new flexible data model, I suggest that we allow any optional columns to be present after the adduct column. These data can then be added as common columns to the feature tables. Any comments to this improvement?

**Comment by tomas-pluskal** [comment]
On Mon, Dec 14, 2015 at 7:28 AM, Thomas F. Dyrlund <notifications@github.com
> wrote:

> I suggest that we add adduct as a standard input when performing local
> database identifications. The order of the input will therefore be:
>
>    - Id
>    - m/z
>    - Retention time
>    - Compound name
>    - Formula
>    - Adduct
>
> The formula and adduct values can be empty.
>
Good idea.


> Furthermore, with the new flexible data model, I suggest that we allow any
> optional columns to be present after the adduct column. These data can then
> be added as common columns to the feature tables. Any comments to this
> improvement?
>

I am not sure if this will be useful, since we don't have any downstream
modules that would use such additional information. Also, you would somehow
need to distinguish whether the data is supposed to be a number or a
String, etc... Sometimes having too much flexibility can make things
confusing.

T.

**Comment by dyrlund** [comment]
Initially, the export modules will be able to support these optional columns. For example, we have a column in our MS library with the ID level of our compounds. This information is useful in our downstream analysis and would therefore be relevant for us to have in the feature tables. Other custom columns include InChI and InChIKeys.

With regards to distinguishing the data, then I think it shouldn’t be difficult to test if all data in one column can be parsed like a double value. If not, then we set the class to String.

**Comment by dyrlund** [comment]
I have added the initial module in #56 and [MSDK #65](https://github.com/msdk/msdk/pull/65) with support for the 6 standard columns (id, m/z, rt, name, formula and adduct). The input data is converted in MZmine to IonAnnotations before sent to MSDK. I do however think that it also makes sense to allow passing user defined columns as an array to the method in MSDK but I won't implement this until we agree on the final implementation of the method.

**Comment by dyrlund** [comment]
We also need to agree on how to handle multiple annotation hits for a single feature. I suggest that we change so that the IonAnnotation column contains a list of IonAnnotations instead of just one as it is now. This will require changes to the data model in MSDK.

**Comment by dyrlund** [comment]
The ion annotation column now holds a list of IonAnnotations which makes it possible to handle multiple annotation hits for a single feature. The changes can be seen in this [MSDK commit] (https://github.com/dyrlund/msdk/commit/14a59d78a3442486fc6f6d05e763ca8f45897499)
