### ISSUE TITLE
Command line use

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#563]
**Is your feature request related to a problem? Please describe.**
It is a feature request or documentation request.

I would like to run mzmine3 headless as mzmine2

**Describe the solution you'd like**
Using mzmine2 it was possible to do the following:
```
./startMZmine_Linux.sh /path/to/batch/file/BatchFileName.xml
```
What would be the equivalent with mzmine3?

**Describe alternatives you've considered**
An alternative would be to create an additional "headless" version of the already existing mzmine image?

**Additional context**
None

Best,

**Comment by SteffenHeu** [comment]
Hey, 
You can find the command line documentation here: 
https://mzmine.github.io/mzmine_documentation/performance.html

**Comment by Adafede** [comment]
Beautiful! 

That's why I labeled it as feature/documentation request, I was sure it existed already! Checked quickly but didn't go in that section...

Thanks a lot!
