### ISSUE TITLE
[Bug] Process priority status not changed on the UI

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#569]
### Basic information

* My operating system: MacOS 12.3
* My MZmine version: 3.0.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

I tried to change the priority of my process from `Normal` to `High`. Log file shows it worked but the change does not appear on the UI (stays `Normal`). 

* Please include all parameter values for the MZmine modules you used. 

No parameters used, just did: `Set priority > high`

* Please upload screenshots of any errors and your log/mzmine.log file.

[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8196351/mzmine_0_0.log)
<img width="1679" alt="Capture d’écran 2022-03-07 à 10 13 14" src="https://user-images.githubusercontent.com/44283913/157002892-45a604f6-15b7-4b66-863c-30a23069cdc2.png">

* Please upload an MZmine project file that demonstrates the problem you are reporting.

NA

**Comment by robinschmid** [comment]
Thanks for the report. Seems to be a wrong binding of the data to the visuals. Will fix it.

**Comment by robinschmid** [comment]
Fixed in the next patch release
