### ISSUE TITLE
Error of task Importing raw data file(mzml format)

### ISSUE THREAD

**Issue by 2952980446** [mzmine/mzmine3#574]
### Basic information

* My operating system:Window 10 home x64
* My MZmine version: MZmine 3.0.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Failed to import data ，how to settle it？
![problem 0f 1 program 2022-03-07 212704](https://user-images.githubusercontent.com/101093685/157043254-1c52093d-bdec-4c07-acc8-4f4adce8e0f4.png)
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
[1FL1.zip](https://github.com/mzmine/mzmine3/files/8198036/1FL1.zip)
* Please upload an MZmine project file that demonstrates the problem you are reporting.
[1FL1.zip](https://github.com/mzmine/mzmine3/files/8198046/1FL1.zip)

**Comment by robinschmid** [comment]
Thats weird. Thanks for reporting the issue. 
Can you specify what software / parameters were used to create the mzml?
