### ISSUE TITLE
[Bug] Ion Identity: Cannot import custom adducts/modifications list from csv

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#575]
### Basic information

* My operating system: MacOS 12.3
* My MZmine version: 3.0.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

I tried importing a custom adducts.csv file but it does not load desired adducts.

* Please include all parameter values for the MZmine modules you used. 

No parameters used, just did: `Feature list methods > Feature grouping > Add more ion identities`

You can try exporting the default list and re-importing while adding a single dummy line it does not work

* Please upload screenshots of any errors and your log/mzmine.log file.

```
2022-03-07 18:24:51 WARNING io.github.mzmine.parameters.parametertypes.MultiChoiceComponent loadChoices Line length is different to header length: 5 to 5
```

* Please upload an MZmine project file that demonstrates the problem you are reporting.

NA

**Comment by robinschmid** [comment]
Will be fixed in the next release. Thanks for reporting.
