### ISSUE TITLE
[Feature] Keep lists order when reloading a project

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#576]
**Is your feature request related to a problem? Please describe.**

When loading a project, (feature) lists are not ordered in the same order as they were created

**Describe the solution you'd like**

I would like lists to keep the same order

**Describe alternatives you've considered**

Giving each lists a prefix like `1_...` to then sorter them alphabetically

**Additional context**

NA

**Comment by robinschmid** [comment]
Always open for contributions :)
That would be a nice first project for someone

**Comment by Adafede** [comment]
@robinschmid 

Does this start by replacing the `.newInstance()` by `.newLinkedInstance()`or shall I forget the idea of putting hands in there directly? 😝

**Comment by robinschmid** [comment]
Can you point to the point in the code?
@SteffenHeu is the expert.

**Comment by SteffenHeu** [comment]
A simple approach would be to sort the feature lists by date. Usually the newest feature lsit will be on top. So what you can do is sort the feature lists in the project by date after loading.

https://github.com/mzmine/mzmine3/blob/83af52a07b875aa9c2dbf1a24524adfb1832f7af/src/main/java/io/github/mzmine/modules/io/projectload/version_3_0/FeatureListLoadTask.java#L176

Keeping the original order would be more difficult.
