### ISSUE TITLE
Export Multiple Individual Feature Tables

### ISSUE THREAD

**Issue by bmgarcia** [mzmine/mzmine3#582]
Hello, I am curious if there is a way to export multiple individual feature tables from MzMine 3.0 at once using either the export .csv module or the batch mode with export csv included? 

In the export .csv module it allows me to select multiple feature tables however the "filename" section only has 1 input - so I'm unsure if I need to just select a directory and put no file name or if there is a way to designate different .csv files for export.

**Comment by SteffenHeu** [comment]
Hey @bmgarcia, 

the legacy and the new csv export should both replace "{}" with the name of the exported feature list. So if "{}" is not present, the same file will just be overridden multiple times.

**Comment by bmgarcia** [comment]
Thank you so much, this was very helpful!
