### ISSUE TITLE
Mass list not generated when applying Retention time filter

### ISSUE THREAD

**Issue by vanjamilenkovic** [mzmine/mzmine3#587]
### Basic information

* My operating system: Ubuntu 20.04.4 LTS, 64-bit (same issue on Windows 10)
* My MZmine version: MZmine 3.0.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

After running "Raw data methods" -> "Mass detection" using the following parameteres:
Retention time filter: 0.00-24.00, 
MS level: 1,
Mass detector: Centroid,
Noise level: 7E6,

And

"Raw data methods" -> "Mass detection" 
Retention time filter: 0.00-24.00, 
MS level: 2,
Mass detector: Centroid,
Noise level: 7E4

I got an error message when running "Feature fetection" -> "LC-MS" -> "ADAP chromatogram builder" 
Error message: "Scan #15519 from Piloteexperiment_21.mzML does not have a mass list. Please run Raw data methods" -> "Mass detection" .

The issue occured when using MZmine 3.0.0-beta on Widows 10 as well. When the Retention time filter is not applied the mass list is generated and ADAP chromatogram is built.

* Please include all parameter values for the MZmine modules you used. 
Included above

* Please upload screenshots of any errors and your log/mzmine.log file.
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8214219/mzmine_0_0.log)

* Please upload an MZmine project file that demonstrates the problem you are reporting.
[Pilot1_vanjamilenkovic_mzmine.zip](https://github.com/mzmine/mzmine3/files/8214237/Pilot1_vanjamilenkovic_mzmine.zip)

**Comment by SteffenHeu** [comment]
Hi vanjamilenkovic, 

Is the chromatographic run of your measurements longer than 24 min? Then you also need to specify the filter in the ADAP chromatogram builder.

Otherwise please upload the project as a standalone project or upload the raw data file the issue happens with.

**Comment by robinschmid** [comment]
Mass detection has nearly no overhead. The easiest way is to run mass detection on all scans (only use filters for MS1 and MS2) and then limit your chromatograms in the chromatogram builder or later with a Rows filter.

Best regards,
Robin

**Comment by SteffenHeu** [comment]
@vanjamilenkovic did the issue persist?

**Comment by vanjamilenkovic** [comment]
> @vanjamilenkovic did the issue persist?

Thank you both for the reply. 

The issue was avoided if I applied the same RT filter when running the ADAP chromatogram builder or applying the RT filter later on in the processing as suggested by @robinschmid 

cheers!
