### ISSUE TITLE
Spectral deconvolution error

### ISSUE THREAD

**Issue by gdelap** [mzmine/mzmine3#595]
### Basic information

* My operating system: Windows 10
* My MZmine version: MZmine 3.0.11-beta

### What happened

Dear developer team, while testing MZmine 3, I run into a bug while trying to reproduce my usual workflow for GC-MS data (unit mass resolution) on my benchmark data set.

* I run the following steps as usual: raw data import, mass detection (centroid), ADAP chromatogram builder, ADAP resolver. I got a feature list corresponding to what I expect.
* Next step: Spectral deconvolution (GC) --> Hierarchical Clustering gives me the followig error:

```
'Unknown error' during peak decomposition
Cannot invoke
"io.github.mzmine.datamodel.FeatureInformation.getAIIProperties()"
because the return value of
"io.github.mzmine.datamode.features.FeatureListRow.getFeatureInformation()" is null
```

* I tried other parameters and data files, still get the same error.

* I tried Multivariate Curve Resolution method as well and get the same error.

I would have included the logs, but I get the following error when generating them:

```
Cannot load module class
io.github.mzmine.modules.auditlogexport.AuditLogExportModule
```

Thank you for the great work on this version 3!

**Comment by robinschmid** [comment]
Thanks for the report. We are working on fixing the spectral deconvolution modules. Something internally seems to be broken.

**Comment by robinschmid** [comment]
Please try the latest development build version >=3.1.3.
Duplicate issue of https://github.com/mzmine/mzmine3/issues/728
