### ISSUE TITLE
Failure to import Bruker TDF timsTof data with mzMine 3.0.11-beta under MacOS 10.14.6

### ISSUE THREAD

**Issue by raimofranke** [mzmine/mzmine3#596]
### Basic information

* My operating system: macOS Mojave 10.14.6
* My MZmine version: MzMine 3.0.11-beta

### What happened

* Raw data import -> Bruker TDF 
* Selected a .d folder containing data of the Bruker TimsTof Pro, meassured with TIMS on / PASEF mode
* 2 error messages appeared:
* "Failed to open the file /path_to_file/filename.tdf_bin using the Bruker TDF library"
* "MacOS is not supported by Bruker Daltonics. Please contact Bruker Daltonics." 
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8231510/mzmine_0_0.log)

**Comment by SteffenHeu** [comment]
Hi raimofranke,

as stated in the error message, Bruker does not support mac os with their library. A library compiled for mac is simply not available.

Best regards

Steffen

**Comment by raimofranke** [comment]
Hi Steffen,

thanks for the quick reply. Does Bruker support Linux with their library? Or are we still forced to work on Windows machines? That would be too bad. Do you think there is hope for the future regarding support for Mac OS and/or Linux from Bruker?

Thanks and best regards,
Raimo

**Comment by SteffenHeu** [comment]
Yes, Linux is supported.

I don't know if Bruker plans to support macOs, though.
