### ISSUE TITLE
Empty GNPS FBMN output file

### ISSUE THREAD

**Issue by niclas-gr** [mzmine/mzmine3#600]
### Basic information

* My operating system: Windows 10 Home Edition 64 bit
* My MZmine version: 3.0.0

### What happened

* Please describe what happened and how it differs from what you expected to happen:

When trying to export my (non-empty) aligned feature list using the _GNPS – feature based molecular network_ method I have encountered the problem that the exported _*_quant.csv_ and _*.mgf_ files are completely empty. 

Proof that my aligned feature list does indeed hold non-zero values
![mzmine3-1](https://user-images.githubusercontent.com/93445374/158494621-e08cacbb-0f00-4785-bccb-a77cac478e5f.PNG)

The resulting *_quant.csv file. In MZmine 5.53 the resulting file would at least show a zero matrix when the aligned feature list was also empty - here, just the heading is printed
![mzmine3_3](https://user-images.githubusercontent.com/93445374/158494615-bf733a4c-cdd8-4a3e-aa85-6dbd61e083e7.PNG)

<br/>

* Please include all parameter values for the MZmine modules you used:

1. Data import from mzXML files (Raw Data Methods -> Raw Data Import -> mzXML)

2. Mass detection MS1 (Raw Data Methods -> Mass Detection -> Mass Detection)

| File  | noise level (absolute) | MS level | scan type      | mass detector | Detect isotope signals below noise level | Chemical elements | absolute tolerance | ppm tolerance |
| ----- | ---------------------- | -------- | -------------- | ------------- | ---------------------------------------- | ----------------- | ------------------ | ------------- |
| NG001 | 5846                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG002 | 507                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG003 | 211                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG004 | 1428                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG005 | 119                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG006 | 339                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG007 | 1178                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG008 | 2546                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG009 | 354                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG010 | 1834                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG011 | 122                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG012 | 1023                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG013 | 746                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG014 | 1072                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG015 | 5079                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG016 | 1825                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG017 | 687                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG018 | 915                    | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG019 | 6600                   | 1        | all scan types | centroid      | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |

3. Mass detection MS2 (Raw Data Methods -> Mass Detection -> Mass Detection)

| File  | noise level (absolute) | MS level | scan type      | Detect isotope signals below noise level | Chemical elements | absolute tolerance | ppm tolerance |
| ----- | ---------------------- | -------- | -------------- | ---------------------------------------- | ----------------- | ------------------ | ------------- |
| NG001 | 215                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG002 | 116                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG003 | 38                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG004 | 355                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG005 | 28                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG006 | 111                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG007 | 351                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG008 | 485                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG009 | 99                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG010 | 622                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG011 | 33                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG012 | 102                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG013 | 148                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG014 | 232                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG015 | 878                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG016 | 566                    | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG017 | 61                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG018 | 88                     | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |
| NG019 | 1527                   | 2        | all scan types | TRUE                                     | H,C,N,O,S         | 0.0005             | 0             |

4. Chromatogram building (Feature Detection -> LC-MS -> ADAP Chromatogram Builder)

| File  | MS level | min rt | max rt | min group size in # of scans | group intensity threshold | min highest intensity | scan to scan accuracy (m/z) | scan to scan accuracy (ppm) | suffix        |
| ----- | -------- | ------ | ------ | ---------------------------- | ------------------------- | --------------------- | --------------------------- | --------------------------- | ------------- |
| NG001 | 1        | 0      | 14     | 5                            | 31459                     | 40039                 | 0.005                       | 0                           | chromatograms |
| NG002 | 1        | 0      | 14     | 5                            | 30197                     | 38433                 | 0.005                       | 0                           | chromatograms |
| NG003 | 1        | 0      | 14     | 5                            | 30220                     | 38462                 | 0.005                       | 0                           | chromatograms |
| NG004 | 1        | 0      | 14     | 5                            | 44010                     | 56013                 | 0.005                       | 0                           | chromatograms |
| NG005 | 1        | 0      | 14     | 5                            | 28697                     | 36523                 | 0.005                       | 0                           | chromatograms |
| NG006 | 1        | 0      | 14     | 5                            | 30032                     | 38223                 | 0.005                       | 0                           | chromatograms |
| NG007 | 1        | 0      | 14     | 5                            | 41434                     | 52734                 | 0.005                       | 0                           | chromatograms |
| NG008 | 1        | 0      | 14     | 5                            | 31440                     | 40015                 | 0.005                       | 0                           | chromatograms |
| NG009 | 1        | 0      | 14     | 5                            | 30469                     | 38779                 | 0.005                       | 0                           | chromatograms |
| NG010 | 1        | 0      | 14     | 5                            | 61717                     | 78548                 | 0.005                       | 0                           | chromatograms |
| NG011 | 1        | 0      | 14     | 5                            | 29845                     | 37985                 | 0.005                       | 0                           | chromatograms |
| NG012 | 1        | 0      | 14     | 5                            | 30078                     | 38282                 | 0.005                       | 0                           | chromatograms |
| NG013 | 1        | 0      | 14     | 5                            | 31018                     | 39477                 | 0.005                       | 0                           | chromatograms |
| NG014 | 1        | 0      | 14     | 5                            | 30943                     | 39382                 | 0.005                       | 0                           | chromatograms |
| NG015 | 1        | 0      | 14     | 5                            | 48114                     | 61236                 | 0.005                       | 0                           | chromatograms |
| NG016 | 1        | 0      | 14     | 5                            | 50437                     | 64193                 | 0.005                       | 0                           | chromatograms |
| NG017 | 1        | 0      | 14     | 5                            | 31154                     | 39651                 | 0.005                       | 0                           | chromatograms |
| NG018 | 1        | 0      | 14     | 5                            | 31585                     | 40200                 | 0.005                       | 0                           | chromatograms |
| NG019 | 1        | 0      | 14     | 5                            | 33636                     | 42809                 | 0.005                       | 0                           | chromatograms |

5. Chromatogram deconvolution (Feature detection -> Chromatogram resolving -> Local Minimum Resolver)

| File  | dimension      | chromatographic theshold | min search range RT | min rel height | min abs height | min top/edge ratio | min peak duration | max peak duration | min # of data points | suffix   |
| ----- | -------------- | ------------------------ | ------------------- | -------------- | -------------- | ------------------ | ----------------- | ----------------- | -------------------- | -------- |
| NG001 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG002 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG003 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG004 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG005 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG006 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG007 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG008 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG009 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG010 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG011 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG012 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG013 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG014 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG015 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG016 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG017 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG018 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |
| NG019 | retention time | 95                       | 0.05                | 5              | 0              | 2.5                | 0                 | 14                | 5                    | resolved |

6. Deisotoping (Feature List Methods -> isotopes -> 13C isotope filter)

| File  | m/z tolerance | ppm tolerance | rt tolerance | tr tolerance unit | max charge | suffix     |
| ----- | ------------- | ------------- | ------------ | ----------------- | ---------- | ---------- |
| NG001 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG002 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG003 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG004 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG005 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG006 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG007 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG008 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG009 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG010 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG011 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG012 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG013 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG014 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG015 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG016 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG017 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG018 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |
| NG019 | 0.02          | 0             | 0.1          | min               | 2          | deisotoped |

7. Feature Alignment (Feature list methods -> Alignment -> Joint Aligner)

| m/z tolerance | m/z tolerance ppm | weight for m/z | rt tolerance | rt tolerance unit | weight for RT |
| ------------- | ----------------- | -------------- | ------------ | ----------------- | ------------- |
| 0.02          | 0                 | 75             | 0.1          | absolute (min)    | 25            |

8. Export (Feature list methods -> Export feature list -> GNPS – feature based molecular network)

| filer rows    | feature intensity | CSV export |
| ------------- | ----------------- | ---------- |
| only with MS2 | peak area         | all        |

Here again as a screenshot to make sure that all the necessary information is included. The export step includes additional parameters that were not available in MZmine 2.53. Can this be the reason for the empty files or are there other things that I will have to tweak?
![mzmine3_2](https://user-images.githubusercontent.com/93445374/158494618-7ed73c99-c164-41fd-bf46-64969ae08a6a.PNG)

<br/>

* Please upload screenshots of any errors and your log/mzmine.log file:

Screenshots as seen above. Logfile: [logfile.log](https://github.com/mzmine/mzmine3/files/8258311/logfile.log)

<br/>

* Please upload an MZmine project file that demonstrates the problem you are reporting.

will be provided if necessary

<br/>
I hope this information is sufficient to show my problem. 

Thanks a lot for your help in advance!

Best,

Niclas

**Comment by SteffenHeu** [comment]
Hello Niclas, the log file says:
`2022-03-16 01:44:04 WARNING io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnMgfExportTask export No MS/MS scans exported.`

In your reported parameters, you did not list the "MS/MS scan pairing" parameter for the local minimum resolver. This is where the MS2 scans are paired to the features.
You can do the pairing either during the resolving or afterwards via "feature list methods -> processing -> group ms2". You can apply that to the aligned feature list. 

Please let us know if the issue persists afterwards.

**Comment by niclas-gr** [comment]
Hi Steffen,

this did indeed solve my problem. Thanks a lot for the quick help.
