### ISSUE TITLE
Export feature list info (parameters) to csv

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#608]
Add export button to FeatureListSummary which is available via right click on any feature list to show past processing steps and parameters.

- [x] add export button to FeatureListSummary
- [x] Simple csv export of all steps and all parameters
- [ ] add module that takes feature list and exports the csv (can be used in batch mode)

**Comment by Tarush-Singh35** [comment]
How do I get started?

**Comment by Tarush-Singh35** [comment]
adding Module to take Feature List and export the CSV

**Comment by robinschmid** [comment]
Great that you looked at this. 
I should have added a screenshot to it. 

The ListView on the left holds all `FeatureListAppliedMethod` that were used to produce this feature list. The center shows all parameters set in the selected step. 
The idea is to loop over all `FeatureListAppliedMethod` and export all parameters in a tabular format (e.g., csv). There is no module available for this right now but it is simple to accumulate all information and just export all parameter names + values

![image](https://user-images.githubusercontent.com/10366914/159300971-348eabd4-9a32-4b26-8a77-f6b64c212e19.png)

**Comment by Tarush-Singh35** [comment]
![CSV_DATA_1](https://user-images.githubusercontent.com/86368099/159540216-c49f5304-c1b2-497e-ae2f-eacac30e0cb1.png)
[Export.csv](https://github.com/mzmine/mzmine3/files/8326585/Export.csv)
[Export.txt](https://github.com/mzmine/mzmine3/files/8326586/Export.txt)

**Comment by Tarush-Singh35** [comment]
can you please confirm the it has all the Required Data
[Export.txt](https://github.com/mzmine/mzmine3/files/8327102/Export.txt)
l

**Comment by Tarush-Singh35** [comment]
[Export.csv](https://github.com/mzmine/mzmine3/files/8329694/Export.csv)
here is the CSV file please check if all the required data are present and right

**Comment by SteffenHeu** [comment]
We were thinking about parsing it in a tab separated format like this:

Module name
--Parameter--parameterValue

since a full parameter set can also be a parameter (see interface EmbeddedParameterSet which is implemented by those), there should be multiple levels of indentation. You should be able to do this by using the `parameterToString`
 method in the FeatureListSummaryController and adding a function argument where the indentation can be passed to, since the method is called recursively.
An excel export is not necessary, csv (with tab separators - so techically a tsv) should be enough.

**Comment by Tarush-Singh35** [comment]
okay I will make the changes

**Comment by Tarush-Singh35** [comment]
for (FeatureListAppliedMethod item : lvAppliedMethods.getItems()) {
        String des=item.getDescription().replaceAll("\\s", "");
        String par =item.getParameters().toString().replaceAll("[,:]",";");
        String fpar=par.replaceAll("\\s", "");
        if(item.getParameters() instanceof Parameter<?> parameter) {
          String Spar = parameterToString(parameter);
          pw.println(des + ";" + Spar);
        }
        else {
          pw.println(des + ";" + fpar);
        }
      }
[Export.csv](https://github.com/mzmine/mzmine3/files/8349773/Export.csv)
this is the code structure and file are they correct @robinschmid @SteffenHeu

**Comment by robinschmid** [comment]
Looks great so far. 
Can you create a PR and link it to this issue. 
I will review your code then. 

Thanks Tarush

**Comment by Tarush-Singh35** [comment]
hey @robinschmid can you tell me reference for this 
[Export.csv](https://github.com/mzmine/mzmine3/files/8351226/Export.csv)

**Comment by Tarush-Singh35** [comment]
for (FeatureListAppliedMethod item : lvAppliedMethods.getItems()) {
        //String par =item.getParameters().toString().replaceAll("[,]","\n");
        StringBuilder sb = new StringBuilder(item.getDescription());
        sb.append(":\t\n");
        pw.println(sb);
        ParameterSet parameterSet = item.getParameters();
        for (Parameter<?> parameter : parameterSet.getParameters())
        {
          pw.println(parameterToString(parameter));
        }
      }
@robinschmid @SteffenHeu i have used ParameterToString over here but the File Names and Spectral Density passed Over here are Addresses
[Export.csv](https://github.com/mzmine/mzmine3/files/8352016/Export.csv)
[eXPORT.txt](https://github.com/mzmine/mzmine3/files/8352032/eXPORT.txt)

should i make a PR to get it reviewed ?

**Comment by robinschmid** [comment]
The export format is great. See my comments in the PR.

I also gave an option how to solve the toString method.
Just add a check if the value is an array.

**Comment by SteffenHeu** [comment]
> The export format is great. See my comments in the PR.
> 
> I also gave an option how to solve the toString method. Just add a check if the value is an array.

that will be solved when the latest master is merged. it is already implemented there....

**Comment by Tarush-Singh35** [comment]
> The export format is great. See my comments in the PR.
> 
> I also gave an option how to solve the toString method.
> Just add a check if the value is an array. 

Should I make the changes or just merge and then go ahead?

**Comment by robinschmid** [comment]
I think as steffen said. Just merge the master and it should be fine

**Comment by Tarush-Singh35** [comment]
@robinschmid how do i get started for the 3rd point

**Comment by Tarush-Singh35** [comment]
okay I will look into this
