### ISSUE TITLE
Issue with BASELINE RESOLVER - 3.0.11-beta version

### ISSUE THREAD

**Issue by Giovanni911** [mzmine/mzmine3#612]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.0.11-beta

### What happened
Dear developers,
I am trying to reproduce a job I already performed on the old version MZmine 2.53, I started from Thermo raw data and I adopted the same parameters for mass detection and ADAP chromatogram builder, when it came to the deconvolution I tried to use the "baseline resolver" algorithm which I think is the equivalent of "baseline cut-off" in the 2.53 version, in fact, I put the same parameters, but this time I got this error for each feature list.

![error ResolvedPeak java 105](https://user-images.githubusercontent.com/72611833/159122637-26a85191-bdc7-431e-9ce6-443482621272.png)

Could you give an explanation for this?

Parameters
-mass detention: MS1 noise level: 10000, MS2 noise level 100
-ADAP chrom builder: Scans MSlevel 1, Min group size n of scans: 3, group intensity: 10000, min intensity:10000, scan accuracy 20 ppm
-Baseline resolver: MS/MS scan pairing (RT toll:0.3, MS1MS2 toll: 5ppm), Min peak height: 10000, peak duration 0-2 min, Baseline level:10000 ---  ERROR ---

Thank you in advance,
Giovanni

**Comment by robinschmid** [comment]
Could you share the raw data file? And maybe your parameters as a batch processing file?

Did you check if the chromatograms list contains features?

Best,
Robin

**Comment by Giovanni911** [comment]
Yes, I checked and they contain some features, please find attached the wetransfer link containing all the requested files.
https://we.tl/t-nRoBJ7jZ9P

Thank you in advance Robin,
Best,
Giovanni

**Comment by SteffenHeu** [comment]
You can check out the latest development build here: 
https://github.com/mzmine/mzmine3/releases

If the issue persits or you find any other problems, you can open a new issue.

Thanks for the report!

**Comment by Giovanni911** [comment]
I apologize I am not a developer, now if I download the
MZmine_Linux_portable.zip
<https://github.com/mzmine/mzmine3/releases/download/Development-release/MZmine_Linux_portable.zip>
version,
this error should be fixed?
Thank you again.

Giovanni

Il giorno ven 25 mar 2022 alle ore 13:48 Steffen Heuckeroth <
***@***.***> ha scritto:

**Comment by Giovanni911** [comment]
I shared them through the WeTransfer link, were you able to download them?

Il lun 21 mar 2022, 12:58 Robin Schmid ***@***.***> ha
scritto:
