### ISSUE TITLE
[Bug] Ion Identity fields are not kept in negative mode

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#615]
### Basic information

* My operating system: MacOS 12.3
* My MZmine version: 3.0.11-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

When I run IIN steps in negative mode, while the step is running I can see I have results but these are deleted when the step is over. (see screenshots below)
(log shows some were detected but they are somehow erased when step finishes)

Very strangely, I do not observe the same behavior with positive mode 😐 ❓ 

* Please include all parameter values for the MZmine modules you used. 

[diagnostic_neg.xml.zip](https://github.com/mzmine/mzmine3/files/8316021/diagnostic_neg.xml.zip)
[211217_QC1.mzML.gz](https://github.com/mzmine/mzmine3/files/8316034/211217_QC1.mzML.gz)

* Please upload screenshots of any errors and your log/mzmine.log file.

<img width="1383" alt="Capture d’écran 2022-03-21 à 15 01 38" src="https://user-images.githubusercontent.com/44283913/159278418-018bf7b2-03dc-4273-af4f-c44a14da2eff.png">
<img width="1387" alt="Capture d’écran 2022-03-21 à 15 01 58" src="https://user-images.githubusercontent.com/44283913/159278450-2ae5efae-fea4-48a9-bc21-87bf758d6a3b.png">

[log.log](https://github.com/mzmine/mzmine3/files/8316046/log.log)

* Please upload an MZmine project file that demonstrates the problem you are reporting.

Later if needed

**Comment by robinschmid** [comment]
Yeah its a bug that needs fixing. Will push a fix now. 
You have to disable the "delete without major" 
![image](https://user-images.githubusercontent.com/10366914/159289496-228d19c3-bfa6-4ecb-9db1-4d644d56330e.png)
This option seems broken

**Comment by Adafede** [comment]
Yup, this is what I am doing in positive mode with 3 different rounds + refinements, it was just a quick&dirty example to illustrate in neg, thank you a lot!

**Comment by robinschmid** [comment]
IIN expert
