### ISSUE TITLE
Error when running Linear normalizer

### ISSUE THREAD

**Issue by roland-berdaguer** [mzmine/mzmine3#617]
### Basic information

* My operating system: Windows 10 Enterprise
* My MZmine version: MZmine 3.0.11-beta (portable)

### What happened

* Please describe what happened and how it differs from what you expected to happen.

I tried using the "Linear normalizer" module in MZmine 3 but am getting the following error message:

![Schermopname (242)](https://user-images.githubusercontent.com/29729874/159328997-952e7d08-1292-4735-8c91-e0b18afabd9d.png)

This happens both when applying the Linear normalizer to the aligned feature list aswell as to individual feature lists.
In MZmine 2.53, the same module works for me, with the same settings.

* Please include all parameter values for the MZmine modules you used. 

First I ran the following batch queue: [pilot_positive_batch.zip](https://github.com/mzmine/mzmine3/files/8317968/pilot_positive_batch.zip)  (zipped because I could not upload xml directly)

Then I ran the Linear normalizer (Feature list methods > Normalization > Linear normalizer), with the following parameters:

![Schermopname (243)](https://user-images.githubusercontent.com/29729874/159329284-f686c524-c933-45d6-b303-77682dd8b7cb.png)

* Please upload screenshots of any errors and your log/mzmine.log file.
Error message: see above.
Log file:  [mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8318083/mzmine_0_0.log)

* Please upload an MZmine project file that demonstrates the problem you are reporting.
Please let me know if this is needed.

**Comment by SteffenHeu** [comment]
Thanks for the report, ill look into it.

**Comment by SteffenHeu** [comment]
You can check out the latest development build here: https://github.com/mzmine/mzmine3/releases/tag/Development-release

The issue should befixed. If it persists, please open a new issue.

**Comment by roland-berdaguer** [comment]
Indeed it works now. Thanks a lot for fixing it so quickly!
