### ISSUE TITLE
[Bug] mztab-m export not working

### ISSUE THREAD

**Issue by Adafede** [mzmine/mzmine3#620]
### Basic information

* My operating system: MacOS 12.3
* My MZmine version: 3.0.11-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.

I wanted to export my feature list as mztab-m file and it errored.

* Please include all parameter values for the MZmine modules you used. 

None

* Please upload screenshots of any errors and your log/mzmine.log file.

```
2022-03-23 11:11:08 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Error of task Exporting feature list(s) [Aligned feature list 13C gaps dup] to MzTab-m file(s): Could not export feature list to file /Users/rutza/Downloads/temp/test.mzTab: Cannot invoke "String.getBytes()" because the return value of "uk.ac.ebi.pride.jmztab2.utils.errors.MZTabErrorOverflowException.getMessage()" is null
```

* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by nilshoffmann** [comment]
@Adafede Could you please attach an exported MZmine project file to help narrow down the issue? This does not need to include all of your data, a subset that still triggers the error should suffice. Also, if the log contains a stack trace, i.e. more details on the origin of the error, please include it here, that would greatly help.

Thanks!
Nils

**Comment by Adafede** [comment]
@nilshoffmann 

Here:

[220324_mztab-m-error.mzmine.zip](https://github.com/mzmine/mzmine3/files/8343408/220324_mztab-m-error.mzmine.zip)

[mzmine_0_0.log.zip](https://github.com/mzmine/mzmine3/files/8343449/mzmine_0_0.log.zip)

Hope it will help!

**Comment by nilshoffmann** [comment]
Thanks for providing the project file. The mzTab-M export module currently expects DB identified / annotated metabolites / features. It currently does not support results from IonIdentityNetworking. I am currently working on improving the code and integrating different levels of reporting of results.

**Comment by meowcat** [comment]
Seconded this. For example, in our case, e.g. for quality evaluation downstream, we are interested mostly in the SML and SMF tables for all features (annotated or not). Anything we can do to support this?

**Comment by titodamiani** [comment]
Hi, 
@omokshyna has been working on it (#1043). I'll close this for now. Feel free to-reopen it if needed:)
