### ISSUE TITLE
Statistical Analysis

### ISSUE THREAD

**Issue by markokkini** [mzmine/mzmine3#627]
MZmine 3.0.11-beta

I cannot find the Data Analysis section that was in Feature List Methods in MZmine 2 that allowed you to do PCA, Heat map plot etc. 
Is it gone in MZmine 3?

**Comment by SteffenHeu** [comment]
Hi markokkini,

yes they have been disabled because they were not updated yet. 

Feel free to contribute if you like! :)

**Comment by robinschmid** [comment]
They were not really maintained and needed updating.
It would be great if someone would join to add more interactive statistical analysis in MZmine.

What modules did you use from MZmine 2?

**Comment by markokkini** [comment]
I was mostly using PCA and Heat map plot. What was missing from MZmine 2 was the scree plot to be able to see the contributions of each principal component when generating the PCA plot.

I would like to help but I only have knowledge as a user :)

**Comment by robinschmid** [comment]
In case you ever find some students who are interested to help, feel free to direct them to this GitHub, and we also have a Slack
