### ISSUE TITLE
Add date and time of data collection to RawDataFile

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#630]
Read date and time from raw data files and provide this information through the metadata
Maybe use LocalDateTime?
https://www.baeldung.com/java-8-date-time-intro

- [ ] mzML (xml element is maybe startTimeStamp)
- [ ] mzXML
- [ ] .d
- [ ] .tdf
- [ ] thermo raw --> uses mzML

Needs #633 to fix project save

Project/Set sample parameters
![image](https://user-images.githubusercontent.com/10366914/160572762-e42467b6-3e96-4f98-bd96-a7ff0f7c91c1.png)

**Comment by nikhilgotpagar** [comment]
I want to work on this issue  ! Please assign me this

**Comment by Mohamadi98** [comment]
Hello, if no one is working on this issue currently, I would like to try and work on it. I've already set up MZmine locally using this guide https://mzmine.github.io/mzmine_documentation/contribute_intellij.html, and the project is working fine. 
It seems like date-time was already added to `RawDataFile` in this issue #696. 
If I'm understanding the codebase correctly, to complete this issue a method should be implemented in src/main/java/io/github/mzmine/modules/io/projectsave/RawDataFileSaveHandler.java that gets the date-time information, please correct me if I'm wrong.
