### ISSUE TITLE
Write and read sample parameters (metadata) as tsv (use in project save)

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#633]
@SteffenHeu reported an issue to save projects with sample parameters. 

- [ ] Save the sample parameters to a tab-separated file (.tsv)
- [ ] Read from .tsv

Sample parameters are set in: **Menu/Project/Set sample parameters**  dialog

**Comment by harshlancer** [comment]
Hey, @robinschmid it's Harsh again, I'm a little confused about the Menu that you are mentioning above, can you please guide me on where to check for the menu?
