### ISSUE TITLE
MSn in scan filter parameters

### ISSUE THREAD

**Issue by corinnabrungs** [mzmine/mzmine3#634]
Currently it is only possible to select one MS level. 
Maybe add an operator to the MS level to choose between = <= >= ...
Or allow ranges, 2-100 feels weird for MSn data

![image](https://user-images.githubusercontent.com/53823597/160607729-af981949-4255-4a42-8c26-1392f4c6c871.png)

**Comment by robinschmid** [comment]
The best way would be to add a new parameter that is similar to the `io.github.mzmine.parameters.parametertypes.OptionalParameter<>` class. This class wraps any other Parameter and adds a CheckBox to the component of the parameter (e.g., a CheckBox and a TextField when combined with an IntegerParameter).

The new class could work similarly, combining a ComboBox<EqualitySign> with the TextBox of an IntegerParameter.

### What is needed:
**enum EqualitySign**: 
- < ≤ = ≥ > ≠  (override toString with symbols)
- boolean accept(int selectedValue, int testValue) { check if tested value matches relationship to selectedValue, e.g., testedValue>selectedValue }

**ConditionalIntegerParameter:**
- copy OptionalParameter or IntegerParameter for basic structure
- [ ] use ComboBox<EqualitySign> in front of TextBox from IntegerParameter
- [ ] add the EqualitySign to the parameter save/load; e.g., use EqualitySign.GREATER.name() for save and EqualitySign.valueOf(name) to load.

**Replace the usage in ScanSelectionComponent:**:
- io.github.mzmine.parameters.parametertypes.selectors.ScanSelectionComponent

### One usage is 
![image](https://user-images.githubusercontent.com/10366914/161383944-c13c73ae-ef91-4890-817c-26cdac5a7802.png)

**Comment by robinschmid** [comment]
Some implementation ideas: 

```java
enum EqualitySign {
    GREATER, GREATER_EQUAL, EQUAL, ....;
    public String toString() { 
        return switch(this) { case EQUAL -> "="; case .... 
    }
}
```

```java
record ConditionalInteger(int value, EqualitySign comparator) {
    public boolean acceptValue(int testValue) {
        return switch(comparator) {
            case EQUAL -> value == testValue;
            case .... 
};}}
```

The actual parameter will then hold the value as a ConditionalInteger. And the component will give controls to set the value and comparator.
```java
public class ConditionalIntegerParameter implements UserParameter<ConditionalInteger, ConditionalIntegerComponent> {
  private IntegerParameter embeddedParameter;
  ....
```

**Comment by itsAfnanAlam** [comment]
Hi, can I work on this?

**Comment by robinschmid** [comment]
Found a new way to do this and is finished
