### ISSUE TITLE
Modular data Structure

### ISSUE THREAD

**Issue by SteffenHeu** [mzmine/mzmine3#64]
Hey guys,

this is supposed to be a discussion issue on the new modular data structure model.

Some stuff i noticed while working on it:

1. https://github.com/SteffenHeu/mzmine3/blob/4819a7fa401d742e61b3eab75c61208ab58cd39d/src/main/java/io/github/mzmine/datamodel/data/ModularFeatureListRow.java#L178
I think this will be misleading, because not every row necessarily contains a feature in every raw data file in an aligned feature list. 
Additionally, I think to access all raw data files in a ModularFeatureListRow via the map returned by this https://github.com/SteffenHeu/mzmine3/blob/4819a7fa401d742e61b3eab75c61208ab58cd39d/src/main/java/io/github/mzmine/datamodel/data/ModularFeatureListRow.java#L148 is too complicated.
Thus, I would say it could be a good idea to add a RawDataFilesType which stores the raw data files in a list. Suggestion: https://github.com/SteffenHeu/mzmine3/blob/47187d2d8bb5b060118f136d2486bbddd22e7878/src/main/java/io/github/mzmine/datamodel/data/types/RawFilesType.java

2. Currently there is no DataType for the "best feature". Suggestion: https://github.com/SteffenHeu/mzmine3/blob/47187d2d8bb5b060118f136d2486bbddd22e7878/src/main/java/io/github/mzmine/datamodel/data/types/BestFeatureType.java

(There is probably more to come)

I will not be able to add everything discussed here myself, this is just meant as a discussion thread, so everyone who joins the work on the data model can leave some thoughts! :)

**Comment by robinschmid** [comment]
We should definitely talk about it. This is not the final structure, so we can still change many things.

### General Note:
- We want to use Properties to easily bind the data model to the JavaFX
- To generate the cells in the feature table, every row relates to the same list of columns (DataTypes)
- First we create a new ModularFeatureList and define all columns

1. You could basically add a filter to the method to return all raw files for detected features.
2. We only implemented some of the DataTypes. We could definitely have the "best feature". With the new data model you can add any new data types or statistics to features and rows.

**Comment by SteffenHeu** [comment]
1. I'm not exactly sure what you mean by that.

Just to add one thing @robinschmid explained to me on the data model, that might be useful to know for any collaborators:
- DataType and it's extending classes are designed to behave like singletons. What that means is:
```
RTType a, b;
row.get(a) == row.get(b); // true
a.equals(b); // true
```

**Comment by SteffenHeu** [comment]
@tomas-pluskal / @robinschmid what would you consider the best way to make the columns in the new feature table distinguishable so we can specifically show/hide them? We could extend TreeTableColumn to store the datatype and raw/feature type it displays or use the property map and just put some properties in there. 

The first option would make the information easy and more convenient to access, I think, as we would not have to introduce two new properties.

**Comment by SteffenHeu** [comment]
I will close this one and open a new issue with to-dos
