### ISSUE TITLE
Restructure the metadata (sample parameters) 

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#644]
Simplify the metadata table with only three main data types.

```
class MetaDataColumn<T> for (String, Double, Date)

// column -> raw file -> value
Map<MetaDataColumn<T>, Map<RawDataFile, T/Object>>

// or raw file -> column -> value
Map<RawDataFile, Map<MetaDataColumn<T>, T/Object>> 
```

- [x] three data types: String, double, Date
- [x] replace the data structure in MZmineProject (everything with UserParameter)
- [x] use the dialog to add new columns and set values in the TableView
- [ ] Import/Export to csv / tsv (tab-separated) (header, types, values)

**Comment by InspiritedCoder** [comment]
I've started working on this issue

**Comment by Tarush-Singh35** [comment]
@InspiritedCoder i would like to help you out tell me how can I get started

**Comment by InspiritedCoder** [comment]
> @InspiritedCoder i would like to help you out tell me how can I get started

@Tarush-Singh35 Thank you for your willingness to help. As far as I understand, it is necessary to implement some "generalized" class through which we will perform basic operations with the project metadata (parameters) table. If you want, we can discuss a possible solution as soon as I come up with one. :)

**Comment by robinschmid** [comment]
Its good if you propose a structure and create a PR once you are ready to show. 
Then we can discuss more together. @Tarush-Singh35, best way would be to then review the code and we can improve it together.
