### ISSUE TITLE
Gap filling doesn't seems to work Java "OutOfBoundsException" error

### ISSUE THREAD

**Issue by froz9** [mzmine/mzmine3#648]
### Basic information

* My operating system: Windows 10 Home Version 21H1
* My MZmine version: 3.0.21 beta
* My CPU: Intel Core i7-9700K
* RAM: 32 GB at 3200 MHz

### What happened
First I had problems with RANSAC alignment module. I uninstalled and install it again. When RANSAC it's completed, I tried to perform a GAP Filling but I always get this error message: 

"Unhandled exception in task Gap filling RANSAC using RT and m/z range: java.lang.IndexOutOfBoundsException (NativeConstructorAccessorImpl.java:-2)

And anything happens after that.

MMZmine parameters for Gap Filling:
![Parameters](https://user-images.githubusercontent.com/73253478/161448250-2e28b95f-607a-45a9-9871-8e2e616a247d.PNG)

Error screenshot:
![Error](https://user-images.githubusercontent.com/73253478/161448304-c6d4cec1-9e43-4fbf-bca1-de129a73bd79.PNG)

Thank you in advance for your help and support.

**Comment by SteffenHeu** [comment]
Thanks for the report, documented the error in another issue.

**Comment by robinschmid** [comment]
Seemed to not be in the tested functions.
I would also recommend the peak finder, which is a bit more advanced but should also perform better.

**Comment by froz9** [comment]
> Seemed to not be in the tested functions. I would also recommend the peak finder, which is a bit more advanced but should also perform better.

I would try peak finder. Thank you so much
