### ISSUE TITLE
Error in the exported CSV quantification table which is incompatible with GNPS workflow

### ISSUE THREAD

**Issue by Giovanni911** [mzmine/mzmine3#653]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.0.21

### What happened
I run classical data analysis on Mzmine with Thermo raw files, mass detection 1 and 2, ADAP chrom builder, Baseline resolver, 13C isotope filter, alignment, and filter to keep only filter with MS2. Everything seems to be good since I check the list and I have features all with MS2. I export with GNPS-FBMN module and when I tried to select once CSV export = Simple and the second time to get a comprehensive quantification table.

When submitted to GNPS:
the job with the simple CSV table was DONE
the one with the comprehensive CSV table FAILED with this
"KeyError: 'row ID'
Tool execution terminates abnormally with exit code [1]
In fact, the simple table has raw ID as the first column, and the comprehensive only has ID. I manually correct it and run it again
and I got the same error but with the second column
![image](https://user-images.githubusercontent.com/72611833/161643971-a2351188-0ab1-423c-8210-abc9960ca6ca.png)

I can furnish the data if it is needed of course.
Bests,
Giovanni

**Comment by SteffenHeu** [comment]
The "full" table is there for future versions of GNPS which will support it. However, this is not the case currently, so you have to use the simple table. You can import the full table to cytoscape afterward.

**Comment by Giovanni911** [comment]
Thank you Steffen
