### ISSUE TITLE
Changing heap size

### ISSUE THREAD

**Issue by EmNZ** [mzmine/mzmine3#657]
### Basic information

* My operating system: Windows 10 Enterprise
* My MZmine version: 3.0.21-beta

### What happened

Hello, I am familiar with MZmine 2 and how to change the heap size in the .bat file, but MZmine 3 is a .exe file which I cannot edit and therefore cannot change the heap size. My .cdf files are very big and the GUI often freezes when I try and do anything once the files have been uploaded. I would like to allocate more memory to MZmine, how do I do that without being able to edit the startup script? Thanks for your help.

**Comment by robinschmid** [comment]
Welcome,
The heap size is set to the default recommendations with a maximum at around 80÷. Due to the way java works, mzmine might even use more than this as a maximum. At least for native functions. 

As far as I know, the only way to set the memory is to change it and compile a new version. 

A few questions.
1. What technique are you using? LC HRMS? 
2. Why cdf and not mzml?
3. Is the spectral data centroided? Or are you using profile mode data?

**Comment by SteffenHeu** [comment]
Hi EmNZ, i want to add some further questions to Robin's:
4. On which particular actions does the GUI freeze? When displaying a chromatogram from the raw data or when openign a feature table.

We have the performance options in MZmine 3, you can find the documentation here: https://mzmine.github.io/mzmine_documentation/performance.html#argument-table The raw data and the features in MZmine are stored in so-called "off-heap memory", usually on the disc. We recommend using an SSD as temporary file space for MZmine, to reduce the time MZmine needs to look up the raw data or the feature data. The documentation of how to change that directory is also listed on the page. If you want, you can prevent MZmine from storign the data on disc and keep everything in memory instead. (see the argument table). However, this will require quite a lot of memory.

**Comment by EmNZ** [comment]
Thank you for your response Robin.

If the default is 80% then adjusting the heap size won’t do much I suppose. In response to your questions (and the one from Steffen):


1.       I am wanting to analyse GC TOF MS data (not HR).

2.       The vendor software outputs cdf files and proteowizard cannot convert cdf files to other formats, though I have just checked and the vendor software can export to mzml. I will do that and try again.

3.       As the spectral data are EI and not HR it should be the equivalent of centroided.

4.       The action the GUI freezes at is when I click on the chromatogram from the raw data to see the spectral data.

5.       I do not have an SSD, I will get one and do the actions you suggest Steffen.

Thanks for the help.

**Comment by robinschmid** [comment]
mzML will definitely be better.
Generally, TOF-MS is considered high resolution MS. 

Any instrument can give you profile mode spectral data which just hast multiple data points per signal or already processed - centroided data
