### ISSUE TITLE
gridmass error NullPointerException

### ISSUE THREAD

**Issue by GeertNL** [mzmine/mzmine3#660]
### Basic information

* My operating system: Windows10Home
* My MZmine version: 3..0.21

### What happened

* Please describe what happened and how it differs from what you expected to happen.
i use gridmass to detect features but at 80%-90% of processing it displays an error (see below). I tried different settings, including default, no different results.
previously, Using 2.53 version of mzmine2 it worked normally and i get results

* Please include all parameter values for the MZmine modules you used. 
I uploaded raw files thermo files, cropped only positive masses
for this bug just consider default settings of gridmass

* Please upload screenshots of any errors and your log/mzmine.log file.
2022-04-08 14:03:12 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Unhandled exception java.lang.NullPointerException: Feature list of the sameRangePeak is null. while processing task Detecting chromatograms (RT) in ACE1A.raw
java.lang.NullPointerException: Feature list of the sameRangePeak is null.

* Please upload an MZmine project file that demonstrates the problem you are reporting.
[MZmine error.txt](https://github.com/mzmine/mzmine3/files/8453792/MZmine.error.txt)

**Comment by SteffenHeu** [comment]
Hi Geert, 

thanks for the report. 
In fact we noticed the same issue as well. Unfortunately, we lack the insight to the gridmass algorithm to maintain it, which is why we deactivated it for the next relase. For the time being, we recommend the ADAP chromatogram builder.

You can check out our new docs to see how it works: https://mzmine.github.io/mzmine_documentation/workflows/lcmsworkflow/lcms-workflow.html

**Comment by robinschmid** [comment]
Hi Geert,
We have never seen many people use the gridmass algorithm. Maybe also because it was using a lot of memory.
Was this your usual workflow? Was gridmass outperforming the ADAP chromatogram builder + any resolver workflow (previously deconvolution)?

**Comment by SteffenHeu** [comment]
Hey Geert, 

thanks for offering your help. The null pointer exception was an easy fix, but the resulting features are weird. you can try to download the build from this pull request (#664) here: https://github.com/mzmine/mzmine3/runs/5980397673?check_suite_focus=true

Please let me know if your features also dont look as you would expect.
