### ISSUE TITLE
[M-H]- mass from formula calculated as if it was [M+H]+

### ISSUE THREAD

**Issue by dcf1007** [mzmine/mzmine3#683]
### Basic information

* My operating system: Windows 10 64-bit [Version 10.0.19044.1645]
* My MZmine version: MZmine 3.0.21-beta. Installed from the msi package

java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

No R installed in the system.

### What happened

In the chromatogram plot parameters window, when selecting m/z from formula and choosing the option [M-H]-, the calculated mass is the one for [M+H]+

[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8614306/mzmine_0_0.log)
![mzmine](https://user-images.githubusercontent.com/29199263/166566292-2d158458-e798-44ac-8811-8bc90970cb73.png)

**Comment by SteffenHeu** [comment]
Thanks for the report, will be fixed in the next release.
