### ISSUE TITLE
Export leads to empty files

### ISSUE THREAD

**Issue by mmzdouc** [mzmine/mzmine3#687]
### Basic information

* My operating system: Ubuntu 20.04
* My MZmine version: MzMine 3.0.21-beta

Dear developers,
I noticed that in the newest version of MzMine3,  the FBMN-GNPS export function exports only blank tables. When I fell back to  3.0.11-beta, the export worked out normally. I guess that there is a bug in the current release version.

Please find the batch-file and  the logs attached (had to add a .txt suffix to be able to upload to github - change if necesary).
[mzmine_0_0.log.txt](https://github.com/mzmine/mzmine3/files/8649390/mzmine_0_0.log.txt)
[testbatch.xml.txt](https://github.com/mzmine/mzmine3/files/8649391/testbatch.xml.txt)

Kind regards, 

Mitja Zdouc

**Comment by SteffenHeu** [comment]
Hi Mitja,

you don't have the MS/MS scan pairing enabled in the baseline resolver step. You can run it there or afterwards via feature list methods -> processing -> ms/ms scan pairing
