### ISSUE TITLE
Local compound database search not working

### ISSUE THREAD

**Issue by vanrub** [mzmine/mzmine3#690]
My operating system: Windows 10 Enterprise
My MZmine version: 3.0.21-beta

I am testing some samples using the processing wizard.  At the end, I have a feature list and tried to run the local compound database search, but there don't seem to be any annotations and no errors generated.  Below are the settings for attaching the database file.  I'm running this using a test file just to get it to work since using MZmine 2 (test database file attached).
[MZmine3_test.csv](https://github.com/mzmine/mzmine3/files/8664327/MZmine3_test.csv)

![image](https://user-images.githubusercontent.com/105315344/167703397-c1fa0e56-3183-495d-812e-d0b18bbe4e24.png)

This is the log record, so I know that there is a problem but not sure what it means:

![image](https://user-images.githubusercontent.com/105315344/167704044-d494d94e-8f1a-422b-9df4-1882ba10070d.png)

Any help is appreciated.

**Comment by SteffenHeu** [comment]
Hi @vanrub , thank you for reporting the issue. 
Can you please post the full log file? Also, an example data file (and maybe the batch file) would be great so we can reproduce the error.

Thanks!

**Comment by vanrub** [comment]
@SteffenHeu below are the batch file attempted plus the wizard settings used with the same result and one of the files used for this testing.
[MZmine3_pos.zip](https://github.com/mzmine/mzmine3/files/8670025/MZmine3_pos.zip)

The other batch settings.  The data files have been removed but they were included for testing.
![image](https://user-images.githubusercontent.com/105315344/167853977-79071e5b-c81b-4d98-a660-f33c6b099c96.png)

The complete log of all of the work done for this testing.  If this is too cumbersome, I can redo without the additional processes for simplicity. 
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/8670042/mzmine_0_0.log)

**Comment by SteffenHeu** [comment]
Closed due to inactivity. Please reopen this issue if the problem persists
