### ISSUE TITLE
How runned MZmine3 on computer cluster ?

### ISSUE THREAD

**Issue by 2AMissinou** [mzmine/mzmine3#697]
### Basic information

Thank you to all developers for these optimizations. 

I have previously run mzMine2on computer cluster, just running ./startMZmine_Linux.sh followed by batch file.

Now, I How to use mzMine3.0.21-beta Linux version batch mode under computer cluster for large sample panel analysis? I have already optimized my parameters on small subsets of data. 

* My operating system: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz  2.21 GHz, 16.0 GB (15.8 GB usable)
* My MZmine version: MZmine3.0.21-beta

### What happened
I have no idea how to install it on a cluster of computers, knowing that I am not an administrator of this computer cluster (just a user). Please do you have any directions/advice/tricks, on how to install it and how to run it?

Thank you

**Comment by robinschmid** [comment]
Hey great that you are running MZmine 3. More memory is always nice... But you should be able to run a couple of hundred samples on your machine. 

There is a small part in the documentation that might need to be updated. But here is an example how to set the temp folder and run a batch file

``` 
"C:\Program Files\MZmine\MZmine.exe" -batch "D:\batch\my_batch_file.xml" -memory none -temp "D:\tmpmzmine"
```
