### ISSUE TITLE
How to upload imaging data?

### ISSUE THREAD

**Issue by troyrsufl** [mzmine/mzmine3#698]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.0.21-beta

### What happened

I am a beginner to this but I cannot figure out how to import imaging data. Any help is appreciated. I use ftms processing and flex imaging (Bruker) to typically work up data.

**Comment by robinschmid** [comment]
What instrument and Fileformat are you working with?

Mzmine supports the timsTOF native format and imzML for non ims data.

Cheers
Robin

**Comment by troyrsufl** [comment]
I use a solarix FTICR and the file format and can export as imzML

**Comment by SteffenHeu** [comment]
Hey, What is the issue with the imzml import?

**Comment by troyrsufl** [comment]
I have solved it. Thank You
