### ISSUE TITLE
can't open project annotation what happens is Error : "Unhandled exception java.lang.ArrayIndexOutOfBoundsException." Please help me

### ISSUE THREAD

**Issue by Idrpermana** [mzmine/mzmine3#699]
### Basic information

* My operating system: x64-bit Operating system' Windows 10 x64 proceessor
* My MZmine version: MZmine_Windows_Installer_3.0.21-beta

### What happened

* can't open project annotation what happens is Error : "Unhandled exception java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0 (ImmutableCollections.java:680)." Please help me this is the first time i use mzmine for college assignment 
![Screenshot_15](https://user-images.githubusercontent.com/106264451/170312952-ab739828-d6ee-47ae-84d7-da948c4adb02.png)

**Comment by SteffenHeu** [comment]
Hello Idrpermana, 
please upload the log file and an example project so we can reproduce the error. For that, it's best to save the project as a standalone project for that, so we can open it.
