### ISSUE TITLE
[Save project] "Failed saving the project"

### ISSUE THREAD

**Issue by jyoungheun** [mzmine/mzmine3#715]
### Basic information

* My operating system: Window 10 pro, 64-bit
* My MZmine version: 3.0.21-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

After processing the data, the error happens when I try to save the project in both 'Standalone' type and 'Referencing' type cases.
The error window is attached.

![MZmine error](https://user-images.githubusercontent.com/106862432/171990109-81b6243b-8d7f-4bc0-ade1-96698e038cd8.png)

**Comment by robinschmid** [comment]
Thanks for reporting this bug. I might know how to fix this bug but it would be great if you could provide  more details on how you processed your data.

Did you add metadata (sample parameters) to the project?
We are still remodelling this function.

**Comment by jyoungheun** [comment]
> 

Hello, robinschmid.
I did set sample parameters for the project (sample type). There was no problem when exporting the data as a metaboanalyst or GNPS (FBMN) format but the error only occurs when I try to save the project.
I will attach the parameter values for the MZmine module I used for this batch.
Hope this problem can be solved as soon as possible as a potential frequent MZmine 3 researcher:)
Thank you.

![MZmine_1](https://user-images.githubusercontent.com/106862432/172166412-43fa6459-1f44-480e-8ddd-d9dac8e7ab32.png)
![MZmine_2](https://user-images.githubusercontent.com/106862432/172166419-cafcd496-9a9f-4313-9f0a-8017dc5bf542.png)
![MZmine_3](https://user-images.githubusercontent.com/106862432/172166422-9d34bd22-6678-4961-a065-d3caecd6d427.png)
![MZmine_4](https://user-images.githubusercontent.com/106862432/172166425-2c94f369-14f8-444e-9aee-ab52e3031e3d.png)
![MZmine_5](https://user-images.githubusercontent.com/106862432/172166428-6d1cffe2-0160-4742-a541-d32e17072e9d.png)
![MZmine_6](https://user-images.githubusercontent.com/106862432/172166430-cdd22e50-adfe-46fd-b275-e9a85a5d978b.png)
![MZmine_7](https://user-images.githubusercontent.com/106862432/172166431-09391a46-c590-4c9e-af4c-484a896b725c.png)
![MZmine_8](https://user-images.githubusercontent.com/106862432/172166432-de961e72-b77f-416c-a076-de472afda337.png)

**Comment by robinschmid** [comment]
This might be a problem with the sample parameters because we are currently remodeling the integration of user metadata. 
I will post here as soon as this is fone

**Comment by robinschmid** [comment]
The gridmass issue might be solved now. Could you try again with the latest development build? >=3.1.4
