### ISSUE TITLE
Error parsing mzML and Adap chromatogram Builder error

### ISSUE THREAD

**Issue by 2AMissinou** [mzmine/mzmine3#722]
### Basic information

* My operating system: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz  2.21 GHz, 16.0 GB (15.8 GB usable)
* My MZmine version: MZmine3.0.21-beta

### What happened
I have mzMLs files of which your version mzMine2.37.corr17.7 manages to read well, except that these files fail to load on mzMine3. Below you will find a photo of the error.
![image](https://user-images.githubusercontent.com/45430190/172361217-bfb8e80c-c221-4d10-84a6-c7a4cf5386a5.png)

The *.RAW files (UPLC_Q-exactive-Orbitrap) contain the acquisition in positive and negative modes. When I try to analyze the data from the *.RAW file specifying the ionization mode for detecting MS1 and MS2, I get a new error in the ADAP chromatogram builder, whether setting the ionization mode or not.
![image](https://user-images.githubusercontent.com/45430190/172371782-e101025b-ca45-46ea-9194-b558ab4ba78d.png)

Thank you

**Comment by robinschmid** [comment]
Thanks for reaching out. 
The first error is toy knowledge resolved if you download the latest version of msconvert to convert the files to mzML.
I don't know why but some files have unsorted data points in the spectra. 
What processing did you apply to the files before or during conversion? 

Otherwise you could try our latest development build which is available from the releases page. 

The second error just means that you did not select a file for mass detection. Make sure to checke the top most parameter of the adap chromatogram builder and set it to the appropriate selector, e.g., all raw data files. Or selected, or....

**Comment by 2AMissinou** [comment]
Hi dear Robin,

Thanks. OK fine. I downloaded your development version. It works without me having to convert my *.RAW files back with MSconvert. It can now be fun to test the complete workflow.   👍 

Otherwise, I had no special treatment for my Files, just classic peak picking.

Thanks for your advice and help

Anani

**Comment by robinschmid** [comment]
Great. You can also check out the batch wizard that might help setup parameters and a "standard" batch
https://mzmine.github.io/mzmine_documentation/workflows/batch_processing/batch-processing.html#processing-wizard

**Comment by 2AMissinou** [comment]
Hi Robin


I have an error when exporting data formatted for GNPS. it seems to say that the error would come from the scans at the mass detection level. I did however perform mass detection with all scans.
![image](https://user-images.githubusercontent.com/45430190/173251098-df7cdf82-410b-4e64-86a2-c8e2b3f4448e.png)
![image](https://user-images.githubusercontent.com/45430190/173251106-c70b7173-cc82-4e28-85b4-d7b6ecd6dcbd.png)

I  checked my aligned feature files after IIMN, and It contains MS2 spectra.

Thank

**Comment by robinschmid** [comment]
Can you show me your mass detection step.
Very often people apply filters there and this is not advised.
Run on MS1 and MS2 on all scans

**Comment by 2AMissinou** [comment]
this was due to the filter. It is all good. Everything works correctly.

however, the files do not work with GNPS. I allow myself to add the output files.

I think there is a lot of MS2 spectrum and often with values of 0.0E0 whereas I tested a threshold of 1.0E4 and 1.0E4 for MS2 detection.

Also, I looked at the structure of the *.mgf file with my previous GNPS scans, there is nothing weird.

Would you have an idea of the problem?
![image](https://user-images.githubusercontent.com/45430190/174278162-5c5ed9ed-e8d1-4ecb-96b7-92aafc654999.png)
