### ISSUE TITLE
Change menu title to "Sample metadata" and set key access

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#724]
@InspiritedCoder can you change the menu title to **Sample metadata** and then set the key access - maybe to SHORTCUT + M

shortcut is either the COMMAND button on macOS and CTRL on UNIX and windows

here is an example
```xml
   <MenuItem text="LC-MS / LC-IMS-MS workflow" onAction="#showWizardTab"
      userData="io.github.mzmine.modules.tools.batchwizard.BatchWizardModule">
      <accelerator>
        <KeyCodeCombination alt="UP" code="W" control="UP" meta="UP" shift="UP" shortcut="DOWN"/>
      </accelerator>
    </MenuItem>
```

**Comment by InspiritedCoder** [comment]
Sounds good, shortcuts are useful. I will implement it

**Comment by InspiritedCoder** [comment]
I think that this issue can be closed because I already implemented it in the previous commits and @robinschmid already checked them (I couldn't do it in a separate branch cause the master branch was unmerged by that time)
