### ISSUE TITLE
MS2 not paired with MS1 after ADAP resolver in Windows

### ISSUE THREAD

**Issue by luigiquiros** [mzmine/mzmine3#726]
### Basic information

* My operating system: Windows 10 Pro 64 bit
* My MZmine version: 3.0.21-beta

### After using the  ADAP resolver module in a WINDOWS computer, the MS2 is not present anymore.
 
After following the standard step by step to get a curated features table, I performed a final filter to keep only the features with an MS2 associated, however, the final table was always empty. 
I checked the problem with several colleagues, using either Mac or Windows. The ones using Mac got the right results and the ones using windows reproduced my problem. 

When using the module ADAP resolver to perform the deconvolution step, the result is a table with deconvoluted peaks but no MS2. 

1) Feature table before ADAP resolver (you can see it recognize the presence of MS2)

![Picture1](https://user-images.githubusercontent.com/49302664/172852520-bfcc788d-1ab9-4b95-9263-523091ae264e.png)

2) after using the ADAP resolver (it does not recognize anymore the MS2 because there is non)
![Picture2](https://user-images.githubusercontent.com/49302664/172852785-50e347a5-5ee9-4488-9622-83381bcb6ad4.png)

Here you can see the parameters i used: 

![Picture3](https://user-images.githubusercontent.com/49302664/172852931-ced799c8-9782-4b24-87ad-38491b8d58e4.png)

But when i use the Local minimum resolver the problem is not present. 

![Picture5](https://user-images.githubusercontent.com/49302664/172853342-7dff80d3-1974-48ce-a87c-e97960c92f39.png)

Thanks for the help!

**Comment by SteffenHeu** [comment]
Hey luigiquiros,

can you check the MS/MS scan pairing parameters here?:
![grafik](https://user-images.githubusercontent.com/37407705/172855133-0224a972-3982-465c-83c4-ea38381d9aa3.png)

What do they say on the windows machines?

**Comment by luigiquiros** [comment]
Here are the parameters for the module.

![image](https://user-images.githubusercontent.com/49302664/172857325-b0da620a-56d0-494e-afa3-d4d3c2893643.png)

Something maybe worth saying is that in MZmine 2.53 it worked perfectly, the same data set.

**Comment by SteffenHeu** [comment]
Mh, there should not be a problem with these parameters. Can you please upload a batch file  (of your processing steps) and the raw data? Or a standalone project

**Comment by robinschmid** [comment]
You could do this on your chromatogram where the MS2 is grouped and check if the MS2 was picked at a different time too far away from the apex of your peak:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/10366914/173333013-76b38743-787b-4f77-b5c8-2d86c7137c75.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/10366914/173333060-07d3828f-37a0-4b68-b9f7-e854ca907dc8.png">

**Comment by robinschmid** [comment]
closed due to inactivity
