### ISSUE TITLE
[MN] Click on edges in visualizer opens MirrorScanWindowFXML or changes selected spectra 

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#731]
@sanbit876 
The MirrorScanWindowFXML shows the relationship between connected nodes. 
- on click on blue edge, open a new dialog and set the two feature list rows as input for the spectral comparison.
- if already open, just change the selected nodes/ features in the dialog with `MirrorScanWindowController.setFeatureListRows` 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/10366914/173341232-a0bde64c-a330-4556-b6e9-6ad211aae857.png">

**Comment by sanbit876** [comment]
I have added a dialog box which pops up with the information of the connected nodes on a mouse click on an edge
Here is the commit: https://github.com/mzmine/mzmine3/pull/753/commits/6fd5b779a6560e3b1ae7820e11b439c4b53c118e
