### ISSUE TITLE
Mass List Error

### ISSUE THREAD

**Issue by israshuster** [mzmine/mzmine3#745]
* My operating system: macOS Monterey 12.4
* My MZmine version: Mzmine 3.1.0-beta

I am attempting to get my mass list for my data that I uploaded. I click ok to run the mass detection, but when I attempt to do ADAP chromatogram builder, it says my file has no mass list. I assume this to be true because mass detection reaches status: FINISHED instantaneously and nothing appears under Feature Lists. 

I uploaded the data as a mzML file. I go from Raw Data Methods to Mass Detection, set up the parameters and click "Ok." Data is centroid and MS level is 1. Noise level is 1.5E4. I also made sure I installed the latest version of Java. I uploaded an image of the error. I have tried changing a few things but have had no luck. I would appreciate any advice! 

-Isra

![Image 6-21-22 at 11 23 AM](https://user-images.githubusercontent.com/107942925/174851326-aac7d1a6-9874-4d24-9f4a-975b85182058.jpg)

**Comment by SteffenHeu** [comment]
Hi isras, can you please upload an example project as a standalone project so we can reproduce the error? Or supply us with the raw data file?

**Comment by oliveiraia** [comment]
I had the same problem, but in my case, I have set a filter for RT in Mass detection step, but did not use the same filter parameter at ADAP chromatogram builder step. So, when I ran the ADAP chromatogram builder, the same error message appeared at the screen, but the console screen showed that there are masses missing in the mass list. Try to execute MZmine3 with the console screen.
