### ISSUE TITLE
[Issue: Bug] Error parsing mzML: io.github.msdk.MSDKRuntimeException: java.io.IOException: Illegal base64 character ox3c

### ISSUE THREAD

**Issue by jyoungheun** [mzmine/mzmine3#746]
### Basic information

* My operating system: Windows 10 Education, 64-bit
* My MZmine version: MZmine 3.1.0-beta

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

Hello, I'm Young-Heun Jung.
I found an issue when trying to import the .mzML file to MZmine.
I used MSConvert (64-bit) (Version: 3.0.22172-198a9d9) which is a recent version to convert the Thermo .raw file into .mzML.
I followed the instruction from GNPS documentation 'Mass Spectrometry File Conversion' (https://ccms-ucsd.github.io/GNPSDocumentation/fileconversion/) to set the parameters and I attached a screenshot of it.
Interestingly, no issue was found when importing the .raw (Thermo) files directly or .mzXML (after the conversion) files to MZmine.
Also, there was no problem when importing the same .mzML files to MZmine-2.5.3 version which indicates this might be MZmine 3-related issue.
There was no problem happening when importing a .mzML file until recently (the last time I tried was almost 2~3 weeks ago).
Hope this problem can be fixed.

All the best, Young-Heun.

![MZmine_report_1](https://user-images.githubusercontent.com/106862432/174924043-a916ea9d-a462-4f0d-9e25-06340c8a8038.png)
![MZmine_report_2](https://user-images.githubusercontent.com/106862432/174924056-321b0c59-da27-4353-acc9-f56244260117.png)

**Comment by jyoungheun** [comment]
One more question.
After downloading the recent version of MZmine 3.1.0-beta, I cannot find 'Set sample parameters' from the 'Project' tab.
Where can I set the sample parameters in the recent version of MZmine 3?

**Comment by robinschmid** [comment]
We are restructuring the metadata support and this will be finished in the next few weeks. Then we will have a better support for it. So please wait before using this feature.

**Comment by jyoungheun** [comment]
Hi there.
These are one of the files I tried to import.
The .mzML file was converted by MSconvert (the latest version) from the
.raw file I attached.
I downloaded MZmine3 3.1.4 and tried to import the same files I used
previously, and the problem still exists for the .mzML file.
(No problem for importing the .raw or .mzXML file.)
Hope this problem can be solved.

Best regards, Young-Heun.
 0h-1.mzML
<https://drive.google.com/file/d/1Nz5tMsqmC0hBUPXmScgBtt3LrntAnqCi/view?usp=drive_web>
 0h-1.raw
<https://drive.google.com/file/d/1hdkYox1j6Ep_JVOyLyg0tICmiP9IJAu7/view?usp=drive_web>


2022년 6월 29일 (수) 오전 5:26, Robin Schmid ***@***.***>님이 작성:

**Comment by robinschmid** [comment]
Need access to the links. thanks

**Comment by jyoungheun** [comment]
You can access to the links now. Thank you!

2022년 6월 30일 (목) 오전 12:43, Robin Schmid ***@***.***>님이 작성:
