### ISSUE TITLE
Error reading raw and mzML Unexpected end tag

### ISSUE THREAD

**Issue by maklp** [mzmine/mzmine3#748]
### Basic information

* My operating system: Windows 64 bit
* My MZmine version: 3.1

### What happened 
I have different Ms files (raw and Mzml) but I can't open them, each time I see an error. I add the picture of the error. 
Sincerely yours, 
Mahdi
![Screenshot (205)](https://user-images.githubusercontent.com/108122820/175499757-2a54bb59-d5a7-48de-a41c-f9a66e44f5bf.png)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by robinschmid** [comment]
Thanks for reporting.
Can you upload the .raw file and maybe your .mzML file so that we can reproduce this error?
Also how do you convert the file?
Any special acquisition?
