### ISSUE TITLE
Windows local data gets full

### ISSUE THREAD

**Issue by mountfort** [mzmine/mzmine3#758]
### Basic information

* My operating system:  Windows 10
* My MZmine version: 3.0.0 

### What happened

The main issue is that it appears that the spectral files get uploaded to the temp area in your local app part of windows and then is not cleared when mzmine is shut down. I guess this is to help with memory management but is there any way to clear the cache once mzmine is closed?

**Comment by mountfort** [comment]
Ah is it so that if a different user restarts mzmine the data will not be cleared from other users cache?

**Comment by robinschmid** [comment]
This is the case. We will add a notification at startup so that people change the temp folder to a public directory with enough space. 
See #759

**Comment by mountfort** [comment]
Thank you!



Sent from my Galaxy



-------- Original message --------
From: Robin Schmid ***@***.***>
Date: 29/06/2022 18:41 (GMT+02:00)
To: mzmine/mzmine3 ***@***.***>
Cc: Alex Dickens ***@***.***>, Author ***@***.***>
Subject: Re: [mzmine/mzmine3] Windows local data gets full (Issue #758)


This is the case. We will add a notification at startup so that people change the temp folder to a public directory with enough space.
See #759<https://github.com/mzmine/mzmine3/pull/759>
