### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by simone7980** [mzmine/mzmine3#761]
### Basic information

* My operating system: win10 with specifications as 
Processor	Intel(R) Core(TM) i5-9500 CPU @ 3.00 GHz   3.00 GHz
Installed RAM	32.00 GB(31.8GB avaliable)
System type	64-bit operating system, x64-based processor

* My MZmine version: MZmine3.1.0_beta

### What happened

* I did the library matching and an error jumped out as "unhandled exception in task Spectral library matching for.......", it is a long error warning, so I posted a pic for the detailed error description here. 

![image](https://user-images.githubusercontent.com/35798605/176865990-6d9fac58-02f4-411e-a30b-b2c2b2d6f1ed.png)

Besides, the species annotation is quite slow, it takes one hour for only 3% progress, which is much slower than what was demonstrated in this tutorial(i believe that the speaker is one of the engineers who built MZmine) https://www.youtube.com/watch?v=hk7WeXibReg 

attached pls find the work log. 

[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9027724/mzmine_0_0.log)

thanks. 
Simone

**Comment by tomas-pluskal** [comment]
Why did you close this issue?

**Comment by simone7980** [comment]
> Why did you close this issue?
because i figured out what was going on, my java type is outdated. undated to the newest java 8, this problem is solved.

**Comment by tomas-pluskal** [comment]
MZmine contains its own Java runtime, it does not use whatever java you installed. So the problem was somewhere else.

**Comment by simone7980** [comment]
> MZmine contains its own Java runtime, it does not use whatever java you installed. So the problem was somewhere else.

but in the installation section of this web, java is required
http://mzmine.github.io/download.html

**Comment by tomas-pluskal** [comment]
Yeah well the website is outdated 😅
We are now working on a new website for MZmine 3.

**Comment by tomas-pluskal** [comment]
Actually, the website says `MZmine 3 is a modern Java software that is packaged with its own runtime. Therefore, it is not need to install Java on the target system. `

**Comment by simone7980** [comment]
> Yeah well the website is outdated 😅 We are now working on a new website for MZmine 3.

oh I see haha, probably i didn't meet that issue again because I re-installed a former type as MZmine 3.011.

**Comment by robinschmid** [comment]
Would be good to also know your parameters that you used for matching

**Comment by simone7980** [comment]
> Would be good to also know your parameters that you used for matching

here are the parameters, they are almost the same as what you showed in the seminar, but I changed the MS level 2 to 1, and minimum match signals from 6 to 4 since our species are small molecules.  
![image](https://user-images.githubusercontent.com/35798605/176996138-3df86e6d-2e8e-4cab-9d4b-e5f9a3986e47.png)

then I realized that I used an MS level 2 database. but our LC-MS data is MS level 1 data, I wonder if I could have any MS level 1 database recommendations? thanks a lot.

**Comment by simone7980** [comment]
Yes, because the data was from MS1 scan, but I didn’t find the MZmine tutorial for MS1 data, mostly of my operation is follow what you treated for MS2 data in this tutorial.  Is that ok?
CMFI Mass Spec Seminar #7 - MZmine3 Hands-On Feature Finding - YouTube<https://www.youtube.com/watch?v=hk7WeXibReg&ab_channel=FunctionalMetabolomicsLab>

Best regards,
Simone

From: Robin Schmid ***@***.***>
Sent: Thursday, July 7, 2022 5:00 AM
To: mzmine/mzmine3 ***@***.***>
Cc: TIAN Xiaomeng ***@***.***>; State change ***@***.***>
Subject: [Ext] Re: [mzmine/mzmine3] Comparison method violates its general contract! (Issue #761)

This email originated from outside of City University of Hong Kong. Do not respond, click links, or open attachments unless you recognize the sender and know that the content is safe.


The question is what do you want to match in MS1?
Are you acquiring with higher in source fragmentation?
The cosine similarity is sensitive for relative signal intensities.

**Comment by robinschmid** [comment]
But wait what do you want to match. 
Spectral library matching uses the whole Ms1 or ms2 spectrum. Or do you want to match just by precursor MZ?

**Comment by simone7980** [comment]
only match MS1 data, because we only did the full scan of our samples, so we don't have MS2 spectra. is that proper to do the data processing for MS1 data(data processing before matching features using feature bank) as introduced in this link? https://www.youtube.com/watch?v=hk7WeXibReg 



> But wait what do you want to match. Spectral library matching uses the whole Ms1 or ms2 spectrum. Or do you want to match just by precursor MZ?
