### ISSUE TITLE
Waters raw import

### ISSUE THREAD

**Issue by ridasilva** [mzmine/mzmine3#764]
### Basic information

* My operating system: Linux
* My MZmine version:  3

### What happened
Using the water .raw (DDA data) import I get:
2022-07-06 13:58:45 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Error of task Opening file XXX.raw: java.io.IOException: Cannot run program "wine": error=13, Permission denied (ProcessBuilder.java:1143)

**Comment by robinschmid** [comment]
No idea if the waters raw data import works on Linux or not. Do you have wine installed as it seems to be trying to open it there.

@tomas-pluskal any idea?

@ridasilva did you try to convert to mzML?

**Comment by ridasilva** [comment]
Hi @robinschmid I tried only on linux. I also tried msconvert but it is missing some MS2 spectra. I also have wine installed and accessible to the user that executed MZmine 3.

**Comment by tomas-pluskal** [comment]
Hi, 
the old Waters import from MZmine 2 could *under good circumstances* also work under wine, which allowed direct import on Linux. That said, installing wine and making it work was not so trivial in my experience (I tried it a few years ago, though, things might have changed). There is a new Waters import module under development, which should also support ion mobility data, so at this point it might be best to wait until the new module is finished.
