### ISSUE TITLE
Can't open set preferences (Ctrl+P)

### ISSUE THREAD

**Issue by jerryuu** [mzmine/mzmine3#773]
### Basic information

* My operating system: Windows11
* My MZmine version:  3.1.0-beta

### What happened

Hi. Even though my computer's RAM is 16GB, it's almost full, so I can't use mzmine3. So I want to check by opening set preferences, but it doesn't open. Any solution? thank you

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* 
![image](https://user-images.githubusercontent.com/109068876/178225943-f65f70b4-12c8-469d-9ff5-c932360584c8.png)

at io.github.mzmine.parameters.dialogs.EmptyParameterSetupDialogBase.showAndWait(EmptyParameterSetupDialogBase.java:198)
        at io.github.mzmine.gui.preferences.MZminePreferences.showSetupDialog(MZminePreferences.java:188)
        at io.github.mzmine.gui.mainwindow.MainMenuController.setPreferences(MainMenuController.java:125)
        ... 53 more

* Please upload an MZmine project file that demonstrates the problem you are reporting.
[can't open set preferences.zip](https://github.com/mzmine/mzmine3/files/9082372/can.t.open.set.preferences.zip)

**Comment by SteffenHeu** [comment]
thanks for reporting and especially for uploading the project, that helped a lot debugging the issue. Should be fixed in #783

**Comment by jerryuu** [comment]
[
![image](https://user-images.githubusercontent.com/109068876/178513873-b064bcd7-610f-498f-b986-8eefe1c6cc34.png)
](url)

thanks for replying. Buy as you see, I don't have a ".mzmine3.conf" in my folder. I check every hidden files.
