### ISSUE TITLE
Add an indication that masses have been detected to raw data overview

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#780]
**Problem**
At the moment in raw data overview there is no indication that mass detection was or was not applied to the data.

**Solution**
Add additional columns after "Scan Definition", like "Mass detected" (yes/no) and "Mass detection algorithm" (i.e., "Centroid").

**Alternatives**
Color coding can be used to highlight data with detected masses.

**Comment by SteffenHeu** [comment]
in the raw data overview's scan window you can select the "show masslist" checkbox at the spectrum parameters

**Comment by MEG311** [comment]
"Show mass list" box is always active. Maybe we could make it inactive in case no masses are detected and/or add a warning?

**Comment by tomas-pluskal** [comment]
The Show mass list checkbox is good for checking the mass list, but there should still be some quick and simple indication for each scan in the list whether the scan has a mass list or not. Something like the green tick marks we had in MZmine 2.
