### ISSUE TITLE
no module-info.java found

### ISSUE THREAD

**Issue by hmalschaert** [mzmine/mzmine3#787]
### Basic information

* My operating system: Red Hat Enterprise Linux 7.9
* My MZmine version: 3.1.0 beta
* Java version : 18.0.1.1

### What happened
The gradlew command is failing. The error message is a missing java module.

The output of the ./gradlew command is :

Error message :
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Project : => no module-info.java found
OS detected as Linux

> Task :compileJava
error: invalid source release 17 with --enable-preview
  (preview language features are only supported for release 18)

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

**Comment by SteffenHeu** [comment]
The error message says it fails due to `error: invalid source release 17 with --enable-preview`...
 The MZmine build.gradle is set to java 17, so it does not work with java 18. As far as i'm aware JDK 18 is not supported by gralde. https://docs.gradle.org/current/userguide/compatibility.html
