### ISSUE TITLE
Error "...Scans not sorted in retention time dimension..."

### ISSUE THREAD

**Issue by roman-bushuiev** [mzmine/mzmine3#788]
### Basic information

* My MZmine version: 3.0.54-beta
* Input file: `.mzML` from [MSV000089819](https://massive.ucsd.edu/ProteoSAFe/dataset_files.jsp?task=f5d802c29fd946ed845c8289bb7456dd#%7B%22table_sort_history%22%3A%22main.collection_asc%22%7D)

### Issue

Clicks on rows in raw data overview or attempts to build a chromatogram give errors "...Scans not sorted in retention time dimension...". So, the file cannot be processed. Probably, it would be better if MZmine could automatically sort spectra by RT values and give a warning about it.

![image](https://user-images.githubusercontent.com/37666912/178846060-a3a7d615-befd-48fb-9667-c900d12d3bfa.png)

**Comment by SteffenHeu** [comment]
bloody waters files... :D 
i thought the mzml import already does the sorting. we definitely had a method to renumber the scans and sort them by rt, maybe the pattern is not recognised correctly.

**Comment by robinschmid** [comment]
I think we are sorting the mz values of the scans but not the RT are we

**Comment by SteffenHeu** [comment]
closing, duplicate

**Comment by mhagar** [comment]
Your Waters file was improperly converted. See fix in #1277
