### ISSUE TITLE
Reordering files after uploading

### ISSUE THREAD

**Issue by sbarnes-AL** [mzmine/mzmine3#794]
In the last series of versions of MZmine 2, in the tab where files were uploaded, there was an option to reorder (alphanumerically) the loaded file names. This seems to have disappeared from MZmine 3. At the present, the order of files displayed in MZmine 3 is the order in which the files complete their upload which is somewhat stochastic. Without the option to reorder the files, that partially randomized order carries over to all other functions in MZmine. This particularly an issue when using ion chromatograms since the random order is reflected in the legend.

The solution should be relatively straightforward to implement since the reorder routine was in MZmine 2

A very slow way to overcome this issue is to upload the file one file at a time.

**Comment by SteffenHeu** [comment]
Did you see the "sort alphabetically" option in the ms data files list?  When you right click you should have the option to sort the files. You need to select the files you want to sort first, though.

**Comment by sbarnes-AL** [comment]
Steffen,

Apologies for the slow response – had my wife’s daughters and their children at our house for several days.

Possibly the issue is that I’m using Mzmine 3.0.10 beta on a MacBook Pro – I don’t see the “sort alphabetically” command. It was in version 2.53.

Apologies if I’ve missed the obvious!!

Regards,

Steve

From: Steffen Heuckeroth ***@***.***>
Date: Monday, July 18, 2022 at 10:45 AM
To: mzmine/mzmine3 ***@***.***>
Cc: Barnes, Stephen ***@***.***>, Author ***@***.***>
Subject: Re: [mzmine/mzmine3] Reordering files after uploading (Issue #794)

Did you see the "sort alphabetically" option in the ms data files list? When you right click you should have the option to sort the files. You need to select the files you want to sort first, though.

**Comment by sbarnes-AL** [comment]
Steffan,

I’ve played a little bit more today with this issue. To get the various options to come up with a right-click, you have to simultaneously press the control key. However, this de-highlights the files that I’d previously selected to be ordered. So, a little progress, but not a winner yet. Remember I’m working on a MacBook Pro with the OS 12.4 operating system.

Steve

From: Barnes, Stephen ***@***.***>
Date: Tuesday, July 26, 2022 at 11:18 PM
To: mzmine/mzmine3 ***@***.***>
Subject: Re: [mzmine/mzmine3] Reordering files after uploading (Issue #794)
Steffen,

Apologies for the slow response – had my wife’s daughters and their children at our house for several days.

Possibly the issue is that I’m using Mzmine 3.0.10 beta on a MacBook Pro – I don’t see the “sort alphabetically” command. It was in version 2.53.

Apologies if I’ve missed the obvious!!

Regards,

Steve

From: Steffen Heuckeroth ***@***.***>
Date: Monday, July 18, 2022 at 10:45 AM
To: mzmine/mzmine3 ***@***.***>
Cc: Barnes, Stephen ***@***.***>, Author ***@***.***>
Subject: Re: [mzmine/mzmine3] Reordering files after uploading (Issue #794)

Did you see the "sort alphabetically" option in the ms data files list? When you right click you should have the option to sort the files. You need to select the files you want to sort first, though.
