### ISSUE TITLE
Bars in the legend of ion chromatograms

### ISSUE THREAD

**Issue by sbarnes-AL** [mzmine/mzmine3#795]
This is a visualization issue - the colored horizontal bar that precedes the file name in the legend is too thin for the color to be recognized. This was an issue in MZmine 2 and continues in MZmine 3. Since MZmine 3 uses a greater range of colors than MZmine 2, (for my eyes) I can't determine what the color actually is.

A **simple fix** would be to double the current size of the bars. A **better fix** would be to offer selection of the bar size in the display parameters and/or unbroken line versus a dotted line.

Don't have an alternative except for importing the ion chromatogram image into PowerPoint and creating one's own legend.

**Comment by robinschmid** [comment]
Thanks for reporting. 

In 3.1.0 you will find the option in Preferences/Visuals/Chart parameters/**Data line width** you can double this value and change the line and the legend. There is currently no option in MZmine to only change the legend. 

The best way is to export as pdf and then edit in Illustrator, Inkscape, or other vector-based software. 


![image](https://user-images.githubusercontent.com/10366914/179962437-91bfa837-0c0e-4d16-82c5-484b5497d9e7.png)
