### ISSUE TITLE
Isotope pattern evaluation

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine3#800]
Maybe add isotope pattern evaluation to the rows filter

- Cl, Br, ... only keep features with specific isotope pattern

@adafede

**Comment by kim17753** [comment]
Hi Robin I actually had a question on this feature, especially for Cl and Br (halogen)

In MZmine 2.53, isotope grouping is only available for 13C/12C, is that correct? 

In the latest MZmine 3, I see there is a isotope pattern finder option. If I add these halogen compounds (Cl, Br), will the isotope filter catch these isotopes as well? Or does it only find the pattern and show the results in the feature list?

Thank you in advance! (sorry if not to ask questions on this post, I can create a new one, if needed)

**Comment by robinschmid** [comment]
Isotope finder goes back to the spectral data to find all signals that might be an isotope signal. Basically following the idea that it is better to catch all signals then loosing a few because of feature constraints. At least better when defining a potential isotope pattern.

The feature list is unchanged. Only the isotope pattern assigned to a feature changes

**Comment by greencodefairy** [comment]
Hello @robinschmid, could it be possible, that the 13 C isotope finder is not able to pick the most intense peak in an isotope pattern anymore, when the isotope pattern is altered, e.g. by the presence of chlorine?
