### ISSUE TITLE
Error importing thermo raw and mzml files

### ISSUE THREAD

**Issue by z840476908** [mzmine/mzmine3#823]
### Basic information

* My operating system:Windows 64bit
* My MZmine version: 3.1

### What happened
I can not  import Ms files (raw and Mzml) successfully. I add the picture of the error.but i successfully imported the file in version 2.53.The file conversion software used is MSConvert
Sincerely yours,
ZC
![image](https://user-images.githubusercontent.com/106716819/182068107-883ea7e3-d4bf-4436-88af-464eb204974b.png)
![image](https://user-images.githubusercontent.com/106716819/182068143-a6af91fb-4802-4cd9-862a-56711bb308e0.png)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by robinschmid** [comment]
Hey ZC 
Always good to try the latest msconvert or the thermorawfileparser. 

At the same time, could you send (GDrive or similar) the raw and mzML file?

**Comment by z840476908** [comment]
The theme raw file can be imported into mzmine version v2.53 normally, I add the Raw file of the erro


> Hey ZC Always good to try the latest msconvert or the thermorawfileparser.
> The theme raw file can be imported into mzmine version v2.53 successfully,but failed in v3.10
> At the same time, could you send (GDrive or similar) the raw and mzML file?
> The raw file is too big to upload,how can i sent the raw file to you.

**Comment by z840476908** [comment]
> Hey ZC Always good to try the latest msconvert or the thermorawfileparser.
> The theme raw file can be imported into mzmine version v2.53 successfully,but failed in v3.10
> At the same time, could you send (GDrive or similar) the raw and mzML file?
  The raw file is too big to upload,how can i sent the raw file to you.

**Comment by robinschmid** [comment]
I cannot see your message it only shows a citation

**Comment by z840476908** [comment]
The raw file is too big to upload, so, i only can show these pictures.
![image](https://user-images.githubusercontent.com/106716819/182783644-f3ad6e74-1dbe-4f70-90ee-05048db9405c.png)
![image](https://user-images.githubusercontent.com/106716819/182783812-5ce0cb29-dfee-4c8f-836f-54baacc8e053.png)

**Comment by z840476908** [comment]
The theme raw file can be imported into mzmine version v2.53 successfully,but failed in v3.10

**Comment by SteffenHeu** [comment]
closing as this is a duplicate
