### ISSUE TITLE
Adduct filtering do not annotate adducts

### ISSUE THREAD

**Issue by anbemp** [mzmine/mzmine3#828]
### Basic information

* My operating system: Windows 11 Pro, 64 bits
* My MZmine version: MZmine 3.1.0 beta

### What happened

I am trying to remove adducts from the Feature grouping, Relations between compounds (IINS); but a new feature list is not created in this step and the previous feature list (after processing adducts grouping) does not contain annotation nor removal of [M+Na]+, [M+NH4]+ adducts (m/z tolerance 0.001 or 5ppm). I have checked it for my IS. Is this a bug or it is just this part of the algorithm is not completely developed for this software version?

Previous steps:
**Mass detection**
Retention time: autorange
MS level: 1
Polarity: Any
Spectrum type: Any

**Feature detection - LC-MS - Chromatogram builder**
Min group size in # of scans: 5
Group intensity threshold: 1.0E5
Min highest intensity: 5.0E5
Scan to scan accuracy 0.02 m/z or 10 ppm

**Smoothing**
Algorithm: Savitzky Golay
Retention time smoothing: 7

**Chromatogram resolver, Local minimum resolver**
Dimension: Retention time
Chromatographic threshold: 50%
Minimum search range RT: 0.075
Minimum relative height: 0%
Minimum absolute height: 1.0E5
Min ratio of peak/top edge: 2
Peak duration range (min): 0 - 0.5
Min of # data points: 5

**Isotopes - 13C isotope filter**
m/z tolerance 0.001 or 5 ppm

Thanks in advance.

**Comment by robinschmid** [comment]
did you apply metaCorrelate for feature grouping and ion identity molecular networking?

You can use the batch wizard to create a batch that contains those steps:
![image](https://user-images.githubusercontent.com/10366914/182800891-141ae45f-37c6-46c1-baad-ff4db886a606.png)

![image](https://user-images.githubusercontent.com/10366914/182800999-01c9dc6f-8fec-4290-89fe-180d606f5586.png)

**Comment by anbemp** [comment]
Thank you very much for your reply. I did not know I had to group the features before annotating the adducts. This batch queue workflow is very useful.
