### ISSUE TITLE
MZmine 3 in Win7 Pro

### ISSUE THREAD

**Issue by Salchi58** [mzmine/mzmine3#830]
### Basic information

* My operating system: Windows 7 Pro (SP1) - 64bit Intel Xeon E5-2620v2 double processor - 64Gb RAM (I have to stick to W7 because of the Waters software to drive my Xevo G2-XS Q-Tof)

* My MZmine version: 3.1.0

### What happened

* Please describe what happened and how it differs from what you expected to happen: : both the installed and portable versions exit upon errors shown in the attached images. Java and R are not installed (the errors are the same even if they are present). The latest 2.53 version worked flawlessly. Running with administrator privileges and/or compatibility mode did not change the behaviour
* Please include all parameter values for the MZmine modules you used: no parameters could be set, of course
* Please upload screenshots of any errors and your log/mzmine.log file: no logfile was generated
* Please upload an MZmine project file that demonstrates the problem you are reporting: obviously, no project could be set up
![Capture3](https://user-images.githubusercontent.com/95000009/182831487-bde8485f-07ba-446e-9d00-472ef7935e24.PNG)
![Capture2](https://user-images.githubusercontent.com/95000009/182831493-597a3870-80c7-4dc2-bf90-37a096439417.PNG)
![Capture](https://user-images.githubusercontent.com/95000009/182831495-b1b37660-c6f0-423a-a8d6-38d967342687.PNG)

**Comment by SteffenHeu** [comment]
Hi salchi, 

it seems like a general error with the executable. Can you run any other of our releases? https://github.com/mzmine/mzmine3/releases

Can you run it on other computers?

**Comment by Salchi58** [comment]
Hi Steffen. I can run any 2.x release on that PC, but no 3.x seems to work. 3.x is working ok on other systems (e.g. my laptop and other desktop PCs running W10). I'd like to use that specific PC because it's the most powerful I have access to.

**Comment by Salchi58** [comment]
Update: I installed Ubuntu as a double boot option and MZ3 fires up fine, but cannot parse any datafile (tested with Thermo .raw files and Waters raw folders), datafiles that I can open correctly on my laptop (same 3.1.0 version). MZmine does not give back any error with Waters folders (but they are not loaded...), while for Thermo files a popup with "java.lang.Exception: No scans found (ThermoRawImportTask.java:185)" error appears.
I'm prone to think that there's a hardware incompatibility (maybe the Xeon processor?) and I'll give up for a while, waiting for more stable versions......

**Comment by SteffenHeu** [comment]
I think it might be a problem with the windows installation. I cannot comment on that.

The waters import is platform dependant, it only works on Windows. The Thermo import should work on any operating system.

Is it SRM data? We don't support SRM data.

If it is not, can you please upload such a file so we can look into it?

**Comment by tomas-pluskal** [comment]
@Salchi58 Please don't give up :) Tracking down this issue is your way to contribute to MZmine development.

**Comment by Salchi58** [comment]
The installation is not the issue (repeated several times, various 3.x releaseses, both .msi and portable). In Ubuntu the Thermo import does not work, the files are DDA and ok on other computers. Will try again on a Linux virtual machine (VirtualBox) on the same PC, this should rule out hardware related issues....I'm stubborn, I never give up :-)

**Comment by tsufz** [comment]
Hi,
For me, this looks like a problem with the system installation rather than a hardware problem. I guess, XEON processors are robust for Java... Your error says that an entry point in a DLL was not found. Maybe, this DLL was not registered correctly (or something goes wrong with Win7...). If the system is running on the Ubuntu installation, try to use mzML files converted with Proteowizard. In my experience, this goes lossless and without trouble for Thermo raw files.

**Comment by Salchi58** [comment]
UPDATE: Tobias is right, the Win 7 problem is Win 7. The whole set of api-ms-win-crt....dll is missing in windows/system32 and MZmine3 crashes before even starting. I don't know an easy fix for that, if any, but as the PC is controlling a Waters system, which is **very** sensitive to software environment modifications, I think I'll try to install Win 10 as a dual boot option.
The problem with parsing Thermo files (and mzML obtained by MSconvert) remains under Ubuntu, both as dual boot installation or as a virtual machine with VirtualBox: the errors I'm getting match those reported in issue#823 (oddly enough, on a win64 system....). The same files are correctly parsed on my laptop or other PCs running Win 10. I uploaded two example files on Google Drive.
[https://drive.google.com/drive/folders/1iNAx9z8Q4IJd6ZW2B1QobeUgLaR3rP1Y?usp=sharing]
Thank you for the support and the excellent work done so far.

Salvatore

**Comment by Salchi58** [comment]
UPDATE: the issue was solved on Win 7 by applying the Windows6.1-KB2999226-x64.msu update. I'm sorry it took me so long to fix, but now I have a sufficiently powerful system to test on - at last! :-)
Again, thank you all for the support (in August!)

S

**Comment by robinschmid** [comment]
Great that you were able to fix this.

**Comment by Salchi58** [comment]
Hi Steffen. I can run any 2.x release on that PC, but no 3.x seems to work.
3.x is working ok on other systems (e.g. my laptop and other desktop PCs
running W10). I'd like to use that specific PC because it's the most
powerful I have access to.


Il giorno dom 7 ago 2022 alle ore 11:23 Steffen Heuckeroth <
***@***.***> ha scritto:
