### ISSUE TITLE
Crop filter is included in two submenus simultaneously

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#841]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: MZmine 3.1.26-beta

### What happened
 **Crop filter** is present both as a standalone module in  **Raw data methods -> Raw data filtering -> Crop filter** and in **Raw data methods -> Raw data filtering -> Scan by scan filtering** as one of the options

**Comment by tomas-pluskal** [comment]
That is a different function. The first one is for cropping files (removing certain scans), the second one is for cropping scans (reducing the m/z range). We should probably give them better names.

**Comment by omokshyna** [comment]
Ok, I'll think about better names
