### ISSUE TITLE
Multiple issues in Spectral deconvolution (GC) -> Hierarchical clustering 

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#849]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version:  MZmine 3.2.4

### What happened

In Spectral deconvolution (GC) -> Hierarchical clustering 
- the possibility to show preview is present, but the preview is not showing
- Task gets frozen and after some time produces Java heap space error

![image](https://user-images.githubusercontent.com/2729783/184920102-acc360c1-9da8-42ca-9f6b-61aa5d43079f.png)

**Comment by SteffenHeu** [comment]
i think this works now @ansgarkorf?
