### ISSUE TITLE
RANSAC Aligner preview crashes

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#859]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: 3.2.4

### What happened

When trying to launch preview in RANSAC aligner, the module first freezes and then crashes.

**Comment by SteffenHeu** [comment]
i think its because the dialog runs the preview on the java FX (=the gui) thread

**Comment by omokshyna** [comment]
@SteffenHeu I checked and indeed preview seems to be running in thread called "JavaFX Application Thread". Should it be otherwise? At the moment, I introduced some fixes and the preview is displayed (but horrifyingly slow). Please, take a look if you have some time before I create a PR - https://github.com/omokshyna/mzmine3/tree/ransac-align-preview-fix

**Comment by SteffenHeu** [comment]
Hi olena, I don't have to time to go through the branch before next week, but thanks for looking into it. 
It's favourable of the data for the preview was calculated in a separate thread which then updates the GUI when it's done. Basically In the same way we use the processing tasks in Mzmine.

**Comment by omokshyna** [comment]
Thanks, next week would be also great. Meanwhile, I'll try to solve the problem with the threads.
