### ISSUE TITLE
CompoundDB:comment appears not in the (aligned) feature list

### ISSUE THREAD

**Issue by tsufz** [mzmine/mzmine3#870]
**Is your feature request related to a problem? Please describe.**
In our application, the comment field in the custom compound DB is important to describe possible issues with compound annotations. We comment for example isobaric compounds, problematic peaks and other things. However, the comment field does not appear in the feature list.

**Describe the solution you'd like**
Add the (optional) CompoundDB:comment field to the feature list.

**Describe alternatives you've considered**
I see no alternatives.

**Additional context**
MZmine 2.3.2
![image](https://user-images.githubusercontent.com/2526819/186985288-179ecd0a-9c11-4d1e-90c7-0f232313bee4.png)

**Comment by SteffenHeu** [comment]
Will be added in the next release. If the feature list is exported currently, you will have the additional information there, it just won't be visible in the feature table.

**Comment by tsufz** [comment]
Great, thanks! I would be preferable, if the comments could appear in the feature list as well to support a streamlined edition of the annotations. It could be an optional field.
