### ISSUE TITLE
Sorting feature lists before alignment in batch mode

### ISSUE THREAD

**Issue by tsufz** [mzmine/mzmine3#872]
**Is your feature request related to a problem? Please describe.**
Sorting of feature lists before alignment in batch mode was possible in MZmine2. We are really missing this feature to reconstruct the original order of samples.

**Describe the solution you'd like**
Add the sort feature lists to batch mode again, please.

**Describe alternatives you've considered**
An alternative could be an optional switch in the alignment. But a general method is preferable.

**Additional context**

**Comment by lisakmalins** [comment]
I also miss the "sort feature lists" method from MZmine2 and would like to see it in MZmine3!

**Comment by SteffenHeu** [comment]
closing for now, as this is a duplicate.
