### ISSUE TITLE
MZmine 3 for GC-MS data?

### ISSUE THREAD

**Issue by gistamayo** [mzmine/mzmine3#876]
### Basic information

* My operating system:  Monterey 12.5, Mac
* My MZmine version: 3.2.3

### 
**What happened:**Confusing workflow for GC-MS and failure to obtain SD

I have downloaded this version about 6 times... to see if there is a bug in the version I had... But I haven't been successful so far.

I want to use MZmine 3.2.3 to process some GC-MS experiments, unsuccessfully. 
The workflow I am using:
1. load mzML files
2. Mass detection:  Centroid, Noise Level 2E2
3. feature detection:  LCMS:  ADAP module, 
           min group size of scans: 8
          Group intensity threshold: 2E2 (same as noise level)
         Min highest intensity:  6E2 (three times the noise level)
         scans accuracy (0.5 m/z or 300 ppm as it is low res)
4. Chromatogram deconvolution:  I use chromatogram resolver: ADAP resolver
          S/N threshold:  4
          S/N estimator Wavelet Coeff SN (peak Wave mult. 3 (defalut))
         min feature height:  200
         coefficient/area threshold:  200
        peak duration range:  0.01 to 0.15
        RT wavelet range:  0.00 to 0.2

I obtain better chromatogram deconvolution using the local minimum resolver (the form of the peaks), yet less detected features.

5. Spectral deconvolution:  Multivariate curve deconvolution
            Chromatograms (the ones from the deconvolution selected in selected files)
            Peaks (the ones from the chromatogram builder in selected files). 
            Deconvolution window width (min):  0.2
           Retention time tolerance (min) 0.02
            Min Number of Peaks:  1
           Adjust Apex:  False
 

But then when I tried to evaluate in Show preview, nothing is there to see. I thought that I have selected the files reversed, but then when selected, nothings is there to see.  When using the other method for Spectral deconvolution, it reports an error.
![Screen Shot 2022-08-29 at 13 10 17](https://user-images.githubusercontent.com/111382086/187279208-5b96dc14-ce9f-4b75-8efa-55ed70580145.png)

So my questions are:  is MZmine 3 ready for GC-MS?  If I have to go back to 2.53, java is preventing to run the program (already tried)....

**Comment by MuhammadRizaludin** [comment]
Hi, I used the latest MZmine 3.2.8 for windows to analyse my GC-MS data and encountered exactly the same problem as @gistamayo described. May I know if you @gistamayo  found the solution already? I have also a question for the developer if this Mzmine version is already optimized for GC-MS data?

**Comment by tomas-pluskal** [comment]
@asmirn1 @du-lab Could you check this issue please?

**Comment by asmirn1** [comment]
@MuhammadRizaludin @gistamayo 

We have fixed a few errors with the Spectral Deconvolution a few days ago, but they are not in the release yet.

Could you try the pre-release version and let us know if you still having the issue?
https://github.com/mzmine/mzmine3/releases/tag/Development-release

Alex
