### ISSUE TITLE
Error in formula predictions and generation of lists

### ISSUE THREAD

**Issue by djb96** [mzmine/mzmine3#878]
### Basic information

* My operating system: Windows 10
* My MZmine version: 3.2.3

### What happened

When using the formula prediction and selecting multiple best formulas, the feature list only provides one formula when exported to a csv. There is the option to select a different formula from the list, but this isn't carried over to the csv. You can double-click on the formula box which turns the formulas into a list, but this is not practical with hundreds of features.

Additionally, the initial formula that is presented in the feature list seems to be that with the highest ppm / m/z tolerance values and the lowest combined score. This, therefore, means that the majority of the formulas don't seem realistic.  As shown below, the C6H10O5 is the more probable formula, but the C7H6N4O is presented. 

![Corrected formula](https://user-images.githubusercontent.com/45171584/187438066-71474f04-d313-4e9d-aaa6-e585a9ae0f03.PNG)
![Incorrect formula](https://user-images.githubusercontent.com/45171584/187438077-01e863c7-5d4f-45f2-9464-e7074b753a8c.PNG)

**Comment by SteffenHeu** [comment]
Hi,

i think we finally found the issue. Feel free to test the latest development built, which should be available in a few minutes.
https://github.com/mzmine/mzmine3/releases/tag/Development-release
