### ISSUE TITLE
Full feature list exported as MS/MS library

### ISSUE THREAD

**Issue by djb96** [mzmine/mzmine3#879]
We are hoping to generate an MS/MS library of unknown compounds, containing hundreds of features. We are able to export spectra to an MS/MS library by right-clicking on the feature list, to export a small number of features. However, could the functionality be improved to allow the entire feature list to be exported at once and with a common adduct?

**Comment by robinschmid** [comment]
We will rework some of the library generation soon. But do I understand correctly that you have no clue what those features are but you just want to create a library that just link them to some metadata?
