### ISSUE TITLE
Can not save a project

### ISSUE THREAD

**Issue by JasonforMn** [mzmine/mzmine3#880]
### Basic information

* My operating system: Window 10 pro, 64-bit
* My MZmine version: 3.2.0

### What happened

Can not save a project!

[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9458349/mzmine_0_0.log)
![can not save a project](https://user-images.githubusercontent.com/30796909/187590614-a1490f99-b893-4148-9834-d303666b529b.jpg)

**Comment by SteffenHeu** [comment]
The error is not displayed in the log file. DId you try to save the project in that log?
