### ISSUE TITLE
Size of dataset to analyse

### ISSUE THREAD

**Issue by svilarl** [mzmine/mzmine3#881]
### Basic information

* My operating system: Windows 64 bit Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz   2.19 GHz  (2 processeurs), RAM 32,0 Go (31,7 Go utilisable)
* My MZmine version: MzMine 3.2.3

### What happened 

*I have a question about how many spectra i can treat with MzMine3? I have a 27 samples batch to analyse, only MS spectra. It finally went well, but to align all these data it's beeing turning for more then 24 hours and it is only at 47%. COmputer seems to handle welle the data treatment, but is it possible that de MzMine3 cannot treat such a big dataset? 
* Please include all parameter values for the MZmine modules you us hours and it is only at ed. I use RANSAC aligner. I tried with Join aligner, it didn't succeded to create aaligne file list. With RANSAC aligner it is running but too slow. 
* Can You please telle me the specification for computer  and also size of dataset up to which we can go?
* Thank You in advance!
* Regards,

* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by SteffenHeu** [comment]
Hi, 

The size of the dataset should be no problem. Make sure you set the temp folder to a ssd. I think it might be due to the parameters you chose. You can try going from the wizard and optimizing the parameters from there.

**Comment by robinschmid** [comment]
As Steffen said the system should be enough to process the 29 samples. You should raise some of the feature constraints in the local minimum feature resolver and that should bring down the number of features in each list. Join aligner will then be relatively fast. Start with the batch wizard. 

cheers
Robin
