### ISSUE TITLE
Issue Importing Thermo Raw files collected on Orbitrap in fullmsddms2 mode

### ISSUE THREAD

**Issue by sarahLy9** [mzmine/mzmine3#882]
### Basic information

* My operating system: windows
* My MZmine version: 3

### What happened
Data was collected in positive mode in full scan data dependent ms2. ms1 scans are profile, ms2 scans are centroid. 

When I import raw files I get a orange warning triangle next to each file name with a warning that states, "mzmine scans were detected as centroid but contain zero intensity values. This may indicate incorrect conversion by MS convert. Make sure to run 'peak picking' with vendor algorithm as first step...."
This warning occurs if I import .raw thermo files or if I convert to mzML file format with MSconvert. 

I can process data but lose my MS2 scans and I need them for annotation. I am a new user to MZmine and would greatly appreciate any insight. Thank you!

**Comment by robinschmid** [comment]
Sorry for the delay.

Can you share one file on google drive or a similar platform?
So profile RAW files should not get the warning there. Its only if its centroided and contains zero intensities. Maybe the type detection is wrong there. Can only check with the file.

This is only a warning though. So you should still be able to process your files. Just try out the batch wizard to setup a standard GNPS MN workflow - this contains the MS2 grouping step during the feature resolving.

For MSConvert. Make sure to have peak picking as the first step when converting to mzML. So you have to move titleMaker down if its still there - or update to a newer version
