### ISSUE TITLE
m/z and RT are zero for the non detected features in Targeted feature detection

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#896]
### Basic information

* My operating system: Windows 10 Pro
* My MZmine version: MZmine 3.2.8

### What happened

In the resulting feature lists, for the non-detected features (marked by an orange dot) the m/z and RT values are set to 0. Meanwhile, zero should be just in the “Area” column.

![image](https://user-images.githubusercontent.com/2729783/189130031-1b0ccaff-4194-477a-86a0-d43d05a7b261.png)

Noticed by @titodamiani

**Comment by SteffenHeu** [comment]
True, they should not be present at all.

**Comment by SteffenHeu** [comment]
will be resolved in #1013
