### ISSUE TITLE
Add: SRM Feature List Builder

### ISSUE THREAD

**Issue by dyrlund** [mzmine/mzmine3#9]

**Comment by dyrlund** [comment]
I finished the initial version of the SRM detection module. As suggested by @tomas-pluskal [here](https://github.com/msdk/msdk/pull/123), the module basically finds the SRM chromatograms from the raw data files and adds them to a feature table. The individual peak in the chromatograms can then later be separated using the [chromatogram deconvolution module](https://github.com/mzmine/mzmine3/issues/48).

When working with SRM data you typically work with Q1 and Q3 values. I have added a new Q3 column to the ColumnNames but the Q1 value is currently stored in the m/z column. Any comments to this approach? And should we add a Q1 column also?

Also, I have updated the ChromatogramToFeatureTableMethod so that similar Q1 values are grouped in the feature tables.

**Comment by tomas-pluskal** [comment]
Hi Thomas,
Currently the SRM detection works only with mzML files, which already have pre-parsed chromatograms. But it doesn't work if you import an SRM RAW file directly. Try this file, for example:
https://dl.dropboxusercontent.com/u/561419/20160306_4X_11.raw

Perhaps it could be extended to not only look for Chromatograms, but also go through the MsScans and select all SRM scans with the same SRM transition. Then the method can call ChromatogramBuilderMethod to build chromatograms from those scans. The important point is not to mix up different types of SRM scans together.

**Comment by tomas-pluskal** [comment]
As for the Q1 and Q3 values, I think it is a good idea to add both to the feature table.

**Comment by tomas-pluskal** [comment]
This SRM RAW file is below 1MB, so we could potentially add it to src/test/resources and use it for a junit test: https://dl.dropboxusercontent.com/u/561419/20160224_Sample01_10m_02.raw

**Comment by dyrlund** [comment]
One more reason to use mzML files instead of RAW instrument files ;-) Thanks for the RAW file – I will update the module to also support generating SRM chromatograms from the MS scans!

I have added the Q1 column to the data model.

**Comment by dyrlund** [comment]
I looked into the last RAW file you provided and I find three unique Q1 values: **149.0, 165.0** and **912.2**. These values are extracted using the `scan.getIsolations()`. Unfortunately, the Q3 values are not present in the `scan.getIsolations()` and we therefore need to find another way to get these. Initially I thought we could get these using the `scan.getMzValues() `. However, when trying this I get 921 unique m/z values from 102.8147 to 103.5852 for Q1=149.0 - this is the distribution:

![149](https://cloud.githubusercontent.com/assets/10582167/13597527/636974c4-e519-11e5-8cbb-bcd782bfc35c.png)

I also tried converting the RAW file to a mzML file using msconvert from ProteoWizard using the following parameters: ` -z --ignoreUnknownInstrumentError`. The mzML file only contains three chromatograms with the following Q1 and Q3 values:
Q1 = 149.0, Q3 = 103.1
Q1 = 165.0, Q3 = 119.1
Q1 = 912.2, Q3 = 408.0

If I look at the scans in the `RawDumpParser.java`, it looks like this:
```
SCAN NUMBER: 1
SCAN ID: + c ESI SRM ms2 149.000 [102.600-103.600]
POLARITY: ?
MS LEVEL: 2
RETENTION TIME: 0.00245000002905726
MZ RANGE: 102.599998474121 - 119.599998474121
PRECURSOR: 0 0
MASS VALUES: 1 x 8 BYTES
INTENSITY VALUES: 1 x 8 BYTES
END OF SCAN

```

The Q3 value in the mzML file therefore seems to be the average value of the scan range for the MS2 scan: 102.600-103.600. Is this the correct way to do this and should we implement it in the same way in MSDK? We currently have the value stored in the `scan.getScanDefinition()`.

**Comment by tomas-pluskal** [comment]
Hi Thomas,

The way it works in the instrument method is you set the Q1 and Q3 values and mass range. For example, in the file above, I set Q1 to 149 and Q3 to 103.1 and mass range 1.0 m/z. So the instrument will isolate 148.5-149.5 in Q1 and 102.6-103.6 in Q3.

I will probably have to update the RawDump exe file to obtain the Q3 values "properly", although in the meantime now we can also parse it from the scan definition, as you suggested.

**Comment by dyrlund** [comment]
Thanks for your explanation. With your example then we should set Q3 to the mean of the isolation window. We are however assuming that the isolation window is equally distributed on each side of Q3. I know that on the Agilent QTOF (I don't know if it is the same case with their QQQ instruments) a ~4 m/z isolation window around the specified mass of 455.29 will give the range from 454.99 to 459.29.

I will update the RawDumpParser.java so that the Q3 value is added to the IsolationInfo based on the information in the scan definition. You can then easily change this when you update the RawDump exe file.

Based on you information above, is there then a reason why you are setting the precursorMz mzRange to a singleton and not the isolation range?
[RawDumpParser.java l.300](https://github.com/msdk/msdk/blob/master/msdk-io/msdk-io-nativeformats/src/main/java/io/github/msdk/io/nativeformats/RawDumpParser.java#L300)

**Comment by tomas-pluskal** [comment]
You're right, it should be the isolation range.

**Comment by dyrlund** [comment]
I made a temporary fix for the missing Q3 information from the raw file parser. See [MSDK #128](https://github.com/msdk/msdk/pull/128).
