### ISSUE TITLE
Importing converted files error

### ISSUE THREAD

**Issue by MarWolan** [mzmine/mzmine3#903]
Edit: Issue solved:
> while making file conversions with MSConvert the MS Levels (in a Peak Picking filtering panel) I used were: 1 - 2, while the instrument that generated the files had 1 - 1 only. Changing 1 - 2 to 1 - 1 solved the problem. The files are now importable in MZmine.

### Basic information

Can you please guys help me solve a problem with file importing. Here are some details.

* My operating system: Windows 10
* My MZmine version: 3.2.8

### What happened

While trying to import mzML files, converted from .wiff to mzML using MSConvert a constat error apears:
Error parsing mzML: io.github.msdk.MSDKRuntimeException: java.io.IOException: Illegal base64 character 0x3e (MzMLMsScan.java:251)
 
None file gets imported into MZmine. 

Please find print screens, corresponding raw and mzMine data files and a log file under the supplied link - see below.

Best regards,
Marcin

[https://drive.google.com/drive/folders/1bEkQ6lbmZbqjROV4uB4LIT1W6Y-3TWyL?usp=sharing](url)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by omokshyna** [comment]
Hi, @MarWolan! We are now working on solving a similar issue (see https://github.com/mzmine/mzmine3/issues/950) . Could you please re-upload your files so we can take a look? Thanks!
