### ISSUE TITLE
Concordance errors in the reading of MS1 spectra between MZmine 3.2 and  older versions, Excalibur from Thermo Raw

### ISSUE THREAD

**Issue by Lsuissa** [mzmine/mzmine3#909]
### Basic information

* My MZmine version: 3.2

Hello
I need your help for a problem concerning the reading of MS1 spectra from Thermo Raw.
When i open MS1 spectra from raw Thermo (profil, negative polarity), i observe supplementary peaks in MZmine 3.2 (or SeeMS) than MZmine 2.53 or Excalibur (Thermo).
I attach an illustration of my problem.
Could you help me?
Thank you in advance
Laurent

[Probleme.pdf](https://github.com/mzmine/mzmine3/files/9617093/Probleme.pdf)

**Comment by SteffenHeu** [comment]
Is it just the one additional peak you observe? Maybe xcalibur cuts the data somehow. It's weird that it's different for different softwares, but all still show the same masses

**Comment by Lsuissa** [comment]
Hello
On the exemple attached, 2 supplementary peaks are observed 80.55 and 81.43……
In oldest version of MZmine, the reading is the same that Excalibur
I don’t understand that
Thanks

De : Steffen Heuckeroth ***@***.***>
Envoyé : mercredi 21 septembre 2022 15:45
À : mzmine/mzmine3 ***@***.***>
Cc : SUISSA Laurent ***@***.***>; Author ***@***.***>
Objet : Re: [mzmine/mzmine3] Concordance errors in the reading of MS1 spectra between MZmine 3.2 and older versions, Excalibur from Thermo Raw (Issue #909)

Is it just the one additional peak you observe? Maybe xcalibur cuts the data somehow. It's weird that it's different for different softwares, but all still show the same masses — Reply to this email directly, view it on GitHub, or ‍ ‍


Is it just the one additional peak you observe? Maybe xcalibur cuts the data somehow. It's weird that it's different for different softwares, but all still show the same masses

**Comment by SteffenHeu** [comment]
My guess is that MZmine 2 and Excalibur use a similar old parser for the raw files. MZmine 3 and SeeMS probably use a newer one which also reads those signals. 

You can try converting the raw file to mzml via https://github.com/compomics/ThermoRawFileParserGUI and import it in MZmine 2. If my theory is correct, you should also see those two signals

**Comment by SteffenHeu** [comment]
Was the issue resolved?

**Comment by Lsuissa** [comment]
No….

De : Steffen Heuckeroth ***@***.***>
Envoyé : samedi 1 octobre 2022 11:28
À : mzmine/mzmine3 ***@***.***>
Cc : SUISSA Laurent ***@***.***>; Author ***@***.***>
Objet : Re: [mzmine/mzmine3] Concordance errors in the reading of MS1 spectra between MZmine 3.2 and older versions, Excalibur from Thermo Raw (Issue #909)

Was the issue resolved? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <mzmine/mzmine3/issues/909/1264305288@ github. com> ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍


Was the issue resolved?
