### ISSUE TITLE
Error during export data for Sirius

### ISSUE THREAD

**Issue by janitensen** [mzmine/mzmine3#910]
### Basic information

* My operating system: Windows 10
* My MZmine version:  MzMine3.2.8

I am a new user to this, so I don't know if it is something to do with my input files or if it is a bug. Just following the advice from the software. 
[sirius_error_mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9617346/sirius_error_mzmine_0_0.log)

I get the following error for my batch run: 

 SEVERE io.github.mzmine.taskcontrol.impl.WorkerThread run Error of task Exporting feature list(s) [Aligned feature list filtered gap-filled filtered] to SIRIUS MGF file(s): Joined features have different polarity. This is most likely a bug. If not, please separate them as individual features and/or write a feature request on github.

[SiriusExport_error_mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9617418/SiriusExport_error_mzmine_0_0.log)
[Screenshot_MZMine.docx](https://github.com/mzmine/mzmine3/files/9617417/Screenshot_MZMine.docx))

**Comment by SteffenHeu** [comment]
Well, do your files have different polarity? If yes, you do have to separate them. Otherwise, please upload the example project as a standalone so we can look into the issue.

**Comment by janitensen** [comment]
Thank you for your quick response. I tried uploading an example project yesterday and it was giving me an error saying it was an invalid file format. But I have been reading a bit and I have run a crop filter now on the raw data, and now it is exporting it, so it was my mistake trying to do something that never could work. My apologies.
