### ISSUE TITLE
Recalibrated Bruker mzML: precursor m/z not recalibrated, different to MS1 (Problems with "Assign MS2 to features")

### ISSUE THREAD

**Issue by IngvildRyde** [mzmine/mzmine3#912]
### Basic information

* My operating system: 64-bit
* My MZmine version: 3.2.8

### What happened

* Please describe what happened and how it differs from what you expected to happen.

To me it seems like there is a mismatch between the MS1 and MS2 scans when looking at the scan table (see screenshot). For example the precursor ion for MS2 in scan #3600 is according to the MS spectrum 245.1169 m/z and is selected based on the MS1 mass 245.1170 m/z seen in the chromatogram. This is also what I see in the software Bruker which I use for data acquisition. However, in the scan table the precursor ion is listed as 245.0565 m/z and is paired with the mass 121.0647 m/z in the "base peak" column (scan #3600). Or is it paired with the MS1 scan #599 having an m/z of 245.1170? Even if so, I think that there is a very large difference in mass between the MS1 and MS2 precursor (~0.065). When I run the "Mass detection" and "Chromatogram builder steps" as described below, I have almost no fragment scans connected to my features. If I go to "Feature list methods" => "Processing" => "Assign MS2 to features" and raise the "MS1 to MS2 precursor tolerance (m/z)" to 0.07 and the "or ppm" to 300, I get more fragment scans connected to my features. To me it just does not seem right having to raise these values this high in order to assign MS2 to my features and I am worried that something might be wrong. Normally I would use a "MS1 to MS2 precursor tolerance" of 0.001. I have recalibrated my data and exported it to mzML files using both Bruker and ProteoWizard, and tried to import it into to MZmine in different ways to see if there might have been a bug somewhere, but the results stay the same. There is also no "Inject time" or "Scan definition" listed in the scan table. Is there any chance that MZmine is somehow reading my data wrongly?

* Please include all parameter values for the MZmine modules you used. 

**Mass detection**
“Raw data methods” => “Mass detection” => “Mass detection”
•	Raw data files: All raw data files
•	Scans: “Set filters”
o	Retention time: 0.8 – 21.00 min
o	MS level: 1/2
o	Polarity: +
o	Spectrum type: Centroid
•	Scan types (IMS): All scan types
•	Mass detector: Centroid => “Setup” => “Show preview”
o	Noise level: 1.0E3 (MS1), 0.00 (MS2)

**Chromatogram builder**
“Feature detection” => “LC-MS” => “ADAP chromatogram builder”
•	Scans: “Set filters”
o	Retention time: 0.8 – 21.00 min
o	MS level: 1
o	Polarity: +
o	Spectrum type: Centroid
•	Min group size in # of scans: 5 
•	Group intensity threshold: 1.0E3 
•	Min highest intensity: 2.0E3 
•	Scan to scan accuracy
o	m/z: 0.005 
o	or ppm: 15

* Please upload screenshots of any errors and your log/mzmine.log file.

![image](https://user-images.githubusercontent.com/114227425/191941984-f429bcdb-3a2a-49fd-845c-ea36a30d6c81.png)

* Please upload an MZmine project file that demonstrates the problem you are reporting.

[project file for MZmine support.zip](https://github.com/mzmine/mzmine3/files/9633047/project.file.for.MZmine.support.zip)

**Comment by IngvildRyde** [comment]
Thanks a lot for your answer Steffen

I have now tried to convert a raw Bruker .d file that I have not calibrated at all into a mzML file and imported to MZmine3. In this file, the MS1 ions and MS2 precursor ions have the same m/z. Then if I calibrate the data, the m/z of the MS1 ions change but not the m/z of the precursor ion for MS2. So I guess that it is a problem in Bruker: should Bruker not calibrate the mass of the precursor ions also? Or a problem in the conversion of the .d file to the mzML file.  

I tried to import the .d Bruker files in MZmine3 directly through the "Raw data methods" => "Data import" => "MS data advanced" because I was curious to see if that might solve the problem. However, I get the following error message:
![image](https://user-images.githubusercontent.com/114227425/194870187-16567ab1-016c-4fdd-9f12-7882a505fdf7.png)
And if I try importing through the "Raw data methods" => "Raw data import" => "Bruker TDF" I get the following error message: 
![image](https://user-images.githubusercontent.com/114227425/194870462-5bd3e8eb-9973-4b59-98a0-9ba2f96aed07.png)
Is there anything I can do to import the .d files? 

Best,
Ingvild

**Comment by SteffenHeu** [comment]
I don't know if the no-precursor recalibration is intentional or not. What i can say is that this doesn't happen if the instrument is calibrated before the run. The precursors use the current instrument calibration, the online recalibration is not applied to the instrument. I think you have to talk to your instrument operator about the issue. For the current data: Either you have to deal with the huge mass shifts of the precursor ion m/z by using a higher tolerance in MZmine or the data should be reacquired.

The native bruker import is only for .tdf and .tsf raw data (check the suffix of the analysis.xyz on your .d folder). These formats are acquired on the timsTOF instruments.
