### ISSUE TITLE
Recalibrated Bruker mzML: precursor m/z not recalibrated, different to MS1 (Problems with "Assign MS2 to features")

### ISSUE THREAD

**Issue by li-chin** [mzmine/mzmine3#915]
### Basic information

* My operating system: Windows 11 Pro
* My MZmine version: 3.2.8

### What happened

***Problem description:** 
- **Data formats conversion:** Bruker qTOF raw .d > mzML (converted using msConvert) > mzMine > .mgf (SIRIUS/GNPS)
- **Overview of data processing steps:** Data import > Mass detection MS1 > Mass detection MS2 > ADAP chromatogram builder > ADAP resolver > 13C Isotope filter > Alignment > Gap filling > Export to mgf (SIRIUS / GNPS)
- **Results:** I can see 521 features after processing steps, but only 27 out of the 521 features were exported in the final step.
- **Suspected cause:** I noticed the issue is likely to happen at the ADAP step, whereby there are 494 features that shows **0 fragment scans** in the feature table **after Step 2d** (described below), and these features are the ones not being exported after all the processing steps. Could you please kindly advise on this? 

Below are my step-by-step data processing:

**Step 1:** Convert Bruker raw file (.d) to mzML (64 bits)
- **Software:** MSConvertGUI (ProteoWizard 3.0.22099 64-bit)
- **Settings:**
i) **Filters:** Peak pick > Vendor (does not work for UNIFI, and it MUST be the first filter!)
ii) **MS Levels:** 1 – 2 > Add > Move “peakPicking” filter to the top
![Picture1](https://user-images.githubusercontent.com/96451969/192199606-90dd6db9-e422-4c63-9ff7-e51f77b91744.png)

**Step 2:** mzMine3 Data Processing (LC-MS Data)

 **(a)	Data import**
- **Steps:** Raw data methods > Raw data import > MS data (advanced) 
- **Advanced settings:**
i) m/z tolerance = 5.000 ppm 
ii) Noise Level (MS1) = 2E3
iii) MS1 detector (Advanced import): Centroid (Noise level: 2.0E3, Detect isotope signals below noise level: Yes)
iv) MS2 detector (Advanced import): No

**Raw data overview:**

![Picture2](https://user-images.githubusercontent.com/96451969/192200296-54cc8567-c7de-4b35-9ef7-b4d05cf2f907.png)

**(b) Mass Detection**

**Mass Detection (MS1):**
- **Steps:** Mass detection > Mass detection
- **Parameters:**
i) Retention time: 1.00 - 15.00
ii) MS level: 1
iii) Polarity: +
iv) Spectrum type: Centroided
v) m/z tolerance: 0.0005 m/z or 5.0000 ppm
vi) Maximum charge of isotope m/z: 1
vii) Noise level: 2.0E3
viii) Detect isotope signals below noise level: Yes 

**Mass Detection (MS2):**
- **Steps:** Mass detection > Mass detection
- **Parameters**: same as MS1, except:
i) MS level: 2
ii) Noise level: 0E0

**(c) Feature detection** 
- **Steps:** Feature detection > LC-MS > ADAP chromatogram builder
- **Parameters:**
i) Retention time: 1.00 - 15.00
ii) MS level: 1
iii) Polarity: +
iv) Spectrum type: Centroided
v) Min group size in # scans: 3
vi) Group intensity threshold: 2.0E3
vii) Min highest intensity: 2.0E3
viii) Scan to scan accuracy (m/z): 0.0015 m/z or 5.0000 ppm

![Picture3(b)](https://user-images.githubusercontent.com/96451969/192200768-0a97ff77-41fe-4637-9173-fa0178f67128.png)

**(d) ADAP chromatogram resolver:**
- **Steps:** Chromatogram resolving > ADAP resolver
- **Parameters:**
i) MS/MS scan pairing: Yes (with Default setting)
ii) Dimension: Retention time
iii) S/N threshold: 3
iv) S/N estimator: Intensity window SN
v) min feature height: 100
vi) coefficient/area threshold
vii) Peak duration range: 0.00 - 2.00
viii) RT wavelet range: 0.00 - 1.00

![Picture4](https://user-images.githubusercontent.com/96451969/192200410-ae42b0c3-f9da-43ec-b391-92b8ee4095d5.png)

Before resolving: 
![Picture5(b)](https://user-images.githubusercontent.com/96451969/192201274-6041bf89-86ab-4233-889c-3d281835b870.png)
After resolving:
![Picture6(b)](https://user-images.githubusercontent.com/96451969/192201289-1d66a6a8-69e9-4c95-9a83-f930e0d589b6.png)

**(e) Isotope grouping:**
- **Steps:** Feature list methods > Isotopes > 13C isotope filter (formerly: isotope grouper)
- **Parameters:** 
i) m/z tolerance: 0.0010 m/z or 2.0000 ppm
ii) Retention time tolerance: 0.010 absolute (min)
iii) Monotopic shape: Yes
iv) Maximum charge: 1 
v) Representative isotope: Most intense
vi) Never remove feature with MS2: Yes
vii) Original feature list: KEEP

**(f) Alignment:**
- **Steps:** Feature list methods: Alignment > Join aligner (Default setting)

**(g) Gap Filing:**
- **Steps:** Feature list methods: Gap filling > Peak finder (Default setting)

**Step 3:** Export feature list
- **Steps:** Export feature list: SIRIUS / CSI-FingerID
- **Parameters (Default):**
i) Merge MS/MS: Yes
ii) m/z tolerance: 0.0020 m/z or 5.0000 ppm
iii) Select spectra to merge: across samples
iv) m/z merge mode: sum intensities
v) Expected mass deviation: 0.0010 m/z or 10.0000 ppm
vi) Cosine threshold (%): 70.0%
vii) Signal count threshold (%): 20.0%
viii) Isolation window offset (m/z): 0.0000
ix) Isolation window width (m/z): 1.0000

After all the processing steps, the feature table has 521 features in the list, but only 27 of them get exported. I have cross checked the feature ID, the ones not exported are features with fragment scans = 0.

**Comment by SteffenHeu** [comment]
Please upload a data file or a standalone project so we can reproduce the issue

**Comment by li-chin** [comment]
> Please upload a data file or a standalone project so we can reproduce the issue

@SteffenHeu  Here is the link to the data file and standalone project https://sarawakbio-my.sharepoint.com/:f:/g/personal/chailc_sbc_org_my/EmF12-HelOxIq_I6whEYIUYB994aBfic_PgRs-vWw6ua_A?e=LuRrMD

Please let me know if the link doesn't work. Thank you.

**Comment by SteffenHeu** [comment]
Hi li chin,

looking at the files it seems that the issue is with the files itself, because the isolation m/z is off by rougly 0020-0.030. There's nothing we can do on the MZmine side. I'd check in the instrument parameters if you have set an isolation offset.

Another option is that the files were falsely converted. For that go to the actual raw files and check the isolation window there. If that is the case, then it's an issue of the msconvert software.

**Comment by SteffenHeu** [comment]
please check the explaination i posted in #912 , this might be relevant for you, too.

**Comment by robinschmid** [comment]
So did you end up with a recalibrated file where both the precursor mz and the MS1 was recalibrated?
Or do you have to leave out recalibration?

**Comment by li-chin** [comment]
@robinschmid Recalibrated for both

**Comment by robinschmid** [comment]
great

**Comment by robinschmid** [comment]
Would you be willing to write a short description in our documentation, so that people can easily find the solution and that we can link it out to other people?
The documentation is hosted here as simple markdown: https://github.com/mzmine/mzmine_documentation

You could add a section for Bruker: Recalibrated files to the data conversion guide
https://mzmine.github.io/mzmine_documentation/data_conversion.html

**Comment by li-chin** [comment]
@robinschmid Sure. It's done, hope that helps, please feel free to review.

**Comment by uc3h2** [comment]
Hi! 

I have a follow up question. 

Would it be possible to by pass the issue by converting the Bruker data to mzML and then calibrate them in mzMine3? 

I am using Internal calibration by NaFormate on the beginning of the analysis on Bruker qTOF. 
I am trying to recalibrate the data by MZmine>Raw data methods>Mass detection>Mass Calibration. 
Yet re-calibration using Universal Calibrant Library as reference leaves the data unchanged. 
I was thinking to use the Standard Calibrant Library (SCL) but had bad luck finding the description how SCL file should be organized. Is it somewhere to be found? Or some examples?

Thanks ahead!

T.

Bruker qTOF 
MZmine 3.2.8 on Debian 11
