### ISSUE TITLE
MS2 has no mass list

### ISSUE THREAD

**Issue by iliakopoulou** [mzmine/mzmine3#919]
### Basic information

* My operating system: Windows 11
* My MZmine version: 3.2.8

### What happened
Problem with the GNPS_MN_export, I get the message: " MS2 scan has no mass list. Run mass detection on all scans while processing task Exporting GNPS mgs of MS2 spectra."

But I have already detetected masses for the MS2 at the beginning of my workflow. Even If I try to do it after an export my list I get the same message.
<img width="960" alt="Χωρίς τίτλο" src="https://user-images.githubusercontent.com/113844171/192486695-3079bd33-d4d8-42ee-88e0-5add6f5a50ee.png">

Noise level at MS1: 2.0E4
Noise level at MS2: 1.0E3
ADAP Chromatogram Builder:  
min group size: 5
Group intens. threshold: 4.0E4
Min highest intsns.: 9.0E4
Scan accuracy: 0.002 or 10.0000 ppm
*

**Comment by SteffenHeu** [comment]
Please check that you run the mass detection on MS2s for all polarities, RTs and so on and don't use filtering that might exclude a spectrum.

If you say you did the mass detection for MS2s, dont provide a log or an example project, there's nothing we can do to debug the issue.

**Comment by iliakopoulou** [comment]
Good morning,
You were right. I had to change the scan type ( from Centroided to Auto)
for mass detection. There were some scans in specific samples whose scan
type was THRESHOLDED, which I don't know why happened.
Thank you for your time and help!
Have a good day!

Best regards,
Iliakopoulou Sofia

Chemist, MSc, PhD

***********************************************************************************

Photo-Catalytic processes and Environmental Chemistry Lab

Institute of Nanoscience and Nanotechnology

NCSR Demokritos

15310 Ag. Paraskevi

Athens, Greece

Phone: +30-2106503633 <callto:+30-2106503633>

Email: ***@***.***
       ***@***.***

Στις Τρί 27 Σεπ 2022 στις 6:11 μ.μ., ο/η Steffen Heuckeroth <
***@***.***> έγραψε:
