### ISSUE TITLE
PrecursorMZ are not read from the Bruker TimsTof tdf file

### ISSUE THREAD

**Issue by chufz** [mzmine/mzmine3#920]
### Basic information

* My operating system: Linuy ubuntu 20.04.05 LTS
* My MZmine version: 3.2.3

### What happened
Mzmine3 is not yet reading the precursor masses of ddMS2 data provided by Bruker tdf files.

![image](https://user-images.githubusercontent.com/38219063/192514687-313d6dd5-545c-406e-ad59-a65f719740de.png)

**Comment by chufz** [comment]
see also https://github.com/rformassspectrometry/MsBackendTimsTof/issues/18#issuecomment-1256174399

**Comment by SteffenHeu** [comment]
The MS2 information should be read anyway.

Have you tried grouping the MS2 with your features already?

Since there is more than one MS2 per frame in the timstof, it is not displayed in that table since it is made for LC-MS data.

**Comment by SteffenHeu** [comment]
see here: https://github.com/mzmine/mzmine3/blob/master/src/main/java/io/github/mzmine/modules/io/import_rawdata_bruker_tdf/datamodel/sql/FramePrecursorTable.java

**Comment by chufz** [comment]
Hi, thanks for the fast response, for now, I just wanted to access the MS2 data without any feature detection, so it seems this is only possible after a complete mzmine workflow?

**Comment by SteffenHeu** [comment]
Yes. If you want to look at the raw ms2 spectra, i suggest using data analysis. 
If you want to see the precursor information,  a sqlite browser is the fastest solution. You could use the ims raw data overview and set the filter to ms2 scans, then you can look at the heat maps.

If you want a quick workflow, you can use the batch wizard. It will run a standard feature detection workflow on the ims data

**Comment by chufz** [comment]
Thanks a lot for that help
