### ISSUE TITLE
Mac mini M1 freezes

### ISSUE THREAD

**Issue by gistamayo** [mzmine/mzmine3#921]
Raw data overview of more than one experiment causes my Mac mini to process everything very slow

- My computer: Mac mini M1, 16 GB RAM

* My operating system:  Monterey 12.5.1
* My MZmine version: 3.2.8

I am dealing with 50 files. After importing the files, and try to use Raw data overview to check on several files in the same window, MZmine becomes very slow, and even freezes for several minutes.

After 15 minutes of waiting, I had to delete the raw data overviews, wait another 15 minutes and then try to do anything else, like changing one name and attempt to order files alphabetically, it took forever!

I checked on RAM, and the software is using 7941/13112 MB free. Other apps running are zoom, WA, Safari, and mail. I just don't understand why it gets so slow!  What is your experience with M1 processors and Mac in general with MZmine 3?

**Comment by robinschmid** [comment]
We have some people using M1 chips and MZmine. I never heard of any specific problems there. 
Sometimes it takes some time when you use many files at the same time (like >5). 

Memory consumption does not say much. Also hard to measure really. But the numbers you provide show that MZmine is using less than 5 GB RAM.
