### ISSUE TITLE
MetaCorrelate on a single chromatogram is not functioning after selecting/deselecting the sample set check box.

### ISSUE THREAD

**Issue by NotReallyContributing** [mzmine/mzmine3#924]
### Basic information

* My operating system: Windows 10 PRO 64-bit (10.0, build 19044)
* My MZmine version: 3.2.8
* My Java version: Version 8 Update 341

### What happened

After selecting and de-selecting the "Sample set" check box from Feature grouping -> metaCorrelate, the module no longer produces a new feature list.

Example workflow to replicate the bug: Import a single CDF file, Mass Detect, ADAP chromatogram builder, Local Min Resolver. 

Using MetaCorrelate on "chromatograms resolved" produces - > "chromatograms resolved corr PEARSON r greq 0.85 dp greq 5"
Using MetaCorrelate a second time on the same list "chromatograms resolved" -> "chromatograms resolved corr PEARSON r greq 0.85 dp greq 5 (1)"
Selecting the box "Sample set" then using MetaCorrelate on "chromatograms resolved" produces nothing.
De-selecting box "Sample set" then using MetaCorrelate on "chromatograms resolved" produces nothing even though it worked twice before.

Perhaps I'm doing something fundamentally wrong, as I could not find documentation for the feature grouping functionality. Regardless, I feel the software's behavior is inconsistent.

![MetaCorrelate Parameters](https://user-images.githubusercontent.com/110992295/193141297-f8a2a585-68db-403d-8eba-4e227f9e52ca.JPG)
![ADAP Parameters](https://user-images.githubusercontent.com/110992295/193140367-e24dbd9f-2252-4ed9-a673-438fddb92797.JPG)
![Local Min Parameters](https://user-images.githubusercontent.com/110992295/193140369-f02b977b-46e4-4465-aec7-9b8b70074769.JPG)
[LogFile.txt](https://github.com/mzmine/mzmine3/files/9679046/LogFile.txt)
![Mass Detect Parameters](https://user-images.githubusercontent.com/110992295/193140372-de79469f-fe1d-4ac6-975a-7cb517936ee2.JPG)
[TroubleShooting Project.zip](https://github.com/mzmine/mzmine3/files/9679055/TroubleShooting.Project.zip)

**Comment by robinschmid** [comment]
Thats an interesting finding. The sample set parameter is also outdated actually. So I will remove it for now. We are working on a better metadata integration into MZmine and this will allow more grouping options
