### ISSUE TITLE
'"MZmine" is damaged and can't be opened. You should move it to the Trash' on macOS

### ISSUE THREAD

**Issue by nilsguillermin** [mzmine/mzmine3#934]
### Basic information

* My operating system: macOS 12.6 (21G115)
* My MZmine version: 3.2.8

### What happened

Ran the installer. Double-clicked the MZmine icon. Got the message:

`"MZmine" is damaged and can't be opened. You should move it to the Trash`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/91959530/194315860-c83d111e-8528-4f03-ac34-c9c9f853ad0b.png">

**Comment by tomas-pluskal** [comment]
Hi, please see the relevant documentation page regarding installation on macOS:
https://mzmine.github.io/mzmine_documentation/getting_started.html#on-macos
