### ISSUE TITLE
Data import

### ISSUE THREAD

**Issue by gidurso** [mzmine/mzmine3#937]
### Basic information

* My operating system: windows 64bit
* My MZmine version: 3.2.8

### What happened: I can't import raw data file; they are data from Thermo wexactive in full MS

the following message appear : child processexited with code 3489660927

Thanks for supporting

**Comment by tomas-pluskal** [comment]
Please upload a .raw file that fails and we can take a look at it.

**Comment by gidurso** [comment]
AA_T0_1a.raw
<https://drive.google.com/file/d/1Zj8WygVpN_INqGJ_FGYHcrGVBf7kMF4f/view?usp=drive_web>


Il giorno mar 11 ott 2022 alle ore 13:36 Tomáš Pluskal <
***@***.***> ha scritto:

**Comment by gidurso** [comment]
I send the file by mail; I want to tell that I can upload one file but when I upload more that 10 file like this there are problem
