### ISSUE TITLE
Bug in ADAP Chromatogram builder with Scans "All"

### ISSUE THREAD

**Issue by omokshyna** [mzmine/mzmine3#938]
### Basic information

* My operating system: Windows 11
* My MZmine version:  3.2.28

### What happened

Launching the ADAP Chromarogram builder without scan filters leads to a cascade of errors, and MZmine crashes. Error reproduces in multiple different data files. This behavior is not reproduced in case if MS level is set to 2 (though it is not intended method usage, the user can do that for now without warning). 

![image](https://user-images.githubusercontent.com/2729783/195081398-de02d3d9-916a-4b9d-8488-930ad3242a7f.png)

![image](https://user-images.githubusercontent.com/2729783/195079646-cb11132a-22f8-4fd5-a474-8cd9884e2335.png)

The console output shows the following:

`Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError`

`Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Task controller thread"`

**Comment by asmirn1** [comment]
@omokshyna It looks like MZmine crashed because of a small amount of RAM. How much RAM does your system have and how big are your files?

If you share your data files, I can test it on my machine.

**Comment by omokshyna** [comment]
Hi @asmirn1! It doesn't seem to be the problem with the files (I tested multiple, but the sample ones are ~45 Mb each) or RAM (my system has 16 GB of it). The sample files are here - https://drive.google.com/drive/folders/1a6VpKTkmvCxBzapk38dHqBpFx-nl4fJU?usp=sharing
I think that's the issue of the filter but you're very welcome to test the issue :)

**Comment by asmirn1** [comment]
@tnguy271 could you take a look at this issue?

**Comment by SteffenHeu** [comment]
Yeah there are usecases where we want other MS levels. For the new DIA correlation i use the ADAP chromatogram builder to build MS2 ion chromatograms to correlate them with the MS1 chromatograms. I looked into the issue and it was an easy fix. Will push it to the master
