### ISSUE TITLE
Unable to load waters .raw file

### ISSUE THREAD

**Issue by gkreder** [mzmine/mzmine3#947]
### Basic information

* My operating system: macOS 12.6
* My MZmine version: 3.2.8

### What happened
I'm trying to import a .raw file generated from a Waters Xevo G2-XS run. When mzmine3 tries to import the .raw file I get an error message saying 

```java.lang.Exception: No scans found (WatersRawImportTask.java:193)```

![image](https://user-images.githubusercontent.com/6944548/195603299-bee78a43-89de-44aa-8064-af08c138369f.png)

When I open the .raw file in massLynx it looks fine. Further, when I convert it to mzML mzmine3 is able to open it and it clearly shows scans (screenshot below). For our work we would much prefer to be able to load into mzmine3 directly in .raw format without having to convert everything. Any ideas what's going on?

![image](https://user-images.githubusercontent.com/6944548/195603406-b01ebc6b-d0ca-4714-8c74-56d192154865.png)

Here's the sample .raw file (and the converted mzML file) I'm working with.

[link to raw files](https://chalmers-my.sharepoint.com/:f:/g/personal/reder_chalmers_se/Evrn5XcI7LlNqD0ZQ0K0T9YBK0_5yNgRpRVpAjrRRIOTqA?e=DabWw2)

**Comment by Tarush-Singh35** [comment]
@robinschmid i would like to work on this issue
