### ISSUE TITLE
Feature List Name Pattern/ Choosing Specific Files

### ISSUE THREAD

**Issue by hhabra** [mzmine/mzmine3#952]
### Basic information

* My operating system: Ubuntu 20.04.4
* My MZmine version: 3.2.8

### What happened
I'm trying to perform operations, such as isotope peak grouping, alignment, etc... on one type of feature list, but I see no way of doing that without selecting each and every list individually (tedious). In the past with MZMine2, they were laid out sequentially, but in MZMine3 they are difficult to disentangle.

For example, in the image below, I would like to align together only those lists with the suffix "chromatograms resolved." I tried the Feature Lists option "Feature List Name Pattern" with the Name Pattern "resolved" or "chromatograms resolved", but both yield 0 files in my selection. Is there something I'm missing here? I found nothing in the documentation to help me figure this out.

![image](https://user-images.githubusercontent.com/8129799/196295658-f156538a-dbf6-42e7-9e00-c55018300aec.png)

![image](https://user-images.githubusercontent.com/8129799/196296528-cc6cb41b-aa77-4e59-9163-4ac0fb49ce01.png)

![image](https://user-images.githubusercontent.com/8129799/196296555-465b0e66-5505-41a4-9c93-9dcbc93bc36e.png)

[Batch1_issue.zip](https://github.com/mzmine/mzmine3/files/9804986/Batch1_issue.zip)

**Comment by robinschmid** [comment]
you need to put a * as wildcard. So *resolved

**Comment by hhabra** [comment]
Ah okay, thanks for letting me know that. I wonder where I missed that bit of information. Either way, closing the issue now.
