### ISSUE TITLE
TIC Visualization for Aligned Peaks consumes all memory

### ISSUE THREAD

**Issue by hhabra** [mzmine/mzmine3#953]
### Basic information

* My operating system: Ubuntu 20.04.4, 1TB total disk space, 32 GB RAM, Java openjdk version "17.0.4" 2022-07-19

* My MZmine version: 3.2.8

### What happened
After performing the peak alignment for this study, I would like to inspect various alignments and other LC-MS peak properties. I right click on one of the shapes (particularly m/z = 114.0638 @ RT = 0.80), click show -> XIC (quick). Unfortunately, my entire system grinds to a halt as this appears to consume all of my memory, to the point that even the mouse barely budges. I never knew this to be a memory-consuming operations in previous MZMine versions, so I'm wondering if there's a solution or something I'm missing here.

I should mention that I tinkered with the MZMine.cfg file to change the RAM percentages to:

java-options=-XX:InitialRAMPercentage=50 (initially 30)
java-options=-XX:MinRAMPercentage=30 (initially 50 or 80??)
java-options=-XX:MaxRAMPercentage=90 (initially 80)

[Batch1_issue.zip](https://github.com/mzmine/mzmine3/files/9814901/Batch1_issue.zip)

![image](https://user-images.githubusercontent.com/8129799/196538040-5553d365-26a4-43d4-8f49-0ba20e22133f.png)

**Comment by robinschmid** [comment]
I think your memory setting should be fine... Although its good to stick to the defaults. There is always an overhead that is above the 80% max.

It seems weird that this would freeze your computer as it can visualize in the feature table... You do not seem to have too many files either. Did you try double click on a file and then visualize in the raw data overview? You can check the box and visualize in more files at once
