### ISSUE TITLE
Manual Integration with "Define Manually" increases peak areas massively

### ISSUE THREAD

**Issue by PerNots** [mzmine/mzmine3#957]
### Basic information

* My operating system: Windows 10 Enterprise
* My MZmine version: 3.2.8 Portable

* Edit: I now also tested on the non-portable version and with mzML files (converted with MSConvert), same problem in both cases

### What happened

Hello,

the issue i am experiencing is with the manual integration of a feature in a specific dataset with the "define manually" function in an aligned feature list.
After manual integration the peak areas increase by magnitudes (e.g. from 9.6E3 to 7.0E7). They do this even if i don´t set new integration borders but just open up the dialogue and click ok leaving everything as it is.

Neither before or after manual integration the peak areas match with the areas reported in the vendor´s software (Thermo Freestyle), which wouldn´t be too bad. However, usually in the large dataset i am trying to integrate, there is always a few features that need manual integration and then are not comparable to the automatically integrated features anymore.
The height value doesn´t seem to be affected by this and matches with the values in the vendor´s software.

My workflow is
- import Thermo RAW data (centroid, negative ion mode)
- Mass Detection (Centroid, noise level: 3E3)
- GridMass (MinHeight: 4.9E3, m/z tol: 0.08, min-max width time: 0.1-1.1min, smoothing time 0.05, smoothing m/z: 0.05, false+ int sim ratio: 0.4, false+ ignore times 0-0)
- Align (m/z tol: 0.08 or 200ppm (weight 80), RT tol: 0.11 (weight 20))
- Feature List Blank Substraction (at least in 3/6 blanks, 150% for exception)
- Peak Finder (Int.Tol: 40%, m/z tol: 0.08, RT tol: 0.1, min data pts: 1)

However, the problem of areas increasing massively when integrating manually already occurs after GridMass if done on a single file´s feature.

The MZmine file as well as the log can be found here (they are too big for github):
https://uppsalauniversitet-my.sharepoint.com/:f:/g/personal/stefan-lukas_ruchti_7587_student_uu_se/Eo_XR0ribiFKo8Sqpe4IuTMBKj49noFg_K_Niv5VSz_dsg?e=K9afOS

**Comment by SteffenHeu** [comment]
Sorry for the late reply.

This issue should be fixed in the latest dev build already. You can try it here: https://github.com/mzmine/mzmine3/releases/tag/Development-release

**Comment by PerNots** [comment]
Hey, thank you so much for getting back to me.

I deinstalled the old mzmine and downloaded both the portable and the non-portable version of the dev build.
I tried to recreate the problem described above but this time i run into an error earlier on. When i try to move the Integration-Start-Line or the Integration-End-Line there is an Error message poping up (see attached screenshot). This happens in both versions and doesn't allow me to integrate manually. The values for areas won't change even if i ignore the error messages and continue to click "ok".
It also already occurs on the feature lists i get after GridMass.

Do you have an idea on how to get around this?

All the Best and thanks again
Stefan
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9852806/mzmine_0_0.log)
![DevBuild-stat](https://user-images.githubusercontent.com/75035875/197561349-3abaa18f-b43a-4bf8-b3cf-c7a3a78368a5.png)

**Comment by SteffenHeu** [comment]
Hi Stefan, 

i cant reproduce that with my own files. Does the project yu uploaded produce the issue? If yes for which feature in which feature list?

**Comment by PerNots** [comment]
Hey Steffen,

i wasn't using the uploaded files when writing my last post but when retrying with the uploaded files, i noticed what provoked the error.
I was trying to make the integration window wider when i got the error message and i am quite sure now that it gave me the error because the new limit for integration was at a point where the intensity was lower than the one defined by GridMass. When i try to make the window smaller it always works and when i adjust the GridMass intensity to a lower value i can also go in both direction (make integration range bigger and smaller)

Thank you so much for your help. I think this is solved :)
Best
Stefan
