### ISSUE TITLE
Mass detection in batch mode doesn't select all raw files

### ISSUE THREAD

**Issue by ivana67000** [mzmine/mzmine3#963]
### Basic information

* My operating system: Windows Server 2019 64-bit, version 1809
* My MZmine version: 3.2.8.

### What happened

The first batch step (I've added the batch file attached) in my case is mass detection here, in which I've chosen the "all raw data" option for selecting files for processing, and "those created by previous batch step" in all consecutive steps. When I upload all raw data (mzML format, works great when I do step by step processing by hand) however, I get this error message stating that at least one raw file must be chosen in Mass detection step. I've tried also selecting the raw data and then using the "those selected in the main window" option for my batch but I get the same message. 
Also a thing to note, I have two mass detection steps for MS1 and MS2 and I don't know in which one does the error occur, but I'm guessing it's the first one?

Thanks in advance,
Ivana

![error](https://user-images.githubusercontent.com/28786806/197737398-7c5af38b-5e2d-475c-a0a4-7c2be783b40c.PNG)
[mzbatch_negative_v5.zip](https://github.com/mzmine/mzmine3/files/9859024/mzbatch_negative_v5.zip)

**Comment by SteffenHeu** [comment]
Hi ivana, 

the way the batch mode works is that it checks which files were present when the module starts and when it ends. If the selection is "those created by previous batch step" the "difference"/new files/feature lists are used for the next step. In case there is no difference, the previous selection will be used.

However, mass detection does not create any new files and if it is the first step in the batch, there are no files selected.

You can set it to "all files" until a new file or feature list is created (e.g. by the ADAP chromatogram builder). Or you can also do the import in the batch mode (use the "Import MS Data" to import any kind of file).

**Comment by ivana67000** [comment]
Oh, that was a mistake on by part. It seems to work now, thank you
