### ISSUE TITLE
Application of positive charges to features detected using a negative mode LC-MS

### ISSUE THREAD

**Issue by ThuridurNott** [mzmine/mzmine3#964]
### Basic information

* My operating system: Windows 10 64-bit
* My MZmine version: 3.2.8

### What happened
This may be more of a question but MzMine applies charges to the features in the samples I give it. In the same sample batch it assigns some as positive or neutral but it is impossible that the detected compounds are anything other than negatively charged as the system used for the analysis is a LC-qToF-MS in negative mode where the MS is used as the detector. Positive and neutral compounds should not be detected. We are several in my research group that are experiencing this with different methods. Is there any processing parameter where one can set the possible charges? Some in the group have started opening the exported MzMine files and changing all charges to -1 manually using a find and replace function, is this a viable procedure?
A project and the batch I used are in this google drive folder https://drive.google.com/drive/folders/1z54UF5X1hSL-LvndCeEWJtEnvY4E6-jQ?usp=sharing. 

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.**
* Issues opened without an example project are unlikely to be processed

**Comment by SteffenHeu** [comment]
I'm not exactly sure what you mean. 
Are you referring to the charge column showing "1" for negative mode measurements? 

The charge is saved as an absolute value in Mzmine, no matter if it is charged positively or negatively. You can multiply the charge column by -1 in your export if you did negative mode measurements.

Where exactly is this an issue for downstream analysis?

**Comment by ThuridurNott** [comment]
We further analyse the features found in MzMine in SIRIUS which attempts to identify the compounds. In the file that MzMine exports for SIRIUS/CSI finger ID when opened in notepad there is for each feature a line with CHARGE = 0 or 1 for example which we have assumed is the assigned charge of the compound. 
![image](https://user-images.githubusercontent.com/116361496/197768065-96cfae0d-8640-433e-a632-d04d6ba5f488.png)
When this is imported to SIRIUS the program assumes these features have this charge and uses that to identify them, so I worry they will not be identified correctly if SIRIUS thinks they are positive when they can only be negative.
So it is possible to just change this charge value to -1 and it should not lead to inconsistencies or problems?

**Comment by ThuridurNott** [comment]
I did not actually know about this as I typically compute many samples at a time where changing the adduct is not a visible option. This all makes sense now. Thank you for the help :)
