### ISSUE TITLE
Unable to group the samples to export the data for metaboanalyst

### ISSUE THREAD

**Issue by Cagakan31** [mzmine/mzmine3#969]
### Basic information
First of all thank you very much for this open source software which is an excellent tool!

* My operating system: Windows10
* My MZmine version: 3.28

### What happened

* Please describe what happened and how it differs from what you expected to happen.
*--I am trying to do lipidomics experiment by using LC-Ms processing wizard. I also created a sample metadata (names and types of the samples (WT/KD), added to batch queue. Annotated the lipids but when I want to export the data for metaboanalsyt, I couldn't because it seems like I did not define the groups of the samples. 

![image](https://user-images.githubusercontent.com/116829832/198541269-62fd5f5d-ca60-4133-a72e-1d83249e99fe.png)

* Please include all parameter values for the MZmine modules you used. 
![image](https://user-images.githubusercontent.com/116829832/198541759-f2c95f5c-eb90-4446-9578-dfc3c4827b6f.png)

* Please upload screenshots of any errors **and** your log/mzmine.log file.

![image](https://user-images.githubusercontent.com/116829832/198564691-7c54949d-5573-42ff-88ed-edc2912964cc.png)

* **Please upload a standalone MZmine project file (or a batch + raw files) that 
* demonstrates the problem you are reporting.**
[Parameters1.zip](https://github.com/mzmine/mzmine3/files/9887595/Parameters1.zip)

* Issues opened without an example project are unlikely to be processed
-I am not sure it is a bug, but I don't know how/where to group the samples.  in MZmine 2 it was like that
![image](https://user-images.githubusercontent.com/116829832/198569463-5f06bea5-200c-4f53-9f52-917a15e75708.png)

**Comment by robinschmid** [comment]
I am very sorry for the inconvenience. 
We have been restructuring the metadata support to make it more flexible and we are still in the process of fixing the export.
I will look into this.

**Comment by Cagakan31** [comment]
Thanks Robin,
Great work!
