### ISSUE TITLE
different result of formula prediction for MZmine 3 and MZmine 2

### ISSUE THREAD

**Issue by IEECAS008** [mzmine/mzmine3#971]
### Basic information

* My operating system:windows 10
* My MZmine version: MZmine 3.2.8 and MZmine 2.5.8

I use the same parameters to do the formula prediction  for the same batch of samples with MZmine 3 and MZmine 2, but the result shows different. It is obvious less formula number were predicted in MZmine3 and also for sulfur contaning organic compands.

Before  formula prediction ,I do Mass detection，ADAP builder，Chromatogram deconvolution, deisotope and Alignment

![a59f655ae5d1d9f3d6246d63de8a554](https://user-images.githubusercontent.com/117164972/199436496-2c410398-3c31-49be-936f-10dc144c0398.png)

**Comment by tomas-pluskal** [comment]
Hi, this is a good observation. Would you be able to upload your project files for MZmine 2 and MZmine 3 somewhere (e.g., Google Drive) so we can take a look at the details?

**Comment by IEECAS008** [comment]
Hi, i upload the raw data  and parameters used in the project. Please check, https://drive.google.com/drive/folders/1etfKy7gZM87Sdgn_pXqXYkV2UG6ZT2ju?usp=sharing

**Comment by IEECAS008** [comment]
> Hi, this is a good observation. Would you be able to upload your project files for MZmine 2 and MZmine 3 somewhere (e.g., Google Drive) so we can take a look at the details?

Hi, i upload the raw data and parameters used in the project. Please check, https://drive.google.com/drive/folders/1etfKy7gZM87Sdgn_pXqXYkV2UG6ZT2ju?usp=sharing

**Comment by robinschmid** [comment]
can you upload oth the MZmine 2 and 3 batch

**Comment by IEECAS008** [comment]
> can you upload both the MZmine 2 and 3 batch
hi， when  I try to save the mzmine3 project, it comes out this error
![image](https://user-images.githubusercontent.com/117164972/200767944-d4d4037d-fa8e-4cc4-aec1-25b1d909c9f4.png)

**Comment by SteffenHeu** [comment]
which raw data modules did you run exactly?
Never seen this in the Mass detection module

**Comment by IEECAS008** [comment]
> can you upload both the MZmine 2 and 3 batch
see the batch from googlr drive,thx
https://drive.google.com/drive/folders/12i5OVA8eSZGGtKXSSD9EPVT1ya1ZO5Ad?usp=sharing

**Comment by IEECAS008** [comment]
> which raw data modules did you run exactly? Never seen this in the Mass detection module

I run the thermo raw data

**Comment by SteffenHeu** [comment]
are you using any other modules prior to the adap chromatogram builder?

Can you right click on a file, go to "show file summary" and then screenshot the parameters of these modules?

**Comment by SteffenHeu** [comment]
This issue should be fixed in the latest development build: https://github.com/mzmine/mzmine3/releases/tag/Development-release

**Comment by IEECAS008** [comment]
> https://drive.google.com/drive/folders/12i5OVA8eSZGGtKXSSD9EPVT1ya1ZO5Ad?usp=sharing

You guys are amazing. THX  so much.
 Hope you can help to fix why the different result of formula prediction from mzmine3 and mzmine2.3.5.
see MZmine 2 and 3 batch from googlr drive,thx
https://drive.google.com/drive/folders/12i5OVA8eSZGGtKXSSD9EPVT1ya1ZO5Ad?usp=sharing

**Comment by IEECAS008** [comment]
> This issue should be fixed in the latest development build: https://github.com/mzmine/mzmine3/releases/tag/Development-release

You guys are amazing. THX so much.
Hope you can help to fix why the different result of formula prediction from mzmine3 and mzmine2.3.5.
see MZmine 2 and 3 batch from googlr drive,thx
https://drive.google.com/drive/folders/12i5OVA8eSZGGtKXSSD9EPVT1ya1ZO5Ad?usp=sharing

**Comment by IEECAS008** [comment]
> 

Hi Robin and Steffen, just wondering  if the difference in the number of formulas between mzmine 3 and mzmine 2 has been resolved. Thanks a lot

**Comment by IEECAS008** [comment]
> can you upload both the MZmine 2 and 3 batch

Hi Robin and Steffen, just wondering if the difference in the number of formulas between mzmine 3 and mzmine 2 has been resolved. Thanks a lot

**Comment by kim17753** [comment]
@IEECAS008 Wow this is a very nice experiment. I am actually navigating between different untargeted analysis software to see how they differ on feature detection, isotopic patterns, and eventually formula assignment. Love MZmine the best.

May I ask how you extracted your formula into Cx Hx Ox etc? Did you export the csv and extracted the predicted formular using different coding software (e.g., R or MATLAB)?

Much appreciated for your help!

**Comment by robinschmid** [comment]
Sorry we did not yet have time to look into this issue. 
To many other things on the todo list. 

Overall the formula predictions needs an update with all the latest features we have. 
Between MZmine 2 and 3 we did change some of the scoring and soring of formulas though.

**Comment by SteffenHeu** [comment]
Hi,

i think we finally found the issue. Feel free to test the latest development built, which should be available in a few minutes.
https://github.com/mzmine/mzmine3/releases/tag/Development-release
