### ISSUE TITLE
Converting files in profile mode into centroid mode (LCMS-IT-TOF instrument)

### ISSUE THREAD

**Issue by ThaoPDoan** [mzmine/mzmine3#976]
I can select centroid mode in the lcms post run analysis, but could not get them in centroided when converting to mzXML format; I also tried MSConvert but they said it does not support data from LCMS-IT-TOF instrument.

![image](https://user-images.githubusercontent.com/117472545/200033707-e0f44b75-0aea-4099-850e-8241f0f957bc.png)

So, what could I do to convert them all into centroid before using MZmine 3? I might be missing something from the post-run analysis from LCMS; and another possible way is how to do it within MZmine 3 (if possible)

Best,
Thao. 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.**
* Issues opened without an example project are unlikely to be processed

**Comment by SteffenHeu** [comment]
Is this an Shimadzu instrument? Similar to Waters instruments, there have always been problems with converting the data to open source formats. If MSConvert and the vendor software does not work, i can only refer you to google or to the vendor himself. Otherwise, if the software supports a profile export, you can try that and do mass detection with a profile mass detector in mzmine.

**Comment by ThaoPDoan** [comment]
Thanks for your reply!
Yes, it is the Shimadzu instrument. So from what I understand, if all files
are in either profile mode or centroid mode (not a fix of both), we can do
mass detection in mzmine.
And I will find a way to convert them.


Thao.

**Comment by robinschmid** [comment]
Shimadzu is actually really nice. So you could also reach out to them and see if they have a solution.
In MZmine you can process either centroid or profile. Very important though - open the spectrum and look at it - compare it to the vendor software to see if it is actually centorid or profile. MZmine might also detect the mode wrong or its wrong in the mzml file.

If it is really a mix, which I doubt, you can setup scan filters to the different scan types and do mass detection with centroid mass detector on centroid, and exact mass on profile

**Comment by ThaoPDoan** [comment]
Dear Robin Schmid,

I figured out that, MZmine detected the mode wrong, which I double checked with Shimadzu. And a technician from Shimadzu suggested: 

"I think I have found a viable solution for your data, but please try this on your system and let me if this works. When importing your mzXML files into MZmine (my version is 3.2.8), I went to Raw data methods, then MS data (advanced).
I then went to select the data files and then did an Advanced import.
I then changed both detectors to Centroid. Also make sure that you then go to setup here and place your noise threshold level (it will not work without this)."


However, i am not sure if this is the correct way to carry out the process plus I got trouble with setting up the noise threshold level as the technician suggested.



Best,

Thao. ,
