### ISSUE TITLE
Empty exported feature list

### ISSUE THREAD

**Issue by weantony** [mzmine/mzmine3#977]
### Basic information

* My operating system: win10 pro 64bit
* My MZmine version: 3.2.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.
[p_m.zip](https://github.com/mzmine/mzmine3/files/9942113/p_m.zip)
Hello,

My name is Jian from Queen's University. I have created a feature list for my data, and I could visually confirm the peaks in mzmine. But if I use the export feature list for GNPS-feature based molecular network exported, csv and mgf files are always empty. I followed the step in the documentation. I wonder if anyone has seen such problem. Thank you very much.

Best Regards,
Jian

**Comment by SteffenHeu** [comment]
my guess is that the ms2 spectra are not assigned to your features. This can be done during the [resolving step](https://mzmine.github.io/mzmine_documentation/module_docs/featdet_resolver_local_minimum/local-minimum-resolver.html#msms-scan-pairing) by selecting the respective parameter or at the end of the processing with the "[Assign MS2 to feature](https://mzmine.github.io/mzmine_documentation/module_docs/featdet_ms2_scan_pairing/ms2_scan_pairing.html)" module.

**Comment by weantony** [comment]
> 

Thank you so much. It worked.
