### ISSUE TITLE
Unable to open MZmine 3 in macOS Ventura

### ISSUE THREAD

**Issue by ZarluisMijangoR** [mzmine/mzmine3#978]
### Basic information

* My operating system: macOS - Ventura 13.0
* My MZmine version: MZmine 3

### What happened
Hi there,

Three weeks ago I managed to used MZmine 3 without any problem but all of the sudden last week I was planning to work on it again and it decided to be in the bin and not open. After that, I decided to download it again, reset my computer but I am not able to have access again. The errors that I am having are the the document is corrupted and that it has to go to the bin. I was wondering if there are some folks out there having the same issue and if there is a way to fix this.

Thanks in advance,
Best,
Zarluis

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.**
* Issues opened without an example project are unlikely to be processed
<img width="262" alt="Screenshot 2022-11-04 at 4 26 11 pm" src="https://user-images.githubusercontent.com/63169552/200349852-8ce00589-46c8-423a-833a-e405403f6e9f.png">

**Comment by SteffenHeu** [comment]
Did you try this: https://mzmine.github.io/mzmine_documentation/getting_started.html#on-macos

**Comment by ZarluisMijangoR** [comment]
Hi Steffen,

First off, thank you very much for your answer. Indeed, I tried this part and used both code terminals.

**Comment by SteffenHeu** [comment]
@tomas-pluskal / @roman-bushuiev any idea then?

**Comment by ZarluisMijangoR** [comment]
Hi @robinschmid,

I am using a 2.3 GHz Quad-Core Intel Core i5.

Best,
Zarluis

**Comment by robinschmid** [comment]
Good to know. Do you know if there was a macOS update?

**Comment by ZarluisMijangoR** [comment]
Yes, there was a recent update (which I did) from MacOS Monterrey to Ventura. Interestingly, I was using zoom today and I had an error installing the new version, and I had to download the new version manually. This might be the issue!? Not sure how to fix it for MZmine :'(

Best,
Zarluis

**Comment by robinschmid** [comment]
Did you try installing the development version which was compiled more recently

**Comment by ZarluisMijangoR** [comment]
I believe I have not tried this, where I can find this development version?

Thanks in advance,
Zarluis

**Comment by RMdCeR** [comment]
Hi,

I have the same issue than @ZarluisMijangoR. Currently running Ventura 13.0.1 on Mac M1.

Any idea when a fix would be available for this issue? 

Thanks!

**Comment by tomas-pluskal** [comment]
Could you try adding MZmine to this list in the System preferences? 
Let us know if that helped.

![fix-damaged-apps-ventura](https://user-images.githubusercontent.com/1796692/202689731-08266d1e-d64d-4a1c-9360-3313b1e425ba.jpg)

**Comment by leizhon** [comment]
Hi Tomas,

I am facing the same problem as described by Zarluis and already tried your suggestions, but unfortunately, it still did not work. 

Thanks,
Lei

**Comment by leizhon** [comment]
Hi all,

I already figured out the problem and can run the new version on my Mac. You might need to open MZmine.app using the terminal.

Best,
Lei

**Comment by leizhon** [comment]
I tried several times and definitely it works now.

**Comment by tomas-pluskal** [comment]
@leizhon Can you write more details how exactly you solved the issue?

**Comment by leizhon** [comment]
![WechatIMG140](https://user-images.githubusercontent.com/102558284/202870476-77557af9-125f-4d7a-b2d6-909e93434f11.jpeg)


![WechatIMG141](https://user-images.githubusercontent.com/102558284/202870489-0cb07ca9-c064-4122-bde9-96268b3ea176.jpeg)

**Comment by tomas-pluskal** [comment]
Ok thanks, we'll look into it.

**Comment by RMdCeR** [comment]
Hi all,

I have added the program to the developed tools list and I've tried to open it through the terminal as suggested by @leizhon , but the same error keeps popping.

@leizhon are u running Ventura on M1?

**Comment by leizhon** [comment]
@RMdCeR
System info: Ventura 13.0 in M1 Pro

**Comment by RMdCeR** [comment]
I'm on Ventura 13.0.1 in M1 Pro.

Can you walk us through what you did to get it to work?

**Comment by leizhon** [comment]
> I'm on Ventura 13.0.1 in M1 Pro.
> 
> Can you walk us through what you did to get it to work?

Here is the link for a screen recording. (The file was too bio to upload)
https://tubcloud.tu-berlin.de/s/yB9pry5WMWoYqbL

**Comment by tomas-pluskal** [comment]
@roman-bushuiev Is now working hard on implementing the code signing and notarization on macOS. It should be finished before the end of the year. That will be the ultimate solution for these problems.

**Comment by gomespwp** [comment]
> 

Dear @leizhon, I saw your record and tried it but it doesn't work. Do you have any idea?

**Comment by Adafede** [comment]
If you replace the `sudo xattr -cr MZmine.app` in the README by `xattr -d com.apple.quarantine /Applications/MZmine.app`, you should see it appear in your security preferences and be able to "open it anyway".

**Comment by gomespwp** [comment]
> 

Thanks Adriano, everything is working right now!

**Comment by stenhagen1** [comment]
Hi! I still have the problem since the mac venture update, and with using this code above it says there is nu such MZmine app. Can someone help me?

**Comment by Adafede** [comment]
> Hi! I still have the problem since the mac venture update, and with using this code above it says there is nu such MZmine app. Can someone help me?

@stenhagen1 
Try to type `xattr -d com.apple.quarantine` into your terminal, do not press enter, then drag & drop the MZmine app icon from your applications into your terminal, this should add the right path to the app, and you should be able to press enter then and have it working.

**Comment by tomas-pluskal** [comment]
@stenhagen1 The command should look like this:
`xattr -d com.apple.quarantine /Applications/MZmine.app`
Did you drag&drop the MZmine app into the terminal as @Adafede suggested?

**Comment by stenhagen1** [comment]
@tomas-pluskal Yes I did... I am using that code and I get this error: Not enough arguments for option -d. Expected at least 2 but got 1.. 

When I use your code it says no such xattr..

**Comment by tomas-pluskal** [comment]
I guess that means the quarantine attribute was already removed from /Applications/MZmine.app, so you should be able to run it.

**Comment by stenhagen1** [comment]
@tomas-pluskal when I run it, it says that it is damaged still.. “MZmine” is damaged and can’t be opened. You should move it to the Bin.

**Comment by tomas-pluskal** [comment]
Then you go to macOS preferences and click "Open Anyway".
<img width="702" alt="Screenshot 2023-01-27 at 14 03 42" src="https://user-images.githubusercontent.com/1796692/215093687-69d43679-c762-4675-8235-e673a079c82d.png">

**Comment by stenhagen1** [comment]
Thanks a lot!! It works now

**Comment by tomas-pluskal** [comment]
This problem should be fixed in the MZmine 3.4.0 release. The macOS builds should be properly signed. Please let us know if it works for you.

**Comment by Adafede** [comment]
@tomas-pluskal, @roman-bushuiev 

Worked on my side 👍🏼
