### ISSUE TITLE
Crashed during Mass Detection

### ISSUE THREAD

**Issue by Landkaml** [mzmine/mzmine3#989]
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/9980940/mzmine_0_0.log)
[mzmine_1_0.log](https://github.com/mzmine/mzmine3/files/9980941/mzmine_1_0.log)
[mzmine_2_0.log](https://github.com/mzmine/mzmine3/files/9980942/mzmine_2_0.log)
Windows Server 2019 Standart
Procesor: AMD Opteron Processor 6272
RAM: 128 GB
Mzmine 3.2.8

### What happened
I tried to analyze 256 files in .mzXML format with a total size of 13.6 GB. It crashed already during the Mass Detection step in the MS1 scan (noise level 5.0E4).
No error is displayed.Program crashed and nothing happens.
When I analyzed less and smaller data, it ran normally. Does MZmine have any file limitations?
Thank you for your help

**Comment by tomas-pluskal** [comment]
MZmine does not have any file limitations. It seems strange that the program would just crash suddenly. Could you try to run it on a different computer to see if you can reproduce the error?

**Comment by robinschmid** [comment]
Make sure to setup the temp path in the preferences to a fast local drive with enough space.
We are saving temp files with the spectral data and the filtered mass lists. Maybe your drive is full at one point.
