### ISSUE TITLE
MS/MS scans

### ISSUE THREAD

**Issue by AKS-NZ** [mzmine/mzmine3#992]
### Basic information

* My operating system:
![image](https://user-images.githubusercontent.com/117885062/201510513-b3e94b21-343c-4b2d-a057-6b3014d493d8.png)
* My MZmine version: 
MZmine 3.2.8
### What happened

* Please describe what happened and how it differs from what you expected to happen.
In spite of checking the box for MS/MS scan pairing in the 'Resolving' step, the results do not show the fragment scans for any of the features. Hence, I am unable to do a library match for the features (based on MS2).
* Please include all parameter values for the MZmine modules you used. 
![image](https://user-images.githubusercontent.com/117885062/201510764-82530251-ae82-46f9-aaf6-8bd82d50d591.png)
![image](https://user-images.githubusercontent.com/117885062/201510796-81045456-f97a-4114-9304-7aea09074e04.png)
![image](https://user-images.githubusercontent.com/117885062/201510819-86541aef-b8f1-4a8a-9592-cda367d28e2a.png)
![image](https://user-images.githubusercontent.com/117885062/201510836-6b93d547-ec1a-4948-9f6c-b8f1527f1bd8.png)
![image](https://user-images.githubusercontent.com/117885062/201510857-ad774545-ea5d-4623-9f21-77384cf6b139.png)
![image](https://user-images.githubusercontent.com/117885062/201510885-1d2878b4-0e11-434b-8670-5e97619d7273.png)
![image](https://user-images.githubusercontent.com/117885062/201510903-0d0ce206-3b74-40c8-8708-e158b6f686a3.png)
![image](https://user-images.githubusercontent.com/117885062/201511007-05bd83f3-ce59-4d37-a063-ff8b368ed6fb.png)
![image](https://user-images.githubusercontent.com/117885062/201511037-34fd3910-0303-4a2d-8858-8fa5dff70e86.png)
* Please upload screenshots of any errors **and** your log/mzmine.log file.
![image](https://user-images.githubusercontent.com/117885062/201511083-700dc1c9-0e7d-47b6-8675-560f7b1bdd44.png)
![image](https://user-images.githubusercontent.com/117885062/201511104-55515f58-db6b-44e7-8ecc-87fb22271fb0.png)

* **Please upload a standalone MZmine project file (or a batch + raw files) that demonstrates the problem you are reporting.**
[mzML_Export_Result.csv](https://github.com/mzmine/mzmine3/files/9997012/mzML_Export_Result.csv)

* Issues opened without an example project are unlikely to be processed
Cannot upload project file. > 25 MB

**Comment by Adityasaini10012001** [comment]
assign this to me

**Comment by AKS-NZ** [comment]
Yes, I think I have - Pls see list of steps above.
If this is not what you mean, where do I do that? Can you send me a screenshot pls? I've been following the steps in your tutorial/video, and saw that not checking the MS/MS scan pairing in the resolving step, you ended with a similar result - no fragment scans in the result. And then you checked that box in the batch mode step, and then you got the fragment scans in the feature list table. I did the same thing in batch mode, but still not able to get the matching.

**Comment by robinschmid** [comment]
in the resolving step you have the group MS2 spectra option and you have to press setup there

**Comment by robinschmid** [comment]
You can also start a new batch mode by using the Batch Wizard and hit build batch. That will give you some starting batch mode and you can adjust options from there
