### ISSUE TITLE
NIST MS Search, cannot find the path specified

### ISSUE THREAD

**Issue by NotReallyContributing** [mzmine/mzmine3#993]
### Basic information

My operating system: Windows 10 PRO 64-bit (10.0, build 19044)
My MZmine version: 3.2.8
My Java version: Version 8 Update 341

### What happened

When using Annotation -> NIST MS Search on a resolved chromatogram, I receive and error stating “The system cannot find the path specified”. The online compound annotation (KEGG) works for the tested chromatogram.

The module appears to attempt to make/find a temp file in a user directory that does not exist on my computer. My temporary directory is set to a public folder. My MS directory is set to the EXE. Location and the NIST program has automation turned on and libraries selected. 

![Error Message](https://user-images.githubusercontent.com/110992295/201718435-269c79e4-a462-4c93-9ce6-a8d1924f5ba9.JPG)
https://www.dropbox.com/s/vrr5pvslp3beqwx/NIST%20Troubleshooting.mzmine?dl=0

Thanks for any help!

**Comment by robinschmid** [comment]
Make sure to set the correct directory. @Kevin-Murray can you look at this.

Otherwise just use the spectral library search that provides more options.

**Comment by Kevin-Murray** [comment]
@NotReallyContributing would you be able to upload a screenshot of the setting `NIST MS Search` parameters window you are using before you submit. 

I've confirmed the module works for me using the latest distribution of MZMine3. Assuming the NIST MS Search directory is set appropriately, the problem is likely in your NIST MS Search library search settings. We can look over your current settings and figure if you don't have something set appropriately. I will use this as an opportunity to update the help documentation.

**Comment by NotReallyContributing** [comment]
Thanks for looking into this @Kevin-Murray. Attached is a screenshot showing the parameters used. 

From the time of posting this issue I have found a work around. 
When using a different computer I encountered the same error with the same path specified. On this computer I'm able to create folders/subfolders to match the path specified in the error and then the NIST MS search functions. However, I'm unable to implement this work around on my main computer due to lacking the admin privileges to create folders in the "User" directory.


![MS Search Parameters](https://user-images.githubusercontent.com/110992295/207098522-82d85c5b-ac2a-49ca-bcce-d267957f392a.JPG)

**Comment by Kevin-Murray** [comment]
Thanks for the information @NotReallyContributing. I will try a fresh install of MZmine on a computer without Admin privileges and see if I can replicate the error. 

The issue you are encountering is strange - the module is supposed to look for the FILESPEC.TXT file in the directory of the NIST MS Search tool. It's unusual that it is directing you to a temporary directory for this. I will review the code for the creation of the locator files. I am probably overlooking the source of the problem. 

Give me a day or two and I will get back to you.

**Comment by Kevin-Murray** [comment]
@NotReallyContributing In your MZmine installation, what is your temporary file directory path?

It is located under Project > Set Preferences > General. Is it the path listed in your original error?

**Comment by NotReallyContributing** [comment]
@Kevin-Murray My temporary file directory is C:\Users\Public. The error occurs with this directory.

**Comment by Kevin-Murray** [comment]
@NotReallyContributing If you changed your temporary file directory to another location, like in your Documents folder - do you obtain the same error?

**Comment by NotReallyContributing** [comment]
@Kevin-Murray I've tried moving the temporary file directory to my Documents and still receive the same error.

**Comment by NotReallyContributing** [comment]
@Kevin-Murray Here is a screen capture showing the work around allowing the module to function. 

https://www.dropbox.com/s/nnghli75pgkstd3/2022-12-15%2011-24-13.mkv?dl=0

**Comment by Kevin-Murray** [comment]
@NotReallyContributing Thank you for this video - it is very helpful. So the NIST software is working but the the software is looking in a folder that doesn't exist on your local computer. So it appears references to the original installation computer are still found in your software somewhere.

First thing, in the NIST MSEARCH directory, there is a file labeled AUTOIMP.MSD. You can open this file in notepad like a txt file. Would you be able to copy the text of this file to a comment? It's possible a lingering reference to the former computer is found in this file and it's not getting overwritten correctly. 

You mentioned that the NIST MSSEARCH was copied to your computer. To be clear, was it copied or did you install the software using official installer package? If you just copied the whole folder, I'm guessing some of keys in the software are still mapped to locations on the original computer. This could be driving the problem. Unfortunately, I cannot find anywhere in the MSSEARCH software to update temporary directories, paths, etc.  I am not a developer of MSSEARCH, so my understanding of their software architecture is limited to what's available in the manuals.

**Comment by NotReallyContributing** [comment]
Good call on the lingering reference, @Kevin-Murray! The AUTOIMP.MSD contains: C:\Users\agricensci\AppData\Local\Temp\FILESPEC.TXT

The NIST MS SEEARCH folder was copied/pasted to a different computer.

Some other observations: The NIST MS executable works (without MZMine3) after pasting without the file path of AUTOIMP.MSD on the local computer.

I believe this issue is the same as encountered in MZMine2: https://github.com/mzmine/mzmine2/issues/871

**Comment by NotReallyContributing** [comment]
Changing the text of AUTOIMP.MSD to a path on the local computer stops the error from occurring.

**Comment by robinschmid** [comment]
Great that it works now. Thanks @Kevin-Murray

**Comment by SteffenHeu** [comment]
this issue explains how to get around restricted licensing. will delete.
