### ISSUE TITLE
Own library match still not working

### ISSUE THREAD

**Issue by mountfort** [mzmine/mzmine3#996]
### Basic information

* Windows 10
* 3.2.8
### What happened

Hello,

So I can not seem to get the annotation to work using our library that did work in MZmine 2 but no longer works in MZmine 3...

I have modified the column headers to match but that is still not working. I have also tried changing from European style to UK style numbering but again no joy... Any thoughts?

Alex
[Tuulia  Libary changed.csv](https://github.com/mzmine/mzmine3/files/10011897/Tuulia.Libary.changed.csv)

**Comment by mountfort** [comment]
https://seafile.utu.fi/d/b5f86aad1d1c49ffa23a/
here is the link to the project

**Comment by mountfort** [comment]
Worked out my issue...

**Comment by tomas-pluskal** [comment]
Hi Alex,

Sorry for the late reply, but could you please let us know what the problem
was?

Tomas

**Comment by mountfort** [comment]
Hi Tuomas

No worries it was that the default column that you see is the manual ID not the database ID which is a few columns over! To be fair both Tuulia and I have been wondering this for a while!

Alex

Sent from my Galaxy



-------- Original message --------
From: Tomáš Pluskal ***@***.***>
Date: 17/11/2022 13:06 (GMT+02:00)
To: mzmine/mzmine3 ***@***.***>
Cc: Alex Dickens ***@***.***>, State change ***@***.***>
Subject: Re: [mzmine/mzmine3] Own library match still not working (Issue #996)


Hi Alex,

Sorry for the late reply, but could you please let us know what the problem
was?

Tomas
