### ISSUE TITLE
Spectral Deconvolution Step Error

### ISSUE THREAD

**Issue by DPC7** [mzmine/mzmine3#998]
### Basic information

* My operating system: Ubuntu 22.04 LTS
* My MZmine version: 3.2.8

### Issue facing
Hi, I am preprocessing GC-MS raw spectra data. I successfully carried out mass detection, Chromatogram building, and the chromatogram deconvolution step. But when I tried the **Spectral Deconvolution (GC)** step with **Hierarchial clustering**, I found the preview pane is not working when I checked it. Additionally, when I put the parameters for that step and run I received an error ([Please see attached snapshot](https://drive.google.com/file/d/15kOD5hhEQjkAZuA0mf1gEQvqKE9SbqZv/view?usp=sharing)).
Can you please suggest something?
Additionally, in my case, I am getting some spectra that seem incomplete in shape ([e.g. shapes in this screenshot](https://drive.google.com/file/d/1XF0QixXBnJjzpJjusxZ-soKxBzbj-JmR/view?usp=sharing)). Is this normal?

**Comment by asmirn1** [comment]
@DPC7 

Could you try the latest version and let us know if you are still having issues?

Alex
